/-
The box check of the constant box 0 of twist 0 (disc 5, centre 3, size 2), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B0

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 5, 3, 2, ⟨5, 3, 2, true, (240502, 141094, 221110), 0⟩, 3593008820300712862086174847802118870532603648587007976995972462924942855200149103135177201920658939381459068506868605736912476306988487460246663681339759295134828995760380462053134, 600, (1400887520054998407398028730529398417408339132223828269017053068976779322170881546777240257739591099126462263037088589189294588946453712081154450400733827207424922953879480220232566, 1779011142920687196257570128630211302837915380165694709041962942965251164846037502395588109220465040154175031007647638395839449641436746886158438728193503540669993417577800176903974, 298190753658268311986116235581656617874553041659787981781342414937699158146480445452260051053820986987500014767533647158605122629193095307373233395930911326876170929425750846300086), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 15
      (3 * (FurioLombardo.M4.T0.constant[0].vM / 3 + FurioLombardo.M4.T0.constant[0].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B0
