/-
The box check of the constant box 19 of twist 0 (disc 1, centre 113, size 8), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B19

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 113, 8, ⟨1, 113, 8, true, (217208, 66680, 37240), 0⟩, 521906751393809084006465115822765468272768697001533860084016207093423252379016574834696468732342865716004310169432254477530646294594938455541184973066363130997182762587725102926496, 600, (3068961222367993990145098429461489908471475406525233037886754281819879622345397814390546260732666561496282727528368388204223883952525548259687982494485689178059651578471951918387320, 3310196180083175025947851611038588150016179365812588387771832092890852454789359752986648395276926075620300742247454585364529589865382515907018504673561749096893961973525360424846456, 3587432467281908435026865287046886483968785420779451879360775216164545091613163929940091877683154120202732562488776932335993841548942050987521540054317273265530933511497426707452280), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 33
      (3 * (FurioLombardo.M4.T0.constant[19].vM / 3 + FurioLombardo.M4.T0.constant[19].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B19
