/-
The box check of the constant box 11 of twist 0 (disc 1, centre 225, size 9), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B11

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 225, 9, ⟨1, 225, 9, true, (91896, 223864, 154360), 0⟩, 257295580109074816693238440932332162546979865065835532319713967615371435647211892720368845985264864681348002705767098182234851120210118163280231443658045356777327520548813335087424, 600, (3518690507934518760827124603744678369390291970361773930465860508988825144021408244952967689480759950339751488513512855668801647688368817515136763579075070610116302972573848310998776, 3605068423093969365274168167863143292833181270474505201876864530969452998243547197186053567219537333169507058492230875379804196734707226128030461676530432504868925375351029215488632, 3464039231728688758717017832920685359801774422142018162996594318696790009166429399695899477083536452931182219561606467802446617972349194467736276920279131045289917069728514212780792), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 36
      (3 * (FurioLombardo.M4.T0.constant[11].vM / 3 + FurioLombardo.M4.T0.constant[11].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B11
