/-
The box check of the constant box 18 of twist 0 (disc 1, centre 241, size 8), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B18

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 241, 8, ⟨1, 241, 8, true, (130168, 136312, 58744), 0⟩, 3409322213588343843282775942903597989562222594623794907449590623416482584786802069748056497387780403329222037351465790714661574408051754969300315017930751391724230698237788819439008, 600, (3412390042990393414800675188526824118106326615681835259263380900673889010400964518478392046131720506486542881201338543886388824353237176440702709405257321367569656253779555709222008, 3290103641983541126502054060484967627446737207034597034294332444907313612623479516624786362334063191096654782416912390059283409384679147066021629814574238349426615123990480371979384, 3356468746642546542333205194662911751917998992878169782372096131932800773456905899630819241470221365385761868359248948761497832448321790718530675606528769236711668325159865810478456), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 33
      (3 * (FurioLombardo.M4.T0.constant[18].vM / 3 + FurioLombardo.M4.T0.constant[18].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B18
