/-
The box check of the constant box 1 of twist 0 (disc 5, centre 1, size 2), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B1

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 5, 1, 2, ⟨5, 1, 2, true, (225630, 201582, 256054), 0⟩, 2926475286495674400385428817177532796763223340000957115889184182480651898347145250772767356320065934222691489081269571031519106128218120537569510833291564217916434666165050838567252, 600, (182654960146681958366694601015886716907860440757023895081326797511892501353698305874274616560055860282276579804412505791743373176389887098370630482830197947645674152362591187857758, 451954161515425312060056082094315100818090847091669136691094149162550288484978102624753592896310774098508644043004668468307707813213018481138208391683243016983561247834393093542766, 2436791575052123266899225279380609791135940602413773522584519477031161653202206677842887630596810241233862638326236803413208752469055515310679805671601157935736712425724389128923190), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 15
      (3 * (FurioLombardo.M4.T0.constant[1].vM / 3 + FurioLombardo.M4.T0.constant[1].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B1
