/-
The box check of the constant box 12 of twist 0 (disc 1, centre 353, size 9), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B12

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 353, 9, ⟨1, 353, 9, true, (4856, 64120, 175864), 0⟩, 948337969591753340453445495084686812444711981768033167921733285941659086218998513512346221971936207420383043665487240512795465889091888169176263216917770489926000828124202815921216, 600, (3805668910119962925157322671434066707203487378874686113038909359863105412271053608149956104210359268903141684409500679816985336979779607366325194330713842792640636811397237509198584, 3565490189288321170240006126629125718741717247723493327134758499313378283599671347949111173292160646655797386174650168112759357924404709480852919276045712073103718234830162946488952, 3197790508750518714122248261073868080994011738469894041679775047574176705100285340112815811421517373608343772382119682487914019282862574333896915775880614090062309474727368396025592), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 36
      (3 * (FurioLombardo.M4.T0.constant[12].vM / 3 + FurioLombardo.M4.T0.constant[12].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B12
