/-
The box check of the constant box 16 of twist 0 (disc 1, centre 289, size 9), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B16

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 289, 9, ⟨1, 289, 9, true, (48376, 176760, 165112), 0⟩, 1800988638720279680054005054034535375043155821289148848266320962207002443017635736564388216349275055033120759722210053103996986832969256171049370730855958254871539994365907175035584, 600, (3159186094550932060723307397599413390961369402449462557939963279095169422344278883438513621595256239211850688574087086898242649586867123035234947487392578977330657826000518628556024, 3334532007953172291570288093394165768629276707243028944973783815482204566397693411549040854770633655525503711736066586325475061043950298997702866078072335195544844861120861771575928, 3664652658411164427698129528129998471986185391684847451771284943597924007207261428992516744192921507569127571085628024142405404159153844347859850806904461360782691690075683033089272), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 36
      (3 * (FurioLombardo.M4.T0.constant[16].vM / 3 + FurioLombardo.M4.T0.constant[16].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B16
