/-
The box check of the constant box 14 of twist 0 (disc 1, centre 417, size 9), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B14

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 417, 9, ⟨1, 417, 9, true, (223480, 148088, 186616), 0⟩, 1287637224597269477385426067848739464113860534133155273427718635320553746676745343288986300874002715868428483857373251939213789977427715698154048563463374400350676987468077924099520, 600, (3228042267942593350893193347731576738689482261918477176869859649448511504991953661968237887403151369717085810481941523874270407254294697678241406611930698335148443218430438164883704, 3022365560430743546484637842462943664182222001219345323808298468344630256304950850550764860317654018002853873444031720218185782545519309368801905806760328025549418623298521634587256, 3340899943459555181933200874033098654051169951712650317665050342041929778413227243750429701598672272872937475388221733467035002688447131346510287430786524995391298244979687900502264), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 36
      (3 * (FurioLombardo.M4.T0.constant[14].vM / 3 + FurioLombardo.M4.T0.constant[14].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B14
