/-
The box check of the constant box 17 of twist 0 (disc 1, centre 33, size 9), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B17

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 33, 9, ⟨1, 33, 9, true, (222456, 234104, 122104), 0⟩, 1186475128926038242645770955875662941081995970881252656006746800124935419022345924005280637461886226441699211786020858240793604746777626502696324961401692378823679871971165967396032, 600, (3344354170990206103063872596124458575727414808321982867365248399843181921473653078734930483184487872960253943079414737833303587444848210804178226287161743191116275834451760449807608, 3366082603159995488013926947117515423279007449982135190362266679889325075269656214146559408956464905714626509860140724382303133028958579560788703256338391012880619717803252286198392, 3209864790129315798004674874270384982329150718830004607266234358451454331549058048204163890482465259410148607174481533076518591325345463195030234873682944079080774719509954726583544), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 36
      (3 * (FurioLombardo.M4.T0.constant[17].vM / 3 + FurioLombardo.M4.T0.constant[17].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B17
