/-
The box check of the constant box 26 of twist 0 (disc 1, centre 121, size 7), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B26

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 121, 7, ⟨1, 121, 7, true, (224056, 17272, 202424), 0⟩, 80583368132715525219584785951723586653090062855269539881571721756841326969901831897755208402752997198423146805492967295087625883238862582144300263672212933301719345342083202111568, 600, (3429291872274087670829169077319034521724638758227474227520055651133669816408043693080622754278800548530482078527586943689942612221358017356458760240190584309417295181401917133646648, 3323269039646520952386650422497367834712404637580455471292313427792043698900339997006189807371193542387262999888007058324417158450839444364464984397646697435301160259786429461971832, 3521794510738222302531019441164776236181499560785266208331205890224132884056193957886899851468341528028160804411109920579572619521342002448303487571085165687749466143302749290960568), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[26].vM / 3 + FurioLombardo.M4.T0.constant[26].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B26
