/-
The box check of the constant box 28 of twist 0 (disc 1, centre 89, size 7), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B28

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 89, 7, ⟨1, 89, 7, true, (16440, 225144, 33208), 0⟩, 964668651222731390006344730350100509507657103992506745063681735954378971897122959897871513085997459050731824371290190321980571875449676019008251264737210954347588045677804926308240, 600, (3437175507764792757726801024276567972073289694836468680653242541049673716819296887040442261466451511929310107499057027463772067137360392720909621194804010984913475568583572821393464, 3286497097577807139438425869221169381674230969582989312954033610836390606818011867299566574746620911377624123381105154717643064283152821335958944270688654321912469627565036702756728, 3092233818758474381006813565364721122874713490355018756462303965980795717703535093878819577134925579539361643483119374379759445339095780518625552620684797692276248763911820610929080), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[28].vM / 3 + FurioLombardo.M4.T0.constant[28].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B28
