/-
The box check of the constant box 25 of twist 0 (disc 1, centre 17, size 8), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B25

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 17, 8, ⟨1, 17, 8, true, (20344, 235640, 21112), 0⟩, 135739881338414352674444867850939227039259395406378845816133631797381642181040967295727850779399128891523216995291075443000574593617257755869513678968034669459370267126437963734112, 600, (3407564917417586132066359166862550686930014802873540427918359770338874765737530432204018094793800469912655944461233671515008517990009345638253899311531340868241013629502557856747384, 3244323211162331606619382841738494822785703133725467660976399807288442344198965451768166971212325447166143374382164248648951860757318311753751889572422850402410376559175096434661496, 3443815967189346361934831847770153704627329053085247941496265419546694113560107919048753890027342685581655287957325455637750097431007501800446830586283838755910842219481838336365176), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 33
      (3 * (FurioLombardo.M4.T0.constant[25].vM / 3 + FurioLombardo.M4.T0.constant[25].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B25
