/-
The box check of the constant box 24 of twist 0 (disc 1, centre 145, size 8), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B24

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 145, 8, ⟨1, 145, 8, true, (195448, 239736, 42616), 0⟩, 1937473400136660706520852441476444750851876401438662638350132961137638231143299657771117118455931072987669745250397844117168221202787026003611302512488345749726147292294389256998752, 600, (3356230031962034862076306684438961306395324860055604704502667178955425842878679479262096508120964193561450032113783729590653537681320424202188569781294620099907738852539943833500536, 3132558274771566827696232325646008226767855125794458768885988598380318156763204327152040238748848634442401176714286303724063705502186268775390747853121153583668865944544981556635768, 3549836698082700097377386855701574204392141806267650775603758809825138837096346464291167918034771427016513082967994506423267335414197955260359536407605396879371664583240897033971320), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 33
      (3 * (FurioLombardo.M4.T0.constant[24].vM / 3 + FurioLombardo.M4.T0.constant[24].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B24
