/-
The box check of the constant box 27 of twist 0 (disc 1, centre 57, size 7), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B27

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 57, 7, ⟨1, 57, 7, true, (202040, 23416, 126136), 0⟩, 2466626158590679303038629376096220705810392051811306346781109586874704038649462663607609703026899446700897805468523469478433049620763769703048626462527588699057922031708530766157520, 600, (3487389480797897696365973317725319279024291628823510087157417367333653055247026378723035864530191362158246567668330586346055181454849159690835592741030190066717051560723016303187256, 3363742471933461597145056275117342918322972124393361158647319798376523801041463613072727867517367031570963740650764218833475478082077882194508095483886422592665672916605829796092792, 3436807102602800871323230934741770968188321371840640958698201322820031910143640521523897893720599978558337273417541562810588560885987466333994341322768227794776729740100721991609528), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[27].vM / 3 + FurioLombardo.M4.T0.constant[27].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B27
