/-
The box check of the constant box 34 of twist 0 (disc 1, centre 61, size 6), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B34

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 61, 6, ⟨1, 61, 6, true, (247448, 254328, 136024), 0⟩, 396630719366396471556805667153510368475554958807791891287820589488171675847503321170540937610809753378204074664931459503541870831507323649519911776279811695550987728968526312507784, 600, (3498889690081415528723126870844785869765146982565829033135936932192960865606972424702936429079354613683958855720183875174273192501594114946314448704596761550263960159439453165438616, 3492607386979141323705173570106115869298635196990703900076094123107655935707417890128345645751324742834194351232146121511076942781023222694776250243428827910103640275482626322063736, 3446457833025715629667620163821144803282826854629633902229743719933756324595620442034504784875370827860679288452153844363175348428754391933593378684022786190842188443379660425139032), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[34].vM / 3 + FurioLombardo.M4.T0.constant[34].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B34
