/-
The box check of the constant box 30 of twist 0 (disc 1, centre 105, size 7), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B30

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 105, 7, ⟨1, 105, 7, true, (5560, 41336, 117816), 0⟩, 2966817606553648535783891491827406218087378740044878751997455979092340304985568494970196389770025811397231639374918112675919528067597698003471329186237158694498418920075122615966192, 600, (3421212532753877029820509325992476153846840699314704325248756508774954604830127251762428598511198660473745169013427983698803133522085820690891907394978532976329489640165181680784824, 3387693288704387398070414065864157608832644471212510478812822675166101169821180999706337131709226586845770757611179029378060138562592325739786506073965602791199445668817763522879864, 3182120006354174392650725327315671160034253253704096763363057474759211277312433205319123412380223786541956648217589220547371653503158702673513617756521006891131415134678869607304248), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[30].vM / 3 + FurioLombardo.M4.T0.constant[30].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B30
