/-
The box check of the constant box 39 of twist 0 (disc 1, centre 21, size 6), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B39

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 21, 6, ⟨1, 21, 6, true, (241880, 90232, 225560), 0⟩, 3411617217243922230357673215969502859397939474074080691018388999038788059483182099641166709525090008798894259440692366504307894517408541357174783816174802626787119559032549356669080, 600, (3552008041084393899341789134192472793565553055750943780376825175213132910589535359629074723215292374403906226136141348545688909067814705838774068382938515228329483986741434332721368, 3339190944807666079471230784692299847530476794911053854342618159128541299143833845810287405515422295018845190674722918341205056007040646984891181862823620329974694347189332765663352, 2979473274045242952640771844801821480078733549409959219814032683310246871919002644496643833222610127418513847637078173993045482694647953663254145510561675653922521771609305101857048), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[39].vM / 3 + FurioLombardo.M4.T0.constant[39].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B39
