/-
The box check of the constant box 31 of twist 0 (disc 1, centre 41, size 7), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B31

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 41, 7, ⟨1, 41, 7, true, (114616, 162168, 41528), 0⟩, 292776342418049035329372899351776186138877200898656345038864291968553748181384934809066539655623884923908283152409493481074737099272352851468332258818515743253751338345529995552880, 600, (3650377101478485062178720707662279596279390688746609012578141788227730279416471161322475259673474736575807161523557880046320239882612055376539842676510962404827506943572346526089144, 3477513405935279115357114784494054169756753461339181769049231546311274390810758202497433995022169960499987318920625549127157015400500976149560154821040277411011128594283206894844280, 3456975736119699495478098619296198491987538533199931318063176141341883126500632607398362232017359111384318196097233797289069079785839803887715610989637485796162092500695416311161400), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[31].vM / 3 + FurioLombardo.M4.T0.constant[31].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B31
