/-
The box check of the constant box 38 of twist 0 (disc 1, centre 53, size 6), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B38

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 53, 6, ⟨1, 53, 6, true, (170968, 138360, 26136), 0⟩, 650162548084433695403699388639998623635131908667215157288231139971486228459035975580844914085496110236866940790346182710771688022047407209450567719114976079653269802766842518331224, 600, (3479772510833661878196724651819365951550732107535563427715391994376031102149005920051308472184102079121023110372073586981394433534152720880810009471362358154325458688200476109741016, 3469276345809269729526419415752380266606956139481928616201642843014252505960103704169353014319925933650880130038230597853682253268554879685592957160684919492754050804763489450728568, 3279998223978883582152662433345787600536315352502632735792470012159761036584844836377413627276715058379943069342833264336881067815634415057522574159825860793255493157588358223914520), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[38].vM / 3 + FurioLombardo.M4.T0.constant[38].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B38
