/-
The box check of the constant box 3 of twist 0 (disc 1, centre 15, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B3

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 15, 5, ⟨1, 15, 5, true, (140344, 58984, 160088), 0⟩, 1941359040680763159890842384906174439619456829144809259935704334051339163243416616529756018785555387955711075428569339471476089013900536113167884034523275874380351167982941617133212, 600, (3206163509060887709653075841167065303990129027827638331648309619061242386265981019635607957376878588569214701027090996241702096048367785880991930580099358385236666932006056625316920, 3554070649914936088313162640135486846532346403395887807847601300870374749596574111621992067089062260716295913282830170723055125071559687550211521474914352104820698789261326830069352, 3461943998800854359270284397600853337891476215548993004701055286007209406193283975611657242900635919227647496098757919519659318595662364517892362020509362061903728859601039553884504), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 24
      (3 * (FurioLombardo.M4.T0.constant[3].vM / 3 + FurioLombardo.M4.T0.constant[3].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B3
