/-
The box check of the constant box 46 of twist 0 (disc 1, centre 26, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B46

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 26, 5, ⟨1, 26, 5, true, (242192, 66784, 185808), 0⟩, 594795463005368781682094928001300568510022761657591521821669227389185404610266636167097628397867950732316957513584462491643882222663997555095936079822586412635629220759319299579028, 600, (3537354431326592184069631501335958166780757164649235448809331048208207369360233296311613894615081629305846353651793669764211378456950803039294539360200227659360230699687152811225616, 3936019419770513264004814579831707934568230232805463827647131128740706222655977504623767582751370307290330530675955239982784757808574817759253687331317227595703266611915131665581280, 3733778979644662302229097483861294557390887333335908459462804556413447409337590905680321164997470263447111667503635421364059631875985867254047248273874867259249241350861794359825872), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 24
      (3 * (FurioLombardo.M4.T0.constant[46].vM / 3 + FurioLombardo.M4.T0.constant[46].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B46
