/-
The box check of the constant box 4 of twist 0 (disc 1, centre 23, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B4

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 23, 5, ⟨1, 23, 5, true, (59768, 150632, 216600), 0⟩, 450891078434432310437607977001846287876528516256910790179703612705508383169021830760289769670258395474880784470715196808610366376229890980104044808382303015983113560684084007756684, 600, (3273580952845245572043967909403390804945520889456536134164772797427472791714369753312056531004408688788506348318710660543955968280348083763283750672549124587812699592737124691536248, 3138709372463029395380481223123430532258024660375979914029586213680756552767547459039693824087443397360975460335997600315484510911376032296152940798879018361267975228533646471875688, 3550166556248482407862548572792918829411637242786653291885940539563228454728005749644203328302189032381221498815126504319474369506107088969491425255713233468675304872090368364989976), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 24
      (3 * (FurioLombardo.M4.T0.constant[4].vM / 3 + FurioLombardo.M4.T0.constant[4].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B4
