/-
The box check of the constant box 49 of twist 0 (disc 1, centre 2, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B49

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 2, 5, ⟨1, 2, 5, true, (158288, 46048, 195600), 0⟩, 346967691893135906924599854136339815134423606364389668335740633957008351824202209633597687987993562771721787233994842305786252529697773115572127728105043664759091210935129135608772, 600, (3725133255929235302731509817586878652368501524353037083495679693499257126983146418028384746968217758900630341453718493005931886466881290041548441150889626388141314364472038177532496, 3701756403648690715952770695969439873632025477097859654710575541955619095573248381359188009101487334920618500511823244731504628873841185400647907688140257308495414844644989063705568, 3765313078225253732371084364599587817841362634302841279420063949689638042532629057826622985753917678419651043989221828413748411753458872011258330453216526928677762331751195031305232), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 24
      (3 * (FurioLombardo.M4.T0.constant[49].vM / 3 + FurioLombardo.M4.T0.constant[49].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B49
