/-
The box check of the constant box 41 of twist 0 (disc 1, centre 5, size 6), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B41

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 5, 6, ⟨1, 5, 6, true, (31576, 191096, 46744), 0⟩, 2935465849233890866178667292839070714733180140382438206412793926680626314797541916889951616135768455270714035998481965270603466197230193424313723021814478873779021651831493408029496, 600, (3208286427881909220033403760901770526524926288376301039977962589639675799407193763779164533589660838257723201406778700152247334129392469905588849596723177481894814953616461998619480, 3396166203883937505280681976916399060132061532665090166861883798180324709264130536424155210039092442639742815539658556525674683365555122602602792530298501609021550419563647736408696, 3158349014770853641838495459836741041828897285437183530323897305066502087721057995520162897194045207902317042594522730431692749071162126162685018954724587999456649945815601187698328), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[41].vM / 3 + FurioLombardo.M4.T0.constant[41].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B41
