/-
The box check of the constant box 54 of twist 0 (disc 1, centre 416, size 9), order 5: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B54

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 416, 9, ⟨1, 416, 9, true, (127232, 90112, 260352), 0⟩, 2681724366752742443567347156605632398057514786546012647878001998127930628266811154810428351871005640535144282726655939633507318172851480937023984513419272208971968453776510575263168, 600, (4121876643094463606857382194547030797182136187971401919927297828646059315503430055264990111452852253498067061399946109394489432035040412206382318113706563099062005656376585023254784, 4125781044954532305802889903147546562775533463753930586526907605057847789366213260982772654572813842736624865161599701662205493507737539514274279493626652401643639906176196024033280, 4118274971335570936938208906461854113539271313086941879266160147331358498837521770932037935005603423377129875478254437915176435800600580459323871520315113364827249391564228220680448), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 5) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 5) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 36
      (3 * (FurioLombardo.M4.T0.constant[54].vM / 3 + FurioLombardo.M4.T0.constant[54].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B54
