/-
The box check of the constant box 57 of twist 0 (disc 1, centre 32, size 9), order 5: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B57

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 32, 9, ⟨1, 32, 9, true, (29952, 155648, 236800), 0⟩, 3785064753488403730988097732244225578668874293181503218881757587467287140311051960634600034430062818849082704914839279118810629511672339149007068128048745177615114958579301935998144, 600, (4123588030123349420288351063434220200396250038493665873449572003561592321789324299789263137864962357225199228705235762404069625910679348159377770240526804923478996645015442731857152, 4133110120158313640219926067101844045720270844595133416524550412258650898724057130799702785289802994669170236258517791531426501120499280322391186921276623767729905581897886590197760, 4125616570182312213251967132249772730309057529099677509585610375225567889281821234977301045313371174150729254775074567038666026400853121303190683837738026276732614137615127107837184), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 5) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 5) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 36
      (3 * (FurioLombardo.M4.T0.constant[57].vM / 3 + FurioLombardo.M4.T0.constant[57].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B57
