/-
The box check of the constant box 59 of twist 0 (disc 1, centre 112, size 8), order 4: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B59

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 112, 8, ⟨1, 112, 8, true, (121216, 219136, 177536), 0⟩, 1607759522363255301083063660841407165067664804563630306664092074817379216212807414252680727095843761508023774836441109127796973174155371616286800179548141048003951708851921802785440, 600, (4081493659166660807149295078658912562318728616069665320881114805245924771595795160952179191950576661676488894028211004971491124483667626980198652486910797232258482082462840175581568, 4101671686888498118887953733727606835103449865951193892155506212261476307728657039341891833215357891103783937670319684989727454207610674079976044949619990243403312814121022044198912, 4103825387455212722157532399614382830451326321199012482665827415108638757598042055043060351531471699836823167647434654542259697294593823374308840019104695808987267041041481821500800), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 4) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 4) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 33
      (3 * (FurioLombardo.M4.T0.constant[59].vM / 3 + FurioLombardo.M4.T0.constant[59].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B59
