/-
The box check of the constant box 5 of twist 0 (disc 1, centre 7, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B5

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 7, 5, ⟨1, 7, 5, true, (179960, 160872, 197784), 0⟩, 383616000001739145100275693034529811012131895318773452058149685360311220539436286474329894729605576052166722084459573203789790077917813596005816045204126028040534287894612290986668, 600, (3446502303408141683669329967406447595806373550104444196539827698376785050900581278548027315392062781864241460226171091271221736686428591890990744499726396398703137151428959926664952, 3396716501166251873422156887288856467932185680975201032360956559646512498799992973159145102649271215351524079573140257778860612105157316610680072421430543714771531963974176446772328, 3341276331148586288456073683233502616147211495220171700045092262935838403122265523115997866897013295692062521419828665038859443638036417279623625010679219065773160757396524903367832), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 24
      (3 * (FurioLombardo.M4.T0.constant[5].vM / 3 + FurioLombardo.M4.T0.constant[5].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B5
