/-
The box check of the constant box 53 of twist 0 (disc 1, centre 96, size 9), order 5: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B53

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 96, 9, ⟨1, 96, 9, true, (41216, 40960, 43264), 0⟩, 2615681142439401823262655688044715674362005179233707133299126884830231630772766946202849542910475371046943707710728467908613242552086090936450547357716043034900271691208725412331072, 600, (4119831024428534891296399769519616104139767082482801382281311772541936851778517499467003699192450134717477181200588032129941564538338888281681280281098353731634308582439888910590208, 4117382419961346664754060298231736431014106377630928818082031580095911561846512091734802177895593666439947194928000009496122477968167773550781014293716953496031116829519120038141952, 4122405161186556113152860806918408596565537222458301794913824854983588342773136124244683115243878223020052095894116057294383553692098368589808730712277975051718996170659055396497664), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 5) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 5) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 36
      (3 * (FurioLombardo.M4.T0.constant[53].vM / 3 + FurioLombardo.M4.T0.constant[53].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B53
