/-
The box check of the constant box 65 of twist 0 (disc 1, centre 16, size 8), order 4: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B65

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 16, 8, ⟨1, 16, 8, true, (165248, 141312, 188800), 0⟩, 2991142552925042549758372427523837390715299885988852131602087392669087990729081575709581819023518876743573906599916502932214050545404794176377310071891924892053443531406467970133088, 600, (4071744536916691233498201948773892332285170272075703287985891341548408830465127854463831547257697413077418620349191203131756503460319530804352895974924518464771912056730731804263808, 4128845641972661165501937189745411146449410096051813864286106603587639231202202359976901227215178659868082607729546974489931267583538749024912515371925333637811337889048222179403776, 4088847010785341913478624678253460737468703712783822905090146022688154893983107429341380741629448718994858041702401104034114059301018569344235406582023994228556405842248911059607936), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 4) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 4) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 33
      (3 * (FurioLombardo.M4.T0.constant[65].vM / 3 + FurioLombardo.M4.T0.constant[65].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B65
