/-
The box check of the constant box 66 of twist 0 (disc 1, centre 120, size 7), order 4: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B66

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 120, 7, ⟨1, 120, 7, true, (55616, 35328, 79680), 0⟩, 1191629211692709025645535793988126693121080807714143869876765528371255851301449672838804116969187249420101354778626529057724687023487890039506043037467973166157557146941297380264272, 600, (3995566981495746262900735459352282825681445141581400597089919862337432000565719904795252664699241951737416079573157578845786139436201013678685595508346828928985579184819750085646656, 4075829213806191486172856403320616637226715574594960999639580442527306812029755938030583120435073418764214905282881426922514482634422196901813066346123366985650764540901008240052736, 4045660043208802296547032690722384182565747429142796088160248553681838335092050370603012815751555741604054546017968806237276122472120594061409364671492345342374404455852672850671424), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 4) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 4) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[66].vM / 3 + FurioLombardo.M4.T0.constant[66].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B66
