/-
The box check of the constant box 68 of twist 0 (disc 1, centre 88, size 7), order 4: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B68

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 88, 7, ⟨1, 88, 7, true, (249408, 129536, 160832), 0⟩, 1188134023885644485397972148485423367167878409543608158549276979329634250487842048883139228540025218726878211595488487040420503452565857741803232095171005123670410004088054153609360, 600, (4020955450784294238758707365001523322002234531993053063131693596565548657445681532146288420079603990817750632944746173782057264440660243342390625840810797802244502434774692908748352, 4031638320714710960701286187640370934655813465593211441127781250303713517919364181725552218662504926352690592594469293577887253884351207246184486522196339667090212062568690079889920, 4020690917747808646338799645376713780731369023656339159663337773381946789721057356465541526300437063085044513302750049197900433627421519102692034912135291353062002489111196588733504), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 4) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 4) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[68].vM / 3 + FurioLombardo.M4.T0.constant[68].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B68
