/-
The box check of the constant box 69 of twist 0 (disc 1, centre 24, size 7), order 4: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B69

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 24, 7, ⟨1, 24, 7, true, (243776, 39424, 28224), 0⟩, 1735592188396651833274951502997320524241252980515304838312685446539155298525448400475150187206112491046015753551375422044156482036613205830861942109339457920470087353190130752323344, 600, (4086635384914379428793099810928372510018889941268843062444161207046282903742805867168144388788674117146971833384282368326870700036542463075433588736299410509425387869007993993148480, 4072746745433845523274427930114084276248373236158025981131641139505633474867028101628092220035928773172696095580829877004220202960105628431450219027922691261667302833048675843086848, 4028272568397622121787548870993779665769288371227268546773695631149964915239639706738338817339129480597251441932190243171714381941611444829126743214399069480473617041136378014101056), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 4) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 4) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[69].vM / 3 + FurioLombardo.M4.T0.constant[69].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B69
