/-
The box check of the constant box 77 of twist 0 (disc 1, centre 12, size 6), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B77

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 12, 6, ⟨1, 12, 6, true, (157664, 64896, 88544), 0⟩, 388011442481188281746101676643520160318261284422274253293282355464454965597256605337297521244451848439002756264966699488409720178532846949496530873742691556733053824492756827163944, 600, (4027891459639551026411984957893755056781037940140491648497805372005178481150976630746618437917516056850570228240418992337742411264042833369407436542028210902118467916792003439519712, 4000266157813605988571590341068255398757690305832225578326388638916628170663904641104281986016656217539413248085211025263350952887042455309764252209348772628786624585559096866438528, 3977460478867424134590744841436605115087790565013919587640221432540723754255740939502867771284358638466014120268317681179237692182731547394406141439803740685329206599032318538635744), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[77].vM / 3 + FurioLombardo.M4.T0.constant[77].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B77
