/-
The box check of the constant box 7 of twist 0 (disc 1, centre 11, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B7

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 11, 5, ⟨1, 11, 5, true, (79256, 219880, 164088), 0⟩, 3527976185252939184340438636319122262148116686333215164174601526166099918915726400985810788606949657359034640018171457282484808911393656998673603230792139600435993160901494997256836, 600, (3549149427162279943943356975292017472402895115352554920816843128006562021842227170301712478456794382787878043968961954453728940582731255337895090276102893550704081457115985055659416, 3234943581228855119985398137203642418161630028105875041686152614016327050654601000986282585136625491245676479750329578585858577787751502665224485398638033330324439513351864894577384, 3747390566183048208605739872508772923247962050495344309026455900628928067212128407500188827265458863060402372371857252884980144174374886951902779589901502233249142961568434010620152), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 24
      (3 * (FurioLombardo.M4.T0.constant[7].vM / 3 + FurioLombardo.M4.T0.constant[7].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B7
