/-
The box check of the constant box 71 of twist 0 (disc 1, centre 40, size 7), order 3: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B71

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 40, 7, ⟨1, 40, 7, true, (197184, 230912, 163904), 0⟩, 1098909580627320825613225942205162041069040535378928557472584319183191971014058680597757858581230240920106930664788753154110460910598761462550994770754788159622057739012629454859632, 600, (4050003374280133030187067524754637302116924965813535692200365779160224242869897397477762370210790779243399145392875696816015317026773938537014682615678611153156730250690669707199040, 4073956404952032874594855103148498362710630481241085139758162520119853596137635164644809950940598578115095087709313819705468070116380338051343938310128620424150367984252998585648640, 4072462966073730010171528090242161854313295772062847506265357488072866156317150187327810243864380482265375213455282234322123533367876790532110046659038979459857090819079374088339520), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 3) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 3) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 30
      (3 * (FurioLombardo.M4.T0.constant[71].vM / 3 + FurioLombardo.M4.T0.constant[71].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B71
