/-
The box check of the constant box 78 of twist 0 (disc 1, centre 52, size 6), order 3: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B78

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 52, 6, ⟨1, 52, 6, true, (91616, 27264, 252384), 0⟩, 1190026867928733121705780297103235864373911644624282934964066376677718386726535243482227002957047419027862497107698269570385874807741866668185629011195279284441683705236240058644248, 600, (4035868156921495935529966644349101029533790746858053657179249550078821201935967351607463251215315211253715769911699620082191749671703986188711931201110312736551289649359833800467936, 3937029346082312639584937981891112647859246248738933045219694991495524074980020826164091358320162903216118136570109106146639581334686832709658577074807976551360775206451705816836736, 3976424165468932096949285960725043708552726389589669209998330139016408611638081849925363454112088975825402203719121850337915696769337557351537194632151062186807641277600853917161952), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 3) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 3) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[78].vM / 3 + FurioLombardo.M4.T0.constant[78].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B78
