/-
The box check of the constant box 75 of twist 0 (disc 1, centre 28, size 6), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B75

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 28, 6, ⟨1, 28, 6, true, (16992, 18816, 168032), 0⟩, 2295965823960762616188276953247239991958711320090853290304042825716749251037843458132041631295422063519998097230117162520725816284611904119325168878966115002618260559662877842773640, 600, (3932737151847144591622473301133453487361786563526821435679155498458316743477921565273850098326350424342230025749823525725554773736246579712081039108392346238527477756609510020760160, 3954261947852556595324807907750051181716077198364944908609205659953014534887623750108516657589350469373916736150434426255321628251161645921771229341251539337996653026451492503308672, 3919630822666536735093051528665129579178165378840005495449720086593891773463145450925111708051911295234982805930333225888066636619752287967128935475740352158670715925802674932060256), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[75].vM / 3 + FurioLombardo.M4.T0.constant[75].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B75
