/-
The box check of the constant box 81 of twist 0 (disc 1, centre 4, size 6), order 3: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B81

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 4, 6, ⟨1, 4, 6, true, (210272, 54912, 200032), 0⟩, 1076519769727972066132344232461815582799991863699208993049360315109926828637521599442927860388873263166593326007170244855310983358952604006058623972531535335911248254548600898496760, 600, (3986130348412950207014707740094061891747850835781913835476067265103363760459215021290493596997493004936723326255901569111385160117631304094579045311171037970802865667766799635264864, 3966846307396413145491416240138454244889148753786356710743774595007723864868357500194683000193607589271824052643578742152626772321032093265081791693461951891404259305150236379108992, 3918428279626244132125979955958697423142872877689945109942082777053873768748512970114668505453944711120275942537649132879370841791247711949246084928000435355203062960843529069727072), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 3) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 3) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[81].vM / 3 + FurioLombardo.M4.T0.constant[81].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B81
