/-
The box check of the constant box 8 of twist 0 (disc 1, centre 19, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B8

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 19, 5, ⟨1, 19, 5, true, (240344, 93928, 48568), 0⟩, 460836961516747855187003066664403791563362312761739442749514366692301623303779958603754087548246906783313752368973806169224272031136234270455629672948695199005496516357054167521524, 600, (3720797258726163076779077472078052555310595713702850576878204167054798497112392348562227917832814986914950541932255328730326588096384367186735645095530406220093030527808939541113560, 3148400099038294031217084299011663161619016600040768074709841519655191126037849124340771768414485527765585965343513948887857901454196627711103315781325778186508906679434988881800936, 3277481707793158563902462496352963620761609532287356178581018755861908628899691993112201692500703603056250054785335556229160179593581419450388274890449667855699467076074382110801336), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 24
      (3 * (FurioLombardo.M4.T0.constant[8].vM / 3 + FurioLombardo.M4.T0.constant[8].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B8
