/-
The box check of the tail box 0 of twist 0 (disc 1, centre 1, size 6), order 2: `boxRun` and `tailOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B82

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 1, 6, ⟨1, 1, 6, true, (214536, 61832, 145416), 0⟩, 0, 600, (3511324362476446378558013702195948951377649972683229905102012837337550862673450522670640845767109728847104541288657901837655022646397694599177569945403722878642949228978898311529992, 3156573416540011354381344050788442526707380901238318829835905768660623090835425534062014327203556850962840894901216772592087015972630914335538388782996349612036997370015545412874632, 3282978320526635674274102878420516520984106074314180206393128735283280703030391406520224136918054475415754355292670522549265417814699690703368446795199311879631124764042597138315272), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (tailOK (B.ctx dCtx 2) DCertData.Tw0.b DCertData.Tw0.A (IntModelKv.aa 0) (M0 0) 27 9 15
      FurioLombardo.M4.T0.tails[0].q FurioLombardo.M4.T0.tails[0].g) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B82
