/-
The box check of the tail box 1 of twist 0 (disc 1, centre 0, size 6), order 2: `boxRun` and `tailOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B83

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 0, 6, ⟨1, 0, 6, false, (38265, 142521, 82213), 0⟩, 0, 600, (833495838482652694422925459347087663973559051411518146339323986694760650546930385252640482354263196836719772864518311217312662944932403293167662832007883824367816055252897834243449, 1996801182234404782940892864046829915026150349612791107680875538252378196914873577508384627196056416442683584664376724033999592716927815222016651557101047431815735668915484044176569, 2098495339373981229287723806161950394280981590817632497131343194564172493298110778124085974736861230462308331672433616484307997384110445262078311496994463083448570801535040315015461), 0, ⟨2, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (tailOK (B.ctx dCtx 2) DCertData.Tw0.b DCertData.Tw0.A (IntModelKv.aa 0) (M0 0) 27 9 15
      FurioLombardo.M4.T0.tails[1].q FurioLombardo.M4.T0.tails[1].g) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B83
