/-
The box check of the constant box 80 of twist 0 (disc 1, centre 36, size 6), order 3: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B80

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 36, 6, ⟨1, 36, 6, true, (98400, 48768, 139360), 0⟩, 805596265661881788621039480372154259296918949872391357579141066011734960302597006921017793127504580217447172268870818189376184486616028161815027694347611836523018900329901671406520, 600, (3922632015809808616401941118245169481545782268912023408790110639866233352043548855532636594847892465002159669479356516444341408333680375602605657924906813304614459321314477322633312, 3946507205296122192428881955089776894668968373835116028239927266555189980508871354771770655168974307656530701015916959707027210251925279470836672949714440730583324919119529846816384, 3917842825330051314478561299572944135280042045466217639843783485819531260890506579483249699010354704154235020101349139499987906676074160768092281132583576230938689177730156143452256), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 3) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 3) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 27
      (3 * (FurioLombardo.M4.T0.constant[80].vM / 3 + FurioLombardo.M4.T0.constant[80].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B80
