/-
The box check of the constant box 9 of twist 0 (disc 1, centre 3, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values0.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist0
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K0B9

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨0, 1, 3, 5, ⟨1, 3, 5, true, (106584, 187112, 136248), 0⟩, 3995646998300387677642459588450297126812762892361596270519757023960065332412877601740955140199822731679951687924468957824061894772313072294862400526233232213276323572635164314782996, 600, (3345246464261249073036865299960124859799589804476303173055601498583231199903913907543174609410770922745584180279016486084497031635204623781714113948323687772110516317917279033860184, 3506475997281073594700209038780407182888278197358377915564987161706816579981431013979675547675242935942121787149367136557482391992132254327718836042237325452429327404837819428821736, 3163971630211204594185139162016164306091978866825637477154643044074860696914117108697857088151540172549594093402987466867874809676310326658223493459054271012506725141566008686679096), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw0.g DCertData.Tw0.E DCertData.Tw0.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw0.b (IntModelKv.aa 0) (M0 0) 24
      (3 * (FurioLombardo.M4.T0.constant[9].vM / 3 + FurioLombardo.M4.T0.constant[9].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K0B9
