/-
The box check of the constant box 0 of twist 1 (disc 3, centre 28, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values1.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist1
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K1B0

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨1, 3, 28, 5, ⟨3, 28, 5, true, (122213, 202069, 174962), 0⟩, 3508580424120665078667672297737390658427205360003393736345094945526456647163705604745134657901491772227006770970778533292287106331093093391449167560780129254891787566191108919199172, 600, (1580963315293159426140163054980060460019740362121105790854299324430140218205180792129743983795989964161820126777397861754842727491849666726705010526055846603175215876948999853694309, 3735630426582477217158133155574096870107915435873930003577112949737248203411924947714523507090517707037889479344783189409264954770406896062113474690740380220907074210985535062873429, 2256543364346610982788873795431858246522635459686711829661436444075047459430957584219929210952870459845005645542796751306404271091282561167461818462525497640137792144793880368950130), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw1.g DCertData.Tw1.E DCertData.Tw1.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw1.b (IntModelKv.aa 1) (M0 1) 18
      (3 * (FurioLombardo.M4.T1.constant[0].vM / 3 + FurioLombardo.M4.T1.constant[0].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K1B0
