/-
The box check of the constant box 1 of twist 1 (disc 3, centre 12, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values1.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist1
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K1B1

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨1, 3, 12, 5, ⟨3, 12, 5, true, (54069, 169893, 184914), 0⟩, 1562384717458305357729927529219951639541237732768196175597944136723189631965777348365935576509105575939263125156523647357470228766984521033185591182572677878547897171342389996654484, 600, (1995287862620996067662688353925085976687078839595112293558652622180920578029567218616743618921893563672108609714663070296456679385006039228985865823613413592108135363853168220361525, 1529268464648207413300343064185995050210239631815452666892583044359534615771804896062627159792268916166676652955128133494941083149428969449489470453838776728639837652162148324513701, 2431650382745171919415271828144467224462887799744325609253537010164839166025268508992056338911903614700260193892418302261067103878906767595688733449499461282804873107142085392126546), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw1.g DCertData.Tw1.E DCertData.Tw1.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw1.b (IntModelKv.aa 1) (M0 1) 18
      (3 * (FurioLombardo.M4.T1.constant[1].vM / 3 + FurioLombardo.M4.T1.constant[1].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K1B1
