/-
The box check of the constant box 14 of twist 1 (disc 3, centre 40, size 6), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values1.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist1
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K1B14

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨1, 3, 40, 6, ⟨3, 40, 6, true, (133185, 170193, 98618), 0⟩, 2353885791771650866483810310624201745462096280521121802044737899717058827399471509429482947735568188141826592235087439600001595106664899534057158685626127644897350177332232166197880, 600, (73874826391086491517889481304415883372707920475562449014768964835435575185426159302744080137446904507951292252721106737654037463971214207670796142483904772153993325824564708378689, 2623920754066908206362036055455679000734613273643143080127419005814443275497595721883391547492329196157190641267643600152191847297689126056606089450883020724554235502178008564930769, 2876970117221032460872848157724309099355722922124219081225838328279060205592805152202071636830891795606970625702314738022459950056693727712301535977482358093533019129075937799143738), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw1.g DCertData.Tw1.E DCertData.Tw1.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw1.b (IntModelKv.aa 1) (M0 1) 21
      (3 * (FurioLombardo.M4.T1.constant[14].vM / 3 + FurioLombardo.M4.T1.constant[14].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K1B14
