/-
The box check of the constant box 3 of twist 1 (disc 3, centre 4, size 5), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values1.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist1
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K1B3

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨1, 3, 4, 5, ⟨3, 4, 5, true, (222013, 102893, 25602), 0⟩, 4047176063378906517010296944698546904086798349424529861616833691156366753568607257810711069703746393234707434540891298657586621145505504332286014755659075172088117972167906081695804, 600, (630032022140494350875291710179565751392202109688898546593540276640471291147469384718969418673794354282727316884671471534619156266065668056839178777374805190310576750758029429531453, 3992545802033165163177076441414780731729565483183571750161437800743827353360392039130797035601112277907236739120615219543818928837950805913301925921977583301852628345102446666027501, 2496219048230144097470644555080132405894222676471665868031615282556059628155120808099905627150173399510545603352101816061992777813073458996571622023187695091254572085883338741015554), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw1.g DCertData.Tw1.E DCertData.Tw1.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw1.b (IntModelKv.aa 1) (M0 1) 18
      (3 * (FurioLombardo.M4.T1.constant[3].vM / 3 + FurioLombardo.M4.T1.constant[3].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K1B3
