/-
The box check of the constant box 4 of twist 1 (disc 3, centre 224, size 8), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values1.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist1
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K1B4

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨1, 3, 224, 8, ⟨3, 224, 8, true, (162601, 201209, 160938), 0⟩, 1554534168457742254295872154873156269625324677128248344513914374621865365650497619393604909092963739235098302348002346720599226211567224354209345749365036455824546645413238667397024, 600, (1605486568967448042102679365057128385561346117897934937070626034951215822692241129921531104604436802042863219787209869872350547362014385627387913433990604129316040570998606003862313, 431411968340220253139028224320104994538194771180395997146372036855267385459709570699635890305765823818185005607306720611114945991508937362000592913427862949016448628117819509903865, 1143688950201780728905223593261117757183589340761255357222792796900151321920220345407164128764715911538142547482915917369678273095805732343673899021168336082101786113095247085335722), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw1.g DCertData.Tw1.E DCertData.Tw1.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw1.b (IntModelKv.aa 1) (M0 1) 27
      (3 * (FurioLombardo.M4.T1.constant[4].vM / 3 + FurioLombardo.M4.T1.constant[4].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K1B4
