/-
The box check of the constant box 5 of twist 1 (disc 3, centre 96, size 8), order 2: `boxRun` and `constOK` in one kernel check
(`constCert_of_ok`, `tailCert_of_ok` are applied in BoxData/Values1.lean).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); the check is done by the kernel.
-/
import FurioLombardo.Discharge.M4Box.DCertData.Twist1
import FurioLombardo.Discharge.M4Box.Comp.BoxTM
import FurioLombardo.M4.Data
import FurioLombardo.Discharge.M4Log.IntModelKv

namespace FurioLombardo.Discharge.M4Box.BoxData.K1B5

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

set_option maxRecDepth 100000

noncomputable def B : BoxSpec :=
  ⟨1, 3, 96, 8, ⟨3, 96, 8, true, (168873, 28281, 233386), 0⟩, 3767408397418287436677804194864471604012734067268624124947967991046359043841744116466229677733439799413481226680247827664139225370202138353959261948620275116632642019546249160559136, 600, (388354855162506139747492915291401973751263911911462416546140891303107415284206071712201485376111060602804191057370655903798037456038904881301663929315224230243760257320980798411689, 1680027725346077691281550491965423839090301720697392424576982806423862050354797631672748643650131624466895311101514732369419127455586114827807390396890818876068948597664272592694905, 3176951603417494756657491656793689006775041913794707868076501359631893762942406854284848641929220175440877283016084746678015482043257115635940264343843985369424754652987070952214442), 0, ⟨0, 0, 0⟩⟩

theorem ok : (boxRun (B.ctx dCtx 2) DCertData.Tw1.g DCertData.Tw1.E DCertData.Tw1.A B).any
    (constOK (B.ctx dCtx 2) DCertData.Tw1.b (IntModelKv.aa 1) (M0 1) 27
      (3 * (FurioLombardo.M4.T1.constant[5].vM / 3 + FurioLombardo.M4.T1.constant[5].s))) = true := by
  decide +kernel

end FurioLombardo.Discharge.M4Box.BoxData.K1B5
