/-
The per box statements of twist 0: `ConstCert` for the 82 boxes of `T0.constant` and `TailCert` for the 2 boxes of
`T0.tails`, from the checks `K0B<i>.ok` of the data files K0B<i>.lean (`constCert_of_ok`, `tailCert_of_ok`).
Generated by code/covering/box_certs_gen.lean (lane lean-m4box); every value is checked by the kernel.
-/
import FurioLombardo.Discharge.M4Box.BoxOk
import FurioLombardo.Discharge.M4Box.BoxData.K0B0
import FurioLombardo.Discharge.M4Box.BoxData.K0B1
import FurioLombardo.Discharge.M4Box.BoxData.K0B2
import FurioLombardo.Discharge.M4Box.BoxData.K0B3
import FurioLombardo.Discharge.M4Box.BoxData.K0B4
import FurioLombardo.Discharge.M4Box.BoxData.K0B5
import FurioLombardo.Discharge.M4Box.BoxData.K0B6
import FurioLombardo.Discharge.M4Box.BoxData.K0B7
import FurioLombardo.Discharge.M4Box.BoxData.K0B8
import FurioLombardo.Discharge.M4Box.BoxData.K0B9
import FurioLombardo.Discharge.M4Box.BoxData.K0B10
import FurioLombardo.Discharge.M4Box.BoxData.K0B11
import FurioLombardo.Discharge.M4Box.BoxData.K0B12
import FurioLombardo.Discharge.M4Box.BoxData.K0B13
import FurioLombardo.Discharge.M4Box.BoxData.K0B14
import FurioLombardo.Discharge.M4Box.BoxData.K0B15
import FurioLombardo.Discharge.M4Box.BoxData.K0B16
import FurioLombardo.Discharge.M4Box.BoxData.K0B17
import FurioLombardo.Discharge.M4Box.BoxData.K0B18
import FurioLombardo.Discharge.M4Box.BoxData.K0B19
import FurioLombardo.Discharge.M4Box.BoxData.K0B20
import FurioLombardo.Discharge.M4Box.BoxData.K0B21
import FurioLombardo.Discharge.M4Box.BoxData.K0B22
import FurioLombardo.Discharge.M4Box.BoxData.K0B23
import FurioLombardo.Discharge.M4Box.BoxData.K0B24
import FurioLombardo.Discharge.M4Box.BoxData.K0B25
import FurioLombardo.Discharge.M4Box.BoxData.K0B26
import FurioLombardo.Discharge.M4Box.BoxData.K0B27
import FurioLombardo.Discharge.M4Box.BoxData.K0B28
import FurioLombardo.Discharge.M4Box.BoxData.K0B29
import FurioLombardo.Discharge.M4Box.BoxData.K0B30
import FurioLombardo.Discharge.M4Box.BoxData.K0B31
import FurioLombardo.Discharge.M4Box.BoxData.K0B32
import FurioLombardo.Discharge.M4Box.BoxData.K0B33
import FurioLombardo.Discharge.M4Box.BoxData.K0B34
import FurioLombardo.Discharge.M4Box.BoxData.K0B35
import FurioLombardo.Discharge.M4Box.BoxData.K0B36
import FurioLombardo.Discharge.M4Box.BoxData.K0B37
import FurioLombardo.Discharge.M4Box.BoxData.K0B38
import FurioLombardo.Discharge.M4Box.BoxData.K0B39
import FurioLombardo.Discharge.M4Box.BoxData.K0B40
import FurioLombardo.Discharge.M4Box.BoxData.K0B41
import FurioLombardo.Discharge.M4Box.BoxData.K0B42
import FurioLombardo.Discharge.M4Box.BoxData.K0B43
import FurioLombardo.Discharge.M4Box.BoxData.K0B44
import FurioLombardo.Discharge.M4Box.BoxData.K0B45
import FurioLombardo.Discharge.M4Box.BoxData.K0B46
import FurioLombardo.Discharge.M4Box.BoxData.K0B47
import FurioLombardo.Discharge.M4Box.BoxData.K0B48
import FurioLombardo.Discharge.M4Box.BoxData.K0B49
import FurioLombardo.Discharge.M4Box.BoxData.K0B50
import FurioLombardo.Discharge.M4Box.BoxData.K0B51
import FurioLombardo.Discharge.M4Box.BoxData.K0B52
import FurioLombardo.Discharge.M4Box.BoxData.K0B53
import FurioLombardo.Discharge.M4Box.BoxData.K0B54
import FurioLombardo.Discharge.M4Box.BoxData.K0B55
import FurioLombardo.Discharge.M4Box.BoxData.K0B56
import FurioLombardo.Discharge.M4Box.BoxData.K0B57
import FurioLombardo.Discharge.M4Box.BoxData.K0B58
import FurioLombardo.Discharge.M4Box.BoxData.K0B59
import FurioLombardo.Discharge.M4Box.BoxData.K0B60
import FurioLombardo.Discharge.M4Box.BoxData.K0B61
import FurioLombardo.Discharge.M4Box.BoxData.K0B62
import FurioLombardo.Discharge.M4Box.BoxData.K0B63
import FurioLombardo.Discharge.M4Box.BoxData.K0B64
import FurioLombardo.Discharge.M4Box.BoxData.K0B65
import FurioLombardo.Discharge.M4Box.BoxData.K0B66
import FurioLombardo.Discharge.M4Box.BoxData.K0B67
import FurioLombardo.Discharge.M4Box.BoxData.K0B68
import FurioLombardo.Discharge.M4Box.BoxData.K0B69
import FurioLombardo.Discharge.M4Box.BoxData.K0B70
import FurioLombardo.Discharge.M4Box.BoxData.K0B71
import FurioLombardo.Discharge.M4Box.BoxData.K0B72
import FurioLombardo.Discharge.M4Box.BoxData.K0B73
import FurioLombardo.Discharge.M4Box.BoxData.K0B74
import FurioLombardo.Discharge.M4Box.BoxData.K0B75
import FurioLombardo.Discharge.M4Box.BoxData.K0B76
import FurioLombardo.Discharge.M4Box.BoxData.K0B77
import FurioLombardo.Discharge.M4Box.BoxData.K0B78
import FurioLombardo.Discharge.M4Box.BoxData.K0B79
import FurioLombardo.Discharge.M4Box.BoxData.K0B80
import FurioLombardo.Discharge.M4Box.BoxData.K0B81
import FurioLombardo.Discharge.M4Box.BoxData.K0B82
import FurioLombardo.Discharge.M4Box.BoxData.K0B83

namespace FurioLombardo.Discharge.M4Box.BoxData

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

theorem K0B0.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[0] :=
  constCert_of_ok 0 K0B0.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 5 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B0.ok

theorem K0B1.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[1] :=
  constCert_of_ok 0 K0B1.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 5 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B1.ok

theorem K0B2.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[2] :=
  constCert_of_ok 0 K0B2.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B2.ok

theorem K0B3.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[3] :=
  constCert_of_ok 0 K0B3.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B3.ok

theorem K0B4.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[4] :=
  constCert_of_ok 0 K0B4.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B4.ok

theorem K0B5.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[5] :=
  constCert_of_ok 0 K0B5.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B5.ok

theorem K0B6.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[6] :=
  constCert_of_ok 0 K0B6.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B6.ok

theorem K0B7.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[7] :=
  constCert_of_ok 0 K0B7.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B7.ok

theorem K0B8.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[8] :=
  constCert_of_ok 0 K0B8.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B8.ok

theorem K0B9.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[9] :=
  constCert_of_ok 0 K0B9.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B9.ok

theorem K0B10.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[10] :=
  constCert_of_ok 0 K0B10.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B10.ok

theorem K0B11.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[11] :=
  constCert_of_ok 0 K0B11.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B11.ok

theorem K0B12.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[12] :=
  constCert_of_ok 0 K0B12.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B12.ok

theorem K0B13.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[13] :=
  constCert_of_ok 0 K0B13.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B13.ok

theorem K0B14.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[14] :=
  constCert_of_ok 0 K0B14.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B14.ok

theorem K0B15.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[15] :=
  constCert_of_ok 0 K0B15.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B15.ok

theorem K0B16.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[16] :=
  constCert_of_ok 0 K0B16.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B16.ok

theorem K0B17.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[17] :=
  constCert_of_ok 0 K0B17.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B17.ok

theorem K0B18.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[18] :=
  constCert_of_ok 0 K0B18.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B18.ok

theorem K0B19.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[19] :=
  constCert_of_ok 0 K0B19.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B19.ok

theorem K0B20.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[20] :=
  constCert_of_ok 0 K0B20.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B20.ok

theorem K0B21.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[21] :=
  constCert_of_ok 0 K0B21.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B21.ok

theorem K0B22.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[22] :=
  constCert_of_ok 0 K0B22.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B22.ok

theorem K0B23.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[23] :=
  constCert_of_ok 0 K0B23.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B23.ok

theorem K0B24.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[24] :=
  constCert_of_ok 0 K0B24.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B24.ok

theorem K0B25.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[25] :=
  constCert_of_ok 0 K0B25.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B25.ok

theorem K0B26.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[26] :=
  constCert_of_ok 0 K0B26.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B26.ok

theorem K0B27.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[27] :=
  constCert_of_ok 0 K0B27.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B27.ok

theorem K0B28.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[28] :=
  constCert_of_ok 0 K0B28.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B28.ok

theorem K0B29.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[29] :=
  constCert_of_ok 0 K0B29.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B29.ok

theorem K0B30.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[30] :=
  constCert_of_ok 0 K0B30.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B30.ok

theorem K0B31.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[31] :=
  constCert_of_ok 0 K0B31.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B31.ok

theorem K0B32.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[32] :=
  constCert_of_ok 0 K0B32.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B32.ok

theorem K0B33.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[33] :=
  constCert_of_ok 0 K0B33.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B33.ok

theorem K0B34.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[34] :=
  constCert_of_ok 0 K0B34.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B34.ok

theorem K0B35.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[35] :=
  constCert_of_ok 0 K0B35.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B35.ok

theorem K0B36.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[36] :=
  constCert_of_ok 0 K0B36.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B36.ok

theorem K0B37.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[37] :=
  constCert_of_ok 0 K0B37.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B37.ok

theorem K0B38.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[38] :=
  constCert_of_ok 0 K0B38.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B38.ok

theorem K0B39.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[39] :=
  constCert_of_ok 0 K0B39.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B39.ok

theorem K0B40.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[40] :=
  constCert_of_ok 0 K0B40.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B40.ok

theorem K0B41.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[41] :=
  constCert_of_ok 0 K0B41.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B41.ok

theorem K0B42.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[42] :=
  constCert_of_ok 0 K0B42.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B42.ok

theorem K0B43.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[43] :=
  constCert_of_ok 0 K0B43.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B43.ok

theorem K0B44.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[44] :=
  constCert_of_ok 0 K0B44.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B44.ok

theorem K0B45.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[45] :=
  constCert_of_ok 0 K0B45.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B45.ok

theorem K0B46.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[46] :=
  constCert_of_ok 0 K0B46.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B46.ok

theorem K0B47.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[47] :=
  constCert_of_ok 0 K0B47.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B47.ok

theorem K0B48.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[48] :=
  constCert_of_ok 0 K0B48.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B48.ok

theorem K0B49.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[49] :=
  constCert_of_ok 0 K0B49.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B49.ok

theorem K0B50.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[50] :=
  constCert_of_ok 0 K0B50.B 5 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B50.ok

theorem K0B51.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[51] :=
  constCert_of_ok 0 K0B51.B 5 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B51.ok

theorem K0B52.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[52] :=
  constCert_of_ok 0 K0B52.B 5 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B52.ok

theorem K0B53.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[53] :=
  constCert_of_ok 0 K0B53.B 5 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B53.ok

theorem K0B54.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[54] :=
  constCert_of_ok 0 K0B54.B 5 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B54.ok

theorem K0B55.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[55] :=
  constCert_of_ok 0 K0B55.B 5 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B55.ok

theorem K0B56.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[56] :=
  constCert_of_ok 0 K0B56.B 5 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B56.ok

theorem K0B57.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[57] :=
  constCert_of_ok 0 K0B57.B 5 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B57.ok

theorem K0B58.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[58] :=
  constCert_of_ok 0 K0B58.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B58.ok

theorem K0B59.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[59] :=
  constCert_of_ok 0 K0B59.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B59.ok

theorem K0B60.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[60] :=
  constCert_of_ok 0 K0B60.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B60.ok

theorem K0B61.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[61] :=
  constCert_of_ok 0 K0B61.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B61.ok

theorem K0B62.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[62] :=
  constCert_of_ok 0 K0B62.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B62.ok

theorem K0B63.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[63] :=
  constCert_of_ok 0 K0B63.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B63.ok

theorem K0B64.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[64] :=
  constCert_of_ok 0 K0B64.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B64.ok

theorem K0B65.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[65] :=
  constCert_of_ok 0 K0B65.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B65.ok

theorem K0B66.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[66] :=
  constCert_of_ok 0 K0B66.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B66.ok

theorem K0B67.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[67] :=
  constCert_of_ok 0 K0B67.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B67.ok

theorem K0B68.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[68] :=
  constCert_of_ok 0 K0B68.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B68.ok

theorem K0B69.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[69] :=
  constCert_of_ok 0 K0B69.B 4 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B69.ok

theorem K0B70.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[70] :=
  constCert_of_ok 0 K0B70.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B70.ok

theorem K0B71.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[71] :=
  constCert_of_ok 0 K0B71.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B71.ok

theorem K0B72.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[72] :=
  constCert_of_ok 0 K0B72.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B72.ok

theorem K0B73.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[73] :=
  constCert_of_ok 0 K0B73.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B73.ok

theorem K0B74.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[74] :=
  constCert_of_ok 0 K0B74.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B74.ok

theorem K0B75.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[75] :=
  constCert_of_ok 0 K0B75.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B75.ok

theorem K0B76.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[76] :=
  constCert_of_ok 0 K0B76.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B76.ok

theorem K0B77.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[77] :=
  constCert_of_ok 0 K0B77.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B77.ok

theorem K0B78.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[78] :=
  constCert_of_ok 0 K0B78.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B78.ok

theorem K0B79.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[79] :=
  constCert_of_ok 0 K0B79.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B79.ok

theorem K0B80.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[80] :=
  constCert_of_ok 0 K0B80.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B80.ok

theorem K0B81.cert : ConstCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.constant[81] :=
  constCert_of_ok 0 K0B81.B 3 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) K0B81.ok

theorem K0B82.cert : TailCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.tails[0] :=
  tailCert_of_ok 0 K0B82.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) (by decide +kernel) (by decide +kernel) K0B82.ok

theorem K0B83.cert : TailCert 0 (IntModelKv.admM0 0) FurioLombardo.M4.T0.tails[1] :=
  tailCert_of_ok 0 K0B83.B 2 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (by decide +kernel)
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA
    (by decide +kernel) (by decide +kernel) (by decide +kernel) K0B83.ok

theorem constCert_0 : ∀ c ∈ FurioLombardo.M4.T0.data.constant, ConstCert 0 (IntModelKv.admM0 0) c := by
  intro c hc
  obtain ⟨i, hi, rfl⟩ := List.mem_iff_getElem.mp hc
  have hi' : i < 82 := hi
  interval_cases i
  exacts [K0B0.cert, K0B1.cert, K0B2.cert, K0B3.cert, K0B4.cert, K0B5.cert, K0B6.cert, K0B7.cert, K0B8.cert, K0B9.cert, K0B10.cert, K0B11.cert, K0B12.cert, K0B13.cert, K0B14.cert, K0B15.cert, K0B16.cert, K0B17.cert, K0B18.cert, K0B19.cert, K0B20.cert, K0B21.cert, K0B22.cert, K0B23.cert, K0B24.cert, K0B25.cert, K0B26.cert, K0B27.cert, K0B28.cert, K0B29.cert, K0B30.cert, K0B31.cert, K0B32.cert, K0B33.cert, K0B34.cert, K0B35.cert, K0B36.cert, K0B37.cert, K0B38.cert, K0B39.cert, K0B40.cert, K0B41.cert, K0B42.cert, K0B43.cert, K0B44.cert, K0B45.cert, K0B46.cert, K0B47.cert, K0B48.cert, K0B49.cert, K0B50.cert, K0B51.cert, K0B52.cert, K0B53.cert, K0B54.cert, K0B55.cert, K0B56.cert, K0B57.cert, K0B58.cert, K0B59.cert, K0B60.cert, K0B61.cert, K0B62.cert, K0B63.cert, K0B64.cert, K0B65.cert, K0B66.cert, K0B67.cert, K0B68.cert, K0B69.cert, K0B70.cert, K0B71.cert, K0B72.cert, K0B73.cert, K0B74.cert, K0B75.cert, K0B76.cert, K0B77.cert, K0B78.cert, K0B79.cert, K0B80.cert, K0B81.cert]

theorem tailCert_0 : ∀ b ∈ FurioLombardo.M4.T0.data.tails, TailCert 0 (IntModelKv.admM0 0) b := by
  intro b hb
  obtain ⟨i, hi, rfl⟩ := List.mem_iff_getElem.mp hb
  have hi' : i < 2 := hi
  interval_cases i
  exacts [K0B82.cert, K0B83.cert]

end FurioLombardo.Discharge.M4Box.BoxData
