import Mathlib
import FurioLombardo.M3a.Hypotheses
import FurioLombardo.M4.Checks

/-!
# (K2) `SelmerInjective` from a Selmer span and the local independence

M3a's `SelmerInjective σ f` says: `μ(Q)` trivial at `v` implies `μ(Q)` trivial, for `Q ∈ A(k)`.
It follows from (K1) `dim Sel²(A/k) = 4` (code/earlier-computations/prym_two_descent.gp) and
(K2) the injectivity of `σ_v` on `Sel²` (code/earlier-computations/sigma_v_injective.gp). In the model:

* `SelmerSpan f g`: the image of `μ = x - T` on `A(k)` lies in the subgroup of `H f` generated by
  four classes `g_1, ..., g_4` (the generators of the image of `Sel²` in `H f`; the Selmer bound
  of p21_29, which uses the class groups and S-units of lane M3b; proved in Lean for the two twists
  through the Selmer bases `SelmerBasis.Assembly.selmerBasis_0`, `selmerBasis_1`);
* `selmerInjective_of_indep`: if moreover the local images `Hmap σ f g_j` are independent modulo
  squares (`∏ Hmap(g_j)^{e_j} = 1` forces every `e_j` even), then `SelmerInjective σ f`;
* `indep_of_SB`: that independence follows from `Hmap(g_j) = ∏ d_i^{SB i j}` for an independent
  family `d_1, ..., d_7` of `H (f.map σ)` (the `x - T` images of the local divisors `D_i`) and a
  left inverse of `SB` modulo 2 (kernel checked in lane M4: `FurioLombardo.M4.T0.hSBL`,
  `T1.hSBL`);
* `selmerInjective_of_SB`: the combination.

The only fact about `H f` used is that it is killed by 2 (`H_sq_eq_one`).
-/

open Polynomial
open FurioLombardo.M3a FurioLombardo.M3a.Genus2 FurioLombardo.M3a.Route

namespace FurioLombardo.Discharge.M3a

variable {K : Type*} [Field K]

/-- `H f = L^× / K^× (L^×)²` is killed by 2. -/
theorem H_sq_eq_one (f : K[X]) (h : H f) : h ^ 2 = 1 := by
  induction h using QuotientGroup.induction_on with
  | H u =>
    rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
    exact Subgroup.mem_sup_right ⟨u, rfl⟩

theorem zpow_two_mul_eq_one {G : Type*} [Group G] {g : G} (hg : g ^ 2 = 1) (c : ℤ) :
    g ^ (2 * c) = 1 := by
  rw [zpow_mul, zpow_two, ← pow_two, hg, one_zpow]

theorem H_zpow_two_mul (f : K[X]) (h : H f) (c : ℤ) : h ^ (2 * c) = 1 :=
  zpow_two_mul_eq_one (H_sq_eq_one f h) c

/-- The image of `μ` on `A(k)` lies in the subgroup generated by `g_1, ..., g_4`. -/
def SelmerSpan (f : K[X]) [GoodSextic f] (g : Fin 4 → H f) : Prop :=
  ∀ Q : Jac f, ∃ e : Fin 4 → ℤ, muJ f Q = ∏ j, g j ^ e j

/-- **(K2) from the Selmer span and the independence of the local images.** -/
theorem selmerInjective_of_indep {kv : Type*} [Field kv] (σ : K →+* kv) (f : K[X])
    [GoodSextic f] (g : Fin 4 → H f) (hspan : SelmerSpan f g)
    (hind : ∀ e : Fin 4 → ℤ, ∏ j, Hmap σ f (g j) ^ e j = 1 → ∀ j, (2 : ℤ) ∣ e j) :
    SelmerInjective σ f := by
  intro Q hQ
  obtain ⟨e, he⟩ := hspan Q
  rw [he] at hQ ⊢
  rw [map_prod] at hQ
  simp only [map_zpow] at hQ
  have h2 := hind e hQ
  refine Finset.prod_eq_one (fun j _ => ?_)
  obtain ⟨c, hc⟩ := h2 j
  rw [hc]
  exact H_zpow_two_mul f (g j) c

/-- Additive form of `indep_of_SB`. -/
theorem indep_of_SB_add {A : Type*} [AddCommGroup A] (x : Fin 4 → A) (d : Fin 7 → A)
    (SB : Matrix (Fin 7) (Fin 4) ℤ) (L : Matrix (Fin 4) (Fin 7) ℤ)
    (hx : ∀ j, x j = ∑ i, SB i j • d i)
    (hind : ∀ c : Fin 7 → ℤ, ∑ i, c i • d i = 0 → ∀ i, (2 : ℤ) ∣ c i)
    (hL : ∀ a b : Fin 4, (2 : ℤ) ∣ (L * SB) a b - if a = b then 1 else 0) :
    ∀ e : Fin 4 → ℤ, ∑ j, e j • x j = 0 → ∀ j, (2 : ℤ) ∣ e j := by
  intro e he
  have himg : ∑ j, e j • x j = ∑ i, (SB.mulVec e) i • d i := by
    simp only [hx, Finset.smul_sum, smul_smul, Matrix.mulVec, dotProduct]
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    rw [Finset.sum_smul]
    exact Finset.sum_congr rfl (fun j _ => by rw [mul_comm])
  have hdiv : ∀ i, (2 : ℤ) ∣ (SB.mulVec e) i := hind _ (by rw [← himg]; exact he)
  intro a
  have h1 : (2 : ℤ) ∣ (L.mulVec (SB.mulVec e)) a := by
    simp only [Matrix.mulVec, dotProduct]
    exact Finset.dvd_sum (fun i _ => Dvd.dvd.mul_left (hdiv i) _)
  rw [Matrix.mulVec_mulVec] at h1
  have h3 : (2 : ℤ) ∣ ((L * SB).mulVec e) a - e a := by
    have : ((L * SB).mulVec e) a - e a = ∑ b, ((L * SB) a b - if a = b then 1 else 0) * e b := by
      simp only [Matrix.mulVec, dotProduct, sub_mul, Finset.sum_sub_distrib, ite_mul, one_mul,
        zero_mul, Finset.sum_ite_eq, Finset.mem_univ, ite_true]
    rw [this]
    exact Finset.dvd_sum (fun b _ => Dvd.dvd.mul_right (hL a b) _)
  have := dvd_sub h1 h3
  rwa [sub_sub_cancel] at this

theorem ofMul_prod_zpow {G : Type*} [CommGroup G] {n : ℕ} (x : Fin n → G) (e : Fin n → ℤ) :
    Additive.ofMul (∏ j, x j ^ e j) = ∑ j, e j • Additive.ofMul (x j) := by
  simp [ofMul_prod, ofMul_zpow]

/-- Independence modulo 2 of the images `x_j = ∏ d_i^{SB i j}` in a commutative group, from the
independence of the `d_i` and a left inverse of `SB` modulo 2. -/
theorem indep_of_SB {G : Type*} [CommGroup G] (x : Fin 4 → G) (d : Fin 7 → G)
    (SB : Matrix (Fin 7) (Fin 4) ℤ) (L : Matrix (Fin 4) (Fin 7) ℤ)
    (hx : ∀ j, x j = ∏ i, d i ^ SB i j)
    (hind : ∀ c : Fin 7 → ℤ, ∏ i, d i ^ c i = 1 → ∀ i, (2 : ℤ) ∣ c i)
    (hL : ∀ a b : Fin 4, (2 : ℤ) ∣ (L * SB) a b - if a = b then 1 else 0) :
    ∀ e : Fin 4 → ℤ, ∏ j, x j ^ e j = 1 → ∀ j, (2 : ℤ) ∣ e j := by
  intro e he
  refine indep_of_SB_add (fun j => Additive.ofMul (x j)) (fun i => Additive.ofMul (d i)) SB L
    (fun j => by rw [hx j, ofMul_prod_zpow]) (fun c hc => hind c ?_) hL e ?_
  · rw [← ofMul_prod_zpow] at hc; exact hc
  · rw [← ofMul_prod_zpow, he]; rfl

/-- **(K2) from the Selmer span, the local images in terms of the `x - T` images `d_i` of the local
divisors, their independence, and a left inverse of `SB` modulo 2.** -/
theorem selmerInjective_of_SB {kv : Type*} [Field kv] (σ : K →+* kv) (f : K[X]) [GoodSextic f]
    (g : Fin 4 → H f) (d : Fin 7 → H (f.map σ)) (SB : Matrix (Fin 7) (Fin 4) ℤ)
    (L : Matrix (Fin 4) (Fin 7) ℤ) (hspan : SelmerSpan f g)
    (hσ : ∀ j, Hmap σ f (g j) = ∏ i, d i ^ SB i j)
    (hind : ∀ c : Fin 7 → ℤ, ∏ i, d i ^ c i = 1 → ∀ i, (2 : ℤ) ∣ c i)
    (hL : ∀ a b : Fin 4, (2 : ℤ) ∣ (L * SB) a b - if a = b then 1 else 0) :
    SelmerInjective σ f :=
  selmerInjective_of_indep σ f g hspan (indep_of_SB _ d SB L hσ hind hL)


/-- (K2) for the twist δ0: the Selmer span, the local images of the generators in terms of the
`x - T` images `d_i` of the local divisors (columns of lane M4's `T0.SB`) and the independence of
the `d_i`; the left inverse of `SB` modulo 2 is lane M4's kernel checked `T0.hSBL`. -/
theorem T0.selmerInjective {kv : Type*} [Field kv] (σ : K →+* kv) (f : K[X]) [GoodSextic f]
    (g : Fin 4 → H f) (d : Fin 7 → H (f.map σ)) (hspan : SelmerSpan f g)
    (hσ : ∀ j, Hmap σ f (g j) = ∏ i, d i ^ FurioLombardo.M4.T0.SB i j)
    (hind : ∀ c : Fin 7 → ℤ, ∏ i, d i ^ c i = 1 → ∀ i, (2 : ℤ) ∣ c i) :
    SelmerInjective σ f :=
  selmerInjective_of_SB σ f g d _ _ hspan hσ hind FurioLombardo.M4.T0.hSBL

/-- (K2) for the twist δ1 (lane M4's `T1.SB`, `T1.hSBL`). -/
theorem T1.selmerInjective {kv : Type*} [Field kv] (σ : K →+* kv) (f : K[X]) [GoodSextic f]
    (g : Fin 4 → H f) (d : Fin 7 → H (f.map σ)) (hspan : SelmerSpan f g)
    (hσ : ∀ j, Hmap σ f (g j) = ∏ i, d i ^ FurioLombardo.M4.T1.SB i j)
    (hind : ∀ c : Fin 7 → ℤ, ∏ i, d i ^ c i = 1 → ∀ i, (2 : ℤ) ∣ c i) :
    SelmerInjective σ f :=
  selmerInjective_of_SB σ f g d _ _ hspan hσ hind FurioLombardo.M4.T1.hSBL
end FurioLombardo.Discharge.M3a
