import Mathlib
import FurioLombardo.M3a.Hypotheses

/-!
# (K1) `XTKernel`: the condition δ(-1) = 0 of Poonen and Schaefer, and its reduction

M3a's `XTKernel f` says that the kernel of `μ = x - T` on `A(k) = Jac f` is `2A(k)`. For a
squarefree sextic `f` with `L = k[T]/(f)`, the Galois cohomology of
`0 → J[2] → μ₂^T/μ₂ → μ₂ → 1` (`N` the norm) gives: `μ` is the composition of the (injective)
connecting map `A(k)/2A(k) → H¹(k, J[2])` with `H¹(k, J[2]) → H¹(k, μ₂^T/μ₂)`, whose kernel is
generated by `δ(-1)`, and `L^×/k^×L^×2 → H¹(k, μ₂^T/μ₂)` is injective (Poonen and Schaefer,
J. reine angew. Math. 488 (1997), sections 5 and 11 to 13; Poonen, Schaefer and Stoll,
arXiv math/0508174, Propositions "fcohom", "P:delta delta", "mapker", for the analogous plane
quartic case; the hyperelliptic case with `A(k) = Pic⁰(C)(k)`, which holds for the real curves by
local solvability at the bad places). So `XTKernel f` follows from `δ(-1) = 0`, i.e. from a
Galois invariant element of `μ₂^T/μ₂` of norm `-1`.

* `DeltaTrivial f`: some `d ∈ k^×` and `ε ∈ L` with `ε² = d` and `N_{L/k}(ε) = -d³` (the element
  `ε/√d` of `μ₂^T` is Galois invariant modulo `μ₂` and has norm `-1`). This is the data form of
  `δ(-1) = 0`.
* `PoonenSchaefer f`: the implication `DeltaTrivial f → XTKernel f` of the literature, as a Prop. It is
  proved without the literature under two side conditions (`poonenSchaefer_of`, K1Kernel.lean), hence
  for the sextics `fRev k` (`Bruin.poonenSchaefer_fRev`, K1Concrete.lean).
* `norm_eq_neg_pow_of_sq` (proved): in any finite dimensional commutative `k`-algebra `A`, a square
  root `ε` of a non-square `d ∈ k` has `N_{A/k}(ε) = (-d)^(dim A / 2)` (`A` is a vector space over
  `k(ε) ≅ k(√d)`, norm transitivity).
* `deltaTrivial_of_sq` (proved): for a sextic, `DeltaTrivial f` holds as soon as some non-square
  `d ∈ k` is a square in `L` (`(-d)³ = -d³`). For the real data, `d = disc q` with `f = c q h`.
* `xtKernel_of_sq`: `XTKernel f` from `PoonenSchaefer f` and such a `d`.
-/

open Polynomial
open FurioLombardo.M3a FurioLombardo.M3a.Genus2 FurioLombardo.M3a.Route

namespace FurioLombardo.Discharge.M3a

variable {K : Type*} [Field K]

/-- The norm of the root of `X² - d` is `-d`. -/
theorem norm_root_X_sq_sub_C (d : K) :
    Algebra.norm K (AdjoinRoot.root (X ^ 2 - C d)) = -d := by
  have hmon : (X ^ 2 - C d : K[X]).Monic := monic_X_pow_sub_C d two_ne_zero
  have h := Algebra.PowerBasis.norm_gen_eq_coeff_zero_minpoly (AdjoinRoot.powerBasis hmon.ne_zero)
  rw [AdjoinRoot.minpoly_powerBasis_gen_of_monic hmon, AdjoinRoot.powerBasis_gen,
    AdjoinRoot.powerBasis_dim, natDegree_X_pow_sub_C] at h
  rw [h]
  simp

/-- **The norm of a square root of a non-square constant.** In a finite dimensional commutative
`K`-algebra `A`, if `ε² = d` with `d ∈ K` not a square, then `N_{A/K}(ε) = (-d)^(dim A / 2)`. -/
theorem norm_eq_neg_pow_of_sq {A : Type*} [CommRing A] [Algebra K A] [FiniteDimensional K A]
    (d : K) (hd : ¬ IsSquare d) (ε : A) (hε : ε ^ 2 = algebraMap K A d) :
    Algebra.norm K ε = (-d) ^ (Module.finrank K A / 2) := by
  have hirr : Irreducible (X ^ 2 - C d : K[X]) :=
    X_pow_sub_C_irreducible_of_prime Nat.prime_two (fun b hb => hd ⟨b, by rw [← hb]; ring⟩)
  have : Fact (Irreducible (X ^ 2 - C d : K[X])) := ⟨hirr⟩
  have hroot : aeval ε (X ^ 2 - C d : K[X]) = 0 := by simp [hε]
  let φ : AdjoinRoot (X ^ 2 - C d : K[X]) →ₐ[K] A :=
    AdjoinRoot.liftAlgHom _ (Algebra.ofId K A) ε (by simp [hε])
  letI : Algebra (AdjoinRoot (X ^ 2 - C d : K[X])) A := φ.toRingHom.toAlgebra
  have : IsScalarTower K (AdjoinRoot (X ^ 2 - C d : K[X])) A :=
    IsScalarTower.of_algebraMap_eq (fun x => (φ.commutes x).symm)
  have : Module.Free (AdjoinRoot (X ^ 2 - C d : K[X])) A := Module.Free.of_divisionRing _ _
  have : Module.Finite (AdjoinRoot (X ^ 2 - C d : K[X])) A :=
    Module.Finite.of_restrictScalars_finite K _ A
  have hεE : ε = algebraMap (AdjoinRoot (X ^ 2 - C d : K[X])) A (AdjoinRoot.root _) :=
    (AdjoinRoot.liftAlgHom_root _ _ _ _).symm
  have hfin2 : Module.finrank K (AdjoinRoot (X ^ 2 - C d : K[X])) = 2 := by
    rw [(AdjoinRoot.powerBasis (monic_X_pow_sub_C d two_ne_zero).ne_zero).finrank,
      AdjoinRoot.powerBasis_dim, natDegree_X_pow_sub_C]
  have htower := Module.finrank_mul_finrank K (AdjoinRoot (X ^ 2 - C d : K[X])) A
  rw [hfin2] at htower
  have hdim : Module.finrank K A / 2 = Module.finrank (AdjoinRoot (X ^ 2 - C d : K[X])) A := by
    omega
  rw [hεE, ← Algebra.norm_norm (S := AdjoinRoot (X ^ 2 - C d : K[X])), Algebra.norm_algebraMap,
    map_pow, norm_root_X_sq_sub_C, hdim]

/-- The data form of `δ(-1) = 0` for `L = K[T]/(f)`: a square root `ε ∈ L` of some `d ∈ K^×` with
`N_{L/K}(ε) = -d³`. -/
def DeltaTrivial (f : K[X]) : Prop :=
  ∃ d : K, d ≠ 0 ∧ ∃ ε : AdjoinRoot f, ε ^ 2 = algebraMap K (AdjoinRoot f) d ∧
    Algebra.norm K ε = -d ^ 3

/-- **Poonen and Schaefer's injectivity of `x - T` when `δ(-1) = 0`**, as a Prop.
For the sextic `f`: if `δ(-1) = 0` then the kernel of `μ` on `A(k)` is `2A(k)` (literature in the
module docstring). Proved for the sextics used, `Bruin.poonenSchaefer_fRev` (K1Concrete.lean), by the
elementary proof `poonenSchaefer_of` (K1Kernel.lean), which needs no `A(k) = Pic⁰(C)(k)`. -/
def PoonenSchaefer (f : K[X]) [GoodSextic f] : Prop :=
  DeltaTrivial f → XTKernel f

/-- For a sextic, a non-square `d ∈ K` which is a square in `K[T]/(f)` gives `δ(-1) = 0`. -/
theorem deltaTrivial_of_sq (f : K[X]) (hf : f.natDegree = 6) (d : K) (hd : ¬ IsSquare d)
    (ε : AdjoinRoot f) (hε : ε ^ 2 = algebraMap K (AdjoinRoot f) d) : DeltaTrivial f := by
  have hf0 : f ≠ 0 := by rintro rfl; simp at hf
  have : FiniteDimensional K (AdjoinRoot f) := (AdjoinRoot.powerBasis hf0).finite
  have hfin : Module.finrank K (AdjoinRoot f) = 6 := by
    rw [(AdjoinRoot.powerBasis hf0).finrank, AdjoinRoot.powerBasis_dim, hf]
  refine ⟨d, fun h0 => hd ⟨0, by rw [h0]; ring⟩, ε, hε, ?_⟩
  rw [norm_eq_neg_pow_of_sq d hd ε hε, hfin]
  ring

/-- **(K1) from Poonen and Schaefer and a non-square constant that is a square in `L`.** -/
theorem xtKernel_of_sq (f : K[X]) [GoodSextic f] (hPS : PoonenSchaefer f) (d : K)
    (hd : ¬ IsSquare d) (ε : AdjoinRoot f) (hε : ε ^ 2 = algebraMap K (AdjoinRoot f) d) :
    XTKernel f :=
  hPS (deltaTrivial_of_sq f GoodSextic.natDegree_eq d hd ε hε)

end FurioLombardo.Discharge.M3a
