\\ bruin_identity_on_curve.gp: the Bruin identity Q1*Q3 - Q2^2 = cB*F over K21 (bruin_form.gp) in the zk coordinates of
\\ M1 (Data.lean's qzk), and writes lean/FurioLombardo/Discharge/M4Cert/DataOnC.lean:
\\   czk     zk coordinates of cB (the x^4 coefficient of Q1*Q3 - Q2^2, since F has x^4 coefficient 1);
\\   cinvzk  zk coordinates of cinvM / cB, cinvM the least positive integer making them integral;
\\   onE     for each of the 15 monomials x^a y^b z^c (a + b + c = 4), the Kronecker expression of its coefficient
\\           in Q1*Q3 - Q2^2 - cB*F, built from the atoms .lin (qzk q i j) (i <= j) and .lin czk;
\\   cinvE   the Kronecker expression of cB * (cinvM / cB) - cinvM.
\\ Every identity is checked here on the zk coordinates (as the Lean kernel will check it on the numerators).
\\ Run from code/earlier-computations:  gp -q ../covering/bruin_identity_on_curve.gp < /dev/null
default(parisizemax, 2*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
[t, x, y, z, X, u, w, a, s, b];
read("bruin_form.gp");
chq(c, msg) = if (!c, error("check failed: ", msg));
nfK = nfinit([K21, [2, 7]]);
Fq = x^4 + 3*x^3*y - 3*x^2*y*z - 3*x^2*z^2 + 6*x*y^3 - 6*x*y^2*z + 3*x*y*z^2 - 2*x*z^3 + 4*y^4 + 2*y^3*z - 5*y*z^3;
VV = [x, y, z];
QQ = [Q1, Q2, Q3];
\\ same as embedding_kv_data.gp
zkco(c) = { my(v = nfalgtobasis(nfK, Mod(c, K21))); chq(denominator(v) == 1, "integral"); v~; };
qcoef(Q, i, j) = { my(c); if (i == j, c = polcoef(polcoef(Q, 2, VV[i]), 0, VV[i]), c = polcoef(polcoef(Q, 1, VV[i]), 1, VV[j]));
  substvec(c, [x, y, z], [0, 0, 0]); }
for (q = 1, 3, chq(QQ[q] == sum(i = 1, 3, sum(j = i, 3, qcoef(QQ[q], i, j) * VV[i] * VV[j])), "Q rebuild"));
\\ the coefficients as elements of K21 rebuilt from their zk coordinates (what Lean's zkE (qzk q i j) is)
qz = vector(3, q, matrix(3, 3, i, j, if (i <= j, zkco(qcoef(QQ[q], i, j)), vector(21, k, 0))));
qel(q, i, j) = Mod(nfbasistoalg(nfK, qz[q][i, j]~), K21);
\\ cB
G = lift(Mod(Q1 * Q3 - Q2^2, K21));
cB0 = polcoef(polcoef(polcoef(G, 4, x), 0, y), 0, z);
chq(Mod(cB0 - cB, K21) == 0, "cB of bruin_form.gp");
chq(Mod(cB0, K21) != 0, "cB nonzero");
chq(lift(Mod(G - cB0 * Fq, K21)) == 0, "Q1 Q3 - Q2^2 = cB F");
czk = zkco(cB0);
cel = Mod(nfbasistoalg(nfK, czk~), K21);
chq(cel == Mod(cB0, K21), "czk");
\\ the inverse certificate
vinv = nfalgtobasis(nfK, 1 / Mod(cB0, K21));
cinvM = denominator(vinv);
cinvzk = (cinvM * vinv)~;
chq(denominator(cinvzk) == 1, "cinvzk integral");
chq(cel * Mod(nfbasistoalg(nfK, cinvzk~), K21) == cinvM, "cB * cinv = cinvM");
print("cinvM = ", cinvM, " = ", factor(cinvM));
print("norm(cB) = ", factor(norm(Mod(cB0, K21))));
print("max |czk| = ", vecmax(abs(czk)), ", max |cinvzk| = ", vecmax(abs(cinvzk)));
\\ exponent vector of x_i x_j
ev2(i, j) = { my(e = [0, 0, 0]); e[i]++; e[j]++; e; };
prs = List(); for (i = 1, 3, for (j = i, 3, listput(prs, [i, j])));
\\ monomials x^a y^b z^c, a from 4 down to 0, then b from 4 - a down to 0
mons = List(); forstep (aa = 4, 0, -1, forstep (bb = 4 - aa, 0, -1, listput(mons, [aa, bb, 4 - aa - bb])));
chq(#mons == 15, "15 monomials");
fco(m) = polcoef(polcoef(polcoef(Fq, m[1], x), m[2], y), m[3], z);
\\ Lean text of an atom and of the coefficient expression of a monomial
atom(q, i, j) = Str(".lin (qzk ", q - 1, " ", i - 1, " ", j - 1, ")");
chainAdd(L) = { my(s = L[1]); for (k = 2, #L, s = Str(".add (", s, ") (", L[k], ")")); s; };
coefE(m) = {
  my(P13 = List(), P22 = List(), val = 0, f = fco(m), e);
  for (u1 = 1, #prs, for (u2 = 1, #prs,
    my(i = prs[u1][1], j = prs[u1][2], k = prs[u2][1], l = prs[u2][2]);
    if (ev2(i, j) + ev2(k, l) == m,
      listput(P13, Str(".mul (", atom(1, i, j), ") (", atom(3, k, l), ")"));
      listput(P22, Str(".mul (", atom(2, i, j), ") (", atom(2, k, l), ")"));
      val += qel(1, i, j) * qel(3, k, l) - qel(2, i, j) * qel(2, k, l))));
  val -= f * cel;
  chq(val == 0, Str("coefficient identity ", m));
  e = Str(".sub (", chainAdd(P13), ") (", chainAdd(P22), ")");
  if (f != 0, e = Str(".sub (", e, ") (.mul (.int (", f, ")) (.lin czk))"));
  [e, #P13];
}
lst(v) = { my(s = "["); for (i = 1, #v, s = concat(s, Str(v[i])); if (i < #v, s = concat(s, ", "))); concat(s, "]"); }
fo = Str(LEANDIR, "FurioLombardo/Discharge/M4Cert/DataOnC.lean");
fh = fileopen(fo, "w");
wr(s) = filewrite(fh, s);
wr("import FurioLombardo.M1.Kron");
wr("import FurioLombardo.Discharge.M4Cert.Data");
wr("");
wr("/-! Data of the Bruin identity `Q1 Q3 - Q2² = cB F` over K21. Generated by code/covering/bruin_identity_on_curve.gp from");
wr("code/earlier-computations/bruin_form.gp (PARI/GP 2.17). Do not edit by hand.");
wr("");
wr("`czk`: the coordinates on PARI's integral basis `nfinit(K21).zk` (lane M1's `zkE`) of `cB`, the coefficient of `x⁴`");
wr("in `Q1 Q3 - Q2²`. `cinvzk`: the same for `cinvM / cB`. `onE`: for the monomials `x^a y^b z^c` (`a` from 4 down to 0,");
wr("then `b` from `4 - a` down to 0), the coefficient of `Q1 Q3 - Q2² - cB F` as a Kronecker expression in the atoms");
wr("`.lin (qzk q i j)` (`i ≤ j`) and `.lin czk`. `cinvE`: the expression `cB · (cinvM / cB) - cinvM`. -/");
wr("");
wr("namespace FurioLombardo.Discharge.M4Cert");
wr("");
wr("open FurioLombardo.M1.Kron");
wr("");
wr("/-- zk coordinates of `cB`. -/");
wr(Str("def czk : List ℤ := ", lst(czk)));
wr("");
wr("/-- The least positive integer `m` with `m / cB` integral on the zk basis. -/");
wr(Str("def cinvM : ℤ := ", cinvM));
wr("");
wr("/-- zk coordinates of `cinvM / cB`. -/");
wr(Str("def cinvzk : List ℤ := ", lst(cinvzk)));
wr("");
wr("/-- `cB · (cinvM / cB) - cinvM`. -/");
wr("def cinvE : KE := .sub (.mul (.lin czk) (.lin cinvzk)) (.int cinvM)");
wr("");
wr("/-- The coefficients of `Q1 Q3 - Q2² - cB F` on the 15 monomials of degree 4. -/");
wr("def onE : List KE := [");
{for (n = 1, #mons, my(r = coefE(mons[n])); print(mons[n], ": ", r[2], " pairs, F coefficient ", fco(mons[n]));
  wr(Str("  -- x^", mons[n][1], " y^", mons[n][2], " z^", mons[n][3]));
  wr(Str("  ", r[1], if (n < #mons, ",", ""))));}
wr("]");
wr("");
wr("end FurioLombardo.Discharge.M4Cert");
fileclose(fh);
print("written ", fo);
quit;
