\\ embedding_kv_data.gp: writes lean/FurioLombardo/Discharge/M4Cert/Data.lean (exact data of the M4Cert certificates):
\\ the Hensel approximation theta0 of the embedding K21 -> K_v, the zk coordinates (M1's zkE) of the
\\ coefficients of the Bruin quadrics Q1, Q2, Q3 (bruin_form.gp, monomials x_i x_j with i <= j) and of
\\ delta0 = d0, delta1 = d1. Run from code/earlier-computations after exclusion_data.gp has been checked:
\\   gp -q ../covering/embedding_kv_data.gp < /dev/null
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
[t, x, y, z, X, u, w, a, s, b];
read("bruin_form.gp");
chq(c, msg) = if (!c, error("check failed: ", msg));
nfK = nfinit([K21, [2, 7]]);
\\ same basis as M1 (lean/FurioLombardo/M1/DataField.lean: Dz and zkNum)
Dz = 168168978404922092768;
chq(denominator(Mat(nfK.zk)) == 1 || 1, "");
zkco(c) = { my(v = nfalgtobasis(nfK, Mod(c, K21))); chq(denominator(v) == 1, "integral"); v~; };
VV = [x, y, z];
qcoef(Q, i, j) = { my(c); if (i == j, c = polcoef(polcoef(Q, 2, VV[i]), 0, VV[i]), c = polcoef(polcoef(Q, 1, VV[i]), 1, VV[j]));
  substvec(c, [x, y, z], [0, 0, 0]); }
QQ = [Q1, Q2, Q3];
for (q = 1, 3, chq(QQ[q] == sum(i = 1, 3, sum(j = i, 3, qcoef(QQ[q], i, j) * VV[i] * VV[j])), "Q rebuild"));
th0 = [163180991353, 3522151726, 560510631928];
lst(v) = { my(s = "["); for (i = 1, #v, s = concat(s, Str(v[i])); if (i < #v, s = concat(s, ", "))); concat(s, "]"); }
f = Str(LEANDIR, "FurioLombardo/Discharge/M4Cert/Data.lean");
system(concat("rm -f ", f));
w(s) = write(f, s);
w("import Mathlib");
w("");
w("/-! Exact data of the M4Cert certificates. Generated by code/covering/embedding_kv_data.gp");
w("from code/earlier-computations/bruin_form.gp and completion_kv.gp (PARI/GP 2.17). Do not edit by hand.");
w("");
w("`θ0`: an integer triple (a₀, a₁, a₂), standing for a₀ + a₁ π + a₂ π² in ℤ[π]/(E), with fQ(θ0) ≡ 0 mod 2^40");
w("coordinatewise (checked in `FurioLombardo.Discharge.M4Cert.Embed`). `qzk q i j`: the coordinates on PARI's");
w("integral basis `nfinit(K21).zk` (lane M1's `zkE`) of the coefficient of x_i x_j (i ≤ j, coordinates x, y, z)");
w("of the Bruin quadric Q_(q+1); zero for i > j. `dzk k`: the same for δ_k (δ0 = δ(P0), δ1 = δ(P1)). -/");
w("");
w("namespace FurioLombardo.Discharge.M4Cert");
w("");
w("/-- The Hensel approximation of the image of θ in K_v (coordinates on 1, π, π²). -/");
w(Str("def θ0 : ℤ × ℤ × ℤ := (", th0[1], ", ", th0[2], ", ", th0[3], ")"));
w("");
w("/-- zk coordinates of the coefficients of the Bruin quadrics (upper triangular, row i, column j). -/");
w("def qzk : Fin 3 → Fin 3 → Fin 3 → List ℤ := ![");
for (q = 1, 3, w("  !["); for (i = 1, 3, my(row = "    !["); for (j = 1, 3, row = concat(row, lst(if (i <= j, zkco(qcoef(QQ[q], i, j)), vector(21, k, 0)))); if (j < 3, row = concat(row, ", "))); w(concat(row, if (i < 3, "],", "]")))); w(if (q < 3, "  ],", "  ]")));
w("]");
w("");
w("/-- zk coordinates of δ0 and δ1. -/");
w(concat(["def dzk : Fin 2 → List ℤ := ![", lst(zkco(d0)), ", ", lst(zkco(d1)), "]"]));
w("");
w("end FurioLombardo.Discharge.M4Cert");
print("written ", f);
quit;
