\\ exclusion_residues_data.gp: writes lean/FurioLombardo/Discharge/M4Cert/DataRes.lean, the residue data of the exclusion
\\ certificates (HExcl of M4), all modulo 2^3 in (Z/8)[pi]/(E):
\\  - uOdd: the inverse of Dodd = Dz / 32 modulo 2^28 (Dz the common denominator of M1's zkE);
\\  - qres8 q i j (q = 0 for Q1, 1 for Q3): the residue of sigma(coefficient of x_i x_j) (i <= j), zero below;
\\  - dres8 k, dinv8 k: the residues of sigma(delta_k) and of its inverse;
\\  - sq8: the list of the squares of (Z/8)[pi]/(E) (residue triples in [0, 8)).
\\ It also prints, for each excluded box, the first of Q1, Q3 that certifies it at m = 2 (the Lean check
\\ boxes_T0, boxes_T1 tries Q1, then Q3). Every residue is recomputed by the Lean kernel from Data.lean (qzk, dzk,
\\ theta0) in FurioLombardo.Discharge.M4Cert.Excl.
\\ Run from code/earlier-computations:  gp -q ../covering/exclusion_residues_data.gp < /dev/null
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
[t, x, y, z, X, u, w, a, s, b];
read("bruin_form.gp");
chq(c, msg) = if (!c, error("check failed: ", msg));
nfK = nfinit([K21, [2, 7]]);
E = 'X^3 + 37469486047374096441064*'X^2 + 16418729904282180494548*'X + 17325639337422721302482;
tr(P) = { my(L = lift(Mod(P, E))); vector(3, i, polcoef(L, i - 1, 'X)); }
tp(v) = v[1] + v[2]*'X + v[3]*'X^2;
tmod(v, n) = vector(3, i, v[i] % 2^n);
tmul(a1, a2, n) = tmod(tr(tp(a1) * tp(a2)), n);
th0 = [163180991353, 3522151726, 560510631928];
hornerT(L, v, n) = { my(r = [0, 0, 0]); forstep (i = #L, 1, -1, r = tmul(r, v, n); r[1] = (r[1] + L[i]) % 2^n); r; }
chq(hornerT(Vecrev(K21), th0, 40) == [0, 0, 0], "theta0");
Dz = 168168978404922092768;
zkNum = [Vecrev(nfK.zk[j] * Dz) | j <- [1 .. 21]];
foreach (zkNum, v, foreach (v, c, chq(denominator(c) == 1, "zkNum integral")));
Dodd = Dz / 32; chq(Dodd % 2 == 1, "Dodd odd");
uOdd = lift(Mod(1, 2^28) / Dodd);
zkco(c) = { my(v = nfalgtobasis(nfK, Mod(c, K21))); chq(denominator(v) == 1, "integral"); v~; };
resZK(av, n) = {
  my(NL = vector(21, k, sum(j = 1, 21, av[j] * if (k <= #zkNum[j], zkNum[j][k], 0))), v);
  v = hornerT(NL, th0, n + 5);
  foreach (v, c, chq(c % 32 == 0, "divisible by 32"));
  tmod(v / 32 * uOdd, n);
}
VV = [x, y, z];
qcoef(Q, i, j) = { my(c); if (i == j, c = polcoef(polcoef(Q, 2, VV[i]), 0, VV[i]), c = polcoef(polcoef(Q, 1, VV[i]), 1, VV[j]));
  substvec(c, [x, y, z], [0, 0, 0]); }
QQ = [Q1, Q3];
NR = 3;
QR = vector(2, q, vector(3, i, vector(3, j, if (i <= j, resZK(zkco(qcoef(QQ[q], i, j)), NR), [0, 0, 0]))));
DR = [resZK(zkco(d0), NR), resZK(zkco(d1), NR)];
tinv(a1, n) = { my(z = [lift(Mod(1, 2^n) / a1[1]), 0, 0]); chq(a1[1] % 2 == 1, "unit");
  for (it = 1, 3 * n + 3, z = tmod(tr(tp(z) * (2 - tp(a1) * tp(z))), n)); chq(tmul(z, a1, n) == [1, 0, 0], "inverse"); z; }
DI = [tinv(DR[1], NR), tinv(DR[2], NR)];
\\ squares modulo 8
SQL = List(); SQM = Map();
forvec (v = vector(3, i, [0, 2^NR - 1]), my(s2 = tmul(v, v, NR)); if (!mapisdefined(SQM, s2), mapput(SQM, s2, 1); listput(SQL, s2)));
SQL = vecsort(Vec(SQL));
printf("%d squares modulo 8\n", #SQL);
\\ box certificates at m = 2 (n = 3)
DISCS = [[1, 0, 0], [1, 1, 0], [1, 1, 1], [2, 0, 0], [2, 1, 0]];
dpt(d, Xr, Yr) = { my(D = DISCS[d]); if (D[1] == 1, [D[2] + 2 * Xr, D[3] + 2 * Yr, 1], [D[2] + 2 * Xr, 1, D[3] + 2 * Yr]); }
Fq(p) = substvec(x^4 + 3*x^3*y - 3*x^2*y*z - 3*x^2*z^2 + 6*x*y^3 - 6*x*y^2*z + 3*x*y*z^2 - 2*x*z^3 + 4*y^4 + 2*y^3*z - 5*y*z^3, [x, y, z], p);
qres(Q, p, n) = { my(r = [0, 0, 0]); for (i = 1, 3, for (j = i, 3, r = tmod(r + tmul(Q[i][j], [p[i] * p[j], 0, 0], n), n))); r; }
BOXES = [[[5, 0, 1], [4, 3, 2], [4, 1, 2], [4, 2, 2], [4, 0, 2], [3, 3, 2], [3, 1, 2], [3, 2, 2], [3, 0, 2], [2, 1, 1], [2, 0, 1]], [[5, 1, 1], [5, 0, 1], [4, 3, 2], [4, 1, 2], [4, 2, 2], [4, 0, 2], [3, 3, 2], [3, 1, 2], [3, 2, 2], [2, 0, 1], [1, 1, 1], [1, 0, 1]]];
M = 2;
boxcert(k, bx, q) = {
  my(n = M + 1, cnt = 0, d = bx[1]);
  for (Xr = 0, 2^M - 1, if (Xr % 2^bx[3] != bx[2] % 2^bx[3], next);
    for (Yr = 0, 2^M - 1, my(p = dpt(d, Xr, Yr)); if (Fq(p) % 2^n != 0, next); cnt++;
      if (mapisdefined(SQM, tmul(qres(QR[q], p, n), DI[k + 1], n)), return(-1))));
  cnt;
}
CH = vector(2, k, vector(#BOXES[k], i, my(c = -1); for (q = 1, 2, if (c < 0 && boxcert(k - 1, BOXES[k][i], q) >= 0, c = q - 1)); chq(c >= 0, "box"); c));
print("choices: ", CH);
lst(v) = { my(s = "["); for (i = 1, #v, s = concat(s, Str(v[i])); if (i < #v, s = concat(s, ", "))); concat(s, "]"); }
trip(v) = Str("(", v[1], ", ", v[2], ", ", v[3], ")");
f = Str(LEANDIR, "FurioLombardo/Discharge/M4Cert/DataRes.lean");
system(concat("rm -f ", f));
w(s) = write(f, s);
w("import Mathlib");
w("");
w("/-! Residue data of the exclusion certificates. Generated by code/covering/exclusion_residues_data.gp (PARI/GP 2.17).");
w("Do not edit by hand. Every item is rechecked by the Lean kernel in `FurioLombardo.Discharge.M4Cert.Excl`. -/");
w("");
w("namespace FurioLombardo.Discharge.M4Cert");
w("");
w("/-- The inverse of `Dz / 32` modulo `2^28`. -/");
w(Str("def uOdd : ℤ := ", uOdd));
w("");
w("/-- The odd part of `Dz`. -/");
w(Str("def Dodd : ℤ := ", Dodd));
w("");
w("/-- Residues modulo 8 of the images in `K_v` of the coefficients of Q1 (`q = 0`) and Q3 (`q = 1`). -/");
w("def qres8 : Fin 2 → Fin 3 → Fin 3 → ℤ × ℤ × ℤ := ![");
for (q = 1, 2, my(s = "  !["); for (i = 1, 3, s = concat(s, "!["); for (j = 1, 3, s = concat(s, trip(QR[q][i][j])); if (j < 3, s = concat(s, ", "))); s = concat(s, if (i < 3, "], ", "]"))); w(concat(s, if (q < 2, "],", "]"))));
w("]");
w("");
w("/-- Residues modulo 8 of the images of δ0, δ1 and of their inverses. -/");
w(Str("def dres8 : Fin 2 → ℤ × ℤ × ℤ := ![", trip(DR[1]), ", ", trip(DR[2]), "]"));
w("");
w(Str("def dinv8 : Fin 2 → ℤ × ℤ × ℤ := ![", trip(DI[1]), ", ", trip(DI[2]), "]"));
w("");
w("/-- The squares of `(ℤ/8)[π]/(E)`. -/");
my(s = "def sq8 : List (ℤ × ℤ × ℤ) := ["); for (i = 1, #SQL, s = concat(s, trip(SQL[i])); if (i < #SQL, s = concat(s, ", "))); w(concat(s, "]"));
w("");
w("end FurioLombardo.Discharge.M4Cert");
print("written ", f);
quit;
