\\ lattice_boxes_data.gp: write lean/FurioLombardo/M4/Data.lean (the integer data of the M4 certificates) from
\\ data/lattice_int_twist<k>.gp, data/lattice_unimodular_twist<k>.gp, data/centres_int_twist<k>.gp, data/tails_int_twist<k>.gp (exporters m4_export_*.gp,
\\ lattice_small_unimodular.gp) and the box lists code/earlier-computations/data/boxes_twist<k>.txt (boxes.gp).
\\ Run from code/covering: gp -q lattice_boxes_data.gp
default(parisizemax, 2 * 10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
chq(c, msg) = if (!c, error("check failed: ", msg));
startswith(s, p) = my(a = Vecsmall(s), bb = Vecsmall(p)); #a >= #bb && a[1 .. #bb] == bb;
field(s, key) = {
  my(A = Vecsmall(s), B = Vecsmall(key), p = 0, e); for (i = 1, #A - #B + 1, if (A[i .. i + #B - 1] == B, p = i + #B; break));
  chq(p, Str("field ", key)); e = p; while (e <= #A && A[e] >= 48 && A[e] <= 57, e++); eval(Strchr(A[p .. e - 1]));
}
out = Str(LEANDIR, "FurioLombardo/M4/Data.lean");
system(Str("rm -f ", out));
w(s) = write(out, s);
lv(v) = Str("![", strjoin(apply(e -> Str(e), Vec(v)), ", "), "]");
lm(M) = { my(s = "!!["); for (i = 1, #M~, s = Str(s, if (i > 1, "; ", ""), strjoin(apply(e -> Str(e), Vec(M[i, ])), ", "))); Str(s, "]"); }
\\ known lifts: parameter X_i in its disc, disc index (discs of p21_37: 1: z = 1, (2X, 2Y); 2: z = 1, (1 + 2X, 2Y); 3: z = 1, (1 + 2X, 1 + 2Y))
XI = Map([0, [1, 0]; 2, [1, 1]; 1, [3, 0]; 3, [2, -1]]);
w("import FurioLombardo.M4.Defs"); w(""); w("/-! Integer data of the M4 certificates at the place v of K21 above 2 with e = 3.");
w("Generated by code/covering/lattice_boxes_data.gp from the certified outputs of code/earlier-computations/lattice_cert.gp,");
w("centres_cert.gp (through code/covering/*_export.gp, lattice_small_unimodular.gp) and the box lists code/earlier-computations/data/boxes_twist<k>.txt");
w("of boxes.gp. Do not edit by hand.");
w("");
w("Coordinates: `V = Fin 6 → ℤ_[2]` is O_v² on the basis 1, π, π² (twice), differentials dt/Y, t dt/Y of y² = f_δ(t).");
w("Namespaces `T0`, `T1` for the twists δ0, δ1. -/");
w("");
w("");
w("");
w("namespace FurioLombardo.M4");
w("");
{ for (k = 0, 1,
  read(Str("data/lattice_int_twist", k, ".gp")); read(Str("data/lattice_unimodular_twist", k, ".gp"));
  my(B = readvec(Str("../earlier-computations/data/boxes_twist", k, ".txt")), CE = readvec(Str("data/centres_int_twist", k, ".gp")), TL = readvec(Str("data/tails_int_twist", k, ".gp")),
     ex = List(), cb = List(), tb = List());
  foreach (B, b, my(s = b[4]);
    if (startswith(s, "excluded"), listput(ex, [b[1], b[2], b[3]]),
      startswith(s, "constant"),
        my(cc = [c | c <- CE, c[1] == b[1] && c[2] == b[2] && c[3] == b[3]]);
        chq(#cc == 1, "one centre per constant box"); cc = cc[1];
        chq(cc[4] == field(s, "nu = ") && cc[5] == field(s, "vM = "), "centre values");
        listput(cb, cc),
      startswith(s, "tail"),
        my(i = field(s, "tail at x_"), rad = field(s, "radius 2^-"), vM = field(s, "vM = "), tt = [t | t <- TL, t[1] == i], xi = mapget(XI, i), g, qg = 62);
        chq(#tt == 1 && xi[1] == b[1], "tail data"); tt = tt[1];
        chq(tt[3] >= 60, "precision of c_1");
        g = vector(6, j, my(e = tt[2][j]); chq(denominator(e) == 1, "c_1 integral"); 4 * lift(Mod(e, 2^60)));
        chq((b[2] - xi[2]) % 2^b[3] == 0, "the box contains X_i");
        listput(tb, [b[1], b[2], b[3], i, xi[2], rad + 1, vM, qg, tt[4] + 2, g]),
      error("verdict")));
  w(Str("namespace T", k)); w("");
  w(Str("/-- Precisions (2-adic, V coordinates) of the balls of log D_1..D_7 (twist δ", k, "). -/"));
  w(Str("def qD : Fin 7 → ℕ := ", lv(q[1 .. 7])));
  w("/-- Centres of the balls of log D_1..D_7, reduced modulo 2^qD. -/");
  w(Str("def lD : Fin 7 → Fin 6 → ℤ := ![", strjoin(vector(7, i, lv(l[i])), ", "), "]"));
  w("/-- Precisions and centres of the balls of log φ_a, log φ_b. -/");
  w(Str("def qa : ℕ := ", q[8])); w(Str("def qb : ℕ := ", q[9]));
  w(Str("def la : Fin 6 → ℤ := ", lv(l[8]))); w(Str("def lb : Fin 6 → ℤ := ", lv(l[9])));
  w("/-- Λ = H ℤ_[2]^6 (Hermite normal form of p21_45) and G = 4 H⁻¹. -/");
  w(Str("def H : Matrix (Fin 6) (Fin 6) ℤ := ", lm(H))); w(Str("def G : Matrix (Fin 6) (Fin 6) ℤ := ", lm(G)));
  w("/-- Nakayama certificate: ∑ i, C k i * lD i ≡ 4 e_k mod 8. -/");
  w(Str("def C : Matrix (Fin 6) (Fin 7) ℤ := ", lm(C)));
  w("/-- The columns of H are in the span of the lD i modulo 4: H ≡ L Cp mod 4. -/");
  w(Str("def Cp : Matrix (Fin 7) (Fin 6) ℤ := ", lm(Cp)));
  w("/-- Unimodular U (rows 0, 1: the saturation block; rows 2 to 5: the projection pr), its inverse, and U G. -/");
  w(Str("def U : Matrix (Fin 6) (Fin 6) ℤ := ", lm(U))); w(Str("def Ui : Matrix (Fin 6) (Fin 6) ℤ := ", lm(Ui)));
  w(Str("def UG : Matrix (Fin 6) (Fin 6) ℤ := ", lm(UG)));
  w("/-- Valuation data of the saturation: the O block of U G la, U G lb is divisible by 2^Jab, the 2 x 2 N block has");
  w("determinant Del of 2-valuation dl, and QChar holds up to the level r = min(Jab, qa, qb) - dl. -/");
  w(Str("def Jab : ℕ := ", Jab)); w(Str("def Del : ℤ := ", Del)); w(Str("def dl : ℕ := ", dl)); w(Str("def r : ℕ := ", r));
  w("/-- Saturation certificates for the columns 0, 1 of H Ui: 2^e σ_j ≡ α_j la + β_j lb mod 2^(r + e + 2). -/");
  w(Str("def sigE : Fin 2 → ℕ := ![", sg[1][2][1], ", ", sg[2][2][1], "]"));
  w(Str("def sigA : Fin 2 → ℤ := ![", sg[1][2][2], ", ", sg[2][2][2], "]"));
  w(Str("def sigB : Fin 2 → ℤ := ![", sg[1][2][3], ", ", sg[2][2][3], "]"));
  w("/-- Representatives of W = ρ(σ_v(Sel²)): the 16 combinations of the four Selmer generators on the lD i. -/");
  w(Str("def W : Fin 16 → Fin 6 → ℤ := ![", strjoin(vector(16, m, lv(W[m])), ", "), "]"));
  w(Str("/-- Selmer generators in the D basis (7 x 4, entries 0/1). -/"));
  w(Str("def SB : Matrix (Fin 7) (Fin 4) ℤ := ", lm(SB)));
  w(Str("/-- The ", #ex, " excluded boxes (disc, c, s). -/"));
  w(Str("def excluded : List (ℕ × ℕ × ℕ) := [", strjoin(apply(e -> Str("(", e[1], ", ", e[2], ", ", e[3], ")"), Vec(ex)), ", "), "]"));
  w(Str("/-- The ", #cb, " constant boxes with their certified centre values. -/"));
  w("def constant : List CBox := [");
  for (j = 1, #cb, my(c = cb[j]); w(Str("  ⟨", c[1], ", ", c[2], ", ", c[3], ", ", c[4], ", ", c[5], ", ", c[7], ", ", lv(c[6]), "⟩", if (j < #cb, ",", ""))));
  w("]");
  w(Str("/-- The ", #tb, " tail boxes. -/"));
  w("def tails : List TBox := [");
  for (j = 1, #tb, my(t = tb[j]); w(Str("  ⟨", t[1], ", ", t[2], ", ", t[3], ", ", t[4], ", ", t[5], ", ", t[6], ", ", t[7], ", ", t[8], ", ", t[9], ", ", lv(t[10]), "⟩", if (j < #tb, ",", ""))));
  w("]");
  w(""); w(Str("end T", k)); w("");
  printf("k = %d: %d excluded, %d constant, %d tail boxes\n", k, #ex, #cb, #tb)); }
w("end FurioLombardo.M4");
print("wrote ", out);
quit;
