\\ conics_no_common_zero.gp: Bruin's three conics Q1, Q2, Q3 have no common zero in P^2 over K21: for each coordinate
\\ R_j (j = 0, 1, 2 for x, y, z) quadratic forms a_{j,i} over K21 with  R_j^4 = sum_i a_{j,i} Q_{i+1}.
\\ Appends the data to lean/FurioLombardo/Discharge/M3a/AbelPrymData2.lean (deleted first):
\\   cfDen[j]        a positive integer D_j;
\\   cfData[j][i][m] zk coordinates of D_j * (coefficient of a_{j,i} on the conic monomial m of x^2, xy, xz, y^2, yz, z^2).
\\ The identity is checked here exactly in K21[x, y, z], and by the Lean kernel coefficientwise on the 15 quartic monomials
\\ (M1's conv / convKE of Conics.lean).
\\ Run from code/genus2-curves: gp -q conics_no_common_zero.gp
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("../descent/descent_data_lib.gp");
chk(cc, msg) = if (!cc, error("FAILED: ", msg));
red(g) = lift(Mod(1, K21) * g);
den(v) = denominator(content(v));
zkl(e) = { my(v = zkc(e)); if (den(v) != 1, error("non integral zk coordinates")); v~ };
mons4 = [[4,0,0],[3,1,0],[3,0,1],[2,2,0],[2,1,1],[2,0,2],[1,3,0],[1,2,1],[1,1,2],[1,0,3],[0,4,0],[0,3,1],[0,2,2],[0,1,3],[0,0,4]];
mon(e) = x^e[1] * y^e[2] * z^e[3];
c4(P) = vector(15, u, Mod(cf(P, mons4[u][1], mons4[u][2], mons4[u][3]), K21));
\\ columns: unknown (i, m), the coefficient vector of mon(m) * Q_i on the quartic monomials
A = matrix(15, 18, u, v, 0);
{ for (i = 1, 3, for (m = 1, 6,
    my(col = c4(mon(mons2[m]) * Qs[i]));
    for (u = 1, 15, A[u, 6 * (i - 1) + m] = col[u]))); }
print("rank of the 15 x 18 system over K21: ", matrank(A));
CD = vector(3); CF = vector(3);
{ for (j = 1, 3,
    my(tgt = [1, 11, 15][j], B = vectorv(15, u, Mod(u == tgt, K21)), S, a, P, D);
    S = matinverseimage(A, B);
    chk(#S == 1 || type(S) == "t_COL", "solvable");
    a = vector(3, i, vector(6, m, S[6 * (i - 1) + m]));
    P = sum(i = 1, 3, sum(m = 1, 6, a[i][m] * mon(mons2[m])) * Qs[i]);
    chk(red(P - [x, y, z][j]^4) == 0, "R_j^4 = sum a Q exactly");
    D = lcm(vector(18, v, den(zkc(S[v]))));
    CD[j] = D;
    CF[j] = vector(3, i, vector(6, m, zkl(D * a[i][m])));
    printf("j = %d: D = %s (%d digits), max coefficient digits %d\n", j - 1, D, #Str(D),
      vecmax(vector(18, v, #Str(vecmax(apply(e -> abs(e), zkl(D * S[v])))))));
  ); }
out = Str(LEANDIR, "FurioLombardo/Discharge/M3a/AbelPrymData2.lean");
system(Str("rm -f ", out));
lst3(V) = { my(s = "["); for (i = 1, #V, s = Str(s, lstl(V[i]), if (i < #V, ",\n  ", ""))); Str(s, "]") };
lst4(V) = { my(s = "["); for (i = 1, #V, s = Str(s, lst3(V[i]), if (i < #V, ",\n  ", ""))); Str(s, "]") };
write(out, "/-! Data of WP4 of the M3a discharge (generated by code/genus2-curves/conics_no_common_zero.gp, PARI/GP):\nfor each coordinate `R_j`, quadratic forms `a_(j,i)` over K21 with `R_j^4 = Σ_i a_(j,i) Q_(i+1)`, so Bruin's three\nconics have no common zero. Every element of K21 is a list of zk coordinates (lane M1's `zkE`); the identity is\nrechecked by the Lean kernel in `FurioLombardo.Discharge.M3a.AbelPrymCheck2`. -/\n\nnamespace FurioLombardo.Discharge.M3a.Bruin\n\nset_option maxRecDepth 100000\n");
write(out, "/-- `cfDen[j] = D_j`. -/\ndef cfDen : List Nat := ", lst(CD), "\n");
write(out, "/-- `cfData[j][i][m]`: `D_j` times the coefficient of `a_(j,i)` on `x^2, xy, xz, y^2, yz, z^2`. -/\ndef cfData : List (List (List (List Int))) :=\n  ", lst4(CF), "\n");
write(out, "end FurioLombardo.Discharge.M3a.Bruin");
print("written ", out);
quit;
