import Mathlib

/-! Residue data of the exclusion certificates. Generated by code/covering/exclusion_residues_data.gp (PARI/GP 2.17).
Do not edit by hand. Every item is rechecked by the Lean kernel in `FurioLombardo.Discharge.M4Cert.Excl`. -/

namespace FurioLombardo.Discharge.M4Cert

/-- The inverse of `Dz / 32` modulo `2^28`. -/
def uOdd : ℤ := 91745367

/-- The odd part of `Dz`. -/
def Dodd : ℤ := 5255280575153815399

/-- Residues modulo 8 of the images in `K_v` of the coefficients of Q1 (`q = 0`) and Q3 (`q = 1`). -/
def qres8 : Fin 2 → Fin 3 → Fin 3 → ℤ × ℤ × ℤ := ![
  ![![(1, 2, 0), (5, 2, 0), (6, 4, 0)], ![(0, 0, 0), (4, 0, 4), (3, 6, 0)], ![(0, 0, 0), (0, 0, 0), (0, 0, 0)]],
  ![![(1, 2, 5), (2, 4, 2), (2, 4, 2)], ![(0, 0, 0), (6, 4, 6), (0, 0, 0)], ![(0, 0, 0), (0, 0, 0), (5, 2, 1)]]
]

/-- Residues modulo 8 of the images of δ0, δ1 and of their inverses. -/
def dres8 : Fin 2 → ℤ × ℤ × ℤ := ![(5, 6, 6), (3, 2, 5)]

def dinv8 : Fin 2 → ℤ × ℤ × ℤ := ![(5, 2, 6), (7, 0, 3)]

/-- The squares of `(ℤ/8)[π]/(E)`. -/
def sq8 : List (ℤ × ℤ × ℤ) := [(0, 0, 0), (0, 0, 1), (0, 0, 4), (0, 2, 1), (0, 6, 0), (0, 6, 4), (1, 0, 0), (1, 0, 4), (1, 2, 1), (1, 2, 2), (1, 2, 5), (1, 2, 6), (1, 4, 0), (1, 4, 4), (1, 6, 1), (1, 6, 2), (1, 6, 5), (1, 6, 6), (4, 0, 0), (4, 0, 4), (4, 4, 1), (4, 6, 0), (4, 6, 4), (4, 6, 5), (5, 0, 3), (5, 0, 7), (5, 4, 3), (5, 4, 7)]

end FurioLombardo.Discharge.M4Cert
