import FurioLombardo.Discharge.M4Cert.Curve
import FurioLombardo.Discharge.M4Cert.DataOnC

/-!
# The Bruin identity `Q1 Q3 - Q2² = cB F` over K21, and the points of `D_δ` lie over `C`

`qvalZ q p` is the value at `p` of Bruin's quadric `Q_(q+1)` with the coefficients `zkE (qzk q i j)`
(`i ≤ j`) of Data.lean. The quartic form `Q1 Q3 - Q2²` equals `cB F`, `cB = zkE czk ≠ 0`
(`bruin_identity`, `czk_ne`): the 15 coefficient identities (DataOnC.lean, generated by
code/covering/bruin_identity_on_curve.gp) are Kronecker tests run by the kernel (lane M1's
`checkK`), and `cB (cinvM / cB) = cinvM ≠ 0` is one more. Consequently a point of M3a's `DPoint` for
matrices of these forms lies on `C` (`onCurve_of_dpoint`), and so does a rational point below it
(`onCurve_of_over`).
-/

namespace FurioLombardo.Discharge.M4Cert

open FurioLombardo.M1 FurioLombardo.M1.Kron Matrix

/-! ## Quadratic forms over K21 -/

/-- The value at `p` of the quadratic form with coefficient `zkE (c i j)` on `x_i x_j`, `i ≤ j`. -/
noncomputable def qvalC (c : Fin 3 → Fin 3 → List ℤ) (p : Fin 3 → K21) : K21 :=
  zkE (c 0 0) * (p 0 * p 0) + zkE (c 0 1) * (p 0 * p 1) + zkE (c 0 2) * (p 0 * p 2) +
    zkE (c 1 1) * (p 1 * p 1) + zkE (c 1 2) * (p 1 * p 2) + zkE (c 2 2) * (p 2 * p 2)

/-- Bruin's quadric `Q_(q+1)` at `p`. -/
noncomputable def qvalZ (q : Fin 3) (p : Fin 3 → K21) : K21 := qvalC (qzk q) p

/-- The K21 version of `quad_eq`: a matrix of the form has the value `qvalC c p` at `p`. -/
theorem quad_eqK {M : Matrix (Fin 3) (Fin 3) K21} {c : Fin 3 → Fin 3 → List ℤ}
    (hM : QFormData M c) (p : Fin 3 → K21) : p ⬝ᵥ (M *ᵥ p) = qvalC c p := by
  obtain ⟨hd, ho⟩ := hM
  have h01 := ho 0 1 (by decide)
  have h02 := ho 0 2 (by decide)
  have h12 := ho 1 2 (by decide)
  simp only [dotProduct, Matrix.mulVec, Fin.sum_univ_three, qvalC]
  rw [← hd 0, ← hd 1, ← hd 2]
  linear_combination (p 0 * p 1) * h01 + (p 0 * p 2) * h02 + (p 1 * p 2) * h12

/-! ## Kernel checks -/

/-- The 15 coefficients of `Q1 Q3 - Q2² - cB F` vanish (Kronecker tests at `N = 2 ^ 256`). -/
theorem ck_onE : onE.all (checkK 256) = true := by decide +kernel

/-- `cB · (cinvM / cB) = cinvM`. -/
theorem ck_cinv : checkK 256 cinvE = true := by decide +kernel

/-- `cinvM = 3² 7² 439² ≠ 0`. -/
theorem ck_cinvM : cinvM ≠ 0 := by decide +kernel

/-- The coefficient expressions of `onE` vanish in K21. -/
theorem onE_zero : ∀ e ∈ onE, evK e = 0 := fun e he =>
  evK_eq_zero_of_check 256 e (List.all_eq_true.mp ck_onE e he)

/-! ## The identity -/

/-- `cB ≠ 0`. -/
theorem czk_ne : zkE czk ≠ 0 := by
  intro h0
  have h := evK_eq_zero_of_check 256 cinvE ck_cinv
  simp only [cinvE, evK_sub, evK_mul, evK_lin, evK_int] at h
  rw [h0, zero_mul, zero_sub, neg_eq_zero, ← map_intCast (algebraMap ℚ K21)] at h
  exact ck_cinvM (Int.cast_eq_zero.mp ((algebraMap ℚ K21).injective (h.trans (map_zero _).symm)))

/-- **Bruin's identity** `Q1 Q3 - Q2² = cB F` as quartic forms over K21. -/
theorem bruin_identity (p : Fin 3 → K21) :
    qvalZ 0 p * qvalZ 2 p - qvalZ 1 p ^ 2 = zkE czk * FurioLombardo.F (p 0) (p 1) (p 2) := by
  have h := onE_zero
  simp only [onE, List.forall_mem_cons, evK_sub, evK_add, evK_mul, evK_lin, evK_int, Int.cast_one,
    Int.cast_ofNat, Int.cast_neg] at h
  obtain ⟨h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14, -⟩ := h
  simp only [qvalZ, qvalC, FurioLombardo.F]
  linear_combination p 0 ^ 4 * h0 + p 0 ^ 3 * p 1 * h1 + p 0 ^ 3 * p 2 * h2 +
    p 0 ^ 2 * p 1 ^ 2 * h3 + p 0 ^ 2 * p 1 * p 2 * h4 + p 0 ^ 2 * p 2 ^ 2 * h5 +
    p 0 * p 1 ^ 3 * h6 + p 0 * p 1 ^ 2 * p 2 * h7 + p 0 * p 1 * p 2 ^ 2 * h8 + p 0 * p 2 ^ 3 * h9 +
    p 1 ^ 4 * h10 + p 1 ^ 3 * p 2 * h11 + p 1 ^ 2 * p 2 ^ 2 * h12 + p 1 * p 2 ^ 3 * h13 +
    p 2 ^ 4 * h14

/-- A point with `Q1 = δ r²`, `Q2 = δ r s`, `Q3 = δ s²` lies on `C`. -/
theorem F_eq_zero_of_qval (p : Fin 3 → K21) {δ r s : K21} (h1 : qvalZ 0 p = δ * r ^ 2)
    (h2 : qvalZ 1 p = δ * (r * s)) (h3 : qvalZ 2 p = δ * s ^ 2) :
    FurioLombardo.F (p 0) (p 1) (p 2) = 0 := by
  have h := bruin_identity p
  rw [h1, h2, h3] at h
  have h0 : zkE czk * FurioLombardo.F (p 0) (p 1) (p 2) = 0 := by rw [← h]; ring
  exact (mul_eq_zero.mp h0).resolve_left czk_ne

/-! ## Points of `D_δ` lie over `C` -/

/-- Every point of M3a's `DPoint` for matrices of Bruin's quadrics lies on `C`. -/
theorem onCurve_of_dpoint {M1 M2 M3 : Matrix (Fin 3) (Fin 3) K21} {δ : K21}
    (h1 : QFormData M1 (qzk 0)) (h2 : QFormData M2 (qzk 1)) (h3 : QFormData M3 (qzk 2))
    (x : FurioLombardo.M3a.DPoint K21 M1 M2 M3 δ) :
    FurioLombardo.F (x.p 0) (x.p 1) (x.p 2) = 0 := by
  have e1 := x.eq1
  have e2 := x.eq2
  have e3 := x.eq3
  rw [quad_eqK h1] at e1
  rw [quad_eqK h2] at e2
  rw [quad_eqK h3] at e3
  exact F_eq_zero_of_qval x.p e1 e2 e3

/-- The rational point below a point of `D_δ` lies on `C`. -/
theorem onCurve_of_over {M1 M2 M3 : Matrix (Fin 3) (Fin 3) K21} {δ : K21}
    (h1 : QFormData M1 (qzk 0)) (h2 : QFormData M2 (qzk 1)) (h3 : QFormData M3 (qzk 2))
    (x : FurioLombardo.M3a.DPoint K21 M1 M2 M3 δ) (a b c : ℚ) (hx : x.Over a b c) :
    FurioLombardo.F a b c = 0 := by
  obtain ⟨t, ht, hp⟩ := hx
  have h := onCurve_of_dpoint h1 h2 h3 x
  rw [hp] at h
  simp only [Pi.smul_apply, smul_eq_mul, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.cons_val_two, Matrix.head_cons, Matrix.tail_cons] at h
  have hF : ∀ u v w : K21, FurioLombardo.F (t * u) (t * v) (t * w) =
      t ^ 4 * FurioLombardo.F u v w := fun u v w => by unfold FurioLombardo.F; ring
  rw [hF, ← map_F] at h
  have h0 := (mul_eq_zero.mp h).resolve_left (pow_ne_zero 4 ht)
  exact (algebraMap ℚ K21).injective (h0.trans (map_zero _).symm)

end FurioLombardo.Discharge.M4Cert
