/-
The constant box centres of twist 0: the certificates `K0C<i>.cert` of the 82 boxes of `T0.constant` from the
data files K0C<i>.lean (`centreOK_of_run`), and `HCentre` for `T0.data` (`hCentre_of_ok`, the ball `(la, qa)` of
PhiCertData).
Generated by code/covering/centre_certs_gen.lean (lane lean-m4box); every value is checked by the kernel.
-/
import FurioLombardo.Discharge.M4Box.CentreValue
import FurioLombardo.Discharge.M4Box.PhiCertData.Values
import FurioLombardo.Discharge.M4Box.CentreData.K0C0
import FurioLombardo.Discharge.M4Box.CentreData.K0C1
import FurioLombardo.Discharge.M4Box.CentreData.K0C2
import FurioLombardo.Discharge.M4Box.CentreData.K0C3
import FurioLombardo.Discharge.M4Box.CentreData.K0C4
import FurioLombardo.Discharge.M4Box.CentreData.K0C5
import FurioLombardo.Discharge.M4Box.CentreData.K0C6
import FurioLombardo.Discharge.M4Box.CentreData.K0C7
import FurioLombardo.Discharge.M4Box.CentreData.K0C8
import FurioLombardo.Discharge.M4Box.CentreData.K0C9
import FurioLombardo.Discharge.M4Box.CentreData.K0C10
import FurioLombardo.Discharge.M4Box.CentreData.K0C11
import FurioLombardo.Discharge.M4Box.CentreData.K0C12
import FurioLombardo.Discharge.M4Box.CentreData.K0C13
import FurioLombardo.Discharge.M4Box.CentreData.K0C14
import FurioLombardo.Discharge.M4Box.CentreData.K0C15
import FurioLombardo.Discharge.M4Box.CentreData.K0C16
import FurioLombardo.Discharge.M4Box.CentreData.K0C17
import FurioLombardo.Discharge.M4Box.CentreData.K0C18
import FurioLombardo.Discharge.M4Box.CentreData.K0C19
import FurioLombardo.Discharge.M4Box.CentreData.K0C20
import FurioLombardo.Discharge.M4Box.CentreData.K0C21
import FurioLombardo.Discharge.M4Box.CentreData.K0C22
import FurioLombardo.Discharge.M4Box.CentreData.K0C23
import FurioLombardo.Discharge.M4Box.CentreData.K0C24
import FurioLombardo.Discharge.M4Box.CentreData.K0C25
import FurioLombardo.Discharge.M4Box.CentreData.K0C26
import FurioLombardo.Discharge.M4Box.CentreData.K0C27
import FurioLombardo.Discharge.M4Box.CentreData.K0C28
import FurioLombardo.Discharge.M4Box.CentreData.K0C29
import FurioLombardo.Discharge.M4Box.CentreData.K0C30
import FurioLombardo.Discharge.M4Box.CentreData.K0C31
import FurioLombardo.Discharge.M4Box.CentreData.K0C32
import FurioLombardo.Discharge.M4Box.CentreData.K0C33
import FurioLombardo.Discharge.M4Box.CentreData.K0C34
import FurioLombardo.Discharge.M4Box.CentreData.K0C35
import FurioLombardo.Discharge.M4Box.CentreData.K0C36
import FurioLombardo.Discharge.M4Box.CentreData.K0C37
import FurioLombardo.Discharge.M4Box.CentreData.K0C38
import FurioLombardo.Discharge.M4Box.CentreData.K0C39
import FurioLombardo.Discharge.M4Box.CentreData.K0C40
import FurioLombardo.Discharge.M4Box.CentreData.K0C41
import FurioLombardo.Discharge.M4Box.CentreData.K0C42
import FurioLombardo.Discharge.M4Box.CentreData.K0C43
import FurioLombardo.Discharge.M4Box.CentreData.K0C44
import FurioLombardo.Discharge.M4Box.CentreData.K0C45
import FurioLombardo.Discharge.M4Box.CentreData.K0C46
import FurioLombardo.Discharge.M4Box.CentreData.K0C47
import FurioLombardo.Discharge.M4Box.CentreData.K0C48
import FurioLombardo.Discharge.M4Box.CentreData.K0C49
import FurioLombardo.Discharge.M4Box.CentreData.K0C50
import FurioLombardo.Discharge.M4Box.CentreData.K0C51
import FurioLombardo.Discharge.M4Box.CentreData.K0C52
import FurioLombardo.Discharge.M4Box.CentreData.K0C53
import FurioLombardo.Discharge.M4Box.CentreData.K0C54
import FurioLombardo.Discharge.M4Box.CentreData.K0C55
import FurioLombardo.Discharge.M4Box.CentreData.K0C56
import FurioLombardo.Discharge.M4Box.CentreData.K0C57
import FurioLombardo.Discharge.M4Box.CentreData.K0C58
import FurioLombardo.Discharge.M4Box.CentreData.K0C59
import FurioLombardo.Discharge.M4Box.CentreData.K0C60
import FurioLombardo.Discharge.M4Box.CentreData.K0C61
import FurioLombardo.Discharge.M4Box.CentreData.K0C62
import FurioLombardo.Discharge.M4Box.CentreData.K0C63
import FurioLombardo.Discharge.M4Box.CentreData.K0C64
import FurioLombardo.Discharge.M4Box.CentreData.K0C65
import FurioLombardo.Discharge.M4Box.CentreData.K0C66
import FurioLombardo.Discharge.M4Box.CentreData.K0C67
import FurioLombardo.Discharge.M4Box.CentreData.K0C68
import FurioLombardo.Discharge.M4Box.CentreData.K0C69
import FurioLombardo.Discharge.M4Box.CentreData.K0C70
import FurioLombardo.Discharge.M4Box.CentreData.K0C71
import FurioLombardo.Discharge.M4Box.CentreData.K0C72
import FurioLombardo.Discharge.M4Box.CentreData.K0C73
import FurioLombardo.Discharge.M4Box.CentreData.K0C74
import FurioLombardo.Discharge.M4Box.CentreData.K0C75
import FurioLombardo.Discharge.M4Box.CentreData.K0C76
import FurioLombardo.Discharge.M4Box.CentreData.K0C77
import FurioLombardo.Discharge.M4Box.CentreData.K0C78
import FurioLombardo.Discharge.M4Box.CentreData.K0C79
import FurioLombardo.Discharge.M4Box.CentreData.K0C80
import FurioLombardo.Discharge.M4Box.CentreData.K0C81

namespace FurioLombardo.Discharge.M4Box.CentreData

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

theorem K0C0.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[0] :=
  centreOK_of_run 0 (e := ⟨5, 3, 2, true, (240502, 141094, 221110), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 5 by unfold IsDisc; decide) (Y0 := 3593008820300712862086174847802118870532603648587007976995972462924942855200149103135177201920658939381459068506868605736912476306988487460246663681339759295134828995760380462053134) (N := 600) (by decide +kernel) dCtx_ok
    K0C0.hin K0C0.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C0.hR K0C0.hfin

theorem K0C1.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[1] :=
  centreOK_of_run 0 (e := ⟨5, 1, 2, true, (225630, 201582, 256054), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 5 by unfold IsDisc; decide) (Y0 := 2926475286495674400385428817177532796763223340000957115889184182480651898347145250772767356320065934222691489081269571031519106128218120537569510833291564217916434666165050838567252) (N := 600) (by decide +kernel) dCtx_ok
    K0C1.hin K0C1.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C1.hR K0C1.hfin

theorem K0C2.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[2] :=
  centreOK_of_run 0 (e := ⟨1, 31, 5, true, (3768, 91752, 56024), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2302438237398375375615457551222986043350482473567470817881052855453483895109263253929362240303484541430983024734606399654365653286818276836994783054488820954506179726311628900653436) (N := 600) (by decide +kernel) dCtx_ok
    K0C2.hin K0C2.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C2.hR K0C2.hfin

theorem K0C3.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[3] :=
  centreOK_of_run 0 (e := ⟨1, 15, 5, true, (140344, 58984, 160088), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1941359040680763159890842384906174439619456829144809259935704334051339163243416616529756018785555387955711075428569339471476089013900536113167884034523275874380351167982941617133212) (N := 600) (by decide +kernel) dCtx_ok
    K0C3.hin K0C3.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C3.hR K0C3.hfin

theorem K0C4.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[4] :=
  centreOK_of_run 0 (e := ⟨1, 23, 5, true, (59768, 150632, 216600), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 450891078434432310437607977001846287876528516256910790179703612705508383169021830760289769670258395474880784470715196808610366376229890980104044808382303015983113560684084007756684) (N := 600) (by decide +kernel) dCtx_ok
    K0C4.hin K0C4.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C4.hR K0C4.hfin

theorem K0C5.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[5] :=
  centreOK_of_run 0 (e := ⟨1, 7, 5, true, (179960, 160872, 197784), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 383616000001739145100275693034529811012131895318773452058149685360311220539436286474329894729605576052166722084459573203789790077917813596005816045204126028040534287894612290986668) (N := 600) (by decide +kernel) dCtx_ok
    K0C5.hin K0C5.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C5.hR K0C5.hfin

theorem K0C6.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[6] :=
  centreOK_of_run 0 (e := ⟨1, 27, 5, true, (131096, 251624, 2680), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 7913301725542918334297657083762180876469151722894088418947481905711032064638232459892163892801612863116183316570373402347532660160393788361447045012741070720888282351017010464868) (N := 600) (by decide +kernel) dCtx_ok
    K0C6.hin K0C6.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C6.hR K0C6.hfin

theorem K0C7.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[7] :=
  centreOK_of_run 0 (e := ⟨1, 11, 5, true, (79256, 219880, 164088), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3527976185252939184340438636319122262148116686333215164174601526166099918915726400985810788606949657359034640018171457282484808911393656998673603230792139600435993160901494997256836) (N := 600) (by decide +kernel) dCtx_ok
    K0C7.hin K0C7.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C7.hR K0C7.hfin

theorem K0C8.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[8] :=
  centreOK_of_run 0 (e := ⟨1, 19, 5, true, (240344, 93928, 48568), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 460836961516747855187003066664403791563362312761739442749514366692301623303779958603754087548246906783313752368973806169224272031136234270455629672948695199005496516357054167521524) (N := 600) (by decide +kernel) dCtx_ok
    K0C8.hin K0C8.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C8.hR K0C8.hfin

theorem K0C9.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[9] :=
  centreOK_of_run 0 (e := ⟨1, 3, 5, true, (106584, 187112, 136248), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3995646998300387677642459588450297126812762892361596270519757023960065332412877601740955140199822731679951687924468957824061894772313072294862400526233232213276323572635164314782996) (N := 600) (by decide +kernel) dCtx_ok
    K0C9.hin K0C9.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C9.hR K0C9.hfin

theorem K0C10.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[10] :=
  centreOK_of_run 0 (e := ⟨1, 481, 9, true, (179960, 166520, 197368), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1594373437495917795169111431785041577083454034145438428852562042443300929643319018148996668100431240443630237255934049256791300791220066322933475295450073328954154339584104173432640) (N := 600) (by decide +kernel) dCtx_ok
    K0C10.hin K0C10.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C10.hR K0C10.hfin

theorem K0C11.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[11] :=
  centreOK_of_run 0 (e := ⟨1, 225, 9, true, (91896, 223864, 154360), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 257295580109074816693238440932332162546979865065835532319713967615371435647211892720368845985264864681348002705767098182234851120210118163280231443658045356777327520548813335087424) (N := 600) (by decide +kernel) dCtx_ok
    K0C11.hin K0C11.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C11.hR K0C11.hfin

theorem K0C12.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[12] :=
  centreOK_of_run 0 (e := ⟨1, 353, 9, true, (4856, 64120, 175864), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 948337969591753340453445495084686812444711981768033167921733285941659086218998513512346221971936207420383043665487240512795465889091888169176263216917770489926000828124202815921216) (N := 600) (by decide +kernel) dCtx_ok
    K0C12.hin K0C12.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C12.hR K0C12.hfin

theorem K0C13.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[13] :=
  centreOK_of_run 0 (e := ⟨1, 97, 9, true, (178936, 121464, 132856), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1649681441241680052203535035658415909050887093031468911691671529361180761830362667399945493601477801192144225085191831827503379398485937305988513345235777726068818017579223881053760) (N := 600) (by decide +kernel) dCtx_ok
    K0C13.hin K0C13.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C13.hR K0C13.hfin

theorem K0C14.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[14] :=
  centreOK_of_run 0 (e := ⟨1, 417, 9, true, (223480, 148088, 186616), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1287637224597269477385426067848739464113860534133155273427718635320553746676745343288986300874002715868428483857373251939213789977427715698154048563463374400350676987468077924099520) (N := 600) (by decide +kernel) dCtx_ok
    K0C14.hin K0C14.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C14.hR K0C14.hfin

theorem K0C15.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[15] :=
  centreOK_of_run 0 (e := ⟨1, 161, 9, true, (135416, 205432, 143608), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3651390622657898888290970057625748101366695537143206413977401220663922230603861602410550959817219826196324877127912093535892968770463101851280711597661651077247523774536053850603456) (N := 600) (by decide +kernel) dCtx_ok
    K0C15.hin K0C15.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C15.hR K0C15.hfin

theorem K0C16.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[16] :=
  centreOK_of_run 0 (e := ⟨1, 289, 9, true, (48376, 176760, 165112), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1800988638720279680054005054034535375043155821289148848266320962207002443017635736564388216349275055033120759722210053103996986832969256171049370730855958254871539994365907175035584) (N := 600) (by decide +kernel) dCtx_ok
    K0C16.hin K0C16.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C16.hR K0C16.hfin

theorem K0C17.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[17] :=
  centreOK_of_run 0 (e := ⟨1, 33, 9, true, (222456, 234104, 122104), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1186475128926038242645770955875662941081995970881252656006746800124935419022345924005280637461886226441699211786020858240793604746777626502696324961401692378823679871971165967396032) (N := 600) (by decide +kernel) dCtx_ok
    K0C17.hin K0C17.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C17.hR K0C17.hfin

theorem K0C18.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[18] :=
  centreOK_of_run 0 (e := ⟨1, 241, 8, true, (130168, 136312, 58744), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3409322213588343843282775942903597989562222594623794907449590623416482584786802069748056497387780403329222037351465790714661574408051754969300315017930751391724230698237788819439008) (N := 600) (by decide +kernel) dCtx_ok
    K0C18.hin K0C18.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C18.hR K0C18.hfin

theorem K0C19.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[19] :=
  centreOK_of_run 0 (e := ⟨1, 113, 8, true, (217208, 66680, 37240), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 521906751393809084006465115822765468272768697001533860084016207093423252379016574834696468732342865716004310169432254477530646294594938455541184973066363130997182762587725102926496) (N := 600) (by decide +kernel) dCtx_ok
    K0C19.hin K0C19.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C19.hR K0C19.hfin

theorem K0C20.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[20] :=
  centreOK_of_run 0 (e := ⟨1, 177, 8, true, (42616, 3192, 47992), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1059293029359563048872296314212704942528420475130338896827324182008850500756842159615861284704101488286788279405190434506436071416922526814730674874951055180702275442034319017255968) (N := 600) (by decide +kernel) dCtx_ok
    K0C20.hin K0C20.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C20.hR K0C20.hfin

theorem K0C21.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[21] :=
  centreOK_of_run 0 (e := ⟨1, 49, 8, true, (129656, 64632, 26488), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3886542761674158796919484549394553473963132335122178543419516992753432218287761127380444179762004469934366205747350299186997877487732774745213020728895044546117190831349475295342880) (N := 600) (by decide +kernel) dCtx_ok
    K0C21.hin K0C21.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C21.hR K0C21.hfin

theorem K0C22.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[22] :=
  centreOK_of_run 0 (e := ⟨1, 209, 8, true, (20856, 143480, 53368), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3042182020646852529633702714623363721128017722918808507802862795010894055844384755261729138831506122917457313975207440145985217298609247342053752284071055325328972824604669801744608) (N := 600) (by decide +kernel) dCtx_ok
    K0C22.hin K0C22.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C22.hR K0C22.hfin

theorem K0C23.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[23] :=
  centreOK_of_run 0 (e := ⟨1, 81, 8, true, (107896, 8312, 31864), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1707462629200869315002274971223478674260563965994657639002792528851544162999181731966480875194614003411036272468720848167704681473699503750271200724354299526579354905273718229407200) (N := 600) (by decide +kernel) dCtx_ok
    K0C23.hin K0C23.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C23.hR K0C23.hfin

theorem K0C24.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[24] :=
  centreOK_of_run 0 (e := ⟨1, 145, 8, true, (195448, 239736, 42616), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1937473400136660706520852441476444750851876401438662638350132961137638231143299657771117118455931072987669745250397844117168221202787026003611302512488345749726147292294389256998752) (N := 600) (by decide +kernel) dCtx_ok
    K0C24.hin K0C24.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C24.hR K0C24.hfin

theorem K0C25.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[25] :=
  centreOK_of_run 0 (e := ⟨1, 17, 8, true, (20344, 235640, 21112), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 135739881338414352674444867850939227039259395406378845816133631797381642181040967295727850779399128891523216995291075443000574593617257755869513678968034669459370267126437963734112) (N := 600) (by decide +kernel) dCtx_ok
    K0C25.hin K0C25.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C25.hR K0C25.hfin

theorem K0C26.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[26] :=
  centreOK_of_run 0 (e := ⟨1, 121, 7, true, (224056, 17272, 202424), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 80583368132715525219584785951723586653090062855269539881571721756841326969901831897755208402752997198423146805492967295087625883238862582144300263672212933301719345342083202111568) (N := 600) (by decide +kernel) dCtx_ok
    K0C26.hin K0C26.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C26.hR K0C26.hfin

theorem K0C27.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[27] :=
  centreOK_of_run 0 (e := ⟨1, 57, 7, true, (202040, 23416, 126136), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2466626158590679303038629376096220705810392051811306346781109586874704038649462663607609703026899446700897805468523469478433049620763769703048626462527588699057922031708530766157520) (N := 600) (by decide +kernel) dCtx_ok
    K0C27.hin K0C27.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C27.hR K0C27.hfin

theorem K0C28.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[28] :=
  centreOK_of_run 0 (e := ⟨1, 89, 7, true, (16440, 225144, 33208), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 964668651222731390006344730350100509507657103992506745063681735954378971897122959897871513085997459050731824371290190321980571875449676019008251264737210954347588045677804926308240) (N := 600) (by decide +kernel) dCtx_ok
    K0C28.hin K0C28.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C28.hR K0C28.hfin

theorem K0C29.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[29] :=
  centreOK_of_run 0 (e := ⟨1, 25, 7, true, (256568, 198520, 219064), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 629440687066375176422550774736514925691985361740998294136534083008364726869508887787419855452019344242927965182159556957618384740166232143671228434371140648384853762721005260729872) (N := 600) (by decide +kernel) dCtx_ok
    K0C29.hin K0C29.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C29.hR K0C29.hfin

theorem K0C30.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[30] :=
  centreOK_of_run 0 (e := ⟨1, 105, 7, true, (5560, 41336, 117816), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2966817606553648535783891491827406218087378740044878751997455979092340304985568494970196389770025811397231639374918112675919528067597698003471329186237158694498418920075122615966192) (N := 600) (by decide +kernel) dCtx_ok
    K0C30.hin K0C30.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C30.hR K0C30.hfin

theorem K0C31.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[31] :=
  centreOK_of_run 0 (e := ⟨1, 41, 7, true, (114616, 162168, 41528), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 292776342418049035329372899351776186138877200898656345038864291968553748181384934809066539655623884923908283152409493481074737099272352851468332258818515743253751338345529995552880) (N := 600) (by decide +kernel) dCtx_ok
    K0C31.hin K0C31.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C31.hR K0C31.hfin

theorem K0C32.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[32] :=
  centreOK_of_run 0 (e := ⟨1, 73, 7, true, (256696, 175480, 79672), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2721936662558583949060974550532152689834025583519294326779208798987946201105075867911740403507486855379790778190406920540762061652377722018412273822356683891237858201053344959166768) (N := 600) (by decide +kernel) dCtx_ok
    K0C32.hin K0C32.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C32.hR K0C32.hfin

theorem K0C33.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[33] :=
  centreOK_of_run 0 (e := ⟨1, 9, 7, true, (103608, 1400, 3384), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1431218957147457042238057034214401190317566284935742150915797701561920487113593376580499532847154365715915975369662984592152847976630844263951377613604424545359748884720257472309168) (N := 600) (by decide +kernel) dCtx_ok
    K0C33.hin K0C33.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C33.hR K0C33.hfin

theorem K0C34.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[34] :=
  centreOK_of_run 0 (e := ⟨1, 61, 6, true, (247448, 254328, 136024), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 396630719366396471556805667153510368475554958807791891287820589488171675847503321170540937610809753378204074664931459503541870831507323649519911776279811695550987728968526312507784) (N := 600) (by decide +kernel) dCtx_ok
    K0C34.hin K0C34.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C34.hR K0C34.hfin

theorem K0C35.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[35] :=
  centreOK_of_run 0 (e := ⟨1, 29, 6, true, (88984, 46456, 73304), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1288122461380877512148537192526088878502195267066772752812692484748085426053477227910813817677558580475233204687143202782485236865176101889279666305440510456898917984338263676845768) (N := 600) (by decide +kernel) dCtx_ok
    K0C35.hin K0C35.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C35.hR K0C35.hfin

theorem K0C36.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[36] :=
  centreOK_of_run 0 (e := ⟨1, 45, 6, true, (250136, 119672, 55512), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2163299207675952774622366889851380004913954246148537410427368159950966894777780621146165082100257604732982166040807131194318994987031196356562822619025490300199527749090924198074920) (N := 600) (by decide +kernel) dCtx_ok
    K0C36.hin K0C36.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C36.hR K0C36.hfin

theorem K0C37.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[37] :=
  centreOK_of_run 0 (e := ⟨1, 13, 6, true, (26136, 165752, 58328), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2722311970570318461769940568071051543849364655225029735853903281159198632385615993790807609820356124365608694709242061258683578658736118200386002042757911006205047398858205545248616) (N := 600) (by decide +kernel) dCtx_ok
    K0C37.hin K0C37.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C37.hR K0C37.hfin

theorem K0C38.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[38] :=
  centreOK_of_run 0 (e := ⟨1, 53, 6, true, (170968, 138360, 26136), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 650162548084433695403699388639998623635131908667215157288231139971486228459035975580844914085496110236866940790346182710771688022047407209450567719114976079653269802766842518331224) (N := 600) (by decide +kernel) dCtx_ok
    K0C38.hin K0C38.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C38.hR K0C38.hfin

theorem K0C39.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[39] :=
  centreOK_of_run 0 (e := ⟨1, 21, 6, true, (241880, 90232, 225560), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3411617217243922230357673215969502859397939474074080691018388999038788059483182099641166709525090008798894259440692366504307894517408541357174783816174802626787119559032549356669080) (N := 600) (by decide +kernel) dCtx_ok
    K0C39.hin K0C39.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C39.hR K0C39.hfin

theorem K0C40.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[40] :=
  centreOK_of_run 0 (e := ⟨1, 37, 6, true, (26200, 116344, 175000), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 530254772769198525242250029474059760046428921124665512515758831906959047491372777781299794591729548162839552730161363824138436237466928760400644210411342318436087962965612099348984) (N := 600) (by decide +kernel) dCtx_ok
    K0C40.hin K0C40.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C40.hR K0C40.hfin

theorem K0C41.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[41] :=
  centreOK_of_run 0 (e := ⟨1, 5, 6, true, (31576, 191096, 46744), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2935465849233890866178667292839070714733180140382438206412793926680626314797541916889951616135768455270714035998481965270603466197230193424313723021814478873779021651831493408029496) (N := 600) (by decide +kernel) dCtx_ok
    K0C41.hin K0C41.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C41.hR K0C41.hfin

theorem K0C42.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[42] :=
  centreOK_of_run 0 (e := ⟨1, 30, 5, true, (232272, 254240, 47504), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 635182994483566521644200395486055604229012593728125447223092816915076059855981332500223719100664531654806035020908244127457326929327953443189949984311621690142614994285702485864748) (N := 600) (by decide +kernel) dCtx_ok
    K0C42.hin K0C42.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C42.hR K0C42.hfin

theorem K0C43.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[43] :=
  centreOK_of_run 0 (e := ⟨1, 14, 5, true, (255440, 229152, 49168), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 623448916493030057326919908616936082170270847764009004384375241106983917759068624950290292419621282291577286838547563293176141569803410660006920609978765094532349393403578137385292) (N := 600) (by decide +kernel) dCtx_ok
    K0C43.hin K0C43.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C43.hR K0C43.hfin

theorem K0C44.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[44] :=
  centreOK_of_run 0 (e := ⟨1, 22, 5, true, (198800, 200224, 57552), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1564635956203626796146808282781599276896049820520455673278487445281832949796554716087925767240109272402709472014502539589616810309112655892187233043211059227523771855104713732988348) (N := 600) (by decide +kernel) dCtx_ok
    K0C44.hin K0C44.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C44.hR K0C44.hfin

theorem K0C45.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[45] :=
  centreOK_of_run 0 (e := ⟨1, 6, 5, true, (205584, 128032, 104272), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2067977873062618576400183481672554951874139621343825024171154901013503577504512305304439955072122767993199034119515937283286710920116721357776152341865012848319621446381091833631708) (N := 600) (by decide +kernel) dCtx_ok
    K0C45.hin K0C45.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C45.hR K0C45.hfin

theorem K0C46.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[46] :=
  centreOK_of_run 0 (e := ⟨1, 26, 5, true, (242192, 66784, 185808), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 594795463005368781682094928001300568510022761657591521821669227389185404610266636167097628397867950732316957513584462491643882222663997555095936079822586412635629220759319299579028) (N := 600) (by decide +kernel) dCtx_ok
    K0C46.hin K0C46.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C46.hR K0C46.hfin

theorem K0C47.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[47] :=
  centreOK_of_run 0 (e := ⟨1, 10, 5, true, (178064, 193248, 182096), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 975603709920236133553829256559360701409725334226500389859878403383696659627408716456169564382436369410683509647340111413139798359325141023545652252300456242210543258689684286369716) (N := 600) (by decide +kernel) dCtx_ok
    K0C47.hin K0C47.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C47.hR K0C47.hfin

theorem K0C48.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[48] :=
  centreOK_of_run 0 (e := ⟨1, 18, 5, true, (9424, 183776, 64144), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 271961817682103058304523020248688292467481614382766157554159354619455414699874912097425828561053436551542498805506906136582962831519354291475089558182986795316869456485608050647716) (N := 600) (by decide +kernel) dCtx_ok
    K0C48.hin K0C48.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C48.hR K0C48.hfin

theorem K0C49.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[49] :=
  centreOK_of_run 0 (e := ⟨1, 2, 5, true, (158288, 46048, 195600), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 346967691893135906924599854136339815134423606364389668335740633957008351824202209633597687987993562771721787233994842305786252529697773115572127728105043664759091210935129135608772) (N := 600) (by decide +kernel) dCtx_ok
    K0C49.hin K0C49.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C49.hR K0C49.hfin

theorem K0C50.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[50] :=
  centreOK_of_run 0 (e := ⟨1, 480, 9, true, (206080, 237568, 19712), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 658442003710318690862406562094458220480639893593513463545123488526426901202639114544273162893008010285698654565801440098479258504330620770553785342558028598041433933646544887879488) (N := 600) (by decide +kernel) dCtx_ok
    K0C50.hin K0C50.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C50.hR K0C50.hfin

theorem K0C51.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[51] :=
  centreOK_of_run 0 (e := ⟨1, 224, 9, true, (183552, 106496, 210176), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3880108846730409494174190663243236136453922986643199376414126889253912983033800355775450610923508745548132084333611116184776224032558737571361312339035877042078272576363389851087168) (N := 600) (by decide +kernel) dCtx_ok
    K0C51.hin K0C51.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C51.hR K0C51.hfin

theorem K0C52.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[52] :=
  centreOK_of_run 0 (e := ⟨1, 352, 9, true, (63744, 172032, 114944), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1268260349921660617399681904417393436256002890991018475766021913899836593729772801537913294243220384676943263842888332163781596150540472705605206420546429719362621509350697986368576) (N := 600) (by decide +kernel) dCtx_ok
    K0C52.hin K0C52.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C52.hR K0C52.hfin

theorem K0C53.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[53] :=
  centreOK_of_run 0 (e := ⟨1, 96, 9, true, (41216, 40960, 43264), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2615681142439401823262655688044715674362005179233707133299126884830231630772766946202849542910475371046943707710728467908613242552086090936450547357716043034900271691208725412331072) (N := 600) (by decide +kernel) dCtx_ok
    K0C53.hin K0C53.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C53.hR K0C53.hfin

theorem K0C54.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[54] :=
  centreOK_of_run 0 (e := ⟨1, 416, 9, true, (127232, 90112, 260352), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2681724366752742443567347156605632398057514786546012647878001998127930628266811154810428351871005640535144282726655939633507318172851480937023984513419272208971968453776510575263168) (N := 600) (by decide +kernel) dCtx_ok
    K0C54.hin K0C54.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C54.hR K0C54.hfin

theorem K0C55.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[55] :=
  centreOK_of_run 0 (e := ⟨1, 160, 9, true, (149760, 221184, 69888), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3315519283604667110258893184248278487204496955653562952572632784062986352489103780026737625311129247688863025449803076178732227717371609958724497441969378695806579253712909933303744) (N := 600) (by decide +kernel) dCtx_ok
    K0C55.hin K0C55.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C55.hR K0C55.hfin

theorem K0C56.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[56] :=
  centreOK_of_run 0 (e := ⟨1, 288, 9, true, (7424, 24576, 165120), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3591910309246897014202161560931795488343096856072565451675451937144748126896070742240204769294093132385467385907807794490037961163421336852512146708532417630651569773816674146175680) (N := 600) (by decide +kernel) dCtx_ok
    K0C56.hin K0C56.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C56.hR K0C56.hfin

theorem K0C57.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[57] :=
  centreOK_of_run 0 (e := ⟨1, 32, 9, true, (29952, 155648, 236800), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3785064753488403730988097732244225578668874293181503218881757587467287140311051960634600034430062818849082704914839279118810629511672339149007068128048745177615114958579301935998144) (N := 600) (by decide +kernel) dCtx_ok
    K0C57.hin K0C57.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C57.hR K0C57.hfin

theorem K0C58.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[58] :=
  centreOK_of_run 0 (e := ⟨1, 240, 8, true, (241024, 251904, 207232), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3873818836762557955473208864273752523758040802990920215869290520826840427123118104655069848381425169693065820544631506299833334691750228117513053473924258585741590381677620022068640) (N := 600) (by decide +kernel) dCtx_ok
    K0C58.hin K0C58.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C58.hR K0C58.hfin

theorem K0C59.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[59] :=
  centreOK_of_run 0 (e := ⟨1, 112, 8, true, (121216, 219136, 177536), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1607759522363255301083063660841407165067664804563630306664092074817379216212807414252680727095843761508023774836441109127796973174155371616286800179548141048003951708851921802785440) (N := 600) (by decide +kernel) dCtx_ok
    K0C59.hin K0C59.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C59.hR K0C59.hfin

theorem K0C60.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[60] :=
  centreOK_of_run 0 (e := ⟨1, 176, 8, true, (181120, 137216, 126848), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3834665320822055801239224800745900295544280266556076006327971368488805525918458249019148317231166036563529101580844037393687319406533712716766460774551573192533373216003941711395872) (N := 600) (by decide +kernel) dCtx_ok
    K0C60.hin K0C60.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C60.hR K0C60.hfin

theorem K0C61.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[61] :=
  centreOK_of_run 0 (e := ⟨1, 48, 8, true, (61312, 235520, 97152), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1514057723983363775257035958114762118083663289814139487002146470488727109550296335941683865694414152709531771520793046558606431575512139096239486423003851935491414771946504334272800) (N := 600) (by decide +kernel) dCtx_ok
    K0C61.hin K0C61.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C61.hR K0C61.hfin

theorem K0C62.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[62] :=
  centreOK_of_run 0 (e := ⟨1, 208, 8, true, (247680, 157696, 144256), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2385509292922840755463674758456193445703605474336579325438508924994501508556395159577039316991823135338336614212709394492788837788368526819922785398636806500371573999164525108144352) (N := 600) (by decide +kernel) dCtx_ok
    K0C62.hin K0C62.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C62.hR K0C62.hfin

theorem K0C63.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[63] :=
  centreOK_of_run 0 (e := ⟨1, 80, 8, true, (105344, 256000, 42880), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2546632153761709834557547389368371603078422744281692826813149082090710791424784353749184843778630007287685810128178935825599252020389887193753909153092513737498953475738086776608224) (N := 600) (by decide +kernel) dCtx_ok
    K0C63.hin K0C63.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C63.hR K0C63.hfin

theorem K0C64.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[64] :=
  centreOK_of_run 0 (e := ⟨1, 144, 8, true, (45440, 174080, 28032), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1656176641249403003186943706599692302597152284534792830750745949572288122731561114852489907505007252241456723380730547977864195577830494525161032775846420536258711312528961959591776) (N := 600) (by decide +kernel) dCtx_ok
    K0C64.hin K0C64.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C64.hR K0C64.hfin

theorem K0C65.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[65] :=
  centreOK_of_run 0 (e := ⟨1, 16, 8, true, (165248, 141312, 188800), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2991142552925042549758372427523837390715299885988852131602087392669087990729081575709581819023518876743573906599916502932214050545404794176377310071891924892053443531406467970133088) (N := 600) (by decide +kernel) dCtx_ok
    K0C65.hin K0C65.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C65.hR K0C65.hfin

theorem K0C66.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[66] :=
  centreOK_of_run 0 (e := ⟨1, 120, 7, true, (55616, 35328, 79680), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1191629211692709025645535793988126693121080807714143869876765528371255851301449672838804116969187249420101354778626529057724687023487890039506043037467973166157557146941297380264272) (N := 600) (by decide +kernel) dCtx_ok
    K0C66.hin K0C66.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C66.hR K0C66.hfin

theorem K0C67.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[67] :=
  centreOK_of_run 0 (e := ⟨1, 56, 7, true, (49984, 43520, 143680), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3027406394067444715006411401275546833939492819013223057244358231452431311717121976717963733746695478795958908981167518376105821819380713104874154057532986977975010503124756493346768) (N := 600) (by decide +kernel) dCtx_ok
    K0C67.hin K0C67.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C67.hR K0C67.hfin

theorem K0C68.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[68] :=
  centreOK_of_run 0 (e := ⟨1, 88, 7, true, (249408, 129536, 160832), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1188134023885644485397972148485423367167878409543608158549276979329634250487842048883139228540025218726878211595488487040420503452565857741803232095171005123670410004088054153609360) (N := 600) (by decide +kernel) dCtx_ok
    K0C68.hin K0C68.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C68.hR K0C68.hfin

theorem K0C69.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[69] :=
  centreOK_of_run 0 (e := ⟨1, 24, 7, true, (243776, 39424, 28224), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1735592188396651833274951502997320524241252980515304838312685446539155298525448400475150187206112491046015753551375422044156482036613205830861942109339457920470087353190130752323344) (N := 600) (by decide +kernel) dCtx_ok
    K0C69.hin K0C69.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C69.hR K0C69.hfin

theorem K0C70.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[70] :=
  centreOK_of_run 0 (e := ⟨1, 104, 7, true, (60480, 58880, 129600), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2384792456905296717671473981647127926805089703344361951887456324611321563874669085474712233548705829311722508787795533926036313145974375012306253354497402325043060643182628077100784) (N := 600) (by decide +kernel) dCtx_ok
    K0C70.hin K0C70.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C70.hR K0C70.hfin

theorem K0C71.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[71] :=
  centreOK_of_run 0 (e := ⟨1, 40, 7, true, (197184, 230912, 163904), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1098909580627320825613225942205162041069040535378928557472584319183191971014058680597757858581230240920106930664788753154110460910598761462550994770754788159622057739012629454859632) (N := 600) (by decide +kernel) dCtx_ok
    K0C71.hin K0C71.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C71.hR K0C71.hfin

theorem K0C72.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[72] :=
  centreOK_of_run 0 (e := ⟨1, 72, 7, true, (63296, 54784, 228672), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1197754510307570846049939463042524471608537437362106215947906549990111555783449289076576520598889742085679723543405413530148071253699835049398816338019186191806992348502978889674288) (N := 600) (by decide +kernel) dCtx_ok
    K0C72.hin K0C72.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C72.hR K0C72.hfin

theorem K0C73.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[73] :=
  centreOK_of_run 0 (e := ⟨1, 8, 7, true, (200000, 62976, 197440), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2417336589590505777283405703084300150598519026588856372916214054099232031293006732596632655497453611779785384380327922600496656354043728543462744582301854795354788393812001380048048) (N := 600) (by decide +kernel) dCtx_ok
    K0C73.hin K0C73.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C73.hR K0C73.hfin

theorem K0C74.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[74] :=
  centreOK_of_run 0 (e := ⟨1, 60, 6, true, (161632, 160128, 105824), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1857954363733320363213320625618132531904125194696823467145671354948838782674811850778447471701367065205302995545478238871350298471512938644121264692181712997995250741254356648586568) (N := 600) (by decide +kernel) dCtx_ok
    K0C74.hin K0C74.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C74.hR K0C74.hfin

theorem K0C75.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[75] :=
  centreOK_of_run 0 (e := ⟨1, 28, 6, true, (16992, 18816, 168032), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 2295965823960762616188276953247239991958711320090853290304042825716749251037843458132041631295422063519998097230117162520725816284611904119325168878966115002618260559662877842773640) (N := 600) (by decide +kernel) dCtx_ok
    K0C75.hin K0C75.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C75.hR K0C75.hfin

theorem K0C76.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[76] :=
  centreOK_of_run 0 (e := ⟨1, 44, 6, true, (105696, 181632, 42720), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 3516256760861359872778842055131863940508871416532449251335781651507037079780403874542402458454813833113185355114247930218196932938743484081869235096395552964042016711643492437511144) (N := 600) (by decide +kernel) dCtx_ok
    K0C76.hin K0C76.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C76.hR K0C76.hfin

theorem K0C77.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[77] :=
  centreOK_of_run 0 (e := ⟨1, 12, 6, true, (157664, 64896, 88544), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 388011442481188281746101676643520160318261284422274253293282355464454965597256605337297521244451848439002756264966699488409720178532846949496530873742691556733053824492756827163944) (N := 600) (by decide +kernel) dCtx_ok
    K0C77.hin K0C77.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C77.hR K0C77.hfin

theorem K0C78.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[78] :=
  centreOK_of_run 0 (e := ⟨1, 52, 6, true, (91616, 27264, 252384), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1190026867928733121705780297103235864373911644624282934964066376677718386726535243482227002957047419027862497107698269570385874807741866668185629011195279284441683705236240058644248) (N := 600) (by decide +kernel) dCtx_ok
    K0C78.hin K0C78.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C78.hR K0C78.hfin

theorem K0C79.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[79] :=
  centreOK_of_run 0 (e := ⟨1, 20, 6, true, (137952, 189056, 165600), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1582968824247806967407591477157249759985926532475358897328597729731205624627458528793538437371156540787727514799074648421971835533361011202331493692025474028636917508866413591260248) (N := 600) (by decide +kernel) dCtx_ok
    K0C79.hin K0C79.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C79.hR K0C79.hfin

theorem K0C80.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[80] :=
  centreOK_of_run 0 (e := ⟨1, 36, 6, true, (98400, 48768, 139360), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 805596265661881788621039480372154259296918949872391357579141066011734960302597006921017793127504580217447172268870818189376184486616028161815027694347611836523018900329901671406520) (N := 600) (by decide +kernel) dCtx_ok
    K0C80.hin K0C80.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C80.hR K0C80.hfin

theorem K0C81.cert : CentreOK 0 FurioLombardo.M4.T0.la FurioLombardo.M4.T0.qa FurioLombardo.M4.T0.constant[81] :=
  centreOK_of_run 0 (e := ⟨1, 4, 6, true, (210272, 54912, 200032), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 1 by unfold IsDisc; decide) (Y0 := 1076519769727972066132344232461815582799991863699208993049360315109926828637521599442927860388873263166593326007170244855310983358952604006058623972531535335911248254548600898496760) (N := 600) (by decide +kernel) dCtx_ok
    K0C81.hin K0C81.hphi DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA K0C81.hR K0C81.hfin

theorem constant_ok_0 : ∀ c ∈ FurioLombardo.M4.T0.data.constant, CentreOK 0 FurioLombardo.M4.T0.data.la FurioLombardo.M4.T0.data.qa c := by
  intro c hc
  obtain ⟨i, hi, rfl⟩ := List.mem_iff_getElem.mp hc
  have hi' : i < 82 := hi
  interval_cases i
  exacts [K0C0.cert, K0C1.cert, K0C2.cert, K0C3.cert, K0C4.cert, K0C5.cert, K0C6.cert, K0C7.cert, K0C8.cert, K0C9.cert, K0C10.cert, K0C11.cert, K0C12.cert, K0C13.cert, K0C14.cert, K0C15.cert, K0C16.cert, K0C17.cert, K0C18.cert, K0C19.cert, K0C20.cert, K0C21.cert, K0C22.cert, K0C23.cert, K0C24.cert, K0C25.cert, K0C26.cert, K0C27.cert, K0C28.cert, K0C29.cert, K0C30.cert, K0C31.cert, K0C32.cert, K0C33.cert, K0C34.cert, K0C35.cert, K0C36.cert, K0C37.cert, K0C38.cert, K0C39.cert, K0C40.cert, K0C41.cert, K0C42.cert, K0C43.cert, K0C44.cert, K0C45.cert, K0C46.cert, K0C47.cert, K0C48.cert, K0C49.cert, K0C50.cert, K0C51.cert, K0C52.cert, K0C53.cert, K0C54.cert, K0C55.cert, K0C56.cert, K0C57.cert, K0C58.cert, K0C59.cert, K0C60.cert, K0C61.cert, K0C62.cert, K0C63.cert, K0C64.cert, K0C65.cert, K0C66.cert, K0C67.cert, K0C68.cert, K0C69.cert, K0C70.cert, K0C71.cert, K0C72.cert, K0C73.cert, K0C74.cert, K0C75.cert, K0C76.cert, K0C77.cert, K0C78.cert, K0C79.cert, K0C80.cert, K0C81.cert]

/-- **`HCentre` for twist 0.** Lemma 7.4 of the paper. -/
theorem hCe_0 : FurioLombardo.M4.HCentre FurioLombardo.M4.T0.data (lamD 0) :=
  hCentre_of_ok 0 FurioLombardo.M4.T0.data (lamInt_of 0 (DCertData.lamK_Dpt_le_one 0)) (fun j => (PhiCertData.P0.cert j).2)
    constant_ok_0

end FurioLombardo.Discharge.M4Box.CentreData
