/-
The constant box centres of twist 1: the certificates `K1C<i>.cert` of the 22 boxes of `T1.constant` from the
data files K1C<i>.lean (`centreOK_of_run`), and `HCentre` for `T1.data` (`hCentre_of_ok`, the ball `(la, qa)` of
PhiCertData).
Generated by code/covering/centre_certs_gen.lean (lane lean-m4box); every value is checked by the kernel.
-/
import FurioLombardo.Discharge.M4Box.CentreValue
import FurioLombardo.Discharge.M4Box.PhiCertData.Values
import FurioLombardo.Discharge.M4Box.CentreData.K1C0
import FurioLombardo.Discharge.M4Box.CentreData.K1C1
import FurioLombardo.Discharge.M4Box.CentreData.K1C2
import FurioLombardo.Discharge.M4Box.CentreData.K1C3
import FurioLombardo.Discharge.M4Box.CentreData.K1C4
import FurioLombardo.Discharge.M4Box.CentreData.K1C5
import FurioLombardo.Discharge.M4Box.CentreData.K1C6
import FurioLombardo.Discharge.M4Box.CentreData.K1C7
import FurioLombardo.Discharge.M4Box.CentreData.K1C8
import FurioLombardo.Discharge.M4Box.CentreData.K1C9
import FurioLombardo.Discharge.M4Box.CentreData.K1C10
import FurioLombardo.Discharge.M4Box.CentreData.K1C11
import FurioLombardo.Discharge.M4Box.CentreData.K1C12
import FurioLombardo.Discharge.M4Box.CentreData.K1C13
import FurioLombardo.Discharge.M4Box.CentreData.K1C14
import FurioLombardo.Discharge.M4Box.CentreData.K1C15
import FurioLombardo.Discharge.M4Box.CentreData.K1C16
import FurioLombardo.Discharge.M4Box.CentreData.K1C17
import FurioLombardo.Discharge.M4Box.CentreData.K1C18
import FurioLombardo.Discharge.M4Box.CentreData.K1C19
import FurioLombardo.Discharge.M4Box.CentreData.K1C20
import FurioLombardo.Discharge.M4Box.CentreData.K1C21

namespace FurioLombardo.Discharge.M4Box.CentreData

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

theorem K1C0.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[0] :=
  centreOK_of_run 1 (e := ⟨3, 28, 5, true, (122213, 202069, 174962), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 3508580424120665078667672297737390658427205360003393736345094945526456647163705604745134657901491772227006770970778533292287106331093093391449167560780129254891787566191108919199172) (N := 600) (by decide +kernel) dCtx_ok
    K1C0.hin K1C0.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C0.hR K1C0.hfin

theorem K1C1.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[1] :=
  centreOK_of_run 1 (e := ⟨3, 12, 5, true, (54069, 169893, 184914), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 1562384717458305357729927529219951639541237732768196175597944136723189631965777348365935576509105575939263125156523647357470228766984521033185591182572677878547897171342389996654484) (N := 600) (by decide +kernel) dCtx_ok
    K1C1.hin K1C1.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C1.hR K1C1.hfin

theorem K1C2.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[2] :=
  centreOK_of_run 1 (e := ⟨3, 20, 5, true, (13805, 120861, 235042), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 3883765917907047923508513110476690525215378155606398189767386074078573447518442442104469899532357707079463551675529298976234364174507261532814424836161290321405168400951592119943532) (N := 600) (by decide +kernel) dCtx_ok
    K1C2.hin K1C2.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C2.hR K1C2.hfin

theorem K1C3.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[3] :=
  centreOK_of_run 1 (e := ⟨3, 4, 5, true, (222013, 102893, 25602), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 4047176063378906517010296944698546904086798349424529861616833691156366753568607257810711069703746393234707434540891298657586621145505504332286014755659075172088117972167906081695804) (N := 600) (by decide +kernel) dCtx_ok
    K1C3.hin K1C3.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C3.hR K1C3.hfin

theorem K1C4.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[4] :=
  centreOK_of_run 1 (e := ⟨3, 224, 8, true, (162601, 201209, 160938), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 1554534168457742254295872154873156269625324677128248344513914374621865365650497619393604909092963739235098302348002346720599226211567224354209345749365036455824546645413238667397024) (N := 600) (by decide +kernel) dCtx_ok
    K1C4.hin K1C4.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C4.hR K1C4.hfin

theorem K1C5.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[5] :=
  centreOK_of_run 1 (e := ⟨3, 96, 8, true, (168873, 28281, 233386), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 3767408397418287436677804194864471604012734067268624124947967991046359043841744116466229677733439799413481226680247827664139225370202138353959261948620275116632642019546249160559136) (N := 600) (by decide +kernel) dCtx_ok
    K1C5.hin K1C5.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C5.hR K1C5.hfin

theorem K1C6.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[6] :=
  centreOK_of_run 1 (e := ⟨3, 160, 8, true, (85865, 34873, 70186), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 2226701513285449342808515487704354537497949719843268223343115058943132434614309348594041516384005760658690745560539276581265969123266840324602614790007809192373133011544954407852256) (N := 600) (by decide +kernel) dCtx_ok
    K1C6.hin K1C6.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C6.hR K1C6.hfin

theorem K1C7.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[7] :=
  centreOK_of_run 1 (e := ⟨3, 32, 8, true, (149481, 181433, 126250), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 1644124171263334077856478595721782570893592048142655123316105771250601171487069152718045588851500657603863526576668383300221547090292559574057829327318448931042293790085223066508128) (N := 600) (by decide +kernel) dCtx_ok
    K1C7.hin K1C7.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C7.hR K1C7.hfin

theorem K1C8.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[8] :=
  centreOK_of_run 1 (e := ⟨3, 112, 7, true, (16409, 12905, 25418), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 671571641598716732139598195513768439685916204156721056754228312153178680222790427628295074375520155394263813965427333733408820012915420083392993145194825943492829599977348320974544) (N := 600) (by decide +kernel) dCtx_ok
    K1C8.hin K1C8.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C8.hR K1C8.hfin

theorem K1C9.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[9] :=
  centreOK_of_run 1 (e := ⟨3, 48, 7, true, (112729, 85161, 67786), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 1532673892348626101961091660493370146064211232469637426122936738695561037951669295126080283369926678727487491961702124318490480512191509677143245496792449306443613845010571579064336) (N := 600) (by decide +kernel) dCtx_ok
    K1C9.hin K1C9.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C9.hR K1C9.hfin

theorem K1C10.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[10] :=
  centreOK_of_run 1 (e := ⟨3, 80, 7, true, (118329, 37257, 195082), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 3817424096750541416649633504505648244119148644944730801999651814614274563225094315922015986212850948449285225192145736996401543375357510521574476448374629869475066959257104234067824) (N := 600) (by decide +kernel) dCtx_ok
    K1C10.hin K1C10.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C10.hR K1C10.hfin

theorem K1C11.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[11] :=
  centreOK_of_run 1 (e := ⟨3, 16, 7, true, (228985, 123849, 233354), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 414430365267726611218324078235913454877666846072117383861317486051759691239741477521605934551822123767195751969170203955540021890314157467809088891133115941778665585654369047523504) (N := 600) (by decide +kernel) dCtx_ok
    K1C11.hin K1C11.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C11.hR K1C11.hfin

theorem K1C12.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[12] :=
  centreOK_of_run 1 (e := ⟨3, 56, 6, true, (152113, 84545, 20442), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 2524875640744231524745220371507820960254303172451449704154376304271654468043382266721170376027487585993135509961966781326659214146334586077934766293791111004696906624602111070028840) (N := 600) (by decide +kernel) dCtx_ok
    K1C12.hin K1C12.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C12.hR K1C12.hfin

theorem K1C13.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[13] :=
  centreOK_of_run 1 (e := ⟨3, 24, 6, true, (232785, 30305, 73882), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 4013667707965044510573497353018202608876670199052227264317405726060332777345222196660298368851096291651341625152461719668433661786468880815986367872659254133544686679374992878201544) (N := 600) (by decide +kernel) dCtx_ok
    K1C13.hin K1C13.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C13.hR K1C13.hfin

theorem K1C14.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[14] :=
  centreOK_of_run 1 (e := ⟨3, 40, 6, true, (133185, 170193, 98618), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 2353885791771650866483810310624201745462096280521121802044737899717058827399471509429482947735568188141826592235087439600001595106664899534057158685626127644897350177332232166197880) (N := 600) (by decide +kernel) dCtx_ok
    K1C14.hin K1C14.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C14.hR K1C14.hfin

theorem K1C15.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[15] :=
  centreOK_of_run 1 (e := ⟨3, 8, 6, true, (184673, 217841, 151034), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 3 by unfold IsDisc; decide) (Y0 := 3852586493455085107398953516275838672921385853129145077706130544040784501226992759297377031740300827005398043130343895221317136364957366172402063654649575368709580137864857000633624) (N := 600) (by decide +kernel) dCtx_ok
    K1C15.hin K1C15.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C15.hR K1C15.hfin

theorem K1C16.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[16] :=
  centreOK_of_run 1 (e := ⟨2, 23, 5, true, (95981, 34261, 240368), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 2 by unfold IsDisc; decide) (Y0 := 1712826829417004979287481513539223173052198601724121963817320084587892458770169585193020078886265176583382609294768605125589383768034271095584565890587184612111847915013129415264064) (N := 600) (by decide +kernel) dCtx_ok
    K1C16.hin K1C16.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C16.hR K1C16.hfin

theorem K1C17.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[17] :=
  centreOK_of_run 1 (e := ⟨2, 7, 5, true, (135341, 18837, 76016), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 2 by unfold IsDisc; decide) (Y0 := 441881995440890398360929146235763033978044857508466890495325249760840149502796305743502361393270867026740570260573519224115558045140813411583524339469168801733154423941475169346880) (N := 600) (by decide +kernel) dCtx_ok
    K1C17.hin K1C17.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C17.hR K1C17.hfin

theorem K1C18.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[18] :=
  centreOK_of_run 1 (e := ⟨2, 11, 4, true, (162621, 42149, 201584), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 2 by unfold IsDisc; decide) (Y0 := 602241848935492455466224658448437927320524768812594343954724134926158870276701732141858469271842070335254503942469845573659919670182563078801173128628358144913376515573976730665296) (N := 600) (by decide +kernel) dCtx_ok
    K1C18.hin K1C18.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C18.hR K1C18.hfin

theorem K1C19.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[19] :=
  centreOK_of_run 1 (e := ⟨2, 3, 4, true, (20253, 187781, 221808), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 2 by unfold IsDisc; decide) (Y0 := 2056737094592526899377148790771943413243464779018439960663137135987857442394278453721465424317556708765421739407446272645080254956199771228760019620482283392473215521518828022680528) (N := 600) (by decide +kernel) dCtx_ok
    K1C19.hin K1C19.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C19.hR K1C19.hfin

theorem K1C20.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[20] :=
  centreOK_of_run 1 (e := ⟨2, 5, 3, true, (141493, 150045, 228528), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 2 by unfold IsDisc; decide) (Y0 := 3563766550905789890717429820193726028286677810885211727512534865154708363459527797639881720632948664975627563692963590494546103118111673040572231734649252641423764841936149402757412) (N := 600) (by decide +kernel) dCtx_ok
    K1C20.hin K1C20.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C20.hR K1C20.hfin

theorem K1C21.cert : CentreOK 1 FurioLombardo.M4.T1.la FurioLombardo.M4.T1.qa FurioLombardo.M4.T1.constant[21] :=
  centreOK_of_run 1 (e := ⟨2, 1, 3, true, (88069, 155885, 227376), 0⟩) (by decide +kernel) (by decide +kernel)
    (show IsDisc 2 by unfold IsDisc; decide) (Y0 := 2641641236348314578260222441334859283044664261102602524775926868606086702397760655286378073095482250091361971745019077644556353722283084951063035991988172929299116634598634527539492) (N := 600) (by decide +kernel) dCtx_ok
    K1C21.hin K1C21.hphi DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA K1C21.hR K1C21.hfin

theorem constant_ok_1 : ∀ c ∈ FurioLombardo.M4.T1.data.constant, CentreOK 1 FurioLombardo.M4.T1.data.la FurioLombardo.M4.T1.data.qa c := by
  intro c hc
  obtain ⟨i, hi, rfl⟩ := List.mem_iff_getElem.mp hc
  have hi' : i < 22 := hi
  interval_cases i
  exacts [K1C0.cert, K1C1.cert, K1C2.cert, K1C3.cert, K1C4.cert, K1C5.cert, K1C6.cert, K1C7.cert, K1C8.cert, K1C9.cert, K1C10.cert, K1C11.cert, K1C12.cert, K1C13.cert, K1C14.cert, K1C15.cert, K1C16.cert, K1C17.cert, K1C18.cert, K1C19.cert, K1C20.cert, K1C21.cert]

/-- **`HCentre` for twist 1.** -/
theorem hCe_1 : FurioLombardo.M4.HCentre FurioLombardo.M4.T1.data (lamD 1) :=
  hCentre_of_ok 1 FurioLombardo.M4.T1.data (lamInt_of 1 (DCertData.lamK_Dpt_le_one 1)) (fun j => (PhiCertData.P1.cert j).2)
    constant_ok_1

end FurioLombardo.Discharge.M4Box.CentreData
