\\ class_number_primes.gp: writes FurioLombardo/M2/Data/P<b>.lean of the Lean package, b = 0..119: for every prime p in
\\ [1000 b, 1000 b + 1000) (the last block runs to Bnd = 120000; p not 2, 7, 45613) a packed record n<p>, the kernel check
\\ c<p> : checkPrime p n<p> = true, the list of records and the coverage check of the block.
\\ Run from code/field: gp -q class_number_primes.gp (G5OUT=<dir>/ writes the blocks to <dir> instead, as class_number_primes_rerun.sh does)
default(parisizemax, 4*10^9); default(nbthreads, 1);
read("class_number_prime_certs.gp"); g4init();
outdir = if (#getenv("G5OUT"), getenv("G5OUT"), "../../FurioLombardo/M2/Data/");
blockfile(b) = {
  my(lo = 1000 * b, hi = if (b == 119, Bnd + 1, 1000 * b + 1000), file, ps = List(), name);
  name = Strprintf("P%03d", b);
  file = concat(concat(outdir, name), ".lean");
  system(concat("rm -f ", file));
  \\ three import chains (b mod 3), so that lake builds at most three blocks at a time
  write(file, if (b < 3, "import FurioLombardo.M2.Check", Strprintf("import FurioLombardo.M2.Data.P%03d", b - 3)));
  write(file, "");
  write(file, Strprintf("/-! Certificates for the primes in [%d, %d) (generated by code/field/class_number_primes.gp). -/", lo, hi));
  write(file, "");
  write(file, "namespace FurioLombardo.M2.Data");
  write(file, "");
  write(file, "open FurioLombardo.M2");
  write(file, "");
  forprime(p = max(lo, 3), hi - 1,
    if (p == 7 || p == 45613, next);
    my(N = primerec(p));
    write(file, Strprintf("def n%d : ℕ := %d", p, N));
    write(file, Strprintf("theorem c%d : checkPrime %d n%d = true := by decide +kernel", p, p, p));
    write(file, "");
    listput(ps, p));
  my(s = Strprintf("def recs%s : List (ℕ × ℕ) := [", name));
  for (i = 1, #ps, s = concat(s, Strprintf("(%d, n%d)%s", ps[i], ps[i], if (i < #ps, ", ", ""))));
  write(file, concat(s, "]"));
  write(file, "");
  s = Strprintf("theorem ok%s : AllTrue recs%s := ⟨", name, name);
  for (i = 1, #ps, s = concat(s, Strprintf("c%d, ", ps[i])));
  write(file, concat(s, "trivial⟩"));
  write(file, "");
  write(file, Strprintf("theorem cov%s : coverCheck %d %d (recs%s.map Prod.fst) = true := by decide +kernel", name, lo, hi - lo, name));
  write(file, "");
  write(file, "end FurioLombardo.M2.Data");
  #ps;
}
t0 = getwalltime(); tot = 0;
for (b = 0, 119, tot += blockfile(b); if (b % 10 == 0, print("block ", b, " primes so far ", tot, " time ", getwalltime() - t0)));
print("total primes ", tot, " time ", getwalltime() - t0);
quit
