\\ class_number_global_data.gp: global constants of the M2 certificate, written as Lean (FurioLombardo/M2/Global.lean).
\\ Integral basis zk of PARI (w_j = W_j(theta)/D), lower coefficients of the characteristic
\\ polynomials of the w_j, Kronecker values at 2^512, the resultant identity U f + V f' = Res.
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
f = x^21 - 7*x^20 + 14*x^19 - 84*x^16 + 98*x^15 + 2*x^14 + 175*x^13 - 609*x^12 + 980*x^11 - 770*x^10 - 280*x^9 + 1008*x^8 - 1072*x^7 + 560*x^6 + 28*x^5 - 336*x^4 + 252*x^3 - 112*x^2 + 28*x - 4;
bnf = read("field_bnf.bin"); nf = bnf.nf; n = 21; kK = 512;
zk = nf.zk;
D = lcm(vector(n, j, denominator(content(zk[j]))));
lst(g, len) = vector(len, j, polcoef(g, j - 1));
W = vector(n, j, lst(D * zk[j], n));
CH = vector(n, j, my(c = charpoly(Mod(zk[j], f))); if (denominator(content(c)) != 1 || pollead(c) != 1 || poldegree(c) != n, error("charpoly")); lst(c, n));
\\ checks: characteristic polynomials vanish, W integral
for (j = 1, n, my(c = Pol(concat(CH[j], [1])~ * 0)); if (subst(x^n + sum(i = 1, n, CH[j][i] * x^(i-1)), x, Mod(zk[j], f)) != 0, error("charpoly value")));
R = polresultantext(f, f'); U = R[1]; V = R[2]; Res = polcoef(R[3], 0);
if (denominator(content(U)) != 1 || denominator(content(V)) != 1, error("U V"));
if (U * f + V * f' != Res, error("bezout"));
om = vector(n, j, subst(D * zk[j], x, 2^kK));
Fk = subst(f, x, 2^kK);
fmtl(v) = { my(s = "["); for (i = 1, #v, s = concat(s, Str(v[i])); if (i < #v, s = concat(s, ", "))); concat(s, "]"); }
out = Str(LEANDIR, "FurioLombardo/M2/Global.lean");
system(concat("rm -f ", out));
w(s) = write(out, s);
w("import FurioLombardo.M2.Defs");
w("");
w("/-!");
w("# Global constants of the M2 certificate (generated by code/field/class_number_global_data.gp)");
w("");
w("`fL`: coefficients of `fZ` (constant first). `DD`, `WL`: PARI's integral basis `w_j = W_j(θ)/DD`.");
w("`chiL`: lower coefficients of the characteristic polynomial of `w_j` (monic, degree 21).");
w("`omL`: the Kronecker values `W_j(2^512)`, `Fk = fZ(2^512)`. `UL`, `VL`, `ResZ`: `U fZ + V fZ' = ResZ`.");
w("-/");
w("");
w("namespace FurioLombardo.M2");
w("");
w("/-- Coefficients of `fZ`, constant term first. -/");
w(concat("def fL : List ℤ := ", fmtl(lst(f, n + 1))));
w("");
w("/-- Lower coefficients of `fZ` (`fZ = X ^ 21 + fLow`). -/");
w(concat("def fLow : List ℤ := ", fmtl(lst(f, n))));
w("");
w("/-- Coefficients of `fZ'`. -/");
w(concat("def fdL : List ℤ := ", fmtl(lst(f', n))));
w("");
w("/-- Common denominator of the integral basis. -/");
w(concat("def DD : ℤ := ", D));
w("");
w("/-- Numerators of the integral basis: `w_j = W_j(θ) / DD`. -/");
w("def WL : List (List ℤ) := [");
for (j = 1, n, w(concat(concat("  ", fmtl(W[j])), if (j < n, ",", "]"))));
w("");
w("/-- Lower coefficients of the characteristic polynomials of the `w_j`. -/");
w("def chiL : List (List ℤ) := [");
for (j = 1, n, w(concat(concat("  ", fmtl(CH[j])), if (j < n, ",", "]"))));
w("");
w("/-- `W_j(2^512)`. -/");
w("def omL : List ℤ := [");
for (j = 1, n, w(concat(concat("  ", Str(om[j])), if (j < n, ",", "]"))));
w("");
w("/-- `fZ(2^512)`. -/");
w(concat("def Fk : ℤ := ", Fk));
w("");
w("/-- The resultant of `fZ` and `fZ'` (up to sign). -/");
w(concat("def ResZ : ℤ := ", Res));
w("");
w("/-- `UL fZ + VL fZ' = ResZ`. -/");
w(concat("def UL : List ℤ := ", fmtl(lst(U, poldegree(U) + 1))));
w("");
w(concat("def VL : List ℤ := ", fmtl(lst(V, poldegree(V) + 1))));
w("");
w("end FurioLombardo.M2");
print("D = ", D, "  Res = ", factor(Res), "  max|W| < 2^", ceil(log(vecmax(apply(v -> vecmax(apply(abs, v)), W)))/log(2)));
print("deg U ", poldegree(U), " deg V ", poldegree(V));
quit
