\\ discriminant_bound.gp: data and kernel checks for the discriminant bound |disc K21| <= 2^22 7^27 of M2,
\\ written as lean/FurioLombardo/M2/DiscrData.lean.
\\ (1) HNF family: hW_j = sum_k hA_j[k] W_k (W_k the numerators of PARI's integral basis, w_k = W_k(theta)/DD),
\\     upper triangular in the power basis (coefficient i of hW_j is 0 for i > j), diagonal product diagP.
\\ (2) beta = f'(theta): characteristic polynomial X^21 + chiB, and M theta = H(beta) with M = MB, H = HB.
\\ (3) diagP^2 chiB[0] = DD^42 2^22 7^27.
\\ Every check the kernel runs is replayed here first. Run from code/field: gp -q discriminant_bound.gp < /dev/null
default(parisizemax, 2*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("class_number_prime_certs.gp"); g4init();
outfile = Str(LEANDIR, "FurioLombardo/M2/DiscrData.lean");
lstr(v) = { my(s = "["); for (i = 1, #v, s = concat(s, Str(v[i])); if (i < #v, s = concat(s, ", "))); concat(s, "]"); }
llstr(V) = { my(s = "[\n"); for (i = 1, #V, s = concat(s, concat("  ", lstr(V[i]))); if (i < #V, s = concat(s, ",\n"))); concat(s, "]"); }
\\ ---- (1) the HNF family
Mw = matrix(n, n, i, j, polcoef(Wp[j], i - 1));
if (denominator(Mw) != 1, error("Mw not integral"));
Hw = mathnf(Mw);
if (matsize(Hw) != [n, n], error("Hw size"));
for (i = 1, n, for (j = 1, i - 1, if (Hw[i, j] != 0, error("Hw not upper triangular ", [i, j]))));
for (j = 1, n, if (Hw[j, j] <= 0, error("Hw diagonal ", j)));
U = Mw^(-1) * Hw;
if (denominator(U) != 1, error("U not integral"));
if (abs(matdet(U)) != 1, error("U not unimodular"));
if (Mw * U != Hw, error("Mw U != Hw"));
hA = vector(n, j, Vec(U[, j]));
hW = vector(n, j, Vec(Hw[, j]));
\\ replay of comboK hA_j WL = hW_j (WL[k] = Vecrev(Wp[k], n))
WLv = vector(n, k, Vecrev(Wp[k], n));
for (j = 1, n, if (sum(k = 1, n, hA[j][k] * WLv[k]) != hW[j], error("combo ", j)));
for (j = 1, n, if (#hW[j] != n || #hA[j] != n, error("lengths ", j)));
diagP = prod(j = 1, n, Hw[j, j]);
idx = D^n / diagP;
if (denominator(idx) != 1, error("index"));
print("index = ", factor(idx));
\\ ---- (2) beta = f'(theta)
fd = f'; b = Mod(fd, f); chi = charpoly(b);
if (poldegree(chi) != n || pollead(chi) != 1, error("chi"));
if (!polisirreducible(chi), error("chi reducible"));
if (subst(chi, x, b) != 0, error("chi(beta)"));
Hm = lift(modreverse(b)); MB = denominator(content(Hm)); HB = MB * Hm;
if (poldegree(HB) > n - 1, error("H degree"));
if (subst(HB, x, b) != MB * Mod(x, f), error("H(beta) != M theta"));
if (Vecrev(fd, n) != [28, -224, 756, -1344, 140, 3360, -7504, 8064, -2520, -7700, 10780, -7308, 2275, 28, 1470, -1344, 0, 0, 266, -140, 21], error("fdL"));
chiB = Vecrev(chi)[1..n]; HBv = Vecrev(HB, n);
if (abs(polcoef(chi, 0)) != abs(poldisc(f)), error("norm vs disc"));
\\ ---- (3) the numerical identity
if (diagP^2 * chiB[1] != D^(2*n) * 2^22 * 7^27, error("numerical identity"));
if (nf.disc != -2^22 * 7^27, error("disc"));
\\ ---- output
system(concat("rm -f ", outfile));
write(outfile, "import FurioLombardo.M2.Check2");
write(outfile, "");
write(outfile, "/-! Data and kernel checks for the discriminant bound of K21 (generated by code/field/discriminant_bound.gp).");
write(outfile, "");
write(outfile, "`hW_j = Σ_k hA_j[k] W_k` is upper triangular in the power basis with diagonal product `diagP`;");
write(outfile, "`β = fZ'(θ)` has characteristic polynomial `X^21 + chiB` and `MB θ = HB(β)`. -/");
write(outfile, "");
write(outfile, "namespace FurioLombardo.M2.Discr");
write(outfile, "");
write(outfile, "open FurioLombardo.M2");
write(outfile, "");
write(outfile, Strprintf("/-- Coordinates of the triangular family in the basis `w`. -/\ndef hA : List (List ℤ) := %s", llstr(hA)));
write(outfile, "");
write(outfile, Strprintf("/-- Numerators of the triangular family: `hW_j(θ) / DD`. -/\ndef hW : List (List ℤ) := %s", llstr(hW)));
write(outfile, "");
write(outfile, Strprintf("/-- Product of the diagonal coefficients of `hW`. -/\ndef diagP : ℤ := %d", diagP));
write(outfile, "");
write(outfile, Strprintf("/-- Lower coefficients of the characteristic polynomial of `fZ'(θ)`. -/\ndef chiB : List ℤ := %s", lstr(chiB)));
write(outfile, "");
write(outfile, Strprintf("/-- `MB θ = HB(fZ'(θ))`. -/\ndef HB : List ℤ := %s", lstr(HBv)));
write(outfile, "");
write(outfile, Strprintf("/-- Denominator of `θ` as a polynomial in `fZ'(θ)`. -/\ndef MB : ℤ := %d", MB));
write(outfile, "");
write(outfile, "theorem hA_combo : ∀ j, j < 21 → allZero (addZ (comboK (hA.getD j []) WL) (smulZ (-1) (hW.getD j []))) = true := by\n  decide +kernel");
write(outfile, "");
write(outfile, "theorem hW_len : ∀ j, j < 21 → (hW.getD j []).length = 21 := by decide +kernel");
write(outfile, "");
write(outfile, "theorem hW_tri : ∀ i, i < 21 → ∀ j, j < i → (hW.getD j []).getD i 0 = 0 := by decide +kernel");
write(outfile, "");
write(outfile, "theorem hW_diag : ((List.range 21).map fun i => (hW.getD i []).getD i 0).prod = diagP := by\n  decide +kernel");
write(outfile, "");
write(outfile, "theorem diag_num : diagP ^ 2 * chiB.getD 0 0 = DD ^ 42 * (2 ^ 22 * 7 ^ 27) := by decide +kernel");
write(outfile, "");
write(outfile, "theorem chiB_len : chiB.length = 21 ∧ HB.length = 21 := by decide +kernel");
write(outfile, "");
write(outfile, "theorem chi_beta : allZero (homogL fLow fdL 1 (chiB ++ [1])) = true := by decide +kernel");
write(outfile, "");
write(outfile, "theorem H_beta : allZero (addZ (homogL fLow fdL 1 HB) [0, -MB]) = true := by decide +kernel");
write(outfile, "");
write(outfile, "theorem MB_ne_zero : MB ≠ 0 := by decide +kernel");
write(outfile, "");
write(outfile, "end FurioLombardo.M2.Discr");
print("hA max bits ", vecmax(apply(v -> exponent(vecmax(apply(abs, v)) + 1), hA)), ", hW max bits ", vecmax(apply(v -> exponent(vecmax(apply(abs, v)) + 1), hW)));
print("diagP = ", factor(diagP));
print("chi0 = ", factor(chiB[1]), "; MB digits ", #Str(MB), "; HB max digits ", vecmax(apply(c -> #Str(abs(c)), HBv)));
quit
