/-! Data of lane M1 (generated by code/descent/sieve_3adic_data.gp, PARI/GP): the residue map `𝓞 K21 → ℤ/27`,
`θ ↦ 17`. Inverses of `DB` and `Dz` modulo 27, residues of the coefficients of `Q1` and `Q3` (on x², xy, xz, y²,
yz, z²) and of `G_k` for the survivors `k < 4` of the good prime sieve. Rechecked by the kernel in Local3.lean. -/

namespace FurioLombardo.M1

/-- `DB⁻¹` modulo 27. -/
def uB27 : Int := 20

/-- `Dz⁻¹` modulo 27. -/
def uD27 : Int := 8

/-- Residues of the coefficients of `Q1` and `Q3`. -/
def q27 : List (List Int) := [[18, 22, 16, 3, 13, 0], [12, 1, 4, 6, 13, 18]]

/-- Residues of `G_k` (`k < 4`). -/
def g27 : List Int := [13, 13, 22, 25]

end FurioLombardo.M1
