#!/bin/sh
# count_lean_data.sh: copies the Lean data that count_certs.gp certifies against (4 fRev_k = FnData, the numerator of
# d = dnData / 46^2, the atoms zData of ND) into count_lean_data.gp, so that the certificates are computed from the exact
# lists the kernel evaluates. Run from code/selmer-local-conditions: sh count_lean_data.sh
L=../../FurioLombardo/Discharge/M3a
ext() { sed -n "/^def $2 /,/^\$/p" "$1" | sed "1s/^def $2 .*:=/{$2 =/" | sed '/^$/d'; echo ";}"; }
{
  printf "%s\n" "\\\\ generated by count_lean_data.sh from lean/FurioLombardo/Discharge/M3a (DataBruin.lean, LocalData.lean)"
  ext $L/DataBruin.lean FnData
  ext $L/DataBruin.lean dnData
  ext $L/LocalData.lean zData
  ext $L/LocalData.lean zDen
} > count_lean_data.gp
