#!/bin/bash
# Writes the kernel checks of the real sign data, one declaration per
# certificate, into lean/FurioLombardo/Discharge/SelmerBasis/:
#   RealSignCheckL.lean   ckLf k i (gensL, k = 0, 1, i < 29), idLf i, the tower ckTf, the bits ckBf, idBeta;
#   RealSignCheckM.lean   ckMf k j (M of gensN at tau', j < 53);
#   RealSignCheckN.lean   ckNf k j (gensN at embH 0);
#   RealSignCheckI0.lean, RealSignCheckI1.lean   idNf j (j < 27, 27 <= j < 53).
# Each file closes with the statements for all indices at once (`interval_cases`).
# Checkers: RealSignDefs.lean; data: RealSignData.lean (code/selmer-local-conditions/local_data_real.gp).
# Usage: code/selmer-local-conditions/kernel_checks_real.sh (from any directory); LEANOUT=<dir> writes into <dir> instead.
set -eu
cd "$(dirname "$0")/../.."
dir=${LEANOUT:-lean/FurioLombardo/Discharge/SelmerBasis}; dir=${dir%/}
list() { local p=$1 a=$2 b=$3 s="" i; for ((i = a; i < b; i++)); do s="$s${s:+, }$p$i"; done; echo "$s"; }
head_() { # imports, title, docstring body
  cat <<EOF
$1

/-!
# $2 (generated by code/selmer-local-conditions/kernel_checks_real.sh)

$3
Every statement is closed by \`decide +kernel\`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.RealRoots

EOF
}
alls() { # name, bound, checker text with @ for the index, per-index prefix, first index
  local nm=$1 n=$2 txt=$3 p=$4 a=${5:-0}
  echo "theorem $nm : ∀ i, $a ≤ i → i < $n → ${txt//@/i} = true := by"
  echo "  intro i ha hi"; echo "  interval_cases i"; echo "  exacts [$(list "$p" "$a" "$n")]"; echo
}
imp="import FurioLombardo.Discharge.SelmerBasis.RealSignDefs"
{
  head_ "$imp" "Kernel checks of the real signs: gensL, tower, bits" \
    "\`ck_L<k>_i\`: the sign certificates of \`gensL i\` at \`embQ k\`; \`id_L_i\`: its norm; \`ck_T\`, \`ck_B\`, \`id_Beta\`."
  for k in 0 1; do
    for ((i = 0; i < 29; i++)); do
      echo "theorem ck_L${k}_$i : ckLf $k $i = true := by decide +kernel"; echo
    done
  done
  for ((i = 0; i < 29; i++)); do
    echo "theorem id_L_$i : idLf $i = true := by decide +kernel"; echo
  done
  echo "theorem ck_T : ∀ k : Fin 2, ckTf k = true := by decide +kernel"; echo
  echo "theorem ck_B : ∀ k : Fin 2, ckBf k = true := by decide +kernel"; echo
  echo "theorem id_Beta : idBeta = true := by decide +kernel"; echo
  alls ck_L0 29 "ckLf 0 @" ck_L0_
  alls ck_L1 29 "ckLf 1 @" ck_L1_
  alls id_L 29 "idLf @" id_L_
  echo "end FurioLombardo.Discharge.SelmerBasis.RealRoots"
} > $dir/RealSignCheckL.lean
for f in M N; do
  {
    head_ "$imp" "Kernel checks of the real signs: ck${f}f" \
      "\`ck_${f}<k>_j\`: \`ck${f}f k j\` for \`k = 0, 1\`, \`j < 53\`."
    for k in 0 1; do
      for ((j = 0; j < 53; j++)); do
        echo "theorem ck_${f}${k}_$j : ck${f}f $k $j = true := by decide +kernel"; echo
      done
    done
    alls ck_${f}0 53 "ck${f}f 0 @" ck_${f}0_
    alls ck_${f}1 53 "ck${f}f 1 @" ck_${f}1_
    echo "end FurioLombardo.Discharge.SelmerBasis.RealRoots"
  } > $dir/RealSignCheck$f.lean
done
for part in 0 1; do
  if [ $part = 0 ]; then a=0; b=27; else a=27; b=53; fi
  {
    head_ "$imp" "Kernel checks of the real signs: identities of gensN, part $part" \
      "\`id_N_j\` ($a ≤ j < $b): \`m0\`, \`m1\`, \`N(M)\`, \`N(A)\`, \`N(b0 + b1 w)\` of \`gensN j\`."
    for ((j = a; j < b; j++)); do
      echo "theorem id_N_$j : idNf $j = true := by decide +kernel"; echo
    done
    alls id_N$part $b "idNf @" id_N_ $a
    echo "end FurioLombardo.Discharge.SelmerBasis.RealRoots"
  } > $dir/RealSignCheckI$part.lean
done
wc -l $dir/RealSignCheck*.lean
