#!/bin/bash
# Writes the kernel checks of the w3 data, one declaration per certificate, into
# lean/FurioLombardo/Discharge/SelmerBasis/:
#   W3CheckE.lean   EisData.ok, LModel.ok, SqrtData.ok;
#   W3CheckK.lean   the 13 kappa certificates and the 29 gensL certificates (component 1);
#   W3CheckN.lean   the 2 x 53 gensN certificates (components 2 and 3);
#   W3CheckK0.lean, W3CheckK1.lean   per twist, the 14 points (okD, okZ, okT) and their 3 x 14 mu certificates.
# Each file closes with the statements for all indices at once (`interval_cases`).
# Data: W3Data.lean, W3DataK<k>.lean (code/selmer-local-conditions/local_data_w6.gp). Kernel costs: code/formal-proof/w6_kernel_probe_full.out.
# Usage: code/selmer-local-conditions/kernel_checks_w6.sh (from the repository root); LEANOUT=<dir> writes into <dir> instead.
set -eu
cd "$(dirname "$0")/../.."
dir=${LEANOUT:-lean/FurioLombardo/Discharge/SelmerBasis}; dir=${dir%/}
list() { local p=$1 n=$2 s="" i; for ((i = 0; i < n; i++)); do s="$s${s:+, }$p$i"; done; echo "$s"; }
head_() { # file, import, title, body text of the docstring
  cat <<EOF
import $2

/-!
# $3 (generated by code/selmer-local-conditions/kernel_checks_w6.sh)

$4
Every statement is closed by \`decide +kernel\`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.W3

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower

EOF
}
{
  head_ W3CheckE FurioLombardo.Discharge.SelmerBasis.W3Data "Kernel checks of the model at w3" \
    "The Eisenstein data \`E\`, the model \`M\` (\`omega -> y + c Y\`) and the square root data \`S\`."
  cat <<'EOF'
theorem ck_E : E.ok = true := by decide +kernel

theorem ck_M : M.ok E = true := by decide +kernel

theorem ck_S : S.ok E M = true := by decide +kernel

end FurioLombardo.Discharge.SelmerBasis.W3
EOF
} > $dir/W3CheckE.lean
{
  head_ W3CheckK "FurioLombardo.Discharge.SelmerBasis.W3Data
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem" "Kernel checks of the kappa and gensL certificates at w3" \
    "\`ck_K_i\`: the square certificate of \`dyGen al i\` (the same at the three components); \`ck_L_s\`: that of
\`iL (gensL s)\` at component 1."
  for ((i = 0; i < 13; i++)); do
    echo "theorem ck_K_$i : certOK E (cK.getD $i default).n0 (kapX E $i) (.int 0) (cK.getD $i default) = true := by"
    echo "  decide +kernel"; echo
  done
  for ((s = 0; s < 29; s++)); do
    echo "theorem ck_L_$s : certOK E (cL.getD $s default).n0 (X0L M (ofL (SUnitData.gL.getD $s [])))"
    echo "    (X1L M (ofL (SUnitData.gL.getD $s []))) (cL.getD $s default) = true := by"
    echo "  decide +kernel"; echo
  done
  echo "theorem ck_K : ∀ i, i < 13 → certOK E (cK.getD i default).n0 (kapX E i) (.int 0) (cK.getD i default) = true := by"
  echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_K_ 13)]"; echo
  echo "theorem ck_L : ∀ s, s < 29 → certOK E (cL.getD s default).n0 (X0L M (ofL (SUnitData.gL.getD s [])))"
  echo "    (X1L M (ofL (SUnitData.gL.getD s []))) (cL.getD s default) = true := by"
  echo "  intro s hs"; echo "  interval_cases s"; echo "  exacts [$(list ck_L_ 29)]"; echo
  echo "end FurioLombardo.Discharge.SelmerBasis.W3"
} > $dir/W3CheckK.lean
{
  head_ W3CheckN "FurioLombardo.Discharge.SelmerBasis.W3Data
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem" "Kernel checks of the gensN certificates at w3" \
    "\`ck_N1_s\`, \`ck_N2_s\`: the square certificates of \`iN true (gensN s)\` and \`iN false (gensN s)\`
(components 2 and 3), for the approximation \`X0N\`, \`X1N\` of PlaceWElem.lean."
  for c in 1 2; do
    b=$([ $c = 1 ] && echo true || echo false)
    for ((s = 0; s < 53; s++)); do
      echo "theorem ck_N${c}_$s : certOK E (cN$c.getD $s default).n0 (X0N E M S (ofN (SUnitData.gN.getD $s [])) $b)"
      echo "    (X1N E M S (ofN (SUnitData.gN.getD $s [])) $b) (cN$c.getD $s default) = true := by"
      echo "  decide +kernel"; echo
    done
    echo "theorem ck_N$c : ∀ s, s < 53 → certOK E (cN$c.getD s default).n0 (X0N E M S (ofN (SUnitData.gN.getD s [])) $b)"
    echo "    (X1N E M S (ofN (SUnitData.gN.getD s [])) $b) (cN$c.getD s default) = true := by"
    echo "  intro s hs"; echo "  interval_cases s"; echo "  exacts [$(list ck_N${c}_ 53)]"; echo
  done
  echo "end FurioLombardo.Discharge.SelmerBasis.W3"
} > $dir/W3CheckN.lean
for k in 0 1; do
  {
    head_ W3CheckK$k "FurioLombardo.Discharge.SelmerBasis.W3Data
import FurioLombardo.Discharge.SelmerBasis.W3DataK$k
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem" "Kernel checks of the points of twist $k at w3" \
      "\`ck_pt_i\`: the point data \`pt_i\` (\`okD\`, \`okZ\` for \`4 fRev_$k\`, \`okT\`); \`ck_M1_i\`, \`ck_M2_i\`, \`ck_M3_i\`:
the square certificates of \`Λ² U_i\` at the three components."
    echo "namespace K$k"; echo
    for ((i = 0; i < 14; i++)); do
      echo "theorem ck_pt_$i : (pts.getD $i default).okD E = true ∧ (pts.getD $i default).okZ E (gW $k) = true ∧"
      echo "    (pts.getD $i default).okT = true := by"
      echo "  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel"; echo
      echo "theorem ck_M1_$i : certOK E (cM1.getD $i default).n0 (X0L M (ofL (pts.getD $i default).tL))"
      echo "    (X1L M (ofL (pts.getD $i default).tL)) (cM1.getD $i default) = true := by"
      echo "  decide +kernel"; echo
      for c in 2 3; do
        b=$([ $c = 2 ] && echo true || echo false)
        echo "theorem ck_M${c}_$i : certOK E (cM$c.getD $i default).n0 (X0N E M S (ofN (pts.getD $i default).tN) $b)"
        echo "    (X1N E M S (ofN (pts.getD $i default).tN) $b) (cM$c.getD $i default) = true := by"
        echo "  decide +kernel"; echo
      done
    done
    echo "theorem ck_pt : ∀ i, i < 14 → (pts.getD i default).okD E = true ∧ (pts.getD i default).okZ E (gW $k) = true ∧"
    echo "    (pts.getD i default).okT = true := by"
    echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_pt_ 14)]"; echo
    echo "theorem ck_M1 : ∀ i, i < 14 → certOK E (cM1.getD i default).n0 (X0L M (ofL (pts.getD i default).tL))"
    echo "    (X1L M (ofL (pts.getD i default).tL)) (cM1.getD i default) = true := by"
    echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_M1_ 14)]"; echo
    for c in 2 3; do
      b=$([ $c = 2 ] && echo true || echo false)
      echo "theorem ck_M$c : ∀ i, i < 14 → certOK E (cM$c.getD i default).n0 (X0N E M S (ofN (pts.getD i default).tN) $b)"
      echo "    (X1N E M S (ofN (pts.getD i default).tN) $b) (cM$c.getD i default) = true := by"
      echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_M${c}_ 14)]"; echo
    done
    echo "end K$k"; echo
    echo "end FurioLombardo.Discharge.SelmerBasis.W3"
  } > $dir/W3CheckK$k.lean
done
