#!/bin/bash
# Installs the w7 data of code/selmer-local-conditions/lean_data_w7.gp and writes its kernel checks,
# one `decide +kernel` per certificate, into lean/FurioLombardo/Discharge/SelmerBasis/:
#   W7Data.lean, W7DataL.lean, W7DataN.lean   the data (copied from /tmp/sp7_2/lean/ after checking lean_data_w7.out);
#   W7CheckM.lean   tab_len, tab_zero, ck_tab, ck_M, ck_pt, ck_pair, ck_K;
#   W7CheckL.lean   ck_L (29 gensL);
#   W7CheckN0.lean, W7CheckN1.lean, W7CheckN.lean   ck_N (53 gensN, s < 27 and 27 <= s < 53, then gathered);
#   W7CheckB.lean   kap_bits, mu_bits, cgL_bits, cgN_bits, annI, leftInv, annCk, annCm, c7_rows;
#   W7Check.lean    imports the four check modules.
# The statements are those of the docstring of W7Spec.lean, closed per index by `interval_cases`.
# Usage: code/selmer-local-conditions/kernel_checks_w7.sh (from any directory); LEANOUT=<dir> writes into <dir> instead.
set -eu
cd "$(dirname "$0")/../.."
dir=${LEANOUT:-lean/FurioLombardo/Discharge/SelmerBasis}; dir=${dir%/}
src=/tmp/sp7_2/lean
out=code/selmer-local-conditions/lean_data_w7.out
last=$(tail -1 $out)
case "$last" in
  "DONE, 0 failed checks"*) ;;
  *) echo "lean_data_w7.out does not end with DONE, 0 failed checks: $last" >&2; exit 1 ;;
esac
if grep -q "CHECK FAILED\|^FAILED" $out; then echo "lean_data_w7.out holds a failed check" >&2; exit 1; fi
for f in W7Data W7DataL W7DataN; do
  sz=$(wc -c < $src/$f.lean)
  if [ "$sz" -gt 450000 ]; then echo "$f.lean is $sz bytes: split it (code/selmer-local-conditions/split_lean_data.sh)" >&2; exit 1; fi
  cp $src/$f.lean $dir/$f.lean
done
list() { local p=$1 a=$2 b=$3 s="" i; for ((i = a; i < b; i++)); do s="$s${s:+, }$p$i"; done; echo "$s"; }
head_() { # imports (one per line), title, docstring body
  echo "$1" | sed 's/^/import /'
  cat <<EOF

/-!
# $2 (generated by code/selmer-local-conditions/kernel_checks_w7.sh)

$3
Every certificate is closed by \`decide +kernel\` in its own declaration. Data: W7Data*.lean (code/selmer-local-conditions/lean_data_w7.gp).
-/

namespace FurioLombardo.Discharge.SelmerBasis.W7

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis
open FurioLombardo.M2.Special (al7)

EOF
}
alls() { # statement name, variable, bound, statement body with @ for the variable, per-index prefix, first index
  local nm=$1 v=$2 n=$3 txt=$4 p=$5 a=${6:-0}
  if [ "$a" = 0 ]; then
    echo "theorem $nm : ∀ $v, $v < $n → ${txt//@/$v} := by"
    echo "  intro $v h$v"
  else
    echo "theorem $nm : ∀ $v, $a ≤ $v → $v < $n → ${txt//@/$v} := by"
    echo "  intro $v ha h$v"
  fi
  echo "  interval_cases $v"; echo "  exacts [$(list "$p" "$a" "$n")]"; echo
}
{
  head_ "FurioLombardo.Discharge.SelmerBasis.W7Data" "Kernel checks of the w7 model, points, pairs and kappa" \
    "The power table, the model \`M\`, the four points, the three pairs (\`okU\`, \`toPt.okT\`, \`okC\`) and the
certificates of \`al7\`, \`-1\` at \`F'\`."
  echo "theorem tab_len : tab.length = 9 := by decide +kernel"; echo
  echo "theorem tab_zero : tab.getD 0 [] = al7 := by decide +kernel"; echo
  for ((i = 0; i < 8; i++)); do
    echo "theorem ck_tab_$i : powOK tab (tabK.getD $i 0) $i = true := by decide +kernel"; echo
  done
  alls ck_tab i 8 "powOK tab (tabK.getD @ 0) @ = true" ck_tab_
  echo "theorem ck_M : M.ok tab = true := by decide +kernel"; echo
  for ((i = 0; i < 4; i++)); do
    echo "theorem ck_pt_$i : (pts.getD $i default).ok tab = true := by decide +kernel"; echo
  done
  alls ck_pt i 4 "(pts.getD @ default).ok tab = true" ck_pt_
  for ((i = 0; i < 3; i++)); do
    echo "theorem ck_pair_$i : (pairs.getD $i default).okU tab pts = true ∧"
    echo "    (pairs.getD $i default).toPt.okT = true ∧ (pairs.getD $i default).okC tab M = true := by"
    echo "  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel"; echo
  done
  alls ck_pair i 3 "(pairs.getD @ default).okU tab pts = true ∧
    (pairs.getD @ default).toPt.okT = true ∧ (pairs.getD @ default).okC tab M = true" ck_pair_
  for ((i = 0; i < 2; i++)); do
    echo "theorem ck_K_$i : (cK.getD $i default).ok tab M.N M.E4U (kapXE $i) (.int 0) = true := by decide +kernel"; echo
  done
  alls ck_K i 2 "(cK.getD @ default).ok tab M.N M.E4U (kapXE @) (.int 0) = true" ck_K_
  echo "end FurioLombardo.Discharge.SelmerBasis.W7"
} > $dir/W7CheckM.lean
{
  head_ "FurioLombardo.Discharge.SelmerBasis.W7Data
FurioLombardo.Discharge.SelmerBasis.W7DataL" "Kernel checks of the gensL certificates at w7" \
    "\`ck_L_s\`: the two \`KCert\`s of \`gensL s\` (components 0, 1)."
  for ((s = 0; s < 29; s++)); do
    echo "theorem ck_L_$s : okL tab M (cL.getD $s default) $s = true := by decide +kernel"; echo
  done
  alls ck_L s 29 "okL tab M (cL.getD @ default) @ = true" ck_L_
  echo "end FurioLombardo.Discharge.SelmerBasis.W7"
} > $dir/W7CheckL.lean
for part in 0 1; do
  if [ $part = 0 ]; then a=0; b=27; else a=27; b=53; fi
  {
    head_ "FurioLombardo.Discharge.SelmerBasis.W7Data
FurioLombardo.Discharge.SelmerBasis.W7DataN" "Kernel checks of the gensN certificates at w7, part $part" \
      "\`ck_N_s\` ($a ≤ s < $b): the \`KCert\`s of \`gensN s\` at the components 2, 3 and its \`FCert\` at \`F'\`."
    for ((s = a; s < b; s++)); do
      echo "theorem ck_N_$s : okN tab M (cN.getD $s default) $s = true := by decide +kernel"; echo
    done
    alls ck_N$part s $b "okN tab M (cN.getD @ default) @ = true" ck_N_ $a
    echo "end FurioLombardo.Discharge.SelmerBasis.W7"
  } > $dir/W7CheckN$part.lean
done
{
  head_ "FurioLombardo.Discharge.SelmerBasis.W7CheckN0
FurioLombardo.Discharge.SelmerBasis.W7CheckN1" "Kernel checks of the gensN certificates at w7" \
    "\`ck_N\`: the two parts gathered."
  echo "theorem ck_N : ∀ s, s < 53 → okN tab M (cN.getD s default) s = true := by"
  echo "  intro s hs"
  echo "  rcases Nat.lt_or_ge s 27 with h | h"
  echo "  · exact ck_N0 s (by omega)"
  echo "  · exact ck_N1 s h hs"; echo
  echo "end FurioLombardo.Discharge.SelmerBasis.W7"
} > $dir/W7CheckN.lean
{
  head_ "FurioLombardo.Discharge.SelmerBasis.W7Data
FurioLombardo.Discharge.SelmerBasis.W7DataL
FurioLombardo.Discharge.SelmerBasis.W7DataN
FurioLombardo.Discharge.SelmerBasis.AssemblyData" "Kernel checks of the F₂ data at w7" \
    "The rows \`Akap\`, \`Amu\`, \`Cg\` are the bits of the certificates; the forms \`QI\` (with the left inverse \`TI\`) and \`QC\`
annihilate them as required, and \`dotRow 10 Cg QC = C7Rows\`."
  cat <<'EOF'
theorem kap_bits : ∀ i, i < 2 → Akap.getD i 0 = kapLow i + 256 * (cK.getD i default).bits := by
  decide +kernel

theorem mu_bits : ∀ i, i < 3 → Amu.getD i 0 = (pairs.getD i default).bits := by
  decide +kernel

theorem cgL_bits : ∀ s, s < 29 → Cg.getD s 0 = bitsL (cL.getD s default) := by
  decide +kernel

theorem cgN_bits : ∀ s, s < 53 → Cg.getD (29 + s) 0 = bitsN (cN.getD s default) := by
  decide +kernel

theorem annI : annOK 10 (fun l => Akap.getD l 0) 2 (fun q => QI.getD q 0) nQI = true := by
  decide +kernel

theorem leftInv : leftInvOK (fun q => dotRow 10 (fun i => Amu.getD i 0) (QI.getD q 0) 3) nQI 3
    (fun q => TI.getD q 0) = true := by
  decide +kernel

theorem annCk : annOK 10 (fun l => Akap.getD l 0) 2 (fun q => QC.getD q 0) 5 = true := by
  decide +kernel

theorem annCm : annOK 10 (fun i => Amu.getD i 0) 3 (fun q => QC.getD q 0) 5 = true := by
  decide +kernel

theorem c7_rows : ∀ q, q < 5 → dotRow 10 (fun s => Cg.getD s 0) (QC.getD q 0) 82 =
    Assembly.C7Rows.getD q 0 := by
  decide +kernel

end FurioLombardo.Discharge.SelmerBasis.W7
EOF
} > $dir/W7CheckB.lean
cat > $dir/W7Check.lean <<'EOF'
import FurioLombardo.Discharge.SelmerBasis.W7CheckM
import FurioLombardo.Discharge.SelmerBasis.W7CheckL
import FurioLombardo.Discharge.SelmerBasis.W7CheckN
import FurioLombardo.Discharge.SelmerBasis.W7CheckB

/-!
# Kernel checks of the w7 data (generated by code/selmer-local-conditions/kernel_checks_w7.sh)

The statements of the docstring of W7Spec.lean, in W7CheckM.lean (`tab_len`, `tab_zero`, `ck_tab`, `ck_M`, `ck_pt`,
`ck_pair`, `ck_K`), W7CheckL.lean (`ck_L`), W7CheckN.lean (`ck_N`) and W7CheckB.lean (`kap_bits`, `mu_bits`, `cgL_bits`,
`cgN_bits`, `annI`, `leftInv`, `annCk`, `annCm`, `c7_rows`).
-/
EOF
wc -c $dir/W7Data*.lean $dir/W7Check*.lean
