#!/bin/bash
# Writes the kernel checks of the v data, one declaration per certificate, into
# lean/FurioLombardo/Discharge/SelmerBasis/:
#   VCheckE.lean    EisData.ok, LModel.ok, SqrtV.ok;
#   VCheckK.lean    the 7 kappa certificates at F1 (WCert) and at F2 (UCert), the 29 gensL certificates at F1;
#   VCheckN0.lean, VCheckN1.lean   the 53 gensN certificates at F2 (0 .. 26, 27 .. 52);
#   VCheckK0.lean, VCheckK1.lean   per twist, the 7 points (okT) and their mu certificates at F1 and F2.
# Each file closes with the statements for all indices at once (`interval_cases`).
# Data: VData.lean, VDataK<k>.lean (code/selmer-local-conditions/local_data_v.gp). A UCert is checked with the truncation 2 n.
# Usage: code/selmer-local-conditions/kernel_checks_v.sh (from the repository root); LEANOUT=<dir> writes into <dir> instead.
set -eu
cd "$(dirname "$0")/../.."
dir=${LEANOUT:-lean/FurioLombardo/Discharge/SelmerBasis}; dir=${dir%/}
list() { local p=$1 a=$2 b=$3 s="" i; for ((i = a; i < b; i++)); do s="$s${s:+, }$p$i"; done; echo "$s"; }
head_() { # imports, title, body text of the docstring
  cat <<EOF
$1

/-!
# $2 (generated by code/selmer-local-conditions/kernel_checks_v.sh)

$3
Every statement is closed by \`decide +kernel\`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.V

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower

EOF
}
xnv() { # the four coordinates of XNv E M S t
  echo "(XNv E M S $1).1 (XNv E M S $1).2.1 (XNv E M S $1).2.2.1 (XNv E M S $1).2.2.2"
}
{
  head_ "import FurioLombardo.Discharge.SelmerBasis.VData" "Kernel checks of the model at v" \
    "The Eisenstein data \`E\`, the model \`M\` (\`omega -> y + c Y\`) and the square root data \`S\` of \`-iL (4 eN) / 3\`."
  cat <<'EOF'
theorem ck_E : E.ok = true := by decide +kernel

theorem ck_M : M.ok E = true := by decide +kernel

theorem ck_S : S.ok E M = true := by decide +kernel

end FurioLombardo.Discharge.SelmerBasis.V
EOF
} > $dir/VCheckE.lean
{
  head_ "import FurioLombardo.Discharge.SelmerBasis.VData
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem" "Kernel checks of the kappa and gensL certificates at v" \
    "\`ck_K1_i\`, \`ck_K2_i\`: the square certificates of \`dyGen al i\` at \`F1\` and \`F2\`; \`ck_L_s\`: that of
\`iL (gensL s)\` at \`F1\`."
  for ((i = 0; i < 7; i++)); do
    echo "theorem ck_K1_$i : certOK E (cK1.getD $i default).n0 (kapX E $i) (.int 0) (cK1.getD $i default) = true := by"
    echo "  decide +kernel"; echo
    echo "theorem ck_K2_$i : certOKU E (2 * (cK2.getD $i default).n) (kapX E $i) (.int 0) (.int 0) (.int 0)"
    echo "    (cK2.getD $i default) = true := by"
    echo "  decide +kernel"; echo
  done
  for ((s = 0; s < 29; s++)); do
    echo "theorem ck_L_$s : certOK E (cL.getD $s default).n0 (X0L M (ofL (SUnitData.gL.getD $s [])))"
    echo "    (X1L M (ofL (SUnitData.gL.getD $s []))) (cL.getD $s default) = true := by"
    echo "  decide +kernel"; echo
  done
  echo "theorem ck_K1 : ∀ i, i < 7 → certOK E (cK1.getD i default).n0 (kapX E i) (.int 0) (cK1.getD i default) = true := by"
  echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_K1_ 0 7)]"; echo
  echo "theorem ck_K2 : ∀ i, i < 7 → certOKU E (2 * (cK2.getD i default).n) (kapX E i) (.int 0) (.int 0) (.int 0)"
  echo "    (cK2.getD i default) = true := by"
  echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_K2_ 0 7)]"; echo
  echo "theorem ck_L : ∀ s, s < 29 → certOK E (cL.getD s default).n0 (X0L M (ofL (SUnitData.gL.getD s [])))"
  echo "    (X1L M (ofL (SUnitData.gL.getD s []))) (cL.getD s default) = true := by"
  echo "  intro s hs"; echo "  interval_cases s"; echo "  exacts [$(list ck_L_ 0 29)]"; echo
  echo "end FurioLombardo.Discharge.SelmerBasis.V"
} > $dir/VCheckK.lean
for part in 0 1; do
  if [ $part = 0 ]; then a=0; b=27; imp="import FurioLombardo.Discharge.SelmerBasis.VData
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem"; else a=27; b=53; imp="import FurioLombardo.Discharge.SelmerBasis.VCheckN0"; fi
  {
    head_ "$imp" "Kernel checks of the gensN certificates at v, part $part" \
      "\`ck_N_j\` ($a ≤ j < $b): the square certificate at \`F2\` of the approximation \`XNv\` of \`iNv (gensN j)\`."
    for ((j = a; j < b; j++)); do
      echo "theorem ck_N_$j : certOKU E (2 * (cN.getD $j default).n) $(xnv "(ofN (SUnitData.gN.getD $j []))")"
      echo "    (cN.getD $j default) = true := by"
      echo "  decide +kernel"; echo
    done
    if [ $part = 1 ]; then
      echo "theorem ck_N : ∀ j, j < 53 → certOKU E (2 * (cN.getD j default).n) $(xnv "(ofN (SUnitData.gN.getD j []))")"
      echo "    (cN.getD j default) = true := by"
      echo "  intro j hj"; echo "  interval_cases j"; echo "  exacts [$(list ck_N_ 0 53)]"; echo
    fi
    echo "end FurioLombardo.Discharge.SelmerBasis.V"
  } > $dir/VCheckN$part.lean
done
for k in 0 1; do
  {
    head_ "import FurioLombardo.Discharge.SelmerBasis.VData
import FurioLombardo.Discharge.SelmerBasis.VDataK$k
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem" "Kernel checks of the points of twist $k at v" \
      "\`ck_pt_i\`: the values \`Λ² U_i(α)\`, \`Λ² U_i(β)\` of the point \`pt_i\` (\`okT\`, and \`d ∣ Λ²\`); \`ck_M1_i\`,
\`ck_M2_i\`: the square certificates of these values at \`F1\` and \`F2\`."
    echo "namespace K$k"; echo
    for ((i = 0; i < 7; i++)); do
      echo "theorem ck_pt_$i : 0 < (pts.getD $i default).d ∧ (pts.getD $i default).lamL ^ 2 % (pts.getD $i default).d = 0 ∧"
      echo "    (pts.getD $i default).lamN ^ 2 % (pts.getD $i default).d = 0 ∧ (pts.getD $i default).okT = true := by"
      echo "  refine ⟨?_, ?_, ?_, ?_⟩ <;> decide +kernel"; echo
      echo "theorem ck_M1_$i : certOK E (cM1.getD $i default).n0 (X0L M (ofL (pts.getD $i default).tL))"
      echo "    (X1L M (ofL (pts.getD $i default).tL)) (cM1.getD $i default) = true := by"
      echo "  decide +kernel"; echo
      echo "theorem ck_M2_$i : certOKU E (2 * (cM2.getD $i default).n) $(xnv "(ofN (pts.getD $i default).tN)")"
      echo "    (cM2.getD $i default) = true := by"
      echo "  decide +kernel"; echo
    done
    echo "theorem ck_pt : ∀ i, i < 7 → 0 < (pts.getD i default).d ∧"
    echo "    (pts.getD i default).lamL ^ 2 % (pts.getD i default).d = 0 ∧"
    echo "    (pts.getD i default).lamN ^ 2 % (pts.getD i default).d = 0 ∧ (pts.getD i default).okT = true := by"
    echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_pt_ 0 7)]"; echo
    echo "theorem ck_M1 : ∀ i, i < 7 → certOK E (cM1.getD i default).n0 (X0L M (ofL (pts.getD i default).tL))"
    echo "    (X1L M (ofL (pts.getD i default).tL)) (cM1.getD i default) = true := by"
    echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_M1_ 0 7)]"; echo
    echo "theorem ck_M2 : ∀ i, i < 7 → certOKU E (2 * (cM2.getD i default).n) $(xnv "(ofN (pts.getD i default).tN)")"
    echo "    (cM2.getD i default) = true := by"
    echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list ck_M2_ 0 7)]"; echo
    echo "end K$k"; echo
    echo "end FurioLombardo.Discharge.SelmerBasis.V"
  } > $dir/VCheckK$k.lean
done
echo "wrote VCheckE, VCheckK, VCheckN0, VCheckN1, VCheckK0, VCheckK1 in $dir"
