#!/bin/bash
# Kernel probes of the w7 certificates at real size: one file per certificate kind, each holding
# the generated data (/tmp/sp7_2/lean/W7Data*.lean, code/selmer-local-conditions/lean_data_w7.gp) and one `decide +kernel` check,
# timed by `lake env lean` under cap. Kinds: powOK (the largest, i = 7), Model.ok, PtSq.ok (point 2, the largest
# precision), the pair 0 (okU, okT, okC), cK 0, okL (gensL 26, the largest), okN (gensN 51, the largest), and the
# F_2 statements (bits of all 82 rows, annI, leftInv, annCk, annCm, c7_rows); base and baseAll: the data alone (the
# import and elaboration baseline; the max RSS includes the mapped Mathlib oleans).
# Usage: code/selmer-local-conditions/kernel_probe_w7.sh [DATA_DIR] (from any directory; DATA_DIR defaults to /tmp/sp7_2/lean, or pass
# lean/FurioLombardo/Discharge/SelmerBasis); output code/selmer-local-conditions/kernel_probe_w7.out.
# Run in the workspace with each lake call under a resource cap (cap -m 7G -c 3).
set -eu
cd "$(dirname "$0")/../.."
src=${1:-/tmp/sp7_2/lean}  # the generated data (identical to the installed W7Data*.lean, same sha256)
pd=code/selmer-local-conditions
body() { sed -n '/^open FurioLombardo.M1$/,/^end FurioLombardo/p' "$src/$1.lean" | sed '1d;$d'; }
entry() { grep "^def $2 " "$src/$1.lean"; }
mk() { # name, data lines (function output), theorem text
  local f=$pd/probe_$1.lean
  {
    echo "import FurioLombardo.Discharge.SelmerBasis.W7Spec"; echo "import FurioLombardo.Discharge.SelmerBasis.AssemblyData"; echo
    echo "/-! Kernel probe \`$1\` of the w7 data (generated by code/selmer-local-conditions/kernel_probe_w7.sh). -/"; echo
    echo "namespace FurioLombardo.Discharge.SelmerBasis.W7"; echo
    echo "open FurioLombardo.M1"; echo
    $2
    echo; echo "$3"; echo
    echo "end FurioLombardo.Discharge.SelmerBasis.W7"
  } > $f
}
dataM() { body W7Data; }
dataL() { body W7Data; entry W7DataL cL_26; }
dataN() { body W7Data; entry W7DataN cN_51; }
dataAll() { body W7Data; body W7DataL; body W7DataN; }
mk base dataM "-- no check: the import and elaboration baseline"
mk baseAll dataAll "-- no check: the import and elaboration baseline with all the data"
mk tab dataM "theorem p_tab7 : powOK tab (tabK.getD 7 0) 7 = true := by decide +kernel"
mk model dataM "theorem p_M : M.ok tab = true := by decide +kernel"
mk pt dataM "theorem p_pt2 : (pts.getD 2 default).ok tab = true := by decide +kernel"
mk pair dataM "theorem p_pair0U : (pairs.getD 0 default).okU tab pts = true := by decide +kernel

theorem p_pair0T : (pairs.getD 0 default).toPt.okT = true := by decide +kernel

theorem p_pair0C : (pairs.getD 0 default).okC tab M = true := by decide +kernel"
mk K dataM "theorem p_K0 : (cK.getD 0 default).ok tab M.N M.E4U (kapXE 0) (.int 0) = true := by decide +kernel"
mk L dataL "theorem p_L26 : okL tab M cL_26 26 = true := by decide +kernel"
mk N dataN "theorem p_N51 : okN tab M cN_51 51 = true := by decide +kernel"
mk F2 dataAll "theorem p_kap : ∀ i, i < 2 → Akap.getD i 0 = kapLow i + 256 * (cK.getD i default).bits := by decide +kernel

theorem p_mu : ∀ i, i < 3 → Amu.getD i 0 = (pairs.getD i default).bits := by decide +kernel

theorem p_cgL : ∀ s, s < 29 → Cg.getD s 0 = bitsL (cL.getD s default) := by decide +kernel

theorem p_cgN : ∀ s, s < 53 → Cg.getD (29 + s) 0 = bitsN (cN.getD s default) := by decide +kernel

theorem p_annI : annOK 10 (fun l => Akap.getD l 0) 2 (fun q => QI.getD q 0) nQI = true := by decide +kernel

theorem p_leftInv : leftInvOK (fun q => dotRow 10 (fun i => Amu.getD i 0) (QI.getD q 0) 3) nQI 3
    (fun q => TI.getD q 0) = true := by decide +kernel

theorem p_annCk : annOK 10 (fun l => Akap.getD l 0) 2 (fun q => QC.getD q 0) 5 = true := by decide +kernel

theorem p_annCm : annOK 10 (fun i => Amu.getD i 0) 3 (fun q => QC.getD q 0) 5 = true := by decide +kernel

theorem p_c7 : ∀ q, q < 5 → dotRow 10 (fun s => Cg.getD s 0) (QC.getD q 0) 82 =
    Assembly.C7Rows.getD q 0 := by decide +kernel"
out=$pd/kernel_probe_w7.out
rm -f $out
echo "# kernel probes, $(date -u +%FT%TZ), data sha256 $(cat $src/W7Data.lean $src/W7DataL.lean $src/W7DataN.lean | sha256sum | cut -c1-16)" > $out
cd lean
for k in base baseAll tab model pt pair K L N F2; do
  f=../$pd/probe_$k.lean
  set +e
  /usr/bin/time -f "%e s wall, %M KB max RSS" -o /tmp/sp7_probe_time lake env lean $f > /tmp/sp7_probe_log 2>&1
  rc=$?
  set -e
  echo "probe_$k: rc=$rc, $(cat /tmp/sp7_probe_time | tail -1)" >> ../$out
  sed 's/^/  /' /tmp/sp7_probe_log >> ../$out
done
cat ../$out
