#!/bin/bash
# Writes the kernel checks of the w2 data, one declaration per certificate, into
# lean/FurioLombardo/Discharge/SelmerBasis/:
#   W2CheckE.lean    EisData.ok, RhoData.ok, SqrtU.ok;
#   W2CheckK.lean    the 25 kappa certificates (dyGen al l, the same at the three components);
#   W2CheckL.lean    the 29 gensL certificates at component 0 (iL2);
#   W2CheckN1.lean, W2CheckN2.lean   the 53 gensN certificates at components 1 and 2 (iN2 true, iN2 false);
#   W2CheckK0.lean, W2CheckK1.lean   per twist, the 26 points (okD, okZ, okT) and their 3 x 26 mu certificates.
# Each file closes with the statements for all indices at once (`interval_cases`).
# Checkers: W2UnramDefs.lean (certOKU1, RhoData.ok, SqrtU.ok, X0L2, X1L2, X0N2, X1N2), PointGen.lean (PtData);
# data: W2Data.lean, W2DataK<k>.lean (code/selmer-local-conditions/local_data_w12.gp, split by code/selmer-local-conditions/split_lean_data.sh).
# Usage: code/selmer-local-conditions/kernel_checks_w12.sh (from any directory); LEANOUT=<dir> writes into <dir> instead.
set -eu
cd "$(dirname "$0")/../.."
dir=${LEANOUT:-lean/FurioLombardo/Discharge/SelmerBasis}; dir=${dir%/}
list() { local p=$1 n=$2 s="" i; for ((i = 0; i < n; i++)); do s="$s${s:+, }$p$i"; done; echo "$s"; }
head_() { # imports (newline separated), title, body text of the docstring
  cat <<EOF
$1

/-!
# $2 (generated by code/selmer-local-conditions/kernel_checks_w12.sh)

$3
Every statement is closed by \`decide +kernel\`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.W2

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower
  FurioLombardo.Discharge.SelmerBasis.W2U

EOF
}
alls() { # name, bound, statement with @ for the index (may span lines), per-index prefix
  local nm=$1 n=$2 txt=$3 p=$4
  echo "theorem $nm : ∀ i, i < $n → ${txt//@/i} := by"
  echo "  intro i hi"; echo "  interval_cases i"; echo "  exacts [$(list "$p" "$n")]"; echo
}
imp="import FurioLombardo.Discharge.SelmerBasis.W2Data"
impE="$imp
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem"
{
  head_ "$imp" "Kernel checks of the model at w2" \
    "The data \`E\` of \`K_w2\` (the powers of \`al\`), \`SR\` (\`3 ρ² = -ε\`) and \`SU\` (the square root of \`iL2 (4 eN)\`)."
  echo "theorem ck_E : E.ok = true := by decide +kernel"; echo
  echo "theorem ck_SR : SR.ok E = true := by decide +kernel"; echo
  echo "theorem ck_SU : SU.ok E SR = true := by decide +kernel"; echo
  echo "end FurioLombardo.Discharge.SelmerBasis.W2"
} > $dir/W2CheckE.lean
{
  head_ "$impE" "Kernel checks of the kappa certificates at w2" \
    "\`ck_K_i\`: the square certificate of \`dyGen al i\` (exact, the same at the three components)."
  for ((i = 0; i < 25; i++)); do
    echo "theorem ck_K_$i : certOKU1 E (kapX E $i) (.int 0) (cK.getD $i default) = true := by"
    echo "  decide +kernel"; echo
  done
  alls ck_K 25 "certOKU1 E (kapX E @) (.int 0) (cK.getD @ default) = true" ck_K_
  echo "end FurioLombardo.Discharge.SelmerBasis.W2"
} > $dir/W2CheckK.lean
{
  head_ "$impE" "Kernel checks of the gensL certificates at w2" \
    "\`ck_L_s\`: the square certificate of \`iL2 (gensL s)\` at component 0, for the approximation \`X0L2\`, \`X1L2\`."
  for ((s = 0; s < 29; s++)); do
    echo "theorem ck_L_$s : certOKU1 E (X0L2 E SR (ofL (SUnitData.gL.getD $s [])))"
    echo "    (X1L2 E SR (ofL (SUnitData.gL.getD $s []))) (cL.getD $s default) = true := by"
    echo "  decide +kernel"; echo
  done
  alls ck_L 29 "certOKU1 E (X0L2 E SR (ofL (SUnitData.gL.getD @ [])))
    (X1L2 E SR (ofL (SUnitData.gL.getD @ []))) (cL.getD @ default) = true" ck_L_
  echo "end FurioLombardo.Discharge.SelmerBasis.W2"
} > $dir/W2CheckL.lean
for c in 1 2; do
  b=$([ $c = 1 ] && echo true || echo false)
  {
    head_ "$impE" "Kernel checks of the gensN certificates at w2, component $c" \
      "\`ck_N${c}_s\`: the square certificate of \`iN2 $b (gensN s)\` (component $c), for the approximation \`X0N2\`, \`X1N2\`."
    for ((s = 0; s < 53; s++)); do
      echo "theorem ck_N${c}_$s : certOKU1 E (X0N2 E SR SU (ofN (SUnitData.gN.getD $s [])) $b)"
      echo "    (X1N2 E SR SU (ofN (SUnitData.gN.getD $s [])) $b) (cN$c.getD $s default) = true := by"
      echo "  decide +kernel"; echo
    done
    alls ck_N$c 53 "certOKU1 E (X0N2 E SR SU (ofN (SUnitData.gN.getD @ [])) $b)
    (X1N2 E SR SU (ofN (SUnitData.gN.getD @ [])) $b) (cN$c.getD @ default) = true" ck_N${c}_
    echo "end FurioLombardo.Discharge.SelmerBasis.W2"
  } > $dir/W2CheckN$c.lean
done
for k in 0 1; do
  {
    head_ "$imp
import FurioLombardo.Discharge.SelmerBasis.W2DataK$k" "Kernel checks of the points of twist $k at w2" \
      "\`ck_pt_i\`: the point data \`pt_i\` (\`okD\`, \`okZ\` for \`4 fRev_$k\`, \`okT\`); \`ck_M1_i\`, \`ck_M2_i\`, \`ck_M3_i\`:
the square certificates of \`Λ² U_i\` at the components 0, 1, 2."
    echo "namespace K$k"; echo
    for ((i = 0; i < 26; i++)); do
      echo "theorem ck_pt_$i : (pts.getD $i default).okD E = true ∧ (pts.getD $i default).okZ E (gW $k) = true ∧"
      echo "    (pts.getD $i default).okT = true := by"
      echo "  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel"; echo
      echo "theorem ck_M1_$i : certOKU1 E (X0L2 E SR (ofL (pts.getD $i default).tL))"
      echo "    (X1L2 E SR (ofL (pts.getD $i default).tL)) (cM1.getD $i default) = true := by"
      echo "  decide +kernel"; echo
      for c in 2 3; do
        b=$([ $c = 2 ] && echo true || echo false)
        echo "theorem ck_M${c}_$i : certOKU1 E (X0N2 E SR SU (ofN (pts.getD $i default).tN) $b)"
        echo "    (X1N2 E SR SU (ofN (pts.getD $i default).tN) $b) (cM$c.getD $i default) = true := by"
        echo "  decide +kernel"; echo
      done
    done
    alls ck_pt 26 "(pts.getD @ default).okD E = true ∧ (pts.getD @ default).okZ E (gW $k) = true ∧
    (pts.getD @ default).okT = true" ck_pt_
    alls ck_M1 26 "certOKU1 E (X0L2 E SR (ofL (pts.getD @ default).tL))
    (X1L2 E SR (ofL (pts.getD @ default).tL)) (cM1.getD @ default) = true" ck_M1_
    for c in 2 3; do
      b=$([ $c = 2 ] && echo true || echo false)
      alls ck_M$c 26 "certOKU1 E (X0N2 E SR SU (ofN (pts.getD @ default).tN) $b)
    (X1N2 E SR SU (ofN (pts.getD @ default).tN) $b) (cM$c.getD @ default) = true" ck_M${c}_
    done
    echo "end K$k"; echo
    echo "end FurioLombardo.Discharge.SelmerBasis.W2"
  } > $dir/W2CheckK$k.lean
done
wc -l $dir/W2Check*.lean
