import FurioLombardo.Discharge.SelmerBasis.W7Place

-- The axioms of every theorem of W7Gen, W7Cert, W7Model, W7Glue and W7Place;
-- run by code/selmer-local-conditions/final_check_w7.sh.

-- W7Gen.lean
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.indep_pi_u
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.isSquare_of_near
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_near_re_aux1
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_near_re_aux2
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_near_re_aux3
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_near_re_aux4
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_near_re
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_fermat
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_euler
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qf_norm_two
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qf_norm_pow_add_one
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_norm_sub_algebraMap
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qfE_isSquare_of_cert
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.b7_prod_fst
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.b7_prod_snd
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.isSquare_mul_rows7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.indep_rows7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.uTwo_monic
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.uTwo_natDegree
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.uTwo_dvd
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.isCoprime_uTwo_vTwo
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.isCoprime_uTwo
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.exists_jac_two
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.coordCond_range_of_imageIn
-- W7Cert.lean
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.powOK_sq
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.evK_alPw_aux
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.evK_alPw
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.unitOK_eq
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.evK_sgnE
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.bitv2_vals
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.norm_evK_le_one
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.norm_unit
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.KCert.sound
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.norm_pow_sub_pow_le
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qf_mul_Z
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qf_mul_neg_one
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.qf_Z_sq
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.fcert_core
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.FCert.sound
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.PtSq.sound
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.norm_XLp_sub
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.norm_XLm_sub
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.norm_qaLift_evL_le
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.norm_XNs_sub
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.iota'_evN
-- W7Model.lean
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.int7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.unif7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.two7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ferm7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.euler7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.negOne7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.two7_ne_zero
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.δ7_le_one
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.δ7_lt_norm
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.δ7_lt_one
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.pow_le_δ7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.Hyp.facts
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.exists_r
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.r7_sq
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.r7_near
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.r7_norm
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hu_p
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hu_m
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ιp_four_eN
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ιm_four_eN
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.int7K
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.norm_two_eb
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.exists_S
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.S7_sq
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.S7_near
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hs_N
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.A4_near
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.A4_norm
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.instFactA4
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hu'
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ιp_comp
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ιm_comp
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ιN_comp
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ι'_comp
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.evG_fst
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.evG_snd
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ev4_mk
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ev'_mk
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ev4_etale
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ev'_etale
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ev4_algebraMap
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.ev'_algebraMap
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.approxLp
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.approxLm
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.approxN
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.approx'
-- W7Glue.lean
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.goodSextic7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.bitv2_mod
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.bitv2_row
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.bitv2_row'
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.isSquare_row7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.KCert.bits_lt
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.FCert.bits_lt
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.isSquare_one_mul_bits0
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.bK_ne_zero
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.unifZ
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.bF7_ne_zero
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hind7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.natCast_ne7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.natCast_neF
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.sqK
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.sqF
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hspan7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hK
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.algebraMap_F7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.kapLow_row
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hAkap
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.pt_sq
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.Checks.hyp
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.exists_D7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.muJ_D7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.U7_coe
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hAmu
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.hCg
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.indepImage_w7_of
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.imageIn_w7_of
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.coordCond_w7_of
-- W7Place.lean
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.not_isSquare_c_w7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.goodSextic_w7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.checks_w7
#print axioms FurioLombardo.Discharge.SelmerBasis.W7.coordCond_w7
