import FurioLombardo.Discharge.SelmerBasis.PlaceWCert
open FurioLombardo.Discharge.SelmerBasis
#print axioms EisData.ok_A
#print axioms EisData.ok_B
#print axioms EisData.ok_alP
#print axioms EisData.ok_Yp0
#print axioms EisData.ok_YpS
#print axioms dot_addL
#print axioms dot_smulL
#print axioms dot_replicate_zero
#print axioms dot_combo
#print axioms zkE_combo
#print axioms dot_eq_evRow
#print axioms map_evRow
#print axioms length_addT
#print axioms length_dpStep
#print axioms length_dpTab
#print axioms length_truncT_row
#print axioms prod_fin_bits
#print axioms norm_evK_le_one
#print axioms norm_pow_sub_pow_lt
#print axioms qf_mk_eq
#print axioms qf_Y_sq
#print axioms qf_pow_of_rec
#print axioms pbb_prod_fin_eq_list_prod
#print axioms prod_bits_basis
#print axioms prod_mulSingle_bits
#print axioms dfact_odd_near
#print axioms WPlace.norm_A
#print axioms WPlace.norm_B_le
#print axioms WPlace.norm_B
#print axioms WPlace.noRoot
#print axioms toF_eq
#print axioms cY_sq
#print axioms toF_add
#print axioms toF_smul
#print axioms toF_Yp
#print axioms algebraMap_alP
#print axioms evK_lcE
#print axioms evK_lcE0
#print axioms evK_lcE1
#print axioms toF_lcE
#print axioms sum_lhsAux
#print axioms algebraMap_combo
#print axioms rowsVal_eRows
#print axioms Ba_eq
#print axioms lhsAux_idx
#print axioms norm_cY_lt_one
#print axioms norm_tC
#print axioms norm_toF_le_one
#print axioms norm_Ba_le_one
#print axioms certOK_isSquare
