\\ di_values_ball_export.gp: ball data of the D_i value chain for the Lean probe kv_d2_*.lean.
\\ For k = 0, 1: the sextic f of g = (fRev k)^sigma and E0 of baseKv k; for each i = 1..7: D_i, the J of di_values_probe.gp
\\ (least J with err - sc >= 3 q_i) and the exact t_J = chartT a R_J, all as balls [c0, c1, c2, e, r] modulo 2^PX
\\ (the Lean side caps r at 3P for its own P <= PX). The data serve a numerical probe.
\\ Run from code/local-group:
\\   gp -q ../local-group/di_values_ball_export.gp > ../local-group/di_values_ball_export.out
default(parisizemax, 3*10^9); default(nbthreads, 1);
[t, x, y, z, X, u, w, a, s, b];
read("../descent/descent_data_lib.gp");
read("completion_kv_lib.gp");
read("lean_data_reader.gp");
read("../local-group/di_values_lib.gp");
PX = 1500;
OUT = "../local-group/di_values_ball_data.lean";
bl(x) = { my(B = toBall(x, PX)); Str("mkB (", B[1], ", ", B[2], ", ", B[3], ") ", B[4], " ", B[5]) };
mumL(D) = Str("⟨", bl(D[1]), ", ", bl(D[2]), ", ", bl(D[3]), ", ", bl(D[4]), "⟩");
{
  write(OUT, "/- di_values_ball_data.lean: generated by di_values_ball_export.gp (ball data of the D_i value chain, P <= ", PX, " bits). -/");
  for (k = 0, 1,
    my(T = twistData(k), f = T[1]);
    write(OUT, "");
    write(OUT, "-- twist ", k, ": a = ", T[2], ", M0 = ", T[3], ", v(b) = ", vpi(T[4]));
    write(OUT, "def f_", k, " : Sext Ball := ⟨", bl(f[1]), ", ", bl(f[2]), ", ", bl(f[3]), ", ", bl(f[4]), ", ", bl(f[5]), ", ",
      bl(f[6]), ", ", bl(f[7]), "⟩");
    write(OUT, "def E0_", k, " : Mum Ball := ", mumL(T[5]));
    for (i = 1, 7,
      my(D = dPoint(k, i, T), ch = dChain(T, D, T[7][i]));
      printf("k = %d, i = %d: q = %d, J = %d, v(t_J) = %s, D = %d, err = 2D - M0 - 3 = %d, sc = %d, input balls r - 3e: %s\n",
        k, i, T[7][i], ch[1], [vpi(ch[3][1]), vpi(ch[3][2])], ch[4], ch[5], 3 * (ch[1] + 6),
        vector(4, c, my(B = toBall(D[c], PX)); B[5] - 3 * B[4]));
      write(OUT, "-- D_", i, ": q = ", T[7][i], ", J = ", ch[1], ", v(t_J) = ", [vpi(ch[3][1]), vpi(ch[3][2])], ", err = ", ch[5]);
      write(OUT, "def D_", k, "_", i, " : Mum Ball := ", mumL(D));
      write(OUT, "def J_", k, "_", i, " : Nat := ", ch[1]);
      write(OUT, "def tJ_", k, "_", i, " : Ball × Ball := (", bl(ch[3][1]), ", ", bl(ch[3][2]), ")");
      write(OUT, "def err_", k, "_", i, " : Nat := ", ch[5])));
}
quit;
