import FurioLombardo.Discharge.M4Box.DCertData.Values
import FurioLombardo.Discharge.M4Box.PtValue
import FurioLombardo.Discharge.M4Box.PhiCertData.P0
import FurioLombardo.Discharge.M4Box.PhiCertData.P1
import FurioLombardo.Discharge.M4Box.PhiCertData.P2
import FurioLombardo.Discharge.M4Box.PhiCertData.P3

/-!
# The balls of the logarithms of `φ(x_a)`, `φ(x_b)` (lane lean-m4box)

From the value certificates of the data files `P<i>.lean` (generated by code/local-group/known_lift_certs_gen.lean,
checked by the kernel): the bounds `P<i>.cert` (`lamK_of_cert`) and the field `hBP : HBallPhi` of `M4RestKvW`
for both twists (`hBallPhi_of_values`), with `x_a, x_b` the lifts `x0, x2` (twist 0) and `x1, x3` (twist 1).
-/

namespace FurioLombardo.Discharge.M4Box.PhiCertData

open FurioLombardo.M3a.Genus2 FurioLombardo.Discharge.M3a FurioLombardo.Discharge.M3a.Bruin
open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

theorem P0.cert (j : Fin 2) :
    ‖lamK 0 (Additive.ofMul (jacMap σ (fRev 0) (phiK 0 x0))) j‖ ≤ 1 ∧
      ‖lamK 0 (Additive.ofMul (jacMap σ (fRev 0) (phiK 0 x0))) j - evZ (lTriple FurioLombardo.M4.T0.la j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qa) :=
  lamK_of_cert 0 (X := Additive.ofMul (jacMap σ (fRev 0) (phiK 0 x0))) (phiMum_onCurve 0 phiRev_x0.2) (phiMum_cls x0 0 phiRev_x0.1) dCtx_ok
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA (mem_phiBall dCtx_ok hD) hR hfin j

theorem P1.cert (j : Fin 2) :
    ‖lamK 1 (Additive.ofMul (jacMap σ (fRev 1) (phiK 1 x1))) j‖ ≤ 1 ∧
      ‖lamK 1 (Additive.ofMul (jacMap σ (fRev 1) (phiK 1 x1))) j - evZ (lTriple FurioLombardo.M4.T1.la j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qa) :=
  lamK_of_cert 1 (X := Additive.ofMul (jacMap σ (fRev 1) (phiK 1 x1))) (phiMum_onCurve 1 phiRev_x1.2) (phiMum_cls x1 1 phiRev_x1.1) dCtx_ok
    DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA (mem_phiBall dCtx_ok hD) hR hfin j

theorem P2.cert (j : Fin 2) :
    ‖lamK 0 (Additive.ofMul (jacMap σ (fRev 0) (phiK 0 x2))) j‖ ≤ 1 ∧
      ‖lamK 0 (Additive.ofMul (jacMap σ (fRev 0) (phiK 0 x2))) j - evZ (lTriple FurioLombardo.M4.T0.lb j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qb) :=
  lamK_of_cert 0 (X := Additive.ofMul (jacMap σ (fRev 0) (phiK 0 x2))) (phiMum_onCurve 2 phiRev_x2.2) (phiMum_cls x2 2 phiRev_x2.1) dCtx_ok
    DCertData.Tw0.hF DCertData.Tw0.hg DCertData.Tw0.hb DCertData.Tw0.hE DCertData.Tw0.hA (mem_phiBall dCtx_ok hD) hR hfin j

theorem P3.cert (j : Fin 2) :
    ‖lamK 1 (Additive.ofMul (jacMap σ (fRev 1) (phiK 1 x3))) j‖ ≤ 1 ∧
      ‖lamK 1 (Additive.ofMul (jacMap σ (fRev 1) (phiK 1 x3))) j - evZ (lTriple FurioLombardo.M4.T1.lb j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qb) :=
  lamK_of_cert 1 (X := Additive.ofMul (jacMap σ (fRev 1) (phiK 1 x3))) (phiMum_onCurve 3 phiRev_x3.2) (phiMum_cls x3 3 phiRev_x3.1) dCtx_ok
    DCertData.Tw1.hF DCertData.Tw1.hg DCertData.Tw1.hb DCertData.Tw1.hE DCertData.Tw1.hA (mem_phiBall dCtx_ok hD) hR hfin j

/-- **`HBallPhi` for twist 0.** -/
theorem hBP_0 : FurioLombardo.M4.HBallPhi FurioLombardo.M4.T0.data
    (logPhi σ (fRev 0) (phiK 0) (lam 0) x0) (logPhi σ (fRev 0) (phiK 0) (lam 0) x2) :=
  hBallPhi_of_values 0 FurioLombardo.M4.T0.data (lamInt_of 0 (DCertData.lamK_Dpt_le_one 0))
    (fun j => (P0.cert j).2) (fun j => (P2.cert j).2)

/-- **`HBallPhi` for twist 1.** -/
theorem hBP_1 : FurioLombardo.M4.HBallPhi FurioLombardo.M4.T1.data
    (logPhi σ (fRev 1) (phiK 1) (lam 1) x1) (logPhi σ (fRev 1) (phiK 1) (lam 1) x3) :=
  hBallPhi_of_values 1 FurioLombardo.M4.T1.data (lamInt_of 1 (DCertData.lamK_Dpt_le_one 1))
    (fun j => (P1.cert j).2) (fun j => (P3.cert j).2)

end FurioLombardo.Discharge.M4Box.PhiCertData
