import FurioLombardo.Discharge.SelmerBasis.KappaData
import FurioLombardo.Discharge.SelmerBasis.MuTCert
import FurioLombardo.M1.DataGens

/-!
# Kernel checks of the kappa data (generated by code/selmer-assembly/kernel_checks_kappa.sh)

For `t < 15`: `ck_PL_t`, `ck_PN_t` (the products of the selected generators), `ck_SL_t`, `ck_SN_t` (the square
identities `y1D² c_t prodL = y1T²` in `L42`, `y2D² c_t prodN = y2T²` in `N84`, `c_t = M1.gensL (t + 1)`), each by
`decide +kernel`; `ck_bits`: `aK t` is `Kappa.κK t` read as a list.
-/

namespace FurioLombardo.Discharge.SelmerBasis.KappaData

set_option maxRecDepth 100000

open FurioLombardo.M1.Kron FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower
  FurioLombardo.Discharge.SelmerBasis.MuTCert

theorem ck_PL_0 : checkLC (pPL.getD 0 0) (ofL (prodL.getD 0 [])) (selProdL (aK.getD 0 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_0 : checkNC (pPN.getD 0 0) (ofN (prodN.getD 0 [])) (selProdN ((aK.getD 0 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_0 : checkLC (pSL.getD 0 0) (smulLC (.mul (.int (((y1D.getD 0 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (0 + 1) []))) (ofL (prodL.getD 0 []))) (mulLC (ofL (y1T.getD 0 [])) (ofL (y1T.getD 0 []))) = true := by
  decide +kernel

theorem ck_SN_0 : checkNC (pSN.getD 0 0) (smulNC (.mul (.int (((y2D.getD 0 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (0 + 1) []))) (ofN (prodN.getD 0 []))) (mulNC (ofN (y2T.getD 0 [])) (ofN (y2T.getD 0 []))) = true := by
  decide +kernel

theorem ck_PL_1 : checkLC (pPL.getD 1 0) (ofL (prodL.getD 1 [])) (selProdL (aK.getD 1 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_1 : checkNC (pPN.getD 1 0) (ofN (prodN.getD 1 [])) (selProdN ((aK.getD 1 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_1 : checkLC (pSL.getD 1 0) (smulLC (.mul (.int (((y1D.getD 1 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (1 + 1) []))) (ofL (prodL.getD 1 []))) (mulLC (ofL (y1T.getD 1 [])) (ofL (y1T.getD 1 []))) = true := by
  decide +kernel

theorem ck_SN_1 : checkNC (pSN.getD 1 0) (smulNC (.mul (.int (((y2D.getD 1 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (1 + 1) []))) (ofN (prodN.getD 1 []))) (mulNC (ofN (y2T.getD 1 [])) (ofN (y2T.getD 1 []))) = true := by
  decide +kernel

theorem ck_PL_2 : checkLC (pPL.getD 2 0) (ofL (prodL.getD 2 [])) (selProdL (aK.getD 2 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_2 : checkNC (pPN.getD 2 0) (ofN (prodN.getD 2 [])) (selProdN ((aK.getD 2 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_2 : checkLC (pSL.getD 2 0) (smulLC (.mul (.int (((y1D.getD 2 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (2 + 1) []))) (ofL (prodL.getD 2 []))) (mulLC (ofL (y1T.getD 2 [])) (ofL (y1T.getD 2 []))) = true := by
  decide +kernel

theorem ck_SN_2 : checkNC (pSN.getD 2 0) (smulNC (.mul (.int (((y2D.getD 2 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (2 + 1) []))) (ofN (prodN.getD 2 []))) (mulNC (ofN (y2T.getD 2 [])) (ofN (y2T.getD 2 []))) = true := by
  decide +kernel

theorem ck_PL_3 : checkLC (pPL.getD 3 0) (ofL (prodL.getD 3 [])) (selProdL (aK.getD 3 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_3 : checkNC (pPN.getD 3 0) (ofN (prodN.getD 3 [])) (selProdN ((aK.getD 3 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_3 : checkLC (pSL.getD 3 0) (smulLC (.mul (.int (((y1D.getD 3 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (3 + 1) []))) (ofL (prodL.getD 3 []))) (mulLC (ofL (y1T.getD 3 [])) (ofL (y1T.getD 3 []))) = true := by
  decide +kernel

theorem ck_SN_3 : checkNC (pSN.getD 3 0) (smulNC (.mul (.int (((y2D.getD 3 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (3 + 1) []))) (ofN (prodN.getD 3 []))) (mulNC (ofN (y2T.getD 3 [])) (ofN (y2T.getD 3 []))) = true := by
  decide +kernel

theorem ck_PL_4 : checkLC (pPL.getD 4 0) (ofL (prodL.getD 4 [])) (selProdL (aK.getD 4 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_4 : checkNC (pPN.getD 4 0) (ofN (prodN.getD 4 [])) (selProdN ((aK.getD 4 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_4 : checkLC (pSL.getD 4 0) (smulLC (.mul (.int (((y1D.getD 4 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (4 + 1) []))) (ofL (prodL.getD 4 []))) (mulLC (ofL (y1T.getD 4 [])) (ofL (y1T.getD 4 []))) = true := by
  decide +kernel

theorem ck_SN_4 : checkNC (pSN.getD 4 0) (smulNC (.mul (.int (((y2D.getD 4 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (4 + 1) []))) (ofN (prodN.getD 4 []))) (mulNC (ofN (y2T.getD 4 [])) (ofN (y2T.getD 4 []))) = true := by
  decide +kernel

theorem ck_PL_5 : checkLC (pPL.getD 5 0) (ofL (prodL.getD 5 [])) (selProdL (aK.getD 5 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_5 : checkNC (pPN.getD 5 0) (ofN (prodN.getD 5 [])) (selProdN ((aK.getD 5 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_5 : checkLC (pSL.getD 5 0) (smulLC (.mul (.int (((y1D.getD 5 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (5 + 1) []))) (ofL (prodL.getD 5 []))) (mulLC (ofL (y1T.getD 5 [])) (ofL (y1T.getD 5 []))) = true := by
  decide +kernel

theorem ck_SN_5 : checkNC (pSN.getD 5 0) (smulNC (.mul (.int (((y2D.getD 5 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (5 + 1) []))) (ofN (prodN.getD 5 []))) (mulNC (ofN (y2T.getD 5 [])) (ofN (y2T.getD 5 []))) = true := by
  decide +kernel

theorem ck_PL_6 : checkLC (pPL.getD 6 0) (ofL (prodL.getD 6 [])) (selProdL (aK.getD 6 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_6 : checkNC (pPN.getD 6 0) (ofN (prodN.getD 6 [])) (selProdN ((aK.getD 6 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_6 : checkLC (pSL.getD 6 0) (smulLC (.mul (.int (((y1D.getD 6 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (6 + 1) []))) (ofL (prodL.getD 6 []))) (mulLC (ofL (y1T.getD 6 [])) (ofL (y1T.getD 6 []))) = true := by
  decide +kernel

theorem ck_SN_6 : checkNC (pSN.getD 6 0) (smulNC (.mul (.int (((y2D.getD 6 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (6 + 1) []))) (ofN (prodN.getD 6 []))) (mulNC (ofN (y2T.getD 6 [])) (ofN (y2T.getD 6 []))) = true := by
  decide +kernel

theorem ck_PL_7 : checkLC (pPL.getD 7 0) (ofL (prodL.getD 7 [])) (selProdL (aK.getD 7 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_7 : checkNC (pPN.getD 7 0) (ofN (prodN.getD 7 [])) (selProdN ((aK.getD 7 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_7 : checkLC (pSL.getD 7 0) (smulLC (.mul (.int (((y1D.getD 7 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (7 + 1) []))) (ofL (prodL.getD 7 []))) (mulLC (ofL (y1T.getD 7 [])) (ofL (y1T.getD 7 []))) = true := by
  decide +kernel

theorem ck_SN_7 : checkNC (pSN.getD 7 0) (smulNC (.mul (.int (((y2D.getD 7 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (7 + 1) []))) (ofN (prodN.getD 7 []))) (mulNC (ofN (y2T.getD 7 [])) (ofN (y2T.getD 7 []))) = true := by
  decide +kernel

theorem ck_PL_8 : checkLC (pPL.getD 8 0) (ofL (prodL.getD 8 [])) (selProdL (aK.getD 8 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_8 : checkNC (pPN.getD 8 0) (ofN (prodN.getD 8 [])) (selProdN ((aK.getD 8 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_8 : checkLC (pSL.getD 8 0) (smulLC (.mul (.int (((y1D.getD 8 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (8 + 1) []))) (ofL (prodL.getD 8 []))) (mulLC (ofL (y1T.getD 8 [])) (ofL (y1T.getD 8 []))) = true := by
  decide +kernel

theorem ck_SN_8 : checkNC (pSN.getD 8 0) (smulNC (.mul (.int (((y2D.getD 8 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (8 + 1) []))) (ofN (prodN.getD 8 []))) (mulNC (ofN (y2T.getD 8 [])) (ofN (y2T.getD 8 []))) = true := by
  decide +kernel

theorem ck_PL_9 : checkLC (pPL.getD 9 0) (ofL (prodL.getD 9 [])) (selProdL (aK.getD 9 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_9 : checkNC (pPN.getD 9 0) (ofN (prodN.getD 9 [])) (selProdN ((aK.getD 9 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_9 : checkLC (pSL.getD 9 0) (smulLC (.mul (.int (((y1D.getD 9 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (9 + 1) []))) (ofL (prodL.getD 9 []))) (mulLC (ofL (y1T.getD 9 [])) (ofL (y1T.getD 9 []))) = true := by
  decide +kernel

theorem ck_SN_9 : checkNC (pSN.getD 9 0) (smulNC (.mul (.int (((y2D.getD 9 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (9 + 1) []))) (ofN (prodN.getD 9 []))) (mulNC (ofN (y2T.getD 9 [])) (ofN (y2T.getD 9 []))) = true := by
  decide +kernel

theorem ck_PL_10 : checkLC (pPL.getD 10 0) (ofL (prodL.getD 10 [])) (selProdL (aK.getD 10 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_10 : checkNC (pPN.getD 10 0) (ofN (prodN.getD 10 [])) (selProdN ((aK.getD 10 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_10 : checkLC (pSL.getD 10 0) (smulLC (.mul (.int (((y1D.getD 10 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (10 + 1) []))) (ofL (prodL.getD 10 []))) (mulLC (ofL (y1T.getD 10 [])) (ofL (y1T.getD 10 []))) = true := by
  decide +kernel

theorem ck_SN_10 : checkNC (pSN.getD 10 0) (smulNC (.mul (.int (((y2D.getD 10 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (10 + 1) []))) (ofN (prodN.getD 10 []))) (mulNC (ofN (y2T.getD 10 [])) (ofN (y2T.getD 10 []))) = true := by
  decide +kernel

theorem ck_PL_11 : checkLC (pPL.getD 11 0) (ofL (prodL.getD 11 [])) (selProdL (aK.getD 11 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_11 : checkNC (pPN.getD 11 0) (ofN (prodN.getD 11 [])) (selProdN ((aK.getD 11 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_11 : checkLC (pSL.getD 11 0) (smulLC (.mul (.int (((y1D.getD 11 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (11 + 1) []))) (ofL (prodL.getD 11 []))) (mulLC (ofL (y1T.getD 11 [])) (ofL (y1T.getD 11 []))) = true := by
  decide +kernel

theorem ck_SN_11 : checkNC (pSN.getD 11 0) (smulNC (.mul (.int (((y2D.getD 11 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (11 + 1) []))) (ofN (prodN.getD 11 []))) (mulNC (ofN (y2T.getD 11 [])) (ofN (y2T.getD 11 []))) = true := by
  decide +kernel

theorem ck_PL_12 : checkLC (pPL.getD 12 0) (ofL (prodL.getD 12 [])) (selProdL (aK.getD 12 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_12 : checkNC (pPN.getD 12 0) (ofN (prodN.getD 12 [])) (selProdN ((aK.getD 12 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_12 : checkLC (pSL.getD 12 0) (smulLC (.mul (.int (((y1D.getD 12 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (12 + 1) []))) (ofL (prodL.getD 12 []))) (mulLC (ofL (y1T.getD 12 [])) (ofL (y1T.getD 12 []))) = true := by
  decide +kernel

theorem ck_SN_12 : checkNC (pSN.getD 12 0) (smulNC (.mul (.int (((y2D.getD 12 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (12 + 1) []))) (ofN (prodN.getD 12 []))) (mulNC (ofN (y2T.getD 12 [])) (ofN (y2T.getD 12 []))) = true := by
  decide +kernel

theorem ck_PL_13 : checkLC (pPL.getD 13 0) (ofL (prodL.getD 13 [])) (selProdL (aK.getD 13 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_13 : checkNC (pPN.getD 13 0) (ofN (prodN.getD 13 [])) (selProdN ((aK.getD 13 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_13 : checkLC (pSL.getD 13 0) (smulLC (.mul (.int (((y1D.getD 13 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (13 + 1) []))) (ofL (prodL.getD 13 []))) (mulLC (ofL (y1T.getD 13 [])) (ofL (y1T.getD 13 []))) = true := by
  decide +kernel

theorem ck_SN_13 : checkNC (pSN.getD 13 0) (smulNC (.mul (.int (((y2D.getD 13 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (13 + 1) []))) (ofN (prodN.getD 13 []))) (mulNC (ofN (y2T.getD 13 [])) (ofN (y2T.getD 13 []))) = true := by
  decide +kernel

theorem ck_PL_14 : checkLC (pPL.getD 14 0) (ofL (prodL.getD 14 [])) (selProdL (aK.getD 14 []) SUnitData.gL) = true := by
  decide +kernel

theorem ck_PN_14 : checkNC (pPN.getD 14 0) (ofN (prodN.getD 14 [])) (selProdN ((aK.getD 14 []).drop 29) SUnitData.gN) = true := by
  decide +kernel

theorem ck_SL_14 : checkLC (pSL.getD 14 0) (smulLC (.mul (.int (((y1D.getD 14 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (14 + 1) []))) (ofL (prodL.getD 14 []))) (mulLC (ofL (y1T.getD 14 [])) (ofL (y1T.getD 14 []))) = true := by
  decide +kernel

theorem ck_SN_14 : checkNC (pSN.getD 14 0) (smulNC (.mul (.int (((y2D.getD 14 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (14 + 1) []))) (ofN (prodN.getD 14 []))) (mulNC (ofN (y2T.getD 14 [])) (ofN (y2T.getD 14 []))) = true := by
  decide +kernel

theorem ck_PL : ∀ t, t < 15 → checkLC (pPL.getD t 0) (ofL (prodL.getD t [])) (selProdL (aK.getD t []) SUnitData.gL) = true := by
  intro t ht
  interval_cases t
  exacts [ck_PL_0, ck_PL_1, ck_PL_2, ck_PL_3, ck_PL_4, ck_PL_5, ck_PL_6, ck_PL_7, ck_PL_8, ck_PL_9, ck_PL_10, ck_PL_11, ck_PL_12, ck_PL_13, ck_PL_14]

theorem ck_PN : ∀ t, t < 15 → checkNC (pPN.getD t 0) (ofN (prodN.getD t [])) (selProdN ((aK.getD t []).drop 29) SUnitData.gN) = true := by
  intro t ht
  interval_cases t
  exacts [ck_PN_0, ck_PN_1, ck_PN_2, ck_PN_3, ck_PN_4, ck_PN_5, ck_PN_6, ck_PN_7, ck_PN_8, ck_PN_9, ck_PN_10, ck_PN_11, ck_PN_12, ck_PN_13, ck_PN_14]

theorem ck_SL : ∀ t, t < 15 → checkLC (pSL.getD t 0) (smulLC (.mul (.int (((y1D.getD t 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (t + 1) []))) (ofL (prodL.getD t []))) (mulLC (ofL (y1T.getD t [])) (ofL (y1T.getD t []))) = true := by
  intro t ht
  interval_cases t
  exacts [ck_SL_0, ck_SL_1, ck_SL_2, ck_SL_3, ck_SL_4, ck_SL_5, ck_SL_6, ck_SL_7, ck_SL_8, ck_SL_9, ck_SL_10, ck_SL_11, ck_SL_12, ck_SL_13, ck_SL_14]

theorem ck_SN : ∀ t, t < 15 → checkNC (pSN.getD t 0) (smulNC (.mul (.int (((y2D.getD t 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (t + 1) []))) (ofN (prodN.getD t []))) (mulNC (ofN (y2T.getD t [])) (ofN (y2T.getD t []))) = true := by
  intro t ht
  interval_cases t
  exacts [ck_SN_0, ck_SN_1, ck_SN_2, ck_SN_3, ck_SN_4, ck_SN_5, ck_SN_6, ck_SN_7, ck_SN_8, ck_SN_9, ck_SN_10, ck_SN_11, ck_SN_12, ck_SN_13, ck_SN_14]

theorem ck_shape : ∀ t, t < 15 → (∀ b ∈ aK.getD t [], b ≤ 1) ∧ 82 ≤ (aK.getD t []).length ∧
    y1D.getD t 0 ≠ 0 ∧ y2D.getD t 0 ≠ 0 := by
  decide +kernel

end FurioLombardo.Discharge.SelmerBasis.KappaData
