import FurioLombardo.Discharge.SelmerBasis.RealSignDefs

/-!
# Kernel checks of the real signs: ckNf (generated by code/selmer-local-conditions/kernel_checks_real.sh)

`ck_N<k>_j`: `ckNf k j` for `k = 0, 1`, `j < 53`.
Every statement is closed by `decide +kernel`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.RealRoots

theorem ck_N0_0 : ckNf 0 0 = true := by decide +kernel

theorem ck_N0_1 : ckNf 0 1 = true := by decide +kernel

theorem ck_N0_2 : ckNf 0 2 = true := by decide +kernel

theorem ck_N0_3 : ckNf 0 3 = true := by decide +kernel

theorem ck_N0_4 : ckNf 0 4 = true := by decide +kernel

theorem ck_N0_5 : ckNf 0 5 = true := by decide +kernel

theorem ck_N0_6 : ckNf 0 6 = true := by decide +kernel

theorem ck_N0_7 : ckNf 0 7 = true := by decide +kernel

theorem ck_N0_8 : ckNf 0 8 = true := by decide +kernel

theorem ck_N0_9 : ckNf 0 9 = true := by decide +kernel

theorem ck_N0_10 : ckNf 0 10 = true := by decide +kernel

theorem ck_N0_11 : ckNf 0 11 = true := by decide +kernel

theorem ck_N0_12 : ckNf 0 12 = true := by decide +kernel

theorem ck_N0_13 : ckNf 0 13 = true := by decide +kernel

theorem ck_N0_14 : ckNf 0 14 = true := by decide +kernel

theorem ck_N0_15 : ckNf 0 15 = true := by decide +kernel

theorem ck_N0_16 : ckNf 0 16 = true := by decide +kernel

theorem ck_N0_17 : ckNf 0 17 = true := by decide +kernel

theorem ck_N0_18 : ckNf 0 18 = true := by decide +kernel

theorem ck_N0_19 : ckNf 0 19 = true := by decide +kernel

theorem ck_N0_20 : ckNf 0 20 = true := by decide +kernel

theorem ck_N0_21 : ckNf 0 21 = true := by decide +kernel

theorem ck_N0_22 : ckNf 0 22 = true := by decide +kernel

theorem ck_N0_23 : ckNf 0 23 = true := by decide +kernel

theorem ck_N0_24 : ckNf 0 24 = true := by decide +kernel

theorem ck_N0_25 : ckNf 0 25 = true := by decide +kernel

theorem ck_N0_26 : ckNf 0 26 = true := by decide +kernel

theorem ck_N0_27 : ckNf 0 27 = true := by decide +kernel

theorem ck_N0_28 : ckNf 0 28 = true := by decide +kernel

theorem ck_N0_29 : ckNf 0 29 = true := by decide +kernel

theorem ck_N0_30 : ckNf 0 30 = true := by decide +kernel

theorem ck_N0_31 : ckNf 0 31 = true := by decide +kernel

theorem ck_N0_32 : ckNf 0 32 = true := by decide +kernel

theorem ck_N0_33 : ckNf 0 33 = true := by decide +kernel

theorem ck_N0_34 : ckNf 0 34 = true := by decide +kernel

theorem ck_N0_35 : ckNf 0 35 = true := by decide +kernel

theorem ck_N0_36 : ckNf 0 36 = true := by decide +kernel

theorem ck_N0_37 : ckNf 0 37 = true := by decide +kernel

theorem ck_N0_38 : ckNf 0 38 = true := by decide +kernel

theorem ck_N0_39 : ckNf 0 39 = true := by decide +kernel

theorem ck_N0_40 : ckNf 0 40 = true := by decide +kernel

theorem ck_N0_41 : ckNf 0 41 = true := by decide +kernel

theorem ck_N0_42 : ckNf 0 42 = true := by decide +kernel

theorem ck_N0_43 : ckNf 0 43 = true := by decide +kernel

theorem ck_N0_44 : ckNf 0 44 = true := by decide +kernel

theorem ck_N0_45 : ckNf 0 45 = true := by decide +kernel

theorem ck_N0_46 : ckNf 0 46 = true := by decide +kernel

theorem ck_N0_47 : ckNf 0 47 = true := by decide +kernel

theorem ck_N0_48 : ckNf 0 48 = true := by decide +kernel

theorem ck_N0_49 : ckNf 0 49 = true := by decide +kernel

theorem ck_N0_50 : ckNf 0 50 = true := by decide +kernel

theorem ck_N0_51 : ckNf 0 51 = true := by decide +kernel

theorem ck_N0_52 : ckNf 0 52 = true := by decide +kernel

theorem ck_N1_0 : ckNf 1 0 = true := by decide +kernel

theorem ck_N1_1 : ckNf 1 1 = true := by decide +kernel

theorem ck_N1_2 : ckNf 1 2 = true := by decide +kernel

theorem ck_N1_3 : ckNf 1 3 = true := by decide +kernel

theorem ck_N1_4 : ckNf 1 4 = true := by decide +kernel

theorem ck_N1_5 : ckNf 1 5 = true := by decide +kernel

theorem ck_N1_6 : ckNf 1 6 = true := by decide +kernel

theorem ck_N1_7 : ckNf 1 7 = true := by decide +kernel

theorem ck_N1_8 : ckNf 1 8 = true := by decide +kernel

theorem ck_N1_9 : ckNf 1 9 = true := by decide +kernel

theorem ck_N1_10 : ckNf 1 10 = true := by decide +kernel

theorem ck_N1_11 : ckNf 1 11 = true := by decide +kernel

theorem ck_N1_12 : ckNf 1 12 = true := by decide +kernel

theorem ck_N1_13 : ckNf 1 13 = true := by decide +kernel

theorem ck_N1_14 : ckNf 1 14 = true := by decide +kernel

theorem ck_N1_15 : ckNf 1 15 = true := by decide +kernel

theorem ck_N1_16 : ckNf 1 16 = true := by decide +kernel

theorem ck_N1_17 : ckNf 1 17 = true := by decide +kernel

theorem ck_N1_18 : ckNf 1 18 = true := by decide +kernel

theorem ck_N1_19 : ckNf 1 19 = true := by decide +kernel

theorem ck_N1_20 : ckNf 1 20 = true := by decide +kernel

theorem ck_N1_21 : ckNf 1 21 = true := by decide +kernel

theorem ck_N1_22 : ckNf 1 22 = true := by decide +kernel

theorem ck_N1_23 : ckNf 1 23 = true := by decide +kernel

theorem ck_N1_24 : ckNf 1 24 = true := by decide +kernel

theorem ck_N1_25 : ckNf 1 25 = true := by decide +kernel

theorem ck_N1_26 : ckNf 1 26 = true := by decide +kernel

theorem ck_N1_27 : ckNf 1 27 = true := by decide +kernel

theorem ck_N1_28 : ckNf 1 28 = true := by decide +kernel

theorem ck_N1_29 : ckNf 1 29 = true := by decide +kernel

theorem ck_N1_30 : ckNf 1 30 = true := by decide +kernel

theorem ck_N1_31 : ckNf 1 31 = true := by decide +kernel

theorem ck_N1_32 : ckNf 1 32 = true := by decide +kernel

theorem ck_N1_33 : ckNf 1 33 = true := by decide +kernel

theorem ck_N1_34 : ckNf 1 34 = true := by decide +kernel

theorem ck_N1_35 : ckNf 1 35 = true := by decide +kernel

theorem ck_N1_36 : ckNf 1 36 = true := by decide +kernel

theorem ck_N1_37 : ckNf 1 37 = true := by decide +kernel

theorem ck_N1_38 : ckNf 1 38 = true := by decide +kernel

theorem ck_N1_39 : ckNf 1 39 = true := by decide +kernel

theorem ck_N1_40 : ckNf 1 40 = true := by decide +kernel

theorem ck_N1_41 : ckNf 1 41 = true := by decide +kernel

theorem ck_N1_42 : ckNf 1 42 = true := by decide +kernel

theorem ck_N1_43 : ckNf 1 43 = true := by decide +kernel

theorem ck_N1_44 : ckNf 1 44 = true := by decide +kernel

theorem ck_N1_45 : ckNf 1 45 = true := by decide +kernel

theorem ck_N1_46 : ckNf 1 46 = true := by decide +kernel

theorem ck_N1_47 : ckNf 1 47 = true := by decide +kernel

theorem ck_N1_48 : ckNf 1 48 = true := by decide +kernel

theorem ck_N1_49 : ckNf 1 49 = true := by decide +kernel

theorem ck_N1_50 : ckNf 1 50 = true := by decide +kernel

theorem ck_N1_51 : ckNf 1 51 = true := by decide +kernel

theorem ck_N1_52 : ckNf 1 52 = true := by decide +kernel

theorem ck_N0 : ∀ i, 0 ≤ i → i < 53 → ckNf 0 i = true := by
  intro i ha hi
  interval_cases i
  exacts [ck_N0_0, ck_N0_1, ck_N0_2, ck_N0_3, ck_N0_4, ck_N0_5, ck_N0_6, ck_N0_7, ck_N0_8, ck_N0_9, ck_N0_10, ck_N0_11, ck_N0_12, ck_N0_13, ck_N0_14, ck_N0_15, ck_N0_16, ck_N0_17, ck_N0_18, ck_N0_19, ck_N0_20, ck_N0_21, ck_N0_22, ck_N0_23, ck_N0_24, ck_N0_25, ck_N0_26, ck_N0_27, ck_N0_28, ck_N0_29, ck_N0_30, ck_N0_31, ck_N0_32, ck_N0_33, ck_N0_34, ck_N0_35, ck_N0_36, ck_N0_37, ck_N0_38, ck_N0_39, ck_N0_40, ck_N0_41, ck_N0_42, ck_N0_43, ck_N0_44, ck_N0_45, ck_N0_46, ck_N0_47, ck_N0_48, ck_N0_49, ck_N0_50, ck_N0_51, ck_N0_52]

theorem ck_N1 : ∀ i, 0 ≤ i → i < 53 → ckNf 1 i = true := by
  intro i ha hi
  interval_cases i
  exacts [ck_N1_0, ck_N1_1, ck_N1_2, ck_N1_3, ck_N1_4, ck_N1_5, ck_N1_6, ck_N1_7, ck_N1_8, ck_N1_9, ck_N1_10, ck_N1_11, ck_N1_12, ck_N1_13, ck_N1_14, ck_N1_15, ck_N1_16, ck_N1_17, ck_N1_18, ck_N1_19, ck_N1_20, ck_N1_21, ck_N1_22, ck_N1_23, ck_N1_24, ck_N1_25, ck_N1_26, ck_N1_27, ck_N1_28, ck_N1_29, ck_N1_30, ck_N1_31, ck_N1_32, ck_N1_33, ck_N1_34, ck_N1_35, ck_N1_36, ck_N1_37, ck_N1_38, ck_N1_39, ck_N1_40, ck_N1_41, ck_N1_42, ck_N1_43, ck_N1_44, ck_N1_45, ck_N1_46, ck_N1_47, ck_N1_48, ck_N1_49, ck_N1_50, ck_N1_51, ck_N1_52]

end FurioLombardo.Discharge.SelmerBasis.RealRoots
