import FurioLombardo.Discharge.SelmerBasis.RealSignDefs

/-!
# Kernel checks of the real signs: gensL, tower, bits (generated by code/selmer-local-conditions/kernel_checks_real.sh)

`ck_L<k>_i`: the sign certificates of `gensL i` at `embQ k`; `id_L_i`: its norm; `ck_T`, `ck_B`, `id_Beta`.
Every statement is closed by `decide +kernel`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.RealRoots

theorem ck_L0_0 : ckLf 0 0 = true := by decide +kernel

theorem ck_L0_1 : ckLf 0 1 = true := by decide +kernel

theorem ck_L0_2 : ckLf 0 2 = true := by decide +kernel

theorem ck_L0_3 : ckLf 0 3 = true := by decide +kernel

theorem ck_L0_4 : ckLf 0 4 = true := by decide +kernel

theorem ck_L0_5 : ckLf 0 5 = true := by decide +kernel

theorem ck_L0_6 : ckLf 0 6 = true := by decide +kernel

theorem ck_L0_7 : ckLf 0 7 = true := by decide +kernel

theorem ck_L0_8 : ckLf 0 8 = true := by decide +kernel

theorem ck_L0_9 : ckLf 0 9 = true := by decide +kernel

theorem ck_L0_10 : ckLf 0 10 = true := by decide +kernel

theorem ck_L0_11 : ckLf 0 11 = true := by decide +kernel

theorem ck_L0_12 : ckLf 0 12 = true := by decide +kernel

theorem ck_L0_13 : ckLf 0 13 = true := by decide +kernel

theorem ck_L0_14 : ckLf 0 14 = true := by decide +kernel

theorem ck_L0_15 : ckLf 0 15 = true := by decide +kernel

theorem ck_L0_16 : ckLf 0 16 = true := by decide +kernel

theorem ck_L0_17 : ckLf 0 17 = true := by decide +kernel

theorem ck_L0_18 : ckLf 0 18 = true := by decide +kernel

theorem ck_L0_19 : ckLf 0 19 = true := by decide +kernel

theorem ck_L0_20 : ckLf 0 20 = true := by decide +kernel

theorem ck_L0_21 : ckLf 0 21 = true := by decide +kernel

theorem ck_L0_22 : ckLf 0 22 = true := by decide +kernel

theorem ck_L0_23 : ckLf 0 23 = true := by decide +kernel

theorem ck_L0_24 : ckLf 0 24 = true := by decide +kernel

theorem ck_L0_25 : ckLf 0 25 = true := by decide +kernel

theorem ck_L0_26 : ckLf 0 26 = true := by decide +kernel

theorem ck_L0_27 : ckLf 0 27 = true := by decide +kernel

theorem ck_L0_28 : ckLf 0 28 = true := by decide +kernel

theorem ck_L1_0 : ckLf 1 0 = true := by decide +kernel

theorem ck_L1_1 : ckLf 1 1 = true := by decide +kernel

theorem ck_L1_2 : ckLf 1 2 = true := by decide +kernel

theorem ck_L1_3 : ckLf 1 3 = true := by decide +kernel

theorem ck_L1_4 : ckLf 1 4 = true := by decide +kernel

theorem ck_L1_5 : ckLf 1 5 = true := by decide +kernel

theorem ck_L1_6 : ckLf 1 6 = true := by decide +kernel

theorem ck_L1_7 : ckLf 1 7 = true := by decide +kernel

theorem ck_L1_8 : ckLf 1 8 = true := by decide +kernel

theorem ck_L1_9 : ckLf 1 9 = true := by decide +kernel

theorem ck_L1_10 : ckLf 1 10 = true := by decide +kernel

theorem ck_L1_11 : ckLf 1 11 = true := by decide +kernel

theorem ck_L1_12 : ckLf 1 12 = true := by decide +kernel

theorem ck_L1_13 : ckLf 1 13 = true := by decide +kernel

theorem ck_L1_14 : ckLf 1 14 = true := by decide +kernel

theorem ck_L1_15 : ckLf 1 15 = true := by decide +kernel

theorem ck_L1_16 : ckLf 1 16 = true := by decide +kernel

theorem ck_L1_17 : ckLf 1 17 = true := by decide +kernel

theorem ck_L1_18 : ckLf 1 18 = true := by decide +kernel

theorem ck_L1_19 : ckLf 1 19 = true := by decide +kernel

theorem ck_L1_20 : ckLf 1 20 = true := by decide +kernel

theorem ck_L1_21 : ckLf 1 21 = true := by decide +kernel

theorem ck_L1_22 : ckLf 1 22 = true := by decide +kernel

theorem ck_L1_23 : ckLf 1 23 = true := by decide +kernel

theorem ck_L1_24 : ckLf 1 24 = true := by decide +kernel

theorem ck_L1_25 : ckLf 1 25 = true := by decide +kernel

theorem ck_L1_26 : ckLf 1 26 = true := by decide +kernel

theorem ck_L1_27 : ckLf 1 27 = true := by decide +kernel

theorem ck_L1_28 : ckLf 1 28 = true := by decide +kernel

theorem id_L_0 : idLf 0 = true := by decide +kernel

theorem id_L_1 : idLf 1 = true := by decide +kernel

theorem id_L_2 : idLf 2 = true := by decide +kernel

theorem id_L_3 : idLf 3 = true := by decide +kernel

theorem id_L_4 : idLf 4 = true := by decide +kernel

theorem id_L_5 : idLf 5 = true := by decide +kernel

theorem id_L_6 : idLf 6 = true := by decide +kernel

theorem id_L_7 : idLf 7 = true := by decide +kernel

theorem id_L_8 : idLf 8 = true := by decide +kernel

theorem id_L_9 : idLf 9 = true := by decide +kernel

theorem id_L_10 : idLf 10 = true := by decide +kernel

theorem id_L_11 : idLf 11 = true := by decide +kernel

theorem id_L_12 : idLf 12 = true := by decide +kernel

theorem id_L_13 : idLf 13 = true := by decide +kernel

theorem id_L_14 : idLf 14 = true := by decide +kernel

theorem id_L_15 : idLf 15 = true := by decide +kernel

theorem id_L_16 : idLf 16 = true := by decide +kernel

theorem id_L_17 : idLf 17 = true := by decide +kernel

theorem id_L_18 : idLf 18 = true := by decide +kernel

theorem id_L_19 : idLf 19 = true := by decide +kernel

theorem id_L_20 : idLf 20 = true := by decide +kernel

theorem id_L_21 : idLf 21 = true := by decide +kernel

theorem id_L_22 : idLf 22 = true := by decide +kernel

theorem id_L_23 : idLf 23 = true := by decide +kernel

theorem id_L_24 : idLf 24 = true := by decide +kernel

theorem id_L_25 : idLf 25 = true := by decide +kernel

theorem id_L_26 : idLf 26 = true := by decide +kernel

theorem id_L_27 : idLf 27 = true := by decide +kernel

theorem id_L_28 : idLf 28 = true := by decide +kernel

theorem ck_T : ∀ k : Fin 2, ckTf k = true := by decide +kernel

theorem ck_B : ∀ k : Fin 2, ckBf k = true := by decide +kernel

theorem id_Beta : idBeta = true := by decide +kernel

theorem ck_L0 : ∀ i, 0 ≤ i → i < 29 → ckLf 0 i = true := by
  intro i ha hi
  interval_cases i
  exacts [ck_L0_0, ck_L0_1, ck_L0_2, ck_L0_3, ck_L0_4, ck_L0_5, ck_L0_6, ck_L0_7, ck_L0_8, ck_L0_9, ck_L0_10, ck_L0_11, ck_L0_12, ck_L0_13, ck_L0_14, ck_L0_15, ck_L0_16, ck_L0_17, ck_L0_18, ck_L0_19, ck_L0_20, ck_L0_21, ck_L0_22, ck_L0_23, ck_L0_24, ck_L0_25, ck_L0_26, ck_L0_27, ck_L0_28]

theorem ck_L1 : ∀ i, 0 ≤ i → i < 29 → ckLf 1 i = true := by
  intro i ha hi
  interval_cases i
  exacts [ck_L1_0, ck_L1_1, ck_L1_2, ck_L1_3, ck_L1_4, ck_L1_5, ck_L1_6, ck_L1_7, ck_L1_8, ck_L1_9, ck_L1_10, ck_L1_11, ck_L1_12, ck_L1_13, ck_L1_14, ck_L1_15, ck_L1_16, ck_L1_17, ck_L1_18, ck_L1_19, ck_L1_20, ck_L1_21, ck_L1_22, ck_L1_23, ck_L1_24, ck_L1_25, ck_L1_26, ck_L1_27, ck_L1_28]

theorem id_L : ∀ i, 0 ≤ i → i < 29 → idLf i = true := by
  intro i ha hi
  interval_cases i
  exacts [id_L_0, id_L_1, id_L_2, id_L_3, id_L_4, id_L_5, id_L_6, id_L_7, id_L_8, id_L_9, id_L_10, id_L_11, id_L_12, id_L_13, id_L_14, id_L_15, id_L_16, id_L_17, id_L_18, id_L_19, id_L_20, id_L_21, id_L_22, id_L_23, id_L_24, id_L_25, id_L_26, id_L_27, id_L_28]

end FurioLombardo.Discharge.SelmerBasis.RealRoots
