import FurioLombardo.Discharge.SelmerBasis.TowerEval
import FurioLombardo.Discharge.M3a.ConcreteDefs

/-!
# Kernel checks of the tower data (generated by code/selmer-global-bound/tower_checks_gen.sh)

With `A = alphaDen α ∈ L42` and `B = betaPowDen β ∈ N84` (SUnitData.lean), the tables `tabA`, `tabB`
of the coordinates of `A^i`, `B^i` (`i ≤ 5`) are checked step by step (`ck_tabA_i`, `ck_tabB_i`),
`P_1` against `alphaL`, `2 betaN`. Then, one `checkLC` / `checkNC` each (`sumPL`, `sumPN` of
TowerEval.lean):

* `ck_qA_k`, `ck_hB_k`: `q k (α) = 0`, `h k (β) = 0` (`k = 0, 1`);
* `ck_pA_s`, `ck_pB_s`: `Pgen s (α)` and `Pgen s (β)` are `gensL s, 1` (`s < 29`) or
  `1, gensN (s - 29)` (`s ≥ 29`).

Every statement is closed by `decide +kernel`, one identity per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.TowerChecks

open FurioLombardo.M1 FurioLombardo.M1.Kron FurioLombardo.Discharge.M3a FurioLombardo.Discharge.M3a.Bruin
  FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower SUnitData

set_option maxRecDepth 100000

/-- The coordinates of `A^i`, `A = alphaDen α`. -/
def tabA : List LC :=
  [ofL alphaPow_0, ofL alphaPow_1, ofL alphaPow_2, ofL alphaPow_3, ofL alphaPow_4, ofL alphaPow_5]

/-- The coordinates of `B^i`, `B = betaPowDen β`. -/
def tabB : List NC :=
  [ofN betaPow_0, ofN betaPow_1, ofN betaPow_2, ofN betaPow_3, ofN betaPow_4, ofN betaPow_5]

/-- `2 betaN` in the coordinates of `mkN` (`betaPowDen = 2 betaDen`). -/
def twoBetaN : NC :=
  ((.mul (.int 2) (.lin (betaN.getD 0 [])), .mul (.int 2) (.lin (betaN.getD 1 []))),
    (.lin (betaN.getD 2 []), .lin (betaN.getD 3 [])))

theorem ck_tabA_0 : checkLC 1024 (ofL alphaPow_0) oneLC = true := by decide +kernel

theorem ck_tabA_1 : checkLC 1024 (ofL alphaPow_1) (ofL alphaL) = true := by decide +kernel

theorem ck_tabA_2 : checkLC 1024 (ofL alphaPow_2) (mulLC (ofL alphaPow_1) (ofL alphaPow_1)) = true := by
  decide +kernel

theorem ck_tabA_3 : checkLC 1024 (ofL alphaPow_3) (mulLC (ofL alphaPow_2) (ofL alphaPow_1)) = true := by
  decide +kernel

theorem ck_tabA_4 : checkLC 1024 (ofL alphaPow_4) (mulLC (ofL alphaPow_3) (ofL alphaPow_1)) = true := by
  decide +kernel

theorem ck_tabA_5 : checkLC 1024 (ofL alphaPow_5) (mulLC (ofL alphaPow_4) (ofL alphaPow_1)) = true := by
  decide +kernel

theorem ck_tabB_0 : checkNC 1024 (ofN betaPow_0) oneNC = true := by decide +kernel

theorem ck_tabB_1 : checkNC 1024 (ofN betaPow_1) twoBetaN = true := by decide +kernel

theorem ck_tabB_2 : checkNC 1024 (ofN betaPow_2) (mulNC (ofN betaPow_1) (ofN betaPow_1)) = true := by
  decide +kernel

theorem ck_tabB_3 : checkNC 1024 (ofN betaPow_3) (mulNC (ofN betaPow_2) (ofN betaPow_1)) = true := by
  decide +kernel

theorem ck_tabB_4 : checkNC 1024 (ofN betaPow_4) (mulNC (ofN betaPow_3) (ofN betaPow_1)) = true := by
  decide +kernel

theorem ck_tabB_5 : checkNC 1024 (ofN betaPow_5) (mulNC (ofN betaPow_4) (ofN betaPow_1)) = true := by
  decide +kernel

theorem ck_qA_0 : checkLC 1024 (sumPL alphaDen 2 (qL 0) tabA)
    (smulLC (.int ((alphaDen ^ 2 * qDenN 0 : ℕ) : ℤ)) zeroLC) = true := by decide +kernel

theorem ck_hB_0 : checkNC 1024 (sumPN betaPowDen 4 (hL 0) tabB)
    (smulNC (.int ((betaPowDen ^ 4 * hDenN 0 : ℕ) : ℤ)) zeroNC) = true := by decide +kernel

theorem ck_qA_1 : checkLC 1024 (sumPL alphaDen 2 (qL 1) tabA)
    (smulLC (.int ((alphaDen ^ 2 * qDenN 1 : ℕ) : ℤ)) zeroLC) = true := by decide +kernel

theorem ck_hB_1 : checkNC 1024 (sumPN betaPowDen 4 (hL 1) tabB)
    (smulNC (.int ((betaPowDen ^ 4 * hDenN 1 : ℕ) : ℤ)) zeroNC) = true := by decide +kernel

theorem ck_pA_0 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 0 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 0 1 : ℕ) : ℤ)) (ofL (gL.getD 0 []))) = true := by decide +kernel

theorem ck_pB_0 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 0 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 0 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_1 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 1 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 1 1 : ℕ) : ℤ)) (ofL (gL.getD 1 []))) = true := by decide +kernel

theorem ck_pB_1 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 1 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 1 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_2 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 2 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 2 1 : ℕ) : ℤ)) (ofL (gL.getD 2 []))) = true := by decide +kernel

theorem ck_pB_2 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 2 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 2 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_3 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 3 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 3 1 : ℕ) : ℤ)) (ofL (gL.getD 3 []))) = true := by decide +kernel

theorem ck_pB_3 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 3 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 3 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_4 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 4 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 4 1 : ℕ) : ℤ)) (ofL (gL.getD 4 []))) = true := by decide +kernel

theorem ck_pB_4 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 4 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 4 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_5 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 5 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 5 1 : ℕ) : ℤ)) (ofL (gL.getD 5 []))) = true := by decide +kernel

theorem ck_pB_5 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 5 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 5 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_6 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 6 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 6 1 : ℕ) : ℤ)) (ofL (gL.getD 6 []))) = true := by decide +kernel

theorem ck_pB_6 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 6 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 6 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_7 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 7 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 7 1 : ℕ) : ℤ)) (ofL (gL.getD 7 []))) = true := by decide +kernel

theorem ck_pB_7 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 7 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 7 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_8 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 8 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 8 1 : ℕ) : ℤ)) (ofL (gL.getD 8 []))) = true := by decide +kernel

theorem ck_pB_8 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 8 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 8 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_9 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 9 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 9 1 : ℕ) : ℤ)) (ofL (gL.getD 9 []))) = true := by decide +kernel

theorem ck_pB_9 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 9 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 9 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_10 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 10 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 10 1 : ℕ) : ℤ)) (ofL (gL.getD 10 []))) = true := by decide +kernel

theorem ck_pB_10 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 10 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 10 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_11 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 11 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 11 1 : ℕ) : ℤ)) (ofL (gL.getD 11 []))) = true := by decide +kernel

theorem ck_pB_11 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 11 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 11 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_12 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 12 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 12 1 : ℕ) : ℤ)) (ofL (gL.getD 12 []))) = true := by decide +kernel

theorem ck_pB_12 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 12 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 12 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_13 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 13 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 13 1 : ℕ) : ℤ)) (ofL (gL.getD 13 []))) = true := by decide +kernel

theorem ck_pB_13 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 13 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 13 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_14 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 14 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 14 1 : ℕ) : ℤ)) (ofL (gL.getD 14 []))) = true := by decide +kernel

theorem ck_pB_14 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 14 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 14 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_15 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 15 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 15 1 : ℕ) : ℤ)) (ofL (gL.getD 15 []))) = true := by decide +kernel

theorem ck_pB_15 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 15 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 15 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_16 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 16 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 16 1 : ℕ) : ℤ)) (ofL (gL.getD 16 []))) = true := by decide +kernel

theorem ck_pB_16 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 16 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 16 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_17 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 17 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 17 1 : ℕ) : ℤ)) (ofL (gL.getD 17 []))) = true := by decide +kernel

theorem ck_pB_17 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 17 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 17 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_18 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 18 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 18 1 : ℕ) : ℤ)) (ofL (gL.getD 18 []))) = true := by decide +kernel

theorem ck_pB_18 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 18 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 18 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_19 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 19 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 19 1 : ℕ) : ℤ)) (ofL (gL.getD 19 []))) = true := by decide +kernel

theorem ck_pB_19 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 19 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 19 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_20 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 20 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 20 1 : ℕ) : ℤ)) (ofL (gL.getD 20 []))) = true := by decide +kernel

theorem ck_pB_20 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 20 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 20 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_21 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 21 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 21 1 : ℕ) : ℤ)) (ofL (gL.getD 21 []))) = true := by decide +kernel

theorem ck_pB_21 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 21 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 21 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_22 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 22 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 22 1 : ℕ) : ℤ)) (ofL (gL.getD 22 []))) = true := by decide +kernel

theorem ck_pB_22 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 22 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 22 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_23 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 23 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 23 1 : ℕ) : ℤ)) (ofL (gL.getD 23 []))) = true := by decide +kernel

theorem ck_pB_23 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 23 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 23 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_24 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 24 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 24 1 : ℕ) : ℤ)) (ofL (gL.getD 24 []))) = true := by decide +kernel

theorem ck_pB_24 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 24 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 24 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_25 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 25 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 25 1 : ℕ) : ℤ)) (ofL (gL.getD 25 []))) = true := by decide +kernel

theorem ck_pB_25 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 25 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 25 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_26 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 26 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 26 1 : ℕ) : ℤ)) (ofL (gL.getD 26 []))) = true := by decide +kernel

theorem ck_pB_26 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 26 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 26 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_27 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 27 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 27 1 : ℕ) : ℤ)) (ofL (gL.getD 27 []))) = true := by decide +kernel

theorem ck_pB_27 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 27 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 27 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_28 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 28 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 28 1 : ℕ) : ℤ)) (ofL (gL.getD 28 []))) = true := by decide +kernel

theorem ck_pB_28 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 28 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 28 1 : ℕ) : ℤ)) oneNC) = true := by decide +kernel

theorem ck_pA_29 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 29 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 29 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_29 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 29 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 29 1 : ℕ) : ℤ)) (ofN (gN.getD 0 []))) = true := by decide +kernel

theorem ck_pA_30 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 30 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 30 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_30 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 30 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 30 1 : ℕ) : ℤ)) (ofN (gN.getD 1 []))) = true := by decide +kernel

theorem ck_pA_31 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 31 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 31 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_31 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 31 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 31 1 : ℕ) : ℤ)) (ofN (gN.getD 2 []))) = true := by decide +kernel

theorem ck_pA_32 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 32 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 32 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_32 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 32 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 32 1 : ℕ) : ℤ)) (ofN (gN.getD 3 []))) = true := by decide +kernel

theorem ck_pA_33 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 33 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 33 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_33 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 33 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 33 1 : ℕ) : ℤ)) (ofN (gN.getD 4 []))) = true := by decide +kernel

theorem ck_pA_34 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 34 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 34 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_34 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 34 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 34 1 : ℕ) : ℤ)) (ofN (gN.getD 5 []))) = true := by decide +kernel

theorem ck_pA_35 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 35 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 35 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_35 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 35 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 35 1 : ℕ) : ℤ)) (ofN (gN.getD 6 []))) = true := by decide +kernel

theorem ck_pA_36 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 36 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 36 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_36 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 36 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 36 1 : ℕ) : ℤ)) (ofN (gN.getD 7 []))) = true := by decide +kernel

theorem ck_pA_37 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 37 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 37 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_37 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 37 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 37 1 : ℕ) : ℤ)) (ofN (gN.getD 8 []))) = true := by decide +kernel

theorem ck_pA_38 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 38 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 38 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_38 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 38 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 38 1 : ℕ) : ℤ)) (ofN (gN.getD 9 []))) = true := by decide +kernel

theorem ck_pA_39 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 39 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 39 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_39 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 39 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 39 1 : ℕ) : ℤ)) (ofN (gN.getD 10 []))) = true := by decide +kernel

theorem ck_pA_40 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 40 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 40 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_40 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 40 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 40 1 : ℕ) : ℤ)) (ofN (gN.getD 11 []))) = true := by decide +kernel

theorem ck_pA_41 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 41 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 41 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_41 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 41 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 41 1 : ℕ) : ℤ)) (ofN (gN.getD 12 []))) = true := by decide +kernel

theorem ck_pA_42 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 42 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 42 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_42 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 42 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 42 1 : ℕ) : ℤ)) (ofN (gN.getD 13 []))) = true := by decide +kernel

theorem ck_pA_43 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 43 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 43 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_43 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 43 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 43 1 : ℕ) : ℤ)) (ofN (gN.getD 14 []))) = true := by decide +kernel

theorem ck_pA_44 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 44 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 44 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_44 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 44 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 44 1 : ℕ) : ℤ)) (ofN (gN.getD 15 []))) = true := by decide +kernel

theorem ck_pA_45 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 45 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 45 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_45 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 45 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 45 1 : ℕ) : ℤ)) (ofN (gN.getD 16 []))) = true := by decide +kernel

theorem ck_pA_46 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 46 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 46 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_46 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 46 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 46 1 : ℕ) : ℤ)) (ofN (gN.getD 17 []))) = true := by decide +kernel

theorem ck_pA_47 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 47 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 47 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_47 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 47 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 47 1 : ℕ) : ℤ)) (ofN (gN.getD 18 []))) = true := by decide +kernel

theorem ck_pA_48 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 48 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 48 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_48 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 48 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 48 1 : ℕ) : ℤ)) (ofN (gN.getD 19 []))) = true := by decide +kernel

theorem ck_pA_49 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 49 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 49 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_49 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 49 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 49 1 : ℕ) : ℤ)) (ofN (gN.getD 20 []))) = true := by decide +kernel

theorem ck_pA_50 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 50 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 50 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_50 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 50 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 50 1 : ℕ) : ℤ)) (ofN (gN.getD 21 []))) = true := by decide +kernel

theorem ck_pA_51 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 51 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 51 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_51 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 51 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 51 1 : ℕ) : ℤ)) (ofN (gN.getD 22 []))) = true := by decide +kernel

theorem ck_pA_52 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 52 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 52 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_52 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 52 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 52 1 : ℕ) : ℤ)) (ofN (gN.getD 23 []))) = true := by decide +kernel

theorem ck_pA_53 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 53 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 53 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_53 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 53 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 53 1 : ℕ) : ℤ)) (ofN (gN.getD 24 []))) = true := by decide +kernel

theorem ck_pA_54 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 54 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 54 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_54 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 54 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 54 1 : ℕ) : ℤ)) (ofN (gN.getD 25 []))) = true := by decide +kernel

theorem ck_pA_55 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 55 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 55 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_55 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 55 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 55 1 : ℕ) : ℤ)) (ofN (gN.getD 26 []))) = true := by decide +kernel

theorem ck_pA_56 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 56 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 56 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_56 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 56 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 56 1 : ℕ) : ℤ)) (ofN (gN.getD 27 []))) = true := by decide +kernel

theorem ck_pA_57 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 57 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 57 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_57 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 57 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 57 1 : ℕ) : ℤ)) (ofN (gN.getD 28 []))) = true := by decide +kernel

theorem ck_pA_58 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 58 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 58 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_58 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 58 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 58 1 : ℕ) : ℤ)) (ofN (gN.getD 29 []))) = true := by decide +kernel

theorem ck_pA_59 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 59 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 59 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_59 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 59 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 59 1 : ℕ) : ℤ)) (ofN (gN.getD 30 []))) = true := by decide +kernel

theorem ck_pA_60 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 60 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 60 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_60 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 60 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 60 1 : ℕ) : ℤ)) (ofN (gN.getD 31 []))) = true := by decide +kernel

theorem ck_pA_61 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 61 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 61 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_61 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 61 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 61 1 : ℕ) : ℤ)) (ofN (gN.getD 32 []))) = true := by decide +kernel

theorem ck_pA_62 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 62 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 62 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_62 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 62 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 62 1 : ℕ) : ℤ)) (ofN (gN.getD 33 []))) = true := by decide +kernel

theorem ck_pA_63 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 63 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 63 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_63 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 63 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 63 1 : ℕ) : ℤ)) (ofN (gN.getD 34 []))) = true := by decide +kernel

theorem ck_pA_64 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 64 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 64 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_64 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 64 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 64 1 : ℕ) : ℤ)) (ofN (gN.getD 35 []))) = true := by decide +kernel

theorem ck_pA_65 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 65 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 65 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_65 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 65 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 65 1 : ℕ) : ℤ)) (ofN (gN.getD 36 []))) = true := by decide +kernel

theorem ck_pA_66 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 66 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 66 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_66 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 66 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 66 1 : ℕ) : ℤ)) (ofN (gN.getD 37 []))) = true := by decide +kernel

theorem ck_pA_67 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 67 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 67 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_67 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 67 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 67 1 : ℕ) : ℤ)) (ofN (gN.getD 38 []))) = true := by decide +kernel

theorem ck_pA_68 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 68 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 68 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_68 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 68 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 68 1 : ℕ) : ℤ)) (ofN (gN.getD 39 []))) = true := by decide +kernel

theorem ck_pA_69 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 69 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 69 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_69 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 69 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 69 1 : ℕ) : ℤ)) (ofN (gN.getD 40 []))) = true := by decide +kernel

theorem ck_pA_70 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 70 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 70 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_70 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 70 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 70 1 : ℕ) : ℤ)) (ofN (gN.getD 41 []))) = true := by decide +kernel

theorem ck_pA_71 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 71 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 71 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_71 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 71 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 71 1 : ℕ) : ℤ)) (ofN (gN.getD 42 []))) = true := by decide +kernel

theorem ck_pA_72 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 72 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 72 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_72 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 72 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 72 1 : ℕ) : ℤ)) (ofN (gN.getD 43 []))) = true := by decide +kernel

theorem ck_pA_73 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 73 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 73 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_73 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 73 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 73 1 : ℕ) : ℤ)) (ofN (gN.getD 44 []))) = true := by decide +kernel

theorem ck_pA_74 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 74 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 74 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_74 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 74 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 74 1 : ℕ) : ℤ)) (ofN (gN.getD 45 []))) = true := by decide +kernel

theorem ck_pA_75 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 75 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 75 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_75 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 75 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 75 1 : ℕ) : ℤ)) (ofN (gN.getD 46 []))) = true := by decide +kernel

theorem ck_pA_76 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 76 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 76 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_76 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 76 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 76 1 : ℕ) : ℤ)) (ofN (gN.getD 47 []))) = true := by decide +kernel

theorem ck_pA_77 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 77 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 77 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_77 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 77 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 77 1 : ℕ) : ℤ)) (ofN (gN.getD 48 []))) = true := by decide +kernel

theorem ck_pA_78 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 78 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 78 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_78 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 78 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 78 1 : ℕ) : ℤ)) (ofN (gN.getD 49 []))) = true := by decide +kernel

theorem ck_pA_79 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 79 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 79 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_79 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 79 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 79 1 : ℕ) : ℤ)) (ofN (gN.getD 50 []))) = true := by decide +kernel

theorem ck_pA_80 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 80 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 80 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_80 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 80 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 80 1 : ℕ) : ℤ)) (ofN (gN.getD 51 []))) = true := by decide +kernel

theorem ck_pA_81 : checkLC 1024 (sumPL alphaDen 5 ((pgen.getD 81 []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD 81 1 : ℕ) : ℤ)) oneLC) = true := by decide +kernel

theorem ck_pB_81 : checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD 81 []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD 81 1 : ℕ) : ℤ)) (ofN (gN.getD 52 []))) = true := by decide +kernel

theorem ck_pA_left : ∀ i, i < 29 → checkLC 1024 (sumPL alphaDen 5 ((pgen.getD (i) []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD (i) 1 : ℕ) : ℤ)) (ofL (gL.getD i []))) = true := by
  intro i hi
  interval_cases i
  exacts [ck_pA_0, ck_pA_1, ck_pA_2, ck_pA_3, ck_pA_4, ck_pA_5, ck_pA_6, ck_pA_7, ck_pA_8, ck_pA_9, ck_pA_10, ck_pA_11, ck_pA_12, ck_pA_13, ck_pA_14, ck_pA_15, ck_pA_16, ck_pA_17, ck_pA_18, ck_pA_19, ck_pA_20, ck_pA_21, ck_pA_22, ck_pA_23, ck_pA_24, ck_pA_25, ck_pA_26, ck_pA_27, ck_pA_28]

theorem ck_pA_right : ∀ j, j < 53 → checkLC 1024 (sumPL alphaDen 5 ((pgen.getD (29 + j) []).map .lin) tabA)
    (smulLC (.int ((alphaDen ^ 5 * pgenDen.getD (29 + j) 1 : ℕ) : ℤ)) oneLC) = true := by
  intro j hj
  interval_cases j
  exacts [ck_pA_29, ck_pA_30, ck_pA_31, ck_pA_32, ck_pA_33, ck_pA_34, ck_pA_35, ck_pA_36, ck_pA_37, ck_pA_38, ck_pA_39, ck_pA_40, ck_pA_41, ck_pA_42, ck_pA_43, ck_pA_44, ck_pA_45, ck_pA_46, ck_pA_47, ck_pA_48, ck_pA_49, ck_pA_50, ck_pA_51, ck_pA_52, ck_pA_53, ck_pA_54, ck_pA_55, ck_pA_56, ck_pA_57, ck_pA_58, ck_pA_59, ck_pA_60, ck_pA_61, ck_pA_62, ck_pA_63, ck_pA_64, ck_pA_65, ck_pA_66, ck_pA_67, ck_pA_68, ck_pA_69, ck_pA_70, ck_pA_71, ck_pA_72, ck_pA_73, ck_pA_74, ck_pA_75, ck_pA_76, ck_pA_77, ck_pA_78, ck_pA_79, ck_pA_80, ck_pA_81]

theorem ck_pB_left : ∀ i, i < 29 → checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD (i) []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD (i) 1 : ℕ) : ℤ)) oneNC) = true := by
  intro i hi
  interval_cases i
  exacts [ck_pB_0, ck_pB_1, ck_pB_2, ck_pB_3, ck_pB_4, ck_pB_5, ck_pB_6, ck_pB_7, ck_pB_8, ck_pB_9, ck_pB_10, ck_pB_11, ck_pB_12, ck_pB_13, ck_pB_14, ck_pB_15, ck_pB_16, ck_pB_17, ck_pB_18, ck_pB_19, ck_pB_20, ck_pB_21, ck_pB_22, ck_pB_23, ck_pB_24, ck_pB_25, ck_pB_26, ck_pB_27, ck_pB_28]

theorem ck_pB_right : ∀ j, j < 53 → checkNC 1024 (sumPN betaPowDen 5 ((pgen.getD (29 + j) []).map .lin) tabB)
    (smulNC (.int ((betaPowDen ^ 5 * pgenDen.getD (29 + j) 1 : ℕ) : ℤ)) (ofN (gN.getD j []))) = true := by
  intro j hj
  interval_cases j
  exacts [ck_pB_29, ck_pB_30, ck_pB_31, ck_pB_32, ck_pB_33, ck_pB_34, ck_pB_35, ck_pB_36, ck_pB_37, ck_pB_38, ck_pB_39, ck_pB_40, ck_pB_41, ck_pB_42, ck_pB_43, ck_pB_44, ck_pB_45, ck_pB_46, ck_pB_47, ck_pB_48, ck_pB_49, ck_pB_50, ck_pB_51, ck_pB_52, ck_pB_53, ck_pB_54, ck_pB_55, ck_pB_56, ck_pB_57, ck_pB_58, ck_pB_59, ck_pB_60, ck_pB_61, ck_pB_62, ck_pB_63, ck_pB_64, ck_pB_65, ck_pB_66, ck_pB_67, ck_pB_68, ck_pB_69, ck_pB_70, ck_pB_71, ck_pB_72, ck_pB_73, ck_pB_74, ck_pB_75, ck_pB_76, ck_pB_77, ck_pB_78, ck_pB_79, ck_pB_80, ck_pB_81]

theorem pgen_length : ∀ s < 82, (pgen.getD s []).length = 6 := by decide +kernel

theorem pgenDen_ne_zero : ∀ s < 82, pgenDen.getD s 1 ≠ 0 := by decide +kernel

end FurioLombardo.Discharge.SelmerBasis.TowerChecks
