import FurioLombardo.Discharge.SelmerBasis.VDataK0P2

/-!
# Points of twist 0 at v (generated by code/selmer-local-conditions/local_data_v.gp, output local_data_v.out)

The 7 points `Dpt 0 i` as `PtData` (only `P`, `R`, `d` and the value fields; `U = X² + (P/d) X + R/d` is lane
SelmerSpan's exact `U`), their mu certificates at `F1` (`cM1`) and `F2` (`cM2`), the mu rows, the forms `QC`
(`dotRow Cg QC = CvRows`), and the relAtV bitmasks `SBB` (parities of the columns of `SB`) and `cB`.
-/
