import FurioLombardo.Discharge.SelmerBasis.VGlue
import FurioLombardo.Discharge.SelmerBasis.SquareLemmas
import FurioLombardo.Discharge.SelmerSpan.Chars
import FurioLombardo.Discharge.R7.KvBall
import FurioLombardo.Discharge.M4Box.Amat
import FurioLombardo.M2.SpecialData
import FurioLombardo.M1.ZKInt

/-!
# The place `v` of `M4Cert.σ : K21 →+* Kv`: the local facts of a `WPlace`

`Kv = ℚ₂[x]/(E)` carries the spectral norm (M4Cert/Kv.lean), `e(Kv/ℚ₂) = 3` with uniformizer `pv`,
residue field `𝔽₂`. The prime `v` of `K21` is generated by `al1` (M2/SpecialData.lean): its residue
triple modulo `8` is `(2, 5, 1)`, so `‖σ al1‖ = ‖pv‖`.

* `int_v`: every element of the zk lattice is integral at `v`;
* `normUnif_v`, `norm_two_v`, `res_v`: uniformizer `σ al1`, `‖2‖ = ‖σ al1‖ ^ 3`, residue field `𝔽₂`;
* `irreducible_q_v`: the quadratic factor `q k` stays irreducible over `Kv`.
-/

namespace FurioLombardo.Discharge.SelmerBasis.V

open Polynomial FurioLombardo.M1 FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7

/-- A uniformizer in the sense of `FurioLombardo.Vendor.Toolbox.UnitBall` is one in the sense of `NormUnif`. -/
theorem normUnif_of_isUniformizer {F : Type*} [NontriviallyNormedField F] {π : F}
    (hπ : FurioLombardo.Vendor.Toolbox.UnitBall.IsUniformizer π) : NormUnif π := by
  refine {
    ne_zero := ?_
    norm_lt_one := hπ.norm_lt_one
    disc := ?_
  }
  · -- π ≠ 0
    exact hπ.ne_zero
  · -- ∀ x : F, x ≠ 0 → ∃ n : ℤ, ‖x‖ = ‖π‖ ^ n
    intro x hx
    have hx_norm_pos : 0 < ‖x‖ := norm_pos_iff.mpr hx
    have hp_pos : 0 < ‖π‖ := hπ.norm_pos
    have hp_lt_one : ‖π‖ < 1 := hπ.norm_lt_one
    have hp_inv_gt_one : 1 < ‖π‖⁻¹ := by
      simpa [one_div] using one_lt_one_div hp_pos hp_lt_one
    -- Get n such that ‖π‖⁻¹ ^ n < ‖x‖ ≤ ‖π‖⁻¹ ^ (n+1)
    obtain ⟨n, hn⟩ := exists_mem_Ioc_zpow hx_norm_pos hp_inv_gt_one
    have h_left : ‖π‖⁻¹ ^ n < ‖x‖ := hn.1
    have h_right : ‖x‖ ≤ ‖π‖⁻¹ ^ (n + 1) := hn.2
    -- Let m = -(n+1)
    set m := -(n + 1) with hm_def
    have hp_pow_m_add_one_lt : ‖π‖ ^ (m + 1) < ‖x‖ := by
      calc
        ‖π‖ ^ (m + 1) = ‖π‖ ^ (-(n + 1) + 1) := rfl
        _ = ‖π‖ ^ (-n) := by ring
        _ = (‖π‖⁻¹) ^ n := by simp
        _ < ‖x‖ := h_left
    have hx_norm_le_pow_m : ‖x‖ ≤ ‖π‖ ^ m := by
      calc
        ‖x‖ ≤ ‖π‖⁻¹ ^ (n + 1) := h_right
        _ = ‖π‖ ^ (-(n + 1)) := by simp
        _ = ‖π‖ ^ m := rfl
    -- Now let y = x / π ^ m
    have hπ_pow_ne_zero : π ^ m ≠ 0 := zpow_ne_zero _ hπ.ne_zero
    set y := x / π ^ m with hy_def
    have hy_norm_pos : 0 < ‖y‖ := by
      rw [hy_def, norm_div]
      exact div_pos hx_norm_pos (norm_pos_iff.mpr hπ_pow_ne_zero)
    have hy_norm_le_one : ‖y‖ ≤ 1 := by
      rw [hy_def, norm_div, norm_zpow]
      exact (div_le_one_of_le₀ hx_norm_le_pow_m (zpow_nonneg (norm_nonneg _) _))
    have hp_lt_hy_norm : ‖π‖ < ‖y‖ := by
      rw [hy_def, norm_div, norm_zpow]
      -- ‖x / π ^ m‖ = ‖x‖ / ‖π‖ ^ m
      -- Need: ‖π‖ < ‖x‖ / ‖π‖ ^ m
      apply (lt_div_iff₀ (zpow_pos hp_pos m)).mpr
      -- Need: ‖π‖ * ‖π‖ ^ m < ‖x‖
      -- i.e., ‖π‖ ^ (m+1) < ‖x‖
      calc
        ‖π‖ * ‖π‖ ^ m = ‖π‖ ^ (1 : ℤ) * ‖π‖ ^ m := by simp
        _ = ‖π‖ ^ ((1 : ℤ) + m) := by rw [zpow_add₀ hp_pos.ne' (1 : ℤ) m]
        _ = ‖π‖ ^ (m + 1) := by ring
        _ < ‖x‖ := hp_pow_m_add_one_lt
    -- Now we have p < ‖y‖ ≤ 1
    by_cases hy_lt_one : ‖y‖ < 1
    · -- If ‖y‖ < 1, then hπ.norm_le_of_lt_one gives ‖y‖ ≤ ‖π‖, contradiction
      have hy_le_p : ‖y‖ ≤ ‖π‖ := hπ.norm_le_of_lt_one (y : F) hy_lt_one
      linarith
    · -- Otherwise ‖y‖ = 1
      have hy_eq_one : ‖y‖ = 1 := by linarith
      -- Then ‖x‖ = ‖y‖ * ‖π ^ m‖ = ‖π‖ ^ m
      refine ⟨m, ?_⟩
      calc
        ‖x‖ = ‖y * π ^ m‖ := by
          rw [hy_def, div_mul_cancel₀ _ hπ_pow_ne_zero]
        _ = ‖y‖ * ‖π ^ m‖ := norm_mul _ _
        _ = ‖y‖ * ‖π‖ ^ m := by rw [norm_zpow]
        _ = 1 * ‖π‖ ^ m := by rw [hy_eq_one]
        _ = ‖π‖ ^ m := by simp

/-- The zk lattice is integral at `v`. -/
theorem int_v (a : List ℤ) : ‖σ (zkE a)‖ ≤ 1 := by
  have h_int : IsIntegral ℤ (zkE a) := isIntegral_zkE a
  have h_int_σ : IsIntegral ℤ (σ (zkE a)) :=
    IsIntegral.map σ.toIntAlgHom h_int
  exact norm_le_one_of_isIntegral h_int_σ

theorem norm_al1_v : ‖σ (zkE M2.Special.al1)‖ = ‖pv‖ := by
  -- Compute ‖evZ (2, 5, 1)‖ = ‖pv‖ once and reuse
  have h_evZ_norm : ‖evZ (2, 5, 1)‖ = ‖pv‖ := by
    calc
      ‖evZ (2, 5, 1)‖ = ‖evQ (qOfT3 (2, 5, 1))‖ := by
        simpa using congrArg norm (evZ_eq_evQ (2, 5, 1))
      _ = max ‖(qOfT3 (2, 5, 1)) 0‖ (max (‖(qOfT3 (2, 5, 1)) 1‖ * ‖pv‖) (‖(qOfT3 (2, 5, 1)) 2‖ * ‖pv‖ ^ 2)) := by
        rw [norm_evQ]
      _ = max ‖(2 : ℚ_[2])‖ (max (‖(5 : ℚ_[2])‖ * ‖pv‖) (‖(1 : ℚ_[2])‖ * ‖pv‖ ^ 2)) := by
        simp [qOfT3]
      _ = max ((2 : ℝ)⁻¹) (max ((1 : ℝ) * ‖pv‖) ((1 : ℝ) * ‖pv‖ ^ 2)) := by
        have h2 : ‖(2 : ℚ_[2])‖ = (2 : ℝ)⁻¹ := by
          simpa using Padic.norm_p (p := 2)
        have h5 : ‖(5 : ℚ_[2])‖ = (1 : ℝ) := by
          have h := (Padic.norm_intCast_eq_one_iff (p := 2) (z := 5)).mpr (by decide)
          simpa using h
        have h1 : ‖(1 : ℚ_[2])‖ = (1 : ℝ) := by
          have h := (Padic.norm_intCast_eq_one_iff (p := 2) (z := 1)).mpr (by decide)
          simpa using h
        simp [h2, h5, h1]
      _ = max ((2 : ℝ)⁻¹) (max ‖pv‖ (‖pv‖ ^ 2)) := by simp
      _ = ‖pv‖ := by
        have h_lt_one : ‖pv‖ < 1 := norm_pv_lt_one
        have h_half_lt : (2⁻¹ : ℝ) < ‖pv‖ := half_lt_norm_pv
        have h_sq_lt : ‖pv‖ ^ 2 < ‖pv‖ := by
          nlinarith
        have h_max_inner : max ‖pv‖ (‖pv‖ ^ 2) = ‖pv‖ :=
          max_eq_left (by linarith)
        rw [h_max_inner]
        exact max_eq_right (by linarith)
  -- Step 1: approximate σ(zkE al1) by zres al1 with precision 3
  have h_approx : Approx (σ (zkE M2.Special.al1)) (zres M2.Special.al1) 3 := by
    set_option maxRecDepth 1000000 in
    exact approx_σ_zkE M2.Special.al1 (by decide) (n := 3) (by norm_num)
  -- Step 2: the divisibility condition for Approx.of_dvd
  have h_div : (2 : ℤ) ^ 3 ∣ (zres M2.Special.al1).1 - (2 : ℤ) ∧
              (2 : ℤ) ^ 3 ∣ (zres M2.Special.al1).2.1 - (5 : ℤ) ∧
              (2 : ℤ) ^ 3 ∣ (zres M2.Special.al1).2.2 - (1 : ℤ) := by
    set_option maxRecDepth 1000000 in
    decide
  -- Step 3: approximate σ(zkE al1) by (2, 5, 1) with precision 3
  have h_approx2 : Approx (σ (zkE M2.Special.al1)) (2, 5, 1) 3 :=
    Approx.of_dvd h_approx h_div
  -- Step 4: the norm equality from approximation, then conclude
  have h_ineq : (2⁻¹ : ℝ) ^ 3 < ‖evZ (2, 5, 1)‖ := by
    rw [h_evZ_norm]
    -- Goal: (2⁻¹ : ℝ) ^ 3 < ‖pv‖
    have h_pow_lt : ((2 : ℝ)⁻¹) ^ 3 < (2 : ℝ)⁻¹ := by
      have h_pos : 0 < (2 : ℝ)⁻¹ := by norm_num
      have h_lt_one : (2 : ℝ)⁻¹ < 1 := by norm_num
      nlinarith
    have h_half_lt : (2⁻¹ : ℝ) < ‖pv‖ := half_lt_norm_pv
    linarith
  have h_eq := FurioLombardo.Discharge.M4Box.norm_eq_of_approx h_approx2 h_ineq
  -- h_eq : ‖σ (zkE M2.Special.al1)‖ = ‖evZ (2, 5, 1)‖
  rw [h_evZ_norm] at h_eq
  exact h_eq

theorem normUnif_v : NormUnif (σ (zkE M2.Special.al1)) := by
  apply normUnif_of_isUniformizer
  refine {
    norm_pos := by
      rw [norm_al1_v]
      exact isUniformizer_pv.norm_pos
    norm_lt_one := by
      rw [norm_al1_v]
      exact isUniformizer_pv.norm_lt_one
    norm_le_of_lt_one := by
      intro x hx
      rw [norm_al1_v]
      exact isUniformizer_pv.norm_le_of_lt_one x hx
  }

theorem norm_two_v : ‖(2 : Kv)‖ = ‖σ (zkE M2.Special.al1)‖ ^ 3 := by
  rw [norm_al1_v, norm_pv_pow_three, norm_two_Kv]

/-- The residue field of `Kv` is `𝔽₂`. -/
theorem res_v : ∀ y : Kv, ‖y‖ ≤ 1 → ‖y‖ < 1 ∨ ‖y - 1‖ < 1 := by
  intro y hy
  obtain ⟨a, ha⟩ := evQ_surjective y
  rw [← ha] at hy
  rw [norm_evQ] at hy
  -- hy : max ‖a 0‖ (max (‖a 1‖ * ‖pv‖) (‖a 2‖ * ‖pv‖ ^ 2)) ≤ 1
  have ha0 : ‖a 0‖ ≤ 1 := by
    have h := le_trans (le_max_left _ _) hy
    exact h
  have hmax : max (‖a 1‖ * ‖pv‖) (‖a 2‖ * ‖pv‖ ^ 2) ≤ 1 :=
    le_trans (le_max_right _ _) hy
  have ha1pv : ‖a 1‖ * ‖pv‖ ≤ 1 :=
    le_trans (le_max_left _ _) hmax
  have ha2pv2 : ‖a 2‖ * ‖pv‖ ^ 2 ≤ 1 :=
    le_trans (le_max_right _ _) hmax
  have hpv_pos : 0 < ‖pv‖ := isUniformizer_pv.norm_pos
  have hpv_lt_one : ‖pv‖ < 1 := isUniformizer_pv.norm_lt_one
  -- From norm_two_v and norm_al1_v, we get ‖(2 : Kv)‖ = ‖pv‖ ^ 3
  -- and norm_algebraMap gives ‖(2 : Kv)‖ = ‖(2 : ℚ_[2])‖ = 1/2
  -- So ‖pv‖ ^ 3 = 1/2
  have hpv_cube : ‖pv‖ ^ 3 = (1/2 : ℝ) := by
    calc
      ‖pv‖ ^ 3 = (‖σ (zkE M2.Special.al1)‖) ^ 3 := by rw [norm_al1_v]
      _ = ‖(2 : Kv)‖ := by rw [norm_two_v]
      _ = ‖algebraMap ℚ_[2] Kv (2 : ℚ_[2])‖ := rfl
      _ = ‖(2 : ℚ_[2])‖ := by rw [FurioLombardo.Discharge.M4Cert.norm_algebraMap]
      _ = (1/2 : ℝ) := by
        simpa using Padic.norm_p (p := 2)
  have hpv_gt_half : 1/2 < ‖pv‖ := by
    -- From ‖pv‖³ = 1/2, and ‖pv‖ > 0, we get ‖pv‖ > (1/2)^(1/3) > 1/2
    -- Actually, we can use: if ‖pv‖ ≤ 1/2, then ‖pv‖³ ≤ 1/8 < 1/2, contradiction
    by_contra! hle
    have hcube : ‖pv‖ ^ 3 ≤ (1/2 : ℝ) ^ 3 := by
      nlinarith [hpv_pos]
    have h8 : (1/2 : ℝ) ^ 3 = 1/8 := by norm_num
    rw [h8] at hcube
    rw [hpv_cube] at hcube
    nlinarith
  -- Now we can bound ‖a 1‖ and ‖a 2‖
  have ha1_le_one : ‖a 1‖ ≤ 1 := by
    by_cases hzero : a 1 = 0
    · rw [hzero, norm_zero]; exact zero_le_one
    · have hnorm := Padic.norm_eq_zpow_neg_valuation hzero
      rw [hnorm] at ha1pv
      have hpos : 0 < (2 : ℝ) ^ (-((a 1).valuation : ℤ)) := by
        apply zpow_pos (by norm_num) _
      have htemp : (2 : ℝ) ^ (-((a 1).valuation : ℤ)) * (1/2) < 1 := by
        calc
          (2 : ℝ) ^ (-((a 1).valuation : ℤ)) * (1/2) < (2 : ℝ) ^ (-((a 1).valuation : ℤ)) * ‖pv‖ :=
            mul_lt_mul_of_pos_left hpv_gt_half hpos
          _ ≤ 1 := ha1pv
      have htemp2 : (2 : ℝ) ^ (-((a 1).valuation : ℤ)) < 2 := by
        nlinarith
      have htemp3 : -((a 1).valuation : ℤ) < (1 : ℤ) := by
        contrapose! htemp2
        have : (2 : ℝ) ^ (-((a 1).valuation : ℤ)) ≥ (2 : ℝ) ^ (1 : ℤ) := by
          refine zpow_le_zpow_right₀ (by norm_num) ?_
          exact htemp2
        simpa [show ((2 : ℝ) ^ (1 : ℤ) = 2) by norm_num] using this
      rw [hnorm]
      have h : (2 : ℝ) ^ (-((a 1).valuation : ℤ)) ≤ (2 : ℝ) ^ (0 : ℤ) := by
        refine zpow_le_zpow_right₀ (by norm_num) ?_
        omega
      simpa using h
  have ha2_le_one : ‖a 2‖ ≤ 1 := by
    by_cases hzero : a 2 = 0
    · rw [hzero, norm_zero]; exact zero_le_one
    · have hnorm := Padic.norm_eq_zpow_neg_valuation hzero
      rw [hnorm] at ha2pv2
      have hpv2_lt_one : ‖pv‖ ^ 2 < 1 := by
        nlinarith [hpv_pos, hpv_lt_one]
      have hpv2_gt_half : 1/2 < ‖pv‖ ^ 2 := by
        by_contra! hle
        have hcube' : ‖pv‖ ^ 3 ≤ ‖pv‖ * (1/2) := by
          nlinarith
        rw [hpv_cube] at hcube'
        nlinarith
      have hpos2 : 0 < (2 : ℝ) ^ (-((a 2).valuation : ℤ)) := by
        apply zpow_pos (by norm_num) _
      have htemp : (2 : ℝ) ^ (-((a 2).valuation : ℤ)) * (1/2) < 1 := by
        calc
          (2 : ℝ) ^ (-((a 2).valuation : ℤ)) * (1/2) < (2 : ℝ) ^ (-((a 2).valuation : ℤ)) * (‖pv‖ ^ 2) :=
            mul_lt_mul_of_pos_left hpv2_gt_half hpos2
          _ ≤ 1 := ha2pv2
      have htemp2 : (2 : ℝ) ^ (-((a 2).valuation : ℤ)) < 2 := by
        nlinarith
      have htemp3 : -((a 2).valuation : ℤ) < (1 : ℤ) := by
        contrapose! htemp2
        have : (2 : ℝ) ^ (-((a 2).valuation : ℤ)) ≥ (2 : ℝ) ^ (1 : ℤ) := by
          refine zpow_le_zpow_right₀ (by norm_num) ?_
          exact htemp2
        simpa [show ((2 : ℝ) ^ (1 : ℤ) = 2) by norm_num] using this
      have htemp4 : -1 ≤ ((a 2).valuation : ℤ) := by
        omega
      rw [hnorm]
      have h : (2 : ℝ) ^ (-((a 2).valuation : ℤ)) ≤ (2 : ℝ) ^ (0 : ℤ) := by
        refine zpow_le_zpow_right₀ (by norm_num) ?_
        omega
      simpa using h
  -- Now we have ‖a 0‖ ≤ 1, ‖a 1‖ ≤ 1, ‖a 2‖ ≤ 1
  -- For a 0, either ‖a 0‖ < 1 or ‖a 0 - 1‖ < 1 (since a 0 ∈ ℤ_[2] and residue field is 𝔽₂)
  have ha0_cases : ‖a 0‖ < 1 ∨ ‖a 0 - 1‖ < 1 := by
    -- a 0 has norm ≤ 1, so it's in ℤ_[2]
    let x : ℤ_[2] := ⟨a 0, ha0⟩
    obtain ⟨n, hn_lt, hn_mem⟩ := PadicInt.exists_mem_range x
    -- n < 2, so n = 0 or n = 1
    have hn_cases : n = 0 ∨ n = 1 := by
      have : n ≤ 1 := by omega
      omega
    rcases hn_cases with (hn0 | hn1)
    · -- n = 0, so x ∈ maximalIdeal, hence ‖x‖ < 1
      have hx_mem : x ∈ IsLocalRing.maximalIdeal ℤ_[2] := by
        simpa [hn0] using hn_mem
      rw [PadicInt.maximalIdeal_eq_span_p] at hx_mem
      rw [Ideal.mem_span_singleton] at hx_mem
      have hnorm : ‖x‖ < 1 := by
        rw [PadicInt.norm_lt_one_iff_dvd]
        exact hx_mem
      left
      simpa [x] using hnorm
    · -- n = 1, so x - 1 ∈ maximalIdeal, hence ‖x - 1‖ < 1
      have hx_mem : x - 1 ∈ IsLocalRing.maximalIdeal ℤ_[2] := by
        simpa [hn1] using hn_mem
      rw [PadicInt.maximalIdeal_eq_span_p] at hx_mem
      rw [Ideal.mem_span_singleton] at hx_mem
      have hnorm : ‖x - 1‖ < 1 := by
        rw [PadicInt.norm_lt_one_iff_dvd]
        exact hx_mem
      right
      have hnorm' : ‖(x : ℚ_[2]) - 1‖ < 1 := by
        simpa [PadicInt.norm_def] using hnorm
      have hx_coe : (x : ℚ_[2]) = a 0 := rfl
      simpa [hx_coe] using hnorm'
  -- Now we analyze the two cases
  rcases ha0_cases with (ha0_lt_one | ha0_sub_one_lt_one)
  · -- Case ‖a 0‖ < 1
    left
    rw [← ha, norm_evQ]
    -- max ‖a 0‖ (max (‖a 1‖ * ‖pv‖) (‖a 2‖ * ‖pv‖ ^ 2)) < 1
    -- We know ‖a 0‖ < 1, and we need the max part < 1
    have hz_lt_one : max (‖a 1‖ * ‖pv‖) (‖a 2‖ * ‖pv‖ ^ 2) < 1 := by
      -- From ha1_le_one and ha2_le_one, we have ‖a 1‖ ≤ 1 and ‖a 2‖ ≤ 1
      -- So ‖a 1‖ * ‖pv‖ ≤ ‖pv‖ < 1 and ‖a 2‖ * ‖pv‖ ^ 2 ≤ ‖pv‖ ^ 2 < ‖pv‖ < 1
      have h1 : ‖a 1‖ * ‖pv‖ ≤ ‖pv‖ := by
        nlinarith [norm_nonneg (a 1), hpv_pos]
      have h2 : ‖a 2‖ * ‖pv‖ ^ 2 ≤ ‖pv‖ ^ 2 := by
        nlinarith [norm_nonneg (a 2)]
      have hpv2_lt_one : ‖pv‖ ^ 2 < 1 := by
        nlinarith
      have hmax_lt_one : max (‖a 1‖ * ‖pv‖) (‖a 2‖ * ‖pv‖ ^ 2) < 1 := by
        apply max_lt
        · calc
            ‖a 1‖ * ‖pv‖ ≤ ‖pv‖ := h1
            _ < 1 := hpv_lt_one
        · calc
            ‖a 2‖ * ‖pv‖ ^ 2 ≤ ‖pv‖ ^ 2 := h2
            _ < 1 := hpv2_lt_one
      exact hmax_lt_one
    apply max_lt ha0_lt_one hz_lt_one
  · -- Case ‖a 0 - 1‖ < 1
    right
    -- Need to show ‖evQ a - 1‖ < 1
    -- evQ a - 1 = algebraMap ℚ_[2] Kv (a 0 - 1) + algebraMap ℚ_[2] Kv (a 1) * pv + algebraMap ℚ_[2] Kv (a 2) * pv ^ 2
    -- This is evQ a' where a' 0 = a 0 - 1, a' 1 = a 1, a' 2 = a 2
    -- So we can apply the same formula
    -- Use norm_evQ on a modified a where a 0 is replaced by a 0 - 1
    let a' : Fin 3 → ℚ_[2] := fun i => match i with | 0 => a 0 - 1 | 1 => a 1 | 2 => a 2
    have h_eq : evQ a - 1 = evQ a' := by
      dsimp [evQ, a']
      simp only [map_sub, map_one]
      abel
    have h_norm : ‖evQ a - 1‖ = ‖evQ a'‖ := by rw [h_eq]
    rw [← ha, h_norm, norm_evQ]
    dsimp [a']
    have hz_lt_one : max (‖a 1‖ * ‖pv‖) (‖a 2‖ * ‖pv‖ ^ 2) < 1 := by
      have h1 : ‖a 1‖ * ‖pv‖ ≤ ‖pv‖ := by
        nlinarith [norm_nonneg (a 1), hpv_pos]
      have h2 : ‖a 2‖ * ‖pv‖ ^ 2 ≤ ‖pv‖ ^ 2 := by
        nlinarith [norm_nonneg (a 2)]
      have hpv2_lt_one : ‖pv‖ ^ 2 < 1 := by
        nlinarith
      apply max_lt
      · calc
          ‖a 1‖ * ‖pv‖ ≤ ‖pv‖ := h1
          _ < 1 := hpv_lt_one
      · calc
          ‖a 2‖ * ‖pv‖ ^ 2 ≤ ‖pv‖ ^ 2 := h2
          _ < 1 := hpv2_lt_one
    apply max_lt ha0_sub_one_lt_one hz_lt_one

/-- `q k` is irreducible over `Kv` (its discriminant `d k` is not a square there). -/
theorem irreducible_q_v (k : Fin 2) : Irreducible ((M3a.Bruin.q k).map σ) := by
  let p := (FurioLombardo.Discharge.M3a.Bruin.q k).map σ
  have hp_monic : p.Monic := by
    dsimp [p]
    exact (FurioLombardo.Discharge.M3a.Bruin.q_monic k).map σ
  have hp_natDegree : p.natDegree = 2 := by
    dsimp [p]
    have hmonic : (FurioLombardo.Discharge.M3a.Bruin.q k).Monic := FurioLombardo.Discharge.M3a.Bruin.q_monic k
    have hlead : σ ((FurioLombardo.Discharge.M3a.Bruin.q k).leadingCoeff) ≠ 0 := by
      rw [hmonic.leadingCoeff]
      simp
    rw [Polynomial.natDegree_map_of_leadingCoeff_ne_zero σ hlead, FurioLombardo.Discharge.M3a.Bruin.q_natDegree k]
  have hp_two_ne_zero : (2 : Kv) ≠ 0 := by
    exact two_ne_zero
  have hp_disc_not_square : ¬ IsSquare (p.coeff 1 ^ 2 - 4 * p.coeff 0) := by
    dsimp [p]
    have hcoeff1 : (((FurioLombardo.Discharge.M3a.Bruin.q k).map σ).coeff 1) = σ ((FurioLombardo.Discharge.M3a.Bruin.q k).coeff 1) := by
      simp
    have hcoeff0 : (((FurioLombardo.Discharge.M3a.Bruin.q k).map σ).coeff 0) = σ ((FurioLombardo.Discharge.M3a.Bruin.q k).coeff 0) := by
      simp
    rw [hcoeff1, hcoeff0]
    have hd_eq : σ ((FurioLombardo.Discharge.M3a.Bruin.q k).coeff 1) ^ 2 - 4 * σ ((FurioLombardo.Discharge.M3a.Bruin.q k).coeff 0) = σ (FurioLombardo.Discharge.M3a.Bruin.d k) := by
      dsimp [FurioLombardo.Discharge.M3a.Bruin.d]
      simp [map_sub, map_pow, map_mul, map_ofNat]
    rw [hd_eq]
    exact FurioLombardo.Discharge.M3a.Bruin.d_not_isSquare_Kv k
  exact irreducible_of_disc hp_monic hp_natDegree hp_two_ne_zero hp_disc_not_square

end FurioLombardo.Discharge.SelmerBasis.V
