import FurioLombardo.Discharge.SelmerBasis.W2Data

/-!
# Kernel checks of the model at w2 (generated by code/selmer-local-conditions/kernel_checks_w12.sh)

The data `E` of `K_w2` (the powers of `al`), `SR` (`3 ρ² = -ε`) and `SU` (the square root of `iL2 (4 eN)`).
Every statement is closed by `decide +kernel`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.W2

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower
  FurioLombardo.Discharge.SelmerBasis.W2U

theorem ck_E : E.ok = true := by decide +kernel

theorem ck_SR : SR.ok E = true := by decide +kernel

theorem ck_SU : SU.ok E SR = true := by decide +kernel

end FurioLombardo.Discharge.SelmerBasis.W2
