import FurioLombardo.Discharge.SelmerBasis.W2Data
import FurioLombardo.Discharge.SelmerBasis.W2DataK0

/-!
# Kernel checks of the points of twist 0 at w2 (generated by code/selmer-local-conditions/kernel_checks_w12.sh)

`ck_pt_i`: the point data `pt_i` (`okD`, `okZ` for `4 fRev_0`, `okT`); `ck_M1_i`, `ck_M2_i`, `ck_M3_i`:
the square certificates of `Λ² U_i` at the components 0, 1, 2.
Every statement is closed by `decide +kernel`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.W2

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower
  FurioLombardo.Discharge.SelmerBasis.W2U

namespace K0

theorem ck_pt_0 : (pts.getD 0 default).okD E = true ∧ (pts.getD 0 default).okZ E (gW 0) = true ∧
    (pts.getD 0 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_0 : certOKU1 E (X0L2 E SR (ofL (pts.getD 0 default).tL))
    (X1L2 E SR (ofL (pts.getD 0 default).tL)) (cM1.getD 0 default) = true := by
  decide +kernel

theorem ck_M2_0 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 0 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 0 default).tN) true) (cM2.getD 0 default) = true := by
  decide +kernel

theorem ck_M3_0 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 0 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 0 default).tN) false) (cM3.getD 0 default) = true := by
  decide +kernel

theorem ck_pt_1 : (pts.getD 1 default).okD E = true ∧ (pts.getD 1 default).okZ E (gW 0) = true ∧
    (pts.getD 1 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_1 : certOKU1 E (X0L2 E SR (ofL (pts.getD 1 default).tL))
    (X1L2 E SR (ofL (pts.getD 1 default).tL)) (cM1.getD 1 default) = true := by
  decide +kernel

theorem ck_M2_1 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 1 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 1 default).tN) true) (cM2.getD 1 default) = true := by
  decide +kernel

theorem ck_M3_1 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 1 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 1 default).tN) false) (cM3.getD 1 default) = true := by
  decide +kernel

theorem ck_pt_2 : (pts.getD 2 default).okD E = true ∧ (pts.getD 2 default).okZ E (gW 0) = true ∧
    (pts.getD 2 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_2 : certOKU1 E (X0L2 E SR (ofL (pts.getD 2 default).tL))
    (X1L2 E SR (ofL (pts.getD 2 default).tL)) (cM1.getD 2 default) = true := by
  decide +kernel

theorem ck_M2_2 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 2 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 2 default).tN) true) (cM2.getD 2 default) = true := by
  decide +kernel

theorem ck_M3_2 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 2 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 2 default).tN) false) (cM3.getD 2 default) = true := by
  decide +kernel

theorem ck_pt_3 : (pts.getD 3 default).okD E = true ∧ (pts.getD 3 default).okZ E (gW 0) = true ∧
    (pts.getD 3 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_3 : certOKU1 E (X0L2 E SR (ofL (pts.getD 3 default).tL))
    (X1L2 E SR (ofL (pts.getD 3 default).tL)) (cM1.getD 3 default) = true := by
  decide +kernel

theorem ck_M2_3 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 3 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 3 default).tN) true) (cM2.getD 3 default) = true := by
  decide +kernel

theorem ck_M3_3 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 3 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 3 default).tN) false) (cM3.getD 3 default) = true := by
  decide +kernel

theorem ck_pt_4 : (pts.getD 4 default).okD E = true ∧ (pts.getD 4 default).okZ E (gW 0) = true ∧
    (pts.getD 4 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_4 : certOKU1 E (X0L2 E SR (ofL (pts.getD 4 default).tL))
    (X1L2 E SR (ofL (pts.getD 4 default).tL)) (cM1.getD 4 default) = true := by
  decide +kernel

theorem ck_M2_4 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 4 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 4 default).tN) true) (cM2.getD 4 default) = true := by
  decide +kernel

theorem ck_M3_4 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 4 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 4 default).tN) false) (cM3.getD 4 default) = true := by
  decide +kernel

theorem ck_pt_5 : (pts.getD 5 default).okD E = true ∧ (pts.getD 5 default).okZ E (gW 0) = true ∧
    (pts.getD 5 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_5 : certOKU1 E (X0L2 E SR (ofL (pts.getD 5 default).tL))
    (X1L2 E SR (ofL (pts.getD 5 default).tL)) (cM1.getD 5 default) = true := by
  decide +kernel

theorem ck_M2_5 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 5 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 5 default).tN) true) (cM2.getD 5 default) = true := by
  decide +kernel

theorem ck_M3_5 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 5 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 5 default).tN) false) (cM3.getD 5 default) = true := by
  decide +kernel

theorem ck_pt_6 : (pts.getD 6 default).okD E = true ∧ (pts.getD 6 default).okZ E (gW 0) = true ∧
    (pts.getD 6 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_6 : certOKU1 E (X0L2 E SR (ofL (pts.getD 6 default).tL))
    (X1L2 E SR (ofL (pts.getD 6 default).tL)) (cM1.getD 6 default) = true := by
  decide +kernel

theorem ck_M2_6 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 6 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 6 default).tN) true) (cM2.getD 6 default) = true := by
  decide +kernel

theorem ck_M3_6 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 6 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 6 default).tN) false) (cM3.getD 6 default) = true := by
  decide +kernel

theorem ck_pt_7 : (pts.getD 7 default).okD E = true ∧ (pts.getD 7 default).okZ E (gW 0) = true ∧
    (pts.getD 7 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_7 : certOKU1 E (X0L2 E SR (ofL (pts.getD 7 default).tL))
    (X1L2 E SR (ofL (pts.getD 7 default).tL)) (cM1.getD 7 default) = true := by
  decide +kernel

theorem ck_M2_7 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 7 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 7 default).tN) true) (cM2.getD 7 default) = true := by
  decide +kernel

theorem ck_M3_7 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 7 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 7 default).tN) false) (cM3.getD 7 default) = true := by
  decide +kernel

theorem ck_pt_8 : (pts.getD 8 default).okD E = true ∧ (pts.getD 8 default).okZ E (gW 0) = true ∧
    (pts.getD 8 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_8 : certOKU1 E (X0L2 E SR (ofL (pts.getD 8 default).tL))
    (X1L2 E SR (ofL (pts.getD 8 default).tL)) (cM1.getD 8 default) = true := by
  decide +kernel

theorem ck_M2_8 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 8 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 8 default).tN) true) (cM2.getD 8 default) = true := by
  decide +kernel

theorem ck_M3_8 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 8 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 8 default).tN) false) (cM3.getD 8 default) = true := by
  decide +kernel

theorem ck_pt_9 : (pts.getD 9 default).okD E = true ∧ (pts.getD 9 default).okZ E (gW 0) = true ∧
    (pts.getD 9 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_9 : certOKU1 E (X0L2 E SR (ofL (pts.getD 9 default).tL))
    (X1L2 E SR (ofL (pts.getD 9 default).tL)) (cM1.getD 9 default) = true := by
  decide +kernel

theorem ck_M2_9 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 9 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 9 default).tN) true) (cM2.getD 9 default) = true := by
  decide +kernel

theorem ck_M3_9 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 9 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 9 default).tN) false) (cM3.getD 9 default) = true := by
  decide +kernel

theorem ck_pt_10 : (pts.getD 10 default).okD E = true ∧ (pts.getD 10 default).okZ E (gW 0) = true ∧
    (pts.getD 10 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_10 : certOKU1 E (X0L2 E SR (ofL (pts.getD 10 default).tL))
    (X1L2 E SR (ofL (pts.getD 10 default).tL)) (cM1.getD 10 default) = true := by
  decide +kernel

theorem ck_M2_10 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 10 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 10 default).tN) true) (cM2.getD 10 default) = true := by
  decide +kernel

theorem ck_M3_10 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 10 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 10 default).tN) false) (cM3.getD 10 default) = true := by
  decide +kernel

theorem ck_pt_11 : (pts.getD 11 default).okD E = true ∧ (pts.getD 11 default).okZ E (gW 0) = true ∧
    (pts.getD 11 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_11 : certOKU1 E (X0L2 E SR (ofL (pts.getD 11 default).tL))
    (X1L2 E SR (ofL (pts.getD 11 default).tL)) (cM1.getD 11 default) = true := by
  decide +kernel

theorem ck_M2_11 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 11 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 11 default).tN) true) (cM2.getD 11 default) = true := by
  decide +kernel

theorem ck_M3_11 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 11 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 11 default).tN) false) (cM3.getD 11 default) = true := by
  decide +kernel

theorem ck_pt_12 : (pts.getD 12 default).okD E = true ∧ (pts.getD 12 default).okZ E (gW 0) = true ∧
    (pts.getD 12 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_12 : certOKU1 E (X0L2 E SR (ofL (pts.getD 12 default).tL))
    (X1L2 E SR (ofL (pts.getD 12 default).tL)) (cM1.getD 12 default) = true := by
  decide +kernel

theorem ck_M2_12 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 12 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 12 default).tN) true) (cM2.getD 12 default) = true := by
  decide +kernel

theorem ck_M3_12 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 12 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 12 default).tN) false) (cM3.getD 12 default) = true := by
  decide +kernel

theorem ck_pt_13 : (pts.getD 13 default).okD E = true ∧ (pts.getD 13 default).okZ E (gW 0) = true ∧
    (pts.getD 13 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_13 : certOKU1 E (X0L2 E SR (ofL (pts.getD 13 default).tL))
    (X1L2 E SR (ofL (pts.getD 13 default).tL)) (cM1.getD 13 default) = true := by
  decide +kernel

theorem ck_M2_13 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 13 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 13 default).tN) true) (cM2.getD 13 default) = true := by
  decide +kernel

theorem ck_M3_13 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 13 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 13 default).tN) false) (cM3.getD 13 default) = true := by
  decide +kernel

theorem ck_pt_14 : (pts.getD 14 default).okD E = true ∧ (pts.getD 14 default).okZ E (gW 0) = true ∧
    (pts.getD 14 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_14 : certOKU1 E (X0L2 E SR (ofL (pts.getD 14 default).tL))
    (X1L2 E SR (ofL (pts.getD 14 default).tL)) (cM1.getD 14 default) = true := by
  decide +kernel

theorem ck_M2_14 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 14 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 14 default).tN) true) (cM2.getD 14 default) = true := by
  decide +kernel

theorem ck_M3_14 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 14 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 14 default).tN) false) (cM3.getD 14 default) = true := by
  decide +kernel

theorem ck_pt_15 : (pts.getD 15 default).okD E = true ∧ (pts.getD 15 default).okZ E (gW 0) = true ∧
    (pts.getD 15 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_15 : certOKU1 E (X0L2 E SR (ofL (pts.getD 15 default).tL))
    (X1L2 E SR (ofL (pts.getD 15 default).tL)) (cM1.getD 15 default) = true := by
  decide +kernel

theorem ck_M2_15 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 15 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 15 default).tN) true) (cM2.getD 15 default) = true := by
  decide +kernel

theorem ck_M3_15 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 15 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 15 default).tN) false) (cM3.getD 15 default) = true := by
  decide +kernel

theorem ck_pt_16 : (pts.getD 16 default).okD E = true ∧ (pts.getD 16 default).okZ E (gW 0) = true ∧
    (pts.getD 16 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_16 : certOKU1 E (X0L2 E SR (ofL (pts.getD 16 default).tL))
    (X1L2 E SR (ofL (pts.getD 16 default).tL)) (cM1.getD 16 default) = true := by
  decide +kernel

theorem ck_M2_16 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 16 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 16 default).tN) true) (cM2.getD 16 default) = true := by
  decide +kernel

theorem ck_M3_16 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 16 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 16 default).tN) false) (cM3.getD 16 default) = true := by
  decide +kernel

theorem ck_pt_17 : (pts.getD 17 default).okD E = true ∧ (pts.getD 17 default).okZ E (gW 0) = true ∧
    (pts.getD 17 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_17 : certOKU1 E (X0L2 E SR (ofL (pts.getD 17 default).tL))
    (X1L2 E SR (ofL (pts.getD 17 default).tL)) (cM1.getD 17 default) = true := by
  decide +kernel

theorem ck_M2_17 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 17 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 17 default).tN) true) (cM2.getD 17 default) = true := by
  decide +kernel

theorem ck_M3_17 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 17 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 17 default).tN) false) (cM3.getD 17 default) = true := by
  decide +kernel

theorem ck_pt_18 : (pts.getD 18 default).okD E = true ∧ (pts.getD 18 default).okZ E (gW 0) = true ∧
    (pts.getD 18 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_18 : certOKU1 E (X0L2 E SR (ofL (pts.getD 18 default).tL))
    (X1L2 E SR (ofL (pts.getD 18 default).tL)) (cM1.getD 18 default) = true := by
  decide +kernel

theorem ck_M2_18 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 18 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 18 default).tN) true) (cM2.getD 18 default) = true := by
  decide +kernel

theorem ck_M3_18 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 18 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 18 default).tN) false) (cM3.getD 18 default) = true := by
  decide +kernel

theorem ck_pt_19 : (pts.getD 19 default).okD E = true ∧ (pts.getD 19 default).okZ E (gW 0) = true ∧
    (pts.getD 19 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_19 : certOKU1 E (X0L2 E SR (ofL (pts.getD 19 default).tL))
    (X1L2 E SR (ofL (pts.getD 19 default).tL)) (cM1.getD 19 default) = true := by
  decide +kernel

theorem ck_M2_19 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 19 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 19 default).tN) true) (cM2.getD 19 default) = true := by
  decide +kernel

theorem ck_M3_19 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 19 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 19 default).tN) false) (cM3.getD 19 default) = true := by
  decide +kernel

theorem ck_pt_20 : (pts.getD 20 default).okD E = true ∧ (pts.getD 20 default).okZ E (gW 0) = true ∧
    (pts.getD 20 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_20 : certOKU1 E (X0L2 E SR (ofL (pts.getD 20 default).tL))
    (X1L2 E SR (ofL (pts.getD 20 default).tL)) (cM1.getD 20 default) = true := by
  decide +kernel

theorem ck_M2_20 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 20 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 20 default).tN) true) (cM2.getD 20 default) = true := by
  decide +kernel

theorem ck_M3_20 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 20 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 20 default).tN) false) (cM3.getD 20 default) = true := by
  decide +kernel

theorem ck_pt_21 : (pts.getD 21 default).okD E = true ∧ (pts.getD 21 default).okZ E (gW 0) = true ∧
    (pts.getD 21 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_21 : certOKU1 E (X0L2 E SR (ofL (pts.getD 21 default).tL))
    (X1L2 E SR (ofL (pts.getD 21 default).tL)) (cM1.getD 21 default) = true := by
  decide +kernel

theorem ck_M2_21 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 21 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 21 default).tN) true) (cM2.getD 21 default) = true := by
  decide +kernel

theorem ck_M3_21 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 21 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 21 default).tN) false) (cM3.getD 21 default) = true := by
  decide +kernel

theorem ck_pt_22 : (pts.getD 22 default).okD E = true ∧ (pts.getD 22 default).okZ E (gW 0) = true ∧
    (pts.getD 22 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_22 : certOKU1 E (X0L2 E SR (ofL (pts.getD 22 default).tL))
    (X1L2 E SR (ofL (pts.getD 22 default).tL)) (cM1.getD 22 default) = true := by
  decide +kernel

theorem ck_M2_22 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 22 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 22 default).tN) true) (cM2.getD 22 default) = true := by
  decide +kernel

theorem ck_M3_22 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 22 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 22 default).tN) false) (cM3.getD 22 default) = true := by
  decide +kernel

theorem ck_pt_23 : (pts.getD 23 default).okD E = true ∧ (pts.getD 23 default).okZ E (gW 0) = true ∧
    (pts.getD 23 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_23 : certOKU1 E (X0L2 E SR (ofL (pts.getD 23 default).tL))
    (X1L2 E SR (ofL (pts.getD 23 default).tL)) (cM1.getD 23 default) = true := by
  decide +kernel

theorem ck_M2_23 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 23 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 23 default).tN) true) (cM2.getD 23 default) = true := by
  decide +kernel

theorem ck_M3_23 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 23 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 23 default).tN) false) (cM3.getD 23 default) = true := by
  decide +kernel

theorem ck_pt_24 : (pts.getD 24 default).okD E = true ∧ (pts.getD 24 default).okZ E (gW 0) = true ∧
    (pts.getD 24 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_24 : certOKU1 E (X0L2 E SR (ofL (pts.getD 24 default).tL))
    (X1L2 E SR (ofL (pts.getD 24 default).tL)) (cM1.getD 24 default) = true := by
  decide +kernel

theorem ck_M2_24 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 24 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 24 default).tN) true) (cM2.getD 24 default) = true := by
  decide +kernel

theorem ck_M3_24 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 24 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 24 default).tN) false) (cM3.getD 24 default) = true := by
  decide +kernel

theorem ck_pt_25 : (pts.getD 25 default).okD E = true ∧ (pts.getD 25 default).okZ E (gW 0) = true ∧
    (pts.getD 25 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_25 : certOKU1 E (X0L2 E SR (ofL (pts.getD 25 default).tL))
    (X1L2 E SR (ofL (pts.getD 25 default).tL)) (cM1.getD 25 default) = true := by
  decide +kernel

theorem ck_M2_25 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 25 default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD 25 default).tN) true) (cM2.getD 25 default) = true := by
  decide +kernel

theorem ck_M3_25 : certOKU1 E (X0N2 E SR SU (ofN (pts.getD 25 default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD 25 default).tN) false) (cM3.getD 25 default) = true := by
  decide +kernel

theorem ck_pt : ∀ i, i < 26 → (pts.getD i default).okD E = true ∧ (pts.getD i default).okZ E (gW 0) = true ∧
    (pts.getD i default).okT = true := by
  intro i hi
  interval_cases i
  exacts [ck_pt_0, ck_pt_1, ck_pt_2, ck_pt_3, ck_pt_4, ck_pt_5, ck_pt_6, ck_pt_7, ck_pt_8, ck_pt_9, ck_pt_10, ck_pt_11, ck_pt_12, ck_pt_13, ck_pt_14, ck_pt_15, ck_pt_16, ck_pt_17, ck_pt_18, ck_pt_19, ck_pt_20, ck_pt_21, ck_pt_22, ck_pt_23, ck_pt_24, ck_pt_25]

theorem ck_M1 : ∀ i, i < 26 → certOKU1 E (X0L2 E SR (ofL (pts.getD i default).tL))
    (X1L2 E SR (ofL (pts.getD i default).tL)) (cM1.getD i default) = true := by
  intro i hi
  interval_cases i
  exacts [ck_M1_0, ck_M1_1, ck_M1_2, ck_M1_3, ck_M1_4, ck_M1_5, ck_M1_6, ck_M1_7, ck_M1_8, ck_M1_9, ck_M1_10, ck_M1_11, ck_M1_12, ck_M1_13, ck_M1_14, ck_M1_15, ck_M1_16, ck_M1_17, ck_M1_18, ck_M1_19, ck_M1_20, ck_M1_21, ck_M1_22, ck_M1_23, ck_M1_24, ck_M1_25]

theorem ck_M2 : ∀ i, i < 26 → certOKU1 E (X0N2 E SR SU (ofN (pts.getD i default).tN) true)
    (X1N2 E SR SU (ofN (pts.getD i default).tN) true) (cM2.getD i default) = true := by
  intro i hi
  interval_cases i
  exacts [ck_M2_0, ck_M2_1, ck_M2_2, ck_M2_3, ck_M2_4, ck_M2_5, ck_M2_6, ck_M2_7, ck_M2_8, ck_M2_9, ck_M2_10, ck_M2_11, ck_M2_12, ck_M2_13, ck_M2_14, ck_M2_15, ck_M2_16, ck_M2_17, ck_M2_18, ck_M2_19, ck_M2_20, ck_M2_21, ck_M2_22, ck_M2_23, ck_M2_24, ck_M2_25]

theorem ck_M3 : ∀ i, i < 26 → certOKU1 E (X0N2 E SR SU (ofN (pts.getD i default).tN) false)
    (X1N2 E SR SU (ofN (pts.getD i default).tN) false) (cM3.getD i default) = true := by
  intro i hi
  interval_cases i
  exacts [ck_M3_0, ck_M3_1, ck_M3_2, ck_M3_3, ck_M3_4, ck_M3_5, ck_M3_6, ck_M3_7, ck_M3_8, ck_M3_9, ck_M3_10, ck_M3_11, ck_M3_12, ck_M3_13, ck_M3_14, ck_M3_15, ck_M3_16, ck_M3_17, ck_M3_18, ck_M3_19, ck_M3_20, ck_M3_21, ck_M3_22, ck_M3_23, ck_M3_24, ck_M3_25]

end K0

end FurioLombardo.Discharge.SelmerBasis.W2
