import FurioLombardo.Discharge.SelmerBasis.W2DataK1P4

/-!
# Points of twist 1 at w2 (generated by code/selmer-local-conditions/local_data_w12.gp, output local_data_w12.out)

The 26 points (`pts`, PointGen.lean's `PtData`), their mu certificates at the three components (`cM1`, `cM2`, `cM3`),
the mu rows `Amu`, the rows `QC` annihilating kappa and mu (read on `Cg` they are `Assembly.C2Rows 1`) and the left
inverse `T` of the forms `QI` on the mu coordinates.
-/
