import FurioLombardo.Discharge.SelmerBasis.W2Unram
import FurioLombardo.Discharge.SelmerBasis.PlaceWRows
import FurioLombardo.Discharge.SelmerBasis.GlobalGens
import FurioLombardo.Discharge.SelmerBasis.AssemblyGen
import FurioLombardo.Discharge.SelmerBasis.Count.AtW2

/-!
# The place w2: `IndepImage`, `ImageIn` and `CoordCond` from the data and its kernel checks (lane selmer-w2)

`σw = adicCoe w2 : K21 →+* K_w2` (`e = 12`, residue field `𝔽₂`). The three components of `K_w2[T]/(fRev k)`
are `F = QF Kw (-1) 1` (W2Unram.lean): `ev3 k` sends `T` to `iL2 α`, `iN2 (+) β`, `iN2 (-) β`, and `evG k`
maps to `G = Fin 3 → Fˣ` with the basis `bW` of `G / G²` (`3 (2e + 2)` elements).

The data `D : Data` (the place model, the certificates of the scalars `dyGen al l`, of the 82 global
generators and of the points, and the `𝔽₂` forms) and their kernel checks `Facts D` are hypotheses here;
W2Place.lean supplies them (data generated by code/selmer-local-conditions/local_data_w12.gp).

* `D2 hF k i`: the points (`PtData.exists_point`), `μ(D2 k i) = [U(T)]`;
* `indepImage_w2`, `imageIn_w2` (with `Count.countBound_w2`), `coordCond_w2_range`: the local Props, the
  coordinate matrix `Cmat D k` being the forms `QC` read on the generator rows.
-/

set_option linter.unusedSectionVars false

namespace FurioLombardo.Discharge.SelmerBasis.W2G

open Polynomial NumberField FurioLombardo.M1 FurioLombardo.M3a.Genus2 FurioLombardo.Discharge.M3a
  FurioLombardo.Discharge.M3a.Bruin FurioLombardo.Discharge.M3b FurioLombardo.Discharge.SelmerBasis
  FurioLombardo.Discharge.SelmerBasis.Tower FurioLombardo.Discharge.SelmerBasis.GlobalK21
  FurioLombardo.Discharge.SelmerBasis.W2U
open scoped FurioLombardo.Discharge.SelmerBasis.Adic

/-! ## The place -/

/-- The completion at `w2`. -/
abbrev Kw : Type := w2.adicCompletion K21

/-- `K21 → K_w2`. -/
noncomputable abbrev σw : K21 →+* Kw := adicCoe w2

instance instNoRoot : Fact (∀ r : Kw, r ^ 2 ≠ -1 + 1 * r) := ⟨noRoot_model res_w2⟩

/-- The component field. -/
abbrev F : Type := QF Kw (-1) 1

instance goodSextic (k : Fin 2) : GoodSextic ((fRev k).map σw) :=
  goodSextic_fRev_map σw k (by rw [fRev_leadingCoeff]; exact Count.not_isSquare_c_w2 k)

theorem int_w2 (a : List ℤ) : ‖σw (zkE a)‖ ≤ 1 := by
  have h := primeOf_norm_le (hP := isPrime_of_absNorm_two absNorm_eltO_al2)
    (hα := elt_ne_zero_of_absNorm absNorm_eltO_al2 two_ne_zero) (x := zkE a) (n := 0)
    (a := eltO a) (b := 1) (b' := 1) (c' := 0) (by ring) (by simp [coe_elt])
  rw [zpow_zero] at h
  exact h

/-! ## Data and kernel facts -/

/-- The data at `w2`. -/
structure Data where
  E : EisData
  SR : RhoData
  SU : SqrtU
  cK : List UCert1
  Akap : List ℕ
  cL : List UCert1
  cN1 : List UCert1
  cN2 : List UCert1
  Cg : List ℕ
  nQI : ℕ
  QI : List ℕ
  pts : Fin 2 → List PtData
  cM : Fin 2 → Fin 3 → List UCert1
  Amu : Fin 2 → List ℕ
  T : Fin 2 → List ℕ
  QC : Fin 2 → List ℕ

/-- The number of bits of a component. -/
abbrev Data.m (D : Data) : ℕ := 2 * D.E.e + 2

/-- The number of bits of a row. -/
abbrev Data.nb (D : Data) : ℕ := 3 * (2 * D.E.e + 2)

/-- The kernel facts of the data. -/
structure Facts (D : Data) : Prop where
  wp : WPlace σw D.E
  sr : D.SR.ok D.E = true
  su : D.SU.ok D.E D.SR = true
  lenK : 2 * D.E.e + 1 ≤ D.E.alPow.length
  ckK : ∀ i, i < 2 * D.E.e + 1 → certOKU1 D.E (kapX D.E i) (.int 0) (D.cK.getD i default) = true
  akBits : ∀ (l : Fin (2 * D.E.e + 1)) (c : Fin 3),
    (D.Akap.getD l 0 >>> ((2 * D.E.e + 2) * c)) % 2 ^ (2 * D.E.e + 2) =
      (D.cK.getD l default).a % 2 ^ (2 * D.E.e + 2)
  ckL : ∀ s, s < 29 → certOKU1 D.E (X0L2 D.E D.SR (ofL (SUnitData.gL.getD s [])))
    (X1L2 D.E D.SR (ofL (SUnitData.gL.getD s []))) (D.cL.getD s default) = true
  ckN1 : ∀ s, s < 53 → certOKU1 D.E (X0N2 D.E D.SR D.SU (ofN (SUnitData.gN.getD s [])) true)
    (X1N2 D.E D.SR D.SU (ofN (SUnitData.gN.getD s [])) true) (D.cN1.getD s default) = true
  ckN2 : ∀ s, s < 53 → certOKU1 D.E (X0N2 D.E D.SR D.SU (ofN (SUnitData.gN.getD s [])) false)
    (X1N2 D.E D.SR D.SU (ofN (SUnitData.gN.getD s [])) false) (D.cN2.getD s default) = true
  gLn : ∀ s : Fin 29, (D.cL.getD s default).n ≤ D.SR.n - D.E.e - D.SR.j
  gNn : ∀ s : Fin 53, (D.cN1.getD s default).n ≤ D.SU.n - D.E.e - D.SU.j ∧
    (D.cN2.getD s default).n ≤ D.SU.n - D.E.e - D.SU.j
  cgLBits : ∀ (i : Fin 29) (c : Fin 3),
    (D.Cg.getD i 0 >>> ((2 * D.E.e + 2) * c)) % 2 ^ (2 * D.E.e + 2) =
      (![(D.cL.getD i default).a, 0, 0] c) % 2 ^ (2 * D.E.e + 2)
  cgNBits : ∀ (j : Fin 53) (c : Fin 3),
    (D.Cg.getD (29 + j) 0 >>> ((2 * D.E.e + 2) * c)) % 2 ^ (2 * D.E.e + 2) =
      (![0, (D.cN1.getD j default).a, (D.cN2.getD j default).a] c) % 2 ^ (2 * D.E.e + 2)
  ckPt : ∀ (k : Fin 2) (i : Fin 26), ((D.pts k).getD i default).okD D.E = true ∧
    ((D.pts k).getD i default).okZ D.E (gW k) = true ∧ ((D.pts k).getD i default).okT = true
  ckM : ∀ (k : Fin 2) (i : Fin 26),
    certOKU1 D.E (X0L2 D.E D.SR (ofL ((D.pts k).getD i default).tL))
        (X1L2 D.E D.SR (ofL ((D.pts k).getD i default).tL)) ((D.cM k 0).getD i default) = true ∧
      certOKU1 D.E (X0N2 D.E D.SR D.SU (ofN ((D.pts k).getD i default).tN) true)
        (X1N2 D.E D.SR D.SU (ofN ((D.pts k).getD i default).tN) true) ((D.cM k 1).getD i default) = true ∧
      certOKU1 D.E (X0N2 D.E D.SR D.SU (ofN ((D.pts k).getD i default).tN) false)
        (X1N2 D.E D.SR D.SU (ofN ((D.pts k).getD i default).tN) false) ((D.cM k 2).getD i default) = true
  muN : ∀ (k : Fin 2) (i : Fin 26), ((D.cM k 0).getD i default).n ≤ D.SR.n - D.E.e - D.SR.j ∧
    ((D.cM k 1).getD i default).n ≤ D.SU.n - D.E.e - D.SU.j ∧
    ((D.cM k 2).getD i default).n ≤ D.SU.n - D.E.e - D.SU.j
  muBits : ∀ (k : Fin 2) (i : Fin 26) (c : Fin 3),
    ((D.Amu k).getD i 0 >>> ((2 * D.E.e + 2) * c)) % 2 ^ (2 * D.E.e + 2) =
      ((D.cM k c).getD i default).a % 2 ^ (2 * D.E.e + 2)
  annI : annOK (3 * (2 * D.E.e + 2)) (fun l => D.Akap.getD l 0) (2 * D.E.e + 1) (fun q => D.QI.getD q 0)
    D.nQI = true
  leftInv : ∀ k : Fin 2, leftInvOK (fun q => dotRow (3 * (2 * D.E.e + 2)) (fun i => (D.Amu k).getD i 0)
    (D.QI.getD q 0) 26) D.nQI 26 (fun q => (D.T k).getD q 0) = true
  annCk : ∀ k : Fin 2, annOK (3 * (2 * D.E.e + 2)) (fun l => D.Akap.getD l 0) (2 * D.E.e + 1)
    (fun q => (D.QC k).getD q 0) 39 = true
  annCm : ∀ k : Fin 2, annOK (3 * (2 * D.E.e + 2)) (fun i => (D.Amu k).getD i 0) 26
    (fun q => (D.QC k).getD q 0) 39 = true

/-- One step `al^(d+1) = al^d al` of the power table of `E`. -/
def alStep (E : EisData) (d : ℕ) : Bool :=
  checkK E.prec (.sub (.lin (E.alP (d + 1))) (.mul (.lin (E.alP d)) (.lin E.al)))

/-- `E.ok` with the power table checked in `K` chunks of `m` steps, each chunk its own kernel check. -/
theorem ok_of_chunks {E : EisData} (K m : ℕ)
    (hA : checkK E.prec (.sub (.lin E.A) (.mul (.lin E.al) (.add (.int 1) (.mul (.lin E.al) (.lin E.cA)))))
      = true)
    (hB : checkK E.prec (.sub (.lin E.B) (.mul (.lin E.al) (.lin E.bB))) = true)
    (h0 : checkK E.prec (.sub (.lin (E.alP 0)) (.int 1)) = true)
    (hlen : E.alPow.length - 1 ≤ K * m)
    (hs : ∀ k, k < K → ∀ d, d < m → alStep E (d + k * m) = true)
    (hY : (checkK E.prec (.sub (.lin (E.Yp 0).1) (.int 1)) && checkK E.prec (.lin (E.Yp 0).2) &&
      allLt (fun n => checkK E.prec (.sub (.lin (E.Yp (n + 1)).1) (.mul (.lin E.A) (.lin (E.Yp n).2))) &&
        checkK E.prec (.sub (.lin (E.Yp (n + 1)).2)
          (.add (.lin (E.Yp n).1) (.mul (.lin E.B) (.lin (E.Yp n).2))))) (E.Ypow.length - 1)) = true) :
    E.ok = true := by
  simp only [EisData.ok, Bool.and_eq_true] at hY ⊢
  refine ⟨⟨⟨⟨⟨⟨hA, hB⟩, h0⟩, ?_⟩, hY.1.1⟩, hY.1.2⟩, hY.2⟩
  rw [allLt_iff]
  intro d hd
  have hdK : d < K * m := Nat.lt_of_lt_of_le hd hlen
  have hm : 0 < m := Nat.pos_of_ne_zero (by rintro rfl; simp at hdK)
  have h := hs (d / m) (Nat.div_lt_of_lt_mul (by rwa [Nat.mul_comm] at hdK)) (d % m) (Nat.mod_lt d hm)
  rw [Nat.mod_add_div'] at h
  exact h

variable {D : Data} (hF : Facts D)
include hF

theorem e_pos : 0 < D.E.e := by
  rcases Nat.eq_zero_or_pos D.E.e with h | h
  · exfalso
    have h2 := hF.wp.two
    rw [h, pow_zero] at h2
    have hle : ‖(2 : Kw)‖ ≤ 1 := by
      rw [show (2 : Kw) = 1 + 1 by norm_num]
      exact (IsUltrametricDist.norm_add_le_max _ _).trans (by simp)
    rcases hF.wp.res 2 hle with h' | h'
    · rw [h2] at h'; exact lt_irrefl _ h'
    · norm_num at h'
  · exact h

/-! ## The three components -/

/-- `T ↦ iL2 α`, `iN2 (+) β`, `iN2 (-) β`. -/
noncomputable def ev3 (k : Fin 2) : Fin 3 → (AdjoinRoot ((fRev k).map σw) →+* F) :=
  ![evAt σw (iL2 σw D.E hF.wp hF.sr) (iL2_comp_algebraMap hF.wp hF.sr) (fRev k) alphaR (aeval_alphaR_fRev k),
    evAt σw (iN2 σw D.E hF.wp hF.sr hF.su true) (iN2_comp_algebraMap hF.wp hF.sr hF.su true) (fRev k)
      betaR (aeval_betaR_fRev k),
    evAt σw (iN2 σw D.E hF.wp hF.sr hF.su false) (iN2_comp_algebraMap hF.wp hF.sr hF.su false) (fRev k)
      betaR (aeval_betaR_fRev k)]

/-- `(K_w2[T]/(fRev_k))ˣ → G`. -/
noncomputable def evG (k : Fin 2) : (AdjoinRoot ((fRev k).map σw))ˣ →* (Fin 3 → Fˣ) :=
  MonoidHom.pi fun c => Units.map (ev3 hF k c).toMonoidHom

theorem bU_ne (i : ℕ) :
    bU (A := (-1 : Kw)) (B := 1) (σw (zkE D.E.al)) D.E.e i ≠ 0 :=
  bU_ne_zero hF.wp.unif hF.wp.res (by simp) (by simp) (e_pos hF) hF.wp.two i

/-- The basis of `G / G²`. -/
noncomputable def bW : Fin (3 * (2 * D.E.e + 2)) → Fin 3 → Fˣ :=
  bG (2 * D.E.e + 2) (fun i => bU (A := (-1 : Kw)) (B := 1) (σw (zkE D.E.al)) D.E.e i) (bU_ne hF)

theorem evG_coe (k : Fin 2) (u : (AdjoinRoot ((fRev k).map σw))ˣ) (c : Fin 3) :
    ((evG hF k u c : Fˣ) : F) = ev3 hF k c (u : AdjoinRoot ((fRev k).map σw)) := rfl

theorem ev3_algebraMap (k : Fin 2) (c : Fin 3) (x : Kw) :
    ev3 hF k c (algebraMap Kw (AdjoinRoot ((fRev k).map σw)) x) = algebraMap Kw F x := by
  fin_cases c
  · exact evAt_algebraMap σw _ (iL2_comp_algebraMap hF.wp hF.sr) (fRev k) alphaR (aeval_alphaR_fRev k) x
  · exact evAt_algebraMap σw _ (iN2_comp_algebraMap hF.wp hF.sr hF.su true) (fRev k) betaR
      (aeval_betaR_fRev k) x
  · exact evAt_algebraMap σw _ (iN2_comp_algebraMap hF.wp hF.sr hF.su false) (fRev k) betaR
      (aeval_betaR_fRev k) x

theorem ev3_mk (k : Fin 2) (P : K21[X]) :
    ev3 hF k 0 (AdjoinRoot.mk _ (P.map σw)) = iL2 σw D.E hF.wp hF.sr (aeval alphaR P) ∧
    ev3 hF k 1 (AdjoinRoot.mk _ (P.map σw)) = iN2 σw D.E hF.wp hF.sr hF.su true (aeval betaR P) ∧
    ev3 hF k 2 (AdjoinRoot.mk _ (P.map σw)) = iN2 σw D.E hF.wp hF.sr hF.su false (aeval betaR P) :=
  ⟨evAt_mk σw _ (iL2_comp_algebraMap hF.wp hF.sr) (fRev k) alphaR (aeval_alphaR_fRev k) P,
    evAt_mk σw _ (iN2_comp_algebraMap hF.wp hF.sr hF.su true) (fRev k) betaR (aeval_betaR_fRev k) P,
    evAt_mk σw _ (iN2_comp_algebraMap hF.wp hF.sr hF.su false) (fRev k) betaR (aeval_betaR_fRev k) P⟩

theorem ev3_etale (k : Fin 2) (P : K21[X]) :
    ev3 hF k 0 (etaleMap σw (fRev k) (AdjoinRoot.mk _ P)) = iL2 σw D.E hF.wp hF.sr (aeval alphaR P) ∧
    ev3 hF k 1 (etaleMap σw (fRev k) (AdjoinRoot.mk _ P)) =
      iN2 σw D.E hF.wp hF.sr hF.su true (aeval betaR P) ∧
    ev3 hF k 2 (etaleMap σw (fRev k) (AdjoinRoot.mk _ P)) =
      iN2 σw D.E hF.wp hF.sr hF.su false (aeval betaR P) :=
  ⟨evAt_etaleMap σw _ (iL2_comp_algebraMap hF.wp hF.sr) (fRev k) alphaR (aeval_alphaR_fRev k) P,
    evAt_etaleMap σw _ (iN2_comp_algebraMap hF.wp hF.sr hF.su true) (fRev k) betaR (aeval_betaR_fRev k) P,
    evAt_etaleMap σw _ (iN2_comp_algebraMap hF.wp hF.sr hF.su false) (fRev k) betaR
      (aeval_betaR_fRev k) P⟩

/-! ## Squares at one component from a certificate -/

omit hF in
theorem natCast_ne_zero_F {n : ℕ} (hn : n ≠ 0) : (n : F) ≠ 0 := by
  rw [← map_natCast (algebraMap Kw F)]
  exact (_root_.map_ne_zero _).mpr (Nat.cast_ne_zero.mpr hn)

/-- Component 1: `Λ² y = iL2 t` and a certificate for the approximation of `t`. -/
theorem sqL2 {y : F} {lam : ℕ} (hlam : lam ≠ 0) {t : List (List ℤ)} {cc : UCert1}
    (hc : certOKU1 D.E (X0L2 D.E D.SR (ofL t)) (X1L2 D.E D.SR (ofL t)) cc = true)
    (hn : cc.n ≤ D.SR.n - D.E.e - D.SR.j)
    (hy : (lam : F) ^ 2 * y = iL2 σw D.E hF.wp hF.sr (mkL t)) : IsSquare (y * BaQ σw D.E cc.a) := by
  have h := certOKU1_isSquare hF.wp hc ((lam : F) ^ 2 * y) (by
    rw [hy, mkL_eq_evL]
    exact (norm_iL2_evL_sub hF.wp hF.sr (ofL t)).trans
      (pow_le_pow_of_le_one (norm_nonneg _) hF.wp.unif.norm_lt_one.le hn))
  refine isSquare_of_sq_mul (natCast_ne_zero_F hlam) ?_
  rwa [← mul_assoc]

/-- Components 2 and 3: `Λ² y = iN2 b t` and a certificate for the approximation of `t`. -/
theorem sqN2 (b : Bool) {y : F} {lam : ℕ} (hlam : lam ≠ 0) {t : List (List ℤ)} {cc : UCert1}
    (hc : certOKU1 D.E (X0N2 D.E D.SR D.SU (ofN t) b) (X1N2 D.E D.SR D.SU (ofN t) b) cc = true)
    (hn : cc.n ≤ D.SU.n - D.E.e - D.SU.j)
    (hy : (lam : F) ^ 2 * y = iN2 σw D.E hF.wp hF.sr hF.su b (mkN t)) :
    IsSquare (y * BaQ σw D.E cc.a) := by
  have h := certOKU1_isSquare hF.wp hc ((lam : F) ^ 2 * y) (by
    rw [hy, mkN_eq_evN]
    exact (norm_iN2_evN_sub hF.wp hF.sr hF.su b (ofN t)).trans
      (pow_le_pow_of_le_one (norm_nonneg _) hF.wp.unif.norm_lt_one.le hn))
  refine isSquare_of_sq_mul (natCast_ne_zero_F hlam) ?_
  rwa [← mul_assoc]

omit hF in
theorem sq_one_BaQ : IsSquare ((1 : F) * BaQ σw D.E 0) := by
  rw [BaQ_zero, one_mul]; exact ⟨1, (mul_one 1).symm⟩

/-- **A row of `G` from its three components.** -/
theorem row_sq (x : Fin 3 → Fˣ) (A : ℕ) (a : Fin 3 → ℕ)
    (ha : ∀ c : Fin 3, (A >>> ((2 * D.E.e + 2) * c)) % 2 ^ (2 * D.E.e + 2) = a c % 2 ^ (2 * D.E.e + 2))
    (h : ∀ c, IsSquare ((x c : F) * BaQ σw D.E (a c))) :
    IsSquare (x * ∏ l, bW hF l ^ (bitv (3 * (2 * D.E.e + 2)) A l).val) := by
  refine isSquare_mul_rows (hb := bU_ne hF) x A fun c => ?_
  have hc := h c
  rw [← BaQ_mod, ← ha c, BaQ_mod] at hc
  exact hc

omit hF in
theorem evK_kapX2 {E : EisData} (hE : E.ok = true) {i : ℕ} (hi : i < E.alPow.length) :
    σw (evK (kapX E i)) = dyGen (σw (zkE E.al)) i := by
  rcases Nat.eq_zero_or_pos i with rfl | hi0
  · simp [kapX, dyGen]
  · simp only [kapX, dyGen, hi0.ne', ite_false, evK_add, evK_int, evK_lin, Int.cast_one, map_add,
      map_one, EisData.ok_alP hE i hi, map_pow]

/-! ## The points -/

theorem exists_D2 (k : Fin 2) (i : Fin 26) :
    ∃ (P : Jac ((fRev k).map σw))
      (hu : IsUnit (AdjoinRoot.mk ((fRev k).map σw) (((D.pts k).getD i default).U.map σw))),
      muJ ((fRev k).map σw) P = (QuotientGroup.mk hu.unit : H ((fRev k).map σw)) :=
  PtData.exists_point hF.wp k (hF.ckPt k i).1 (hF.ckPt k i).2.1

/-- **The 26 points of twist `k` at `w2`.** -/
noncomputable def D2 (k : Fin 2) (i : Fin 26) : Jac ((fRev k).map σw) := (exists_D2 hF k i).choose

/-- `U(T)` for the point `D2 k i`. -/
noncomputable def U2 (k : Fin 2) (i : Fin 26) : (AdjoinRoot ((fRev k).map σw))ˣ :=
  (exists_D2 hF k i).choose_spec.choose.unit

theorem muJ_D2 (k : Fin 2) (i : Fin 26) :
    muJ ((fRev k).map σw) (D2 hF k i) = QuotientGroup.mk (U2 hF k i) :=
  (exists_D2 hF k i).choose_spec.choose_spec

/-! ## Rows -/

/-- The scalars `dyGen al l`. -/
noncomputable def kap0 (l : Fin (2 * D.E.e + 1)) : Kwˣ :=
  Units.mk0 (dyGen (σw (zkE D.E.al)) l) (dyGen_ne_zero hF.wp.unif l)

/-- Their images in `G`. -/
noncomputable def kapG (k : Fin 2) (l : Fin (2 * D.E.e + 1)) : Fin 3 → Fˣ :=
  evG hF k (Units.map (algebraMap Kw (AdjoinRoot ((fRev k).map σw))).toMonoidHom (kap0 hF l))

theorem hAkap (k : Fin 2) (l : Fin (2 * D.E.e + 1)) :
    IsSquare (kapG hF k l * ∏ i, bW hF i ^ (bitv (3 * (2 * D.E.e + 2)) (D.Akap.getD l 0) i).val) := by
  refine row_sq hF _ _ (fun _ => (D.cK.getD l default).a) (hF.akBits l) fun c => ?_
  have hx : ((kapG hF k l c : Fˣ) : F) = toU1 σw (kapX D.E l) (.int 0) := by
    rw [toU1, evK_int, Int.cast_zero, map_zero, evK_kapX2 hF.wp.ok (lt_of_lt_of_le l.isLt hF.lenK), kapG,
      evG_coe]
    rw [show QF.mk Kw (-1) 1 (dyGen (σw (zkE D.E.al)) l) 0 =
      algebraMap Kw F (dyGen (σw (zkE D.E.al)) l) by rw [qf_mk_eq_cZ1, map_zero, zero_mul, add_zero]]
    exact ev3_algebraMap hF k c _
  exact certOKU1_isSquare hF.wp (hF.ckK l l.isLt) _ (by rw [hx, sub_self, norm_zero]; positivity)

theorem hAmu (k : Fin 2) (i : Fin 26) :
    IsSquare (evG hF k (U2 hF k i) *
      ∏ j, bW hF j ^ (bitv (3 * (2 * D.E.e + 2)) ((D.Amu k).getD i 0) j).val) := by
  have hD := (hF.ckPt k i).1
  have hT := (hF.ckPt k i).2.2
  have hD' := hD
  simp only [PtData.okD, Bool.and_eq_true, decide_eq_true_eq] at hD'
  obtain ⟨⟨⟨⟨⟨⟨⟨⟨⟨⟨⟨-, -⟩, -⟩, -⟩, -⟩, -⟩, -⟩, -⟩, hlL⟩, hlN⟩, -⟩, -⟩ := hD'
  have hU : ((U2 hF k i : (AdjoinRoot ((fRev k).map σw))ˣ) : AdjoinRoot ((fRev k).map σw)) =
      AdjoinRoot.mk _ (((D.pts k).getD i default).U.map σw) :=
    (exists_D2 hF k i).choose_spec.choose.unit_spec
  have hL := PtData.aeval_alphaR_U D.E hD hT
  have hN := PtData.aeval_betaR_U D.E hD hT
  obtain ⟨c1, c2, c3⟩ := hF.ckM k i
  obtain ⟨n1, n2, n3⟩ := hF.muN k i
  obtain ⟨e1, e2, e3⟩ := ev3_mk hF k ((D.pts k).getD i default).U
  have h0 : IsSquare (((evG hF k (U2 hF k i) 0 : Fˣ) : F) * BaQ σw D.E ((D.cM k 0).getD i default).a) := by
    rw [evG_coe, hU, e1]
    refine sqL2 hF hlL.ne' c1 n1 ?_
    rw [← hL, map_mul, map_pow, map_natCast]
  have h1 : IsSquare (((evG hF k (U2 hF k i) 1 : Fˣ) : F) * BaQ σw D.E ((D.cM k 1).getD i default).a) := by
    rw [evG_coe, hU, e2]
    refine sqN2 hF true hlN.ne' c2 n2 ?_
    rw [← hN, map_mul, map_pow, map_natCast]
  have h2 : IsSquare (((evG hF k (U2 hF k i) 2 : Fˣ) : F) * BaQ σw D.E ((D.cM k 2).getD i default).a) := by
    rw [evG_coe, hU, e3]
    refine sqN2 hF false hlN.ne' c3 n3 ?_
    rw [← hN, map_mul, map_pow, map_natCast]
  refine row_sq hF _ _ (fun c => ((D.cM k c).getD i default).a) (hF.muBits k i) fun c => ?_
  fin_cases c
  exacts [h0, h1, h2]

theorem hCg (k : Fin 2) (s : Fin 82) :
    IsSquare (evG hF k (Units.map (etaleMap σw (fRev k)).toMonoidHom (gKu k s)) *
      ∏ j, bW hF j ^ (bitv (3 * (2 * D.E.e + 2)) (D.Cg.getD s 0) j).val) := by
  have hg : ∀ s : Fin 82, (((Units.map (etaleMap σw (fRev k)).toMonoidHom (gKu k s)) :
      (AdjoinRoot ((fRev k).map σw))ˣ) : AdjoinRoot ((fRev k).map σw)) =
      etaleMap σw (fRev k) (AdjoinRoot.mk _ (Pgen s)) := fun s => by
    change etaleMap σw (fRev k) (gKu k s : AdjoinRoot (fRev k)) = _
    rw [gKu_coe]
  revert s
  show ∀ s : Fin (29 + 53), _
  intro s
  refine Fin.addCases (fun i => ?_) (fun j => ?_) s
  · obtain ⟨e1, e2, e3⟩ := ev3_etale hF k (Pgen (Fin.castAdd 53 i))
    have h0 : IsSquare ((((evG hF k (Units.map (etaleMap σw (fRev k)).toMonoidHom
        (gKu k (Fin.castAdd 53 i))) 0 : Fˣ)) : F) * BaQ σw D.E (D.cL.getD i default).a) := by
      rw [evG_coe, hg, e1, Pgen_alphaR_left]
      refine sqL2 hF one_ne_zero (hF.ckL i i.isLt) (hF.gLn i) ?_
      rw [Nat.cast_one, one_pow, one_mul]; rfl
    have h12 : ∀ b : Bool,
        iN2 σw D.E hF.wp hF.sr hF.su b (aeval betaR (Pgen (Fin.castAdd 53 i))) = 1 :=
      fun b => by rw [Pgen_betaR_left, map_one]
    have h1 : IsSquare ((((evG hF k (Units.map (etaleMap σw (fRev k)).toMonoidHom
        (gKu k (Fin.castAdd 53 i))) 1 : Fˣ)) : F) * BaQ σw D.E 0) := by
      rw [evG_coe, hg, e2, h12]; exact sq_one_BaQ
    have h2 : IsSquare ((((evG hF k (Units.map (etaleMap σw (fRev k)).toMonoidHom
        (gKu k (Fin.castAdd 53 i))) 2 : Fˣ)) : F) * BaQ σw D.E 0) := by
      rw [evG_coe, hg, e3, h12]; exact sq_one_BaQ
    refine row_sq hF _ _ (fun c => ![(D.cL.getD i default).a, 0, 0] c) (hF.cgLBits i) fun c => ?_
    fin_cases c
    exacts [h0, h1, h2]
  · obtain ⟨e1, e2, e3⟩ := ev3_etale hF k (Pgen (Fin.natAdd 29 j))
    obtain ⟨n1, n2⟩ := hF.gNn j
    have h1 : IsSquare ((((evG hF k (Units.map (etaleMap σw (fRev k)).toMonoidHom
        (gKu k (Fin.natAdd 29 j))) 1 : Fˣ)) : F) * BaQ σw D.E (D.cN1.getD j default).a) := by
      rw [evG_coe, hg, e2, Pgen_betaR_right]
      refine sqN2 hF true one_ne_zero (hF.ckN1 j j.isLt) n1 ?_
      rw [Nat.cast_one, one_pow, one_mul]; rfl
    have h2 : IsSquare ((((evG hF k (Units.map (etaleMap σw (fRev k)).toMonoidHom
        (gKu k (Fin.natAdd 29 j))) 2 : Fˣ)) : F) * BaQ σw D.E (D.cN2.getD j default).a) := by
      rw [evG_coe, hg, e3, Pgen_betaR_right]
      refine sqN2 hF false one_ne_zero (hF.ckN2 j j.isLt) n2 ?_
      rw [Nat.cast_one, one_pow, one_mul]; rfl
    have h0 : IsSquare ((((evG hF k (Units.map (etaleMap σw (fRev k)).toMonoidHom
        (gKu k (Fin.natAdd 29 j))) 0 : Fˣ)) : F) * BaQ σw D.E 0) := by
      rw [evG_coe, hg, e1, Pgen_alphaR_right, map_one]; exact sq_one_BaQ
    refine row_sq hF _ _ (fun c => ![0, (D.cN1.getD j default).a, (D.cN2.getD j default).a] c)
      (hF.cgNBits j) fun c => ?_
    fin_cases c
    exacts [h0, h1, h2]

theorem hind : ∀ ε : Fin (3 * (2 * D.E.e + 2)) → ZMod 2, IsSquare (∏ i, bW hF i ^ (ε i).val) → ε = 0 :=
  indep_rows (bU_indep hF.wp.unif hF.wp.res (by simp) (by simp) (e_pos hF) hF.wp.two)

theorem hspan (x : Kw) (hx : x ≠ 0) :
    ∃ c : Fin (2 * D.E.e + 1) → ZMod 2, IsSquare (x * ∏ l, (kap0 hF l : Kw) ^ (c l).val) := by
  obtain ⟨c, hc⟩ := sb_span_dyadic hF.wp.unif (e_pos hF) hF.wp.two hF.wp.res x hx
  refine ⟨c, ?_⟩
  simp only [kap0, Units.val_mk0]
  exact hc

/-- The subgroup of the scalars. -/
noncomputable def Ksub (k : Fin 2) : Subgroup (Fin 3 → Fˣ) :=
  ((evG hF k).comp (Units.map (algebraMap Kw (AdjoinRoot ((fRev k).map σw))).toMonoidHom)).range

theorem hK (k : Fin 2) :
    ∀ x ∈ Ksub hF k, ∃ c : Fin (2 * D.E.e + 1) → ZMod 2, IsSquare (x * ∏ l, kapG hF k l ^ (c l).val) :=
  hK_of_span (evG hF k) (kap0 hF) (hspan hF)

/-! ## The local Props -/

/-- **`IndepImage` at `w2`.** -/
theorem indepImage_w2 (k : Fin 2) : IndepImage ((fRev k).map σw) (D2 hF k) :=
  indepImage_of_coords _ (D2 hF k) (U2 hF k) (muJ_D2 hF k) (evG hF k) (Ksub hF k) (fun c => ⟨c, rfl⟩)
    (bW hF) (hind hF) (kapG hF k) (fun l => ⟨kap0 hF l, rfl⟩) (hK hF k)
    (fun l => bitv (3 * (2 * D.E.e + 2)) (D.Akap.getD l 0)) (hAkap hF k)
    (fun i => bitv (3 * (2 * D.E.e + 2)) ((D.Amu k).getD i 0)) (hAmu hF k)
    (hcert_indep_of_bits (fun l => D.Akap.getD l 0) (fun i => (D.Amu k).getD i 0) (fun q => D.QI.getD q 0)
      (fun q => (D.T k).getD q 0) hF.annI (hF.leftInv k))

/-- **`ImageIn` at `w2`.** -/
theorem imageIn_w2 (k : Fin 2) :
    ImageIn ((fRev k).map σw) (Subgroup.closure (Set.range fun i => muJ ((fRev k).map σw) (D2 hF k i))) :=
  imageIn_closure_of_count_indep _ (D2 hF k) (Count.countBound_w2 k) (indepImage_w2 hF k)

/-- The coordinate matrix at `w2`: the forms `QC` read on the generator rows. -/
def Cmat (D : Data) (k : Fin 2) : Matrix (Fin 39) (Fin 82) (ZMod 2) :=
  Matrix.of fun i s => bitv 82 (dotRow (3 * (2 * D.E.e + 2)) (fun s => D.Cg.getD s 0) ((D.QC k).getD i 0) 82) s

/-- **`CoordCond` at `w2`** on the subgroup of the points. -/
theorem coordCond_w2_closure (k : Fin 2) :
    CoordCond σw (fRev k) (gK k)
      (Subgroup.closure (Set.range fun i => muJ ((fRev k).map σw) (D2 hF k i))) (Cmat D k) :=
  coordCond_of_coords σw (fRev k) (gKu k) (D2 hF k) (U2 hF k) (muJ_D2 hF k) (evG hF k) (Ksub hF k)
    (fun c => ⟨c, rfl⟩) (bW hF) (hind hF) (kapG hF k) (fun l => ⟨kap0 hF l, rfl⟩) (hK hF k)
    (fun l => bitv (3 * (2 * D.E.e + 2)) (D.Akap.getD l 0)) (hAkap hF k)
    (fun i => bitv (3 * (2 * D.E.e + 2)) ((D.Amu k).getD i 0)) (hAmu hF k)
    (fun s => bitv (3 * (2 * D.E.e + 2)) (D.Cg.getD s 0)) (hCg hF k) (Cmat D k)
    (hcert_coord_of_bits (fun l => D.Akap.getD l 0) (fun i => (D.Amu k).getD i 0) (fun s => D.Cg.getD s 0)
      (fun q => (D.QC k).getD q 0) (hF.annCk k) (hF.annCm k))

/-- **`CoordCond` at `w2`** on the image of `μ`. -/
theorem coordCond_w2_range (k : Fin 2) :
    CoordCond σw (fRev k) (gK k) (muJ ((fRev k).map σw)).range (Cmat D k) :=
  coordCond_range σw (fRev k) (gK k) (Cmat D k) (coordCond_w2_closure hF k) (imageIn_w2 hF k)

end FurioLombardo.Discharge.SelmerBasis.W2G
