import FurioLombardo.Discharge.SelmerBasis.W3Data

/-!
# Kernel checks of the model at w3 (generated by code/selmer-local-conditions/kernel_checks_w6.sh)

The Eisenstein data `E`, the model `M` (`omega -> y + c Y`) and the square root data `S`.
Every statement is closed by `decide +kernel`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.W3

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower

theorem ck_E : E.ok = true := by decide +kernel

theorem ck_M : M.ok E = true := by decide +kernel

theorem ck_S : S.ok E M = true := by decide +kernel

end FurioLombardo.Discharge.SelmerBasis.W3
