import FurioLombardo.Discharge.SelmerBasis.W3Data
import FurioLombardo.Discharge.SelmerBasis.W3DataK0
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem

/-!
# Kernel checks of the points of twist 0 at w3 (generated by code/selmer-local-conditions/kernel_checks_w6.sh)

`ck_pt_i`: the point data `pt_i` (`okD`, `okZ` for `4 fRev_0`, `okT`); `ck_M1_i`, `ck_M2_i`, `ck_M3_i`:
the square certificates of `Λ² U_i` at the three components.
Every statement is closed by `decide +kernel`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.W3

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower

namespace K0

theorem ck_pt_0 : (pts.getD 0 default).okD E = true ∧ (pts.getD 0 default).okZ E (gW 0) = true ∧
    (pts.getD 0 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_0 : certOK E (cM1.getD 0 default).n0 (X0L M (ofL (pts.getD 0 default).tL))
    (X1L M (ofL (pts.getD 0 default).tL)) (cM1.getD 0 default) = true := by
  decide +kernel

theorem ck_M2_0 : certOK E (cM2.getD 0 default).n0 (X0N E M S (ofN (pts.getD 0 default).tN) true)
    (X1N E M S (ofN (pts.getD 0 default).tN) true) (cM2.getD 0 default) = true := by
  decide +kernel

theorem ck_M3_0 : certOK E (cM3.getD 0 default).n0 (X0N E M S (ofN (pts.getD 0 default).tN) false)
    (X1N E M S (ofN (pts.getD 0 default).tN) false) (cM3.getD 0 default) = true := by
  decide +kernel

theorem ck_pt_1 : (pts.getD 1 default).okD E = true ∧ (pts.getD 1 default).okZ E (gW 0) = true ∧
    (pts.getD 1 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_1 : certOK E (cM1.getD 1 default).n0 (X0L M (ofL (pts.getD 1 default).tL))
    (X1L M (ofL (pts.getD 1 default).tL)) (cM1.getD 1 default) = true := by
  decide +kernel

theorem ck_M2_1 : certOK E (cM2.getD 1 default).n0 (X0N E M S (ofN (pts.getD 1 default).tN) true)
    (X1N E M S (ofN (pts.getD 1 default).tN) true) (cM2.getD 1 default) = true := by
  decide +kernel

theorem ck_M3_1 : certOK E (cM3.getD 1 default).n0 (X0N E M S (ofN (pts.getD 1 default).tN) false)
    (X1N E M S (ofN (pts.getD 1 default).tN) false) (cM3.getD 1 default) = true := by
  decide +kernel

theorem ck_pt_2 : (pts.getD 2 default).okD E = true ∧ (pts.getD 2 default).okZ E (gW 0) = true ∧
    (pts.getD 2 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_2 : certOK E (cM1.getD 2 default).n0 (X0L M (ofL (pts.getD 2 default).tL))
    (X1L M (ofL (pts.getD 2 default).tL)) (cM1.getD 2 default) = true := by
  decide +kernel

theorem ck_M2_2 : certOK E (cM2.getD 2 default).n0 (X0N E M S (ofN (pts.getD 2 default).tN) true)
    (X1N E M S (ofN (pts.getD 2 default).tN) true) (cM2.getD 2 default) = true := by
  decide +kernel

theorem ck_M3_2 : certOK E (cM3.getD 2 default).n0 (X0N E M S (ofN (pts.getD 2 default).tN) false)
    (X1N E M S (ofN (pts.getD 2 default).tN) false) (cM3.getD 2 default) = true := by
  decide +kernel

theorem ck_pt_3 : (pts.getD 3 default).okD E = true ∧ (pts.getD 3 default).okZ E (gW 0) = true ∧
    (pts.getD 3 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_3 : certOK E (cM1.getD 3 default).n0 (X0L M (ofL (pts.getD 3 default).tL))
    (X1L M (ofL (pts.getD 3 default).tL)) (cM1.getD 3 default) = true := by
  decide +kernel

theorem ck_M2_3 : certOK E (cM2.getD 3 default).n0 (X0N E M S (ofN (pts.getD 3 default).tN) true)
    (X1N E M S (ofN (pts.getD 3 default).tN) true) (cM2.getD 3 default) = true := by
  decide +kernel

theorem ck_M3_3 : certOK E (cM3.getD 3 default).n0 (X0N E M S (ofN (pts.getD 3 default).tN) false)
    (X1N E M S (ofN (pts.getD 3 default).tN) false) (cM3.getD 3 default) = true := by
  decide +kernel

theorem ck_pt_4 : (pts.getD 4 default).okD E = true ∧ (pts.getD 4 default).okZ E (gW 0) = true ∧
    (pts.getD 4 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_4 : certOK E (cM1.getD 4 default).n0 (X0L M (ofL (pts.getD 4 default).tL))
    (X1L M (ofL (pts.getD 4 default).tL)) (cM1.getD 4 default) = true := by
  decide +kernel

theorem ck_M2_4 : certOK E (cM2.getD 4 default).n0 (X0N E M S (ofN (pts.getD 4 default).tN) true)
    (X1N E M S (ofN (pts.getD 4 default).tN) true) (cM2.getD 4 default) = true := by
  decide +kernel

theorem ck_M3_4 : certOK E (cM3.getD 4 default).n0 (X0N E M S (ofN (pts.getD 4 default).tN) false)
    (X1N E M S (ofN (pts.getD 4 default).tN) false) (cM3.getD 4 default) = true := by
  decide +kernel

theorem ck_pt_5 : (pts.getD 5 default).okD E = true ∧ (pts.getD 5 default).okZ E (gW 0) = true ∧
    (pts.getD 5 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_5 : certOK E (cM1.getD 5 default).n0 (X0L M (ofL (pts.getD 5 default).tL))
    (X1L M (ofL (pts.getD 5 default).tL)) (cM1.getD 5 default) = true := by
  decide +kernel

theorem ck_M2_5 : certOK E (cM2.getD 5 default).n0 (X0N E M S (ofN (pts.getD 5 default).tN) true)
    (X1N E M S (ofN (pts.getD 5 default).tN) true) (cM2.getD 5 default) = true := by
  decide +kernel

theorem ck_M3_5 : certOK E (cM3.getD 5 default).n0 (X0N E M S (ofN (pts.getD 5 default).tN) false)
    (X1N E M S (ofN (pts.getD 5 default).tN) false) (cM3.getD 5 default) = true := by
  decide +kernel

theorem ck_pt_6 : (pts.getD 6 default).okD E = true ∧ (pts.getD 6 default).okZ E (gW 0) = true ∧
    (pts.getD 6 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_6 : certOK E (cM1.getD 6 default).n0 (X0L M (ofL (pts.getD 6 default).tL))
    (X1L M (ofL (pts.getD 6 default).tL)) (cM1.getD 6 default) = true := by
  decide +kernel

theorem ck_M2_6 : certOK E (cM2.getD 6 default).n0 (X0N E M S (ofN (pts.getD 6 default).tN) true)
    (X1N E M S (ofN (pts.getD 6 default).tN) true) (cM2.getD 6 default) = true := by
  decide +kernel

theorem ck_M3_6 : certOK E (cM3.getD 6 default).n0 (X0N E M S (ofN (pts.getD 6 default).tN) false)
    (X1N E M S (ofN (pts.getD 6 default).tN) false) (cM3.getD 6 default) = true := by
  decide +kernel

theorem ck_pt_7 : (pts.getD 7 default).okD E = true ∧ (pts.getD 7 default).okZ E (gW 0) = true ∧
    (pts.getD 7 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_7 : certOK E (cM1.getD 7 default).n0 (X0L M (ofL (pts.getD 7 default).tL))
    (X1L M (ofL (pts.getD 7 default).tL)) (cM1.getD 7 default) = true := by
  decide +kernel

theorem ck_M2_7 : certOK E (cM2.getD 7 default).n0 (X0N E M S (ofN (pts.getD 7 default).tN) true)
    (X1N E M S (ofN (pts.getD 7 default).tN) true) (cM2.getD 7 default) = true := by
  decide +kernel

theorem ck_M3_7 : certOK E (cM3.getD 7 default).n0 (X0N E M S (ofN (pts.getD 7 default).tN) false)
    (X1N E M S (ofN (pts.getD 7 default).tN) false) (cM3.getD 7 default) = true := by
  decide +kernel

theorem ck_pt_8 : (pts.getD 8 default).okD E = true ∧ (pts.getD 8 default).okZ E (gW 0) = true ∧
    (pts.getD 8 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_8 : certOK E (cM1.getD 8 default).n0 (X0L M (ofL (pts.getD 8 default).tL))
    (X1L M (ofL (pts.getD 8 default).tL)) (cM1.getD 8 default) = true := by
  decide +kernel

theorem ck_M2_8 : certOK E (cM2.getD 8 default).n0 (X0N E M S (ofN (pts.getD 8 default).tN) true)
    (X1N E M S (ofN (pts.getD 8 default).tN) true) (cM2.getD 8 default) = true := by
  decide +kernel

theorem ck_M3_8 : certOK E (cM3.getD 8 default).n0 (X0N E M S (ofN (pts.getD 8 default).tN) false)
    (X1N E M S (ofN (pts.getD 8 default).tN) false) (cM3.getD 8 default) = true := by
  decide +kernel

theorem ck_pt_9 : (pts.getD 9 default).okD E = true ∧ (pts.getD 9 default).okZ E (gW 0) = true ∧
    (pts.getD 9 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_9 : certOK E (cM1.getD 9 default).n0 (X0L M (ofL (pts.getD 9 default).tL))
    (X1L M (ofL (pts.getD 9 default).tL)) (cM1.getD 9 default) = true := by
  decide +kernel

theorem ck_M2_9 : certOK E (cM2.getD 9 default).n0 (X0N E M S (ofN (pts.getD 9 default).tN) true)
    (X1N E M S (ofN (pts.getD 9 default).tN) true) (cM2.getD 9 default) = true := by
  decide +kernel

theorem ck_M3_9 : certOK E (cM3.getD 9 default).n0 (X0N E M S (ofN (pts.getD 9 default).tN) false)
    (X1N E M S (ofN (pts.getD 9 default).tN) false) (cM3.getD 9 default) = true := by
  decide +kernel

theorem ck_pt_10 : (pts.getD 10 default).okD E = true ∧ (pts.getD 10 default).okZ E (gW 0) = true ∧
    (pts.getD 10 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_10 : certOK E (cM1.getD 10 default).n0 (X0L M (ofL (pts.getD 10 default).tL))
    (X1L M (ofL (pts.getD 10 default).tL)) (cM1.getD 10 default) = true := by
  decide +kernel

theorem ck_M2_10 : certOK E (cM2.getD 10 default).n0 (X0N E M S (ofN (pts.getD 10 default).tN) true)
    (X1N E M S (ofN (pts.getD 10 default).tN) true) (cM2.getD 10 default) = true := by
  decide +kernel

theorem ck_M3_10 : certOK E (cM3.getD 10 default).n0 (X0N E M S (ofN (pts.getD 10 default).tN) false)
    (X1N E M S (ofN (pts.getD 10 default).tN) false) (cM3.getD 10 default) = true := by
  decide +kernel

theorem ck_pt_11 : (pts.getD 11 default).okD E = true ∧ (pts.getD 11 default).okZ E (gW 0) = true ∧
    (pts.getD 11 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_11 : certOK E (cM1.getD 11 default).n0 (X0L M (ofL (pts.getD 11 default).tL))
    (X1L M (ofL (pts.getD 11 default).tL)) (cM1.getD 11 default) = true := by
  decide +kernel

theorem ck_M2_11 : certOK E (cM2.getD 11 default).n0 (X0N E M S (ofN (pts.getD 11 default).tN) true)
    (X1N E M S (ofN (pts.getD 11 default).tN) true) (cM2.getD 11 default) = true := by
  decide +kernel

theorem ck_M3_11 : certOK E (cM3.getD 11 default).n0 (X0N E M S (ofN (pts.getD 11 default).tN) false)
    (X1N E M S (ofN (pts.getD 11 default).tN) false) (cM3.getD 11 default) = true := by
  decide +kernel

theorem ck_pt_12 : (pts.getD 12 default).okD E = true ∧ (pts.getD 12 default).okZ E (gW 0) = true ∧
    (pts.getD 12 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_12 : certOK E (cM1.getD 12 default).n0 (X0L M (ofL (pts.getD 12 default).tL))
    (X1L M (ofL (pts.getD 12 default).tL)) (cM1.getD 12 default) = true := by
  decide +kernel

theorem ck_M2_12 : certOK E (cM2.getD 12 default).n0 (X0N E M S (ofN (pts.getD 12 default).tN) true)
    (X1N E M S (ofN (pts.getD 12 default).tN) true) (cM2.getD 12 default) = true := by
  decide +kernel

theorem ck_M3_12 : certOK E (cM3.getD 12 default).n0 (X0N E M S (ofN (pts.getD 12 default).tN) false)
    (X1N E M S (ofN (pts.getD 12 default).tN) false) (cM3.getD 12 default) = true := by
  decide +kernel

theorem ck_pt_13 : (pts.getD 13 default).okD E = true ∧ (pts.getD 13 default).okZ E (gW 0) = true ∧
    (pts.getD 13 default).okT = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_M1_13 : certOK E (cM1.getD 13 default).n0 (X0L M (ofL (pts.getD 13 default).tL))
    (X1L M (ofL (pts.getD 13 default).tL)) (cM1.getD 13 default) = true := by
  decide +kernel

theorem ck_M2_13 : certOK E (cM2.getD 13 default).n0 (X0N E M S (ofN (pts.getD 13 default).tN) true)
    (X1N E M S (ofN (pts.getD 13 default).tN) true) (cM2.getD 13 default) = true := by
  decide +kernel

theorem ck_M3_13 : certOK E (cM3.getD 13 default).n0 (X0N E M S (ofN (pts.getD 13 default).tN) false)
    (X1N E M S (ofN (pts.getD 13 default).tN) false) (cM3.getD 13 default) = true := by
  decide +kernel

theorem ck_pt : ∀ i, i < 14 → (pts.getD i default).okD E = true ∧ (pts.getD i default).okZ E (gW 0) = true ∧
    (pts.getD i default).okT = true := by
  intro i hi
  interval_cases i
  exacts [ck_pt_0, ck_pt_1, ck_pt_2, ck_pt_3, ck_pt_4, ck_pt_5, ck_pt_6, ck_pt_7, ck_pt_8, ck_pt_9, ck_pt_10, ck_pt_11, ck_pt_12, ck_pt_13]

theorem ck_M1 : ∀ i, i < 14 → certOK E (cM1.getD i default).n0 (X0L M (ofL (pts.getD i default).tL))
    (X1L M (ofL (pts.getD i default).tL)) (cM1.getD i default) = true := by
  intro i hi
  interval_cases i
  exacts [ck_M1_0, ck_M1_1, ck_M1_2, ck_M1_3, ck_M1_4, ck_M1_5, ck_M1_6, ck_M1_7, ck_M1_8, ck_M1_9, ck_M1_10, ck_M1_11, ck_M1_12, ck_M1_13]

theorem ck_M2 : ∀ i, i < 14 → certOK E (cM2.getD i default).n0 (X0N E M S (ofN (pts.getD i default).tN) true)
    (X1N E M S (ofN (pts.getD i default).tN) true) (cM2.getD i default) = true := by
  intro i hi
  interval_cases i
  exacts [ck_M2_0, ck_M2_1, ck_M2_2, ck_M2_3, ck_M2_4, ck_M2_5, ck_M2_6, ck_M2_7, ck_M2_8, ck_M2_9, ck_M2_10, ck_M2_11, ck_M2_12, ck_M2_13]

theorem ck_M3 : ∀ i, i < 14 → certOK E (cM3.getD i default).n0 (X0N E M S (ofN (pts.getD i default).tN) false)
    (X1N E M S (ofN (pts.getD i default).tN) false) (cM3.getD i default) = true := by
  intro i hi
  interval_cases i
  exacts [ck_M3_0, ck_M3_1, ck_M3_2, ck_M3_3, ck_M3_4, ck_M3_5, ck_M3_6, ck_M3_7, ck_M3_8, ck_M3_9, ck_M3_10, ck_M3_11, ck_M3_12, ck_M3_13]

end K0

end FurioLombardo.Discharge.SelmerBasis.W3
