import FurioLombardo.Discharge.SelmerBasis.W3Data
import FurioLombardo.Discharge.SelmerBasis.PlaceWElem

/-!
# Kernel checks of the kappa and gensL certificates at w3 (generated by code/selmer-local-conditions/kernel_checks_w6.sh)

`ck_K_i`: the square certificate of `dyGen al i` (the same at the three components); `ck_L_s`: that of
`iL (gensL s)` at component 1.
Every statement is closed by `decide +kernel`, one certificate per declaration.
-/

namespace FurioLombardo.Discharge.SelmerBasis.W3

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower

theorem ck_K_0 : certOK E (cK.getD 0 default).n0 (kapX E 0) (.int 0) (cK.getD 0 default) = true := by
  decide +kernel

theorem ck_K_1 : certOK E (cK.getD 1 default).n0 (kapX E 1) (.int 0) (cK.getD 1 default) = true := by
  decide +kernel

theorem ck_K_2 : certOK E (cK.getD 2 default).n0 (kapX E 2) (.int 0) (cK.getD 2 default) = true := by
  decide +kernel

theorem ck_K_3 : certOK E (cK.getD 3 default).n0 (kapX E 3) (.int 0) (cK.getD 3 default) = true := by
  decide +kernel

theorem ck_K_4 : certOK E (cK.getD 4 default).n0 (kapX E 4) (.int 0) (cK.getD 4 default) = true := by
  decide +kernel

theorem ck_K_5 : certOK E (cK.getD 5 default).n0 (kapX E 5) (.int 0) (cK.getD 5 default) = true := by
  decide +kernel

theorem ck_K_6 : certOK E (cK.getD 6 default).n0 (kapX E 6) (.int 0) (cK.getD 6 default) = true := by
  decide +kernel

theorem ck_K_7 : certOK E (cK.getD 7 default).n0 (kapX E 7) (.int 0) (cK.getD 7 default) = true := by
  decide +kernel

theorem ck_K_8 : certOK E (cK.getD 8 default).n0 (kapX E 8) (.int 0) (cK.getD 8 default) = true := by
  decide +kernel

theorem ck_K_9 : certOK E (cK.getD 9 default).n0 (kapX E 9) (.int 0) (cK.getD 9 default) = true := by
  decide +kernel

theorem ck_K_10 : certOK E (cK.getD 10 default).n0 (kapX E 10) (.int 0) (cK.getD 10 default) = true := by
  decide +kernel

theorem ck_K_11 : certOK E (cK.getD 11 default).n0 (kapX E 11) (.int 0) (cK.getD 11 default) = true := by
  decide +kernel

theorem ck_K_12 : certOK E (cK.getD 12 default).n0 (kapX E 12) (.int 0) (cK.getD 12 default) = true := by
  decide +kernel

theorem ck_L_0 : certOK E (cL.getD 0 default).n0 (X0L M (ofL (SUnitData.gL.getD 0 [])))
    (X1L M (ofL (SUnitData.gL.getD 0 []))) (cL.getD 0 default) = true := by
  decide +kernel

theorem ck_L_1 : certOK E (cL.getD 1 default).n0 (X0L M (ofL (SUnitData.gL.getD 1 [])))
    (X1L M (ofL (SUnitData.gL.getD 1 []))) (cL.getD 1 default) = true := by
  decide +kernel

theorem ck_L_2 : certOK E (cL.getD 2 default).n0 (X0L M (ofL (SUnitData.gL.getD 2 [])))
    (X1L M (ofL (SUnitData.gL.getD 2 []))) (cL.getD 2 default) = true := by
  decide +kernel

theorem ck_L_3 : certOK E (cL.getD 3 default).n0 (X0L M (ofL (SUnitData.gL.getD 3 [])))
    (X1L M (ofL (SUnitData.gL.getD 3 []))) (cL.getD 3 default) = true := by
  decide +kernel

theorem ck_L_4 : certOK E (cL.getD 4 default).n0 (X0L M (ofL (SUnitData.gL.getD 4 [])))
    (X1L M (ofL (SUnitData.gL.getD 4 []))) (cL.getD 4 default) = true := by
  decide +kernel

theorem ck_L_5 : certOK E (cL.getD 5 default).n0 (X0L M (ofL (SUnitData.gL.getD 5 [])))
    (X1L M (ofL (SUnitData.gL.getD 5 []))) (cL.getD 5 default) = true := by
  decide +kernel

theorem ck_L_6 : certOK E (cL.getD 6 default).n0 (X0L M (ofL (SUnitData.gL.getD 6 [])))
    (X1L M (ofL (SUnitData.gL.getD 6 []))) (cL.getD 6 default) = true := by
  decide +kernel

theorem ck_L_7 : certOK E (cL.getD 7 default).n0 (X0L M (ofL (SUnitData.gL.getD 7 [])))
    (X1L M (ofL (SUnitData.gL.getD 7 []))) (cL.getD 7 default) = true := by
  decide +kernel

theorem ck_L_8 : certOK E (cL.getD 8 default).n0 (X0L M (ofL (SUnitData.gL.getD 8 [])))
    (X1L M (ofL (SUnitData.gL.getD 8 []))) (cL.getD 8 default) = true := by
  decide +kernel

theorem ck_L_9 : certOK E (cL.getD 9 default).n0 (X0L M (ofL (SUnitData.gL.getD 9 [])))
    (X1L M (ofL (SUnitData.gL.getD 9 []))) (cL.getD 9 default) = true := by
  decide +kernel

theorem ck_L_10 : certOK E (cL.getD 10 default).n0 (X0L M (ofL (SUnitData.gL.getD 10 [])))
    (X1L M (ofL (SUnitData.gL.getD 10 []))) (cL.getD 10 default) = true := by
  decide +kernel

theorem ck_L_11 : certOK E (cL.getD 11 default).n0 (X0L M (ofL (SUnitData.gL.getD 11 [])))
    (X1L M (ofL (SUnitData.gL.getD 11 []))) (cL.getD 11 default) = true := by
  decide +kernel

theorem ck_L_12 : certOK E (cL.getD 12 default).n0 (X0L M (ofL (SUnitData.gL.getD 12 [])))
    (X1L M (ofL (SUnitData.gL.getD 12 []))) (cL.getD 12 default) = true := by
  decide +kernel

theorem ck_L_13 : certOK E (cL.getD 13 default).n0 (X0L M (ofL (SUnitData.gL.getD 13 [])))
    (X1L M (ofL (SUnitData.gL.getD 13 []))) (cL.getD 13 default) = true := by
  decide +kernel

theorem ck_L_14 : certOK E (cL.getD 14 default).n0 (X0L M (ofL (SUnitData.gL.getD 14 [])))
    (X1L M (ofL (SUnitData.gL.getD 14 []))) (cL.getD 14 default) = true := by
  decide +kernel

theorem ck_L_15 : certOK E (cL.getD 15 default).n0 (X0L M (ofL (SUnitData.gL.getD 15 [])))
    (X1L M (ofL (SUnitData.gL.getD 15 []))) (cL.getD 15 default) = true := by
  decide +kernel

theorem ck_L_16 : certOK E (cL.getD 16 default).n0 (X0L M (ofL (SUnitData.gL.getD 16 [])))
    (X1L M (ofL (SUnitData.gL.getD 16 []))) (cL.getD 16 default) = true := by
  decide +kernel

theorem ck_L_17 : certOK E (cL.getD 17 default).n0 (X0L M (ofL (SUnitData.gL.getD 17 [])))
    (X1L M (ofL (SUnitData.gL.getD 17 []))) (cL.getD 17 default) = true := by
  decide +kernel

theorem ck_L_18 : certOK E (cL.getD 18 default).n0 (X0L M (ofL (SUnitData.gL.getD 18 [])))
    (X1L M (ofL (SUnitData.gL.getD 18 []))) (cL.getD 18 default) = true := by
  decide +kernel

theorem ck_L_19 : certOK E (cL.getD 19 default).n0 (X0L M (ofL (SUnitData.gL.getD 19 [])))
    (X1L M (ofL (SUnitData.gL.getD 19 []))) (cL.getD 19 default) = true := by
  decide +kernel

theorem ck_L_20 : certOK E (cL.getD 20 default).n0 (X0L M (ofL (SUnitData.gL.getD 20 [])))
    (X1L M (ofL (SUnitData.gL.getD 20 []))) (cL.getD 20 default) = true := by
  decide +kernel

theorem ck_L_21 : certOK E (cL.getD 21 default).n0 (X0L M (ofL (SUnitData.gL.getD 21 [])))
    (X1L M (ofL (SUnitData.gL.getD 21 []))) (cL.getD 21 default) = true := by
  decide +kernel

theorem ck_L_22 : certOK E (cL.getD 22 default).n0 (X0L M (ofL (SUnitData.gL.getD 22 [])))
    (X1L M (ofL (SUnitData.gL.getD 22 []))) (cL.getD 22 default) = true := by
  decide +kernel

theorem ck_L_23 : certOK E (cL.getD 23 default).n0 (X0L M (ofL (SUnitData.gL.getD 23 [])))
    (X1L M (ofL (SUnitData.gL.getD 23 []))) (cL.getD 23 default) = true := by
  decide +kernel

theorem ck_L_24 : certOK E (cL.getD 24 default).n0 (X0L M (ofL (SUnitData.gL.getD 24 [])))
    (X1L M (ofL (SUnitData.gL.getD 24 []))) (cL.getD 24 default) = true := by
  decide +kernel

theorem ck_L_25 : certOK E (cL.getD 25 default).n0 (X0L M (ofL (SUnitData.gL.getD 25 [])))
    (X1L M (ofL (SUnitData.gL.getD 25 []))) (cL.getD 25 default) = true := by
  decide +kernel

theorem ck_L_26 : certOK E (cL.getD 26 default).n0 (X0L M (ofL (SUnitData.gL.getD 26 [])))
    (X1L M (ofL (SUnitData.gL.getD 26 []))) (cL.getD 26 default) = true := by
  decide +kernel

theorem ck_L_27 : certOK E (cL.getD 27 default).n0 (X0L M (ofL (SUnitData.gL.getD 27 [])))
    (X1L M (ofL (SUnitData.gL.getD 27 []))) (cL.getD 27 default) = true := by
  decide +kernel

theorem ck_L_28 : certOK E (cL.getD 28 default).n0 (X0L M (ofL (SUnitData.gL.getD 28 [])))
    (X1L M (ofL (SUnitData.gL.getD 28 []))) (cL.getD 28 default) = true := by
  decide +kernel

theorem ck_K : ∀ i, i < 13 → certOK E (cK.getD i default).n0 (kapX E i) (.int 0) (cK.getD i default) = true := by
  intro i hi
  interval_cases i
  exacts [ck_K_0, ck_K_1, ck_K_2, ck_K_3, ck_K_4, ck_K_5, ck_K_6, ck_K_7, ck_K_8, ck_K_9, ck_K_10, ck_K_11, ck_K_12]

theorem ck_L : ∀ s, s < 29 → certOK E (cL.getD s default).n0 (X0L M (ofL (SUnitData.gL.getD s [])))
    (X1L M (ofL (SUnitData.gL.getD s []))) (cL.getD s default) = true := by
  intro s hs
  interval_cases s
  exacts [ck_L_0, ck_L_1, ck_L_2, ck_L_3, ck_L_4, ck_L_5, ck_L_6, ck_L_7, ck_L_8, ck_L_9, ck_L_10, ck_L_11, ck_L_12, ck_L_13, ck_L_14, ck_L_15, ck_L_16, ck_L_17, ck_L_18, ck_L_19, ck_L_20, ck_L_21, ck_L_22, ck_L_23, ck_L_24, ck_L_25, ck_L_26, ck_L_27, ck_L_28]

end FurioLombardo.Discharge.SelmerBasis.W3
