import FurioLombardo.Discharge.SelmerBasis.W7Data
import FurioLombardo.Discharge.SelmerBasis.W7DataL

/-!
# Kernel checks of the gensL certificates at w7 (generated by code/selmer-local-conditions/kernel_checks_w7.sh)

`ck_L_s`: the two `KCert`s of `gensL s` (components 0, 1).
Every certificate is closed by `decide +kernel` in its own declaration. Data: W7Data*.lean (code/selmer-local-conditions/lean_data_w7.gp).
-/

namespace FurioLombardo.Discharge.SelmerBasis.W7

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis
open FurioLombardo.M2.Special (al7)

theorem ck_L_0 : okL tab M (cL.getD 0 default) 0 = true := by decide +kernel

theorem ck_L_1 : okL tab M (cL.getD 1 default) 1 = true := by decide +kernel

theorem ck_L_2 : okL tab M (cL.getD 2 default) 2 = true := by decide +kernel

theorem ck_L_3 : okL tab M (cL.getD 3 default) 3 = true := by decide +kernel

theorem ck_L_4 : okL tab M (cL.getD 4 default) 4 = true := by decide +kernel

theorem ck_L_5 : okL tab M (cL.getD 5 default) 5 = true := by decide +kernel

theorem ck_L_6 : okL tab M (cL.getD 6 default) 6 = true := by decide +kernel

theorem ck_L_7 : okL tab M (cL.getD 7 default) 7 = true := by decide +kernel

theorem ck_L_8 : okL tab M (cL.getD 8 default) 8 = true := by decide +kernel

theorem ck_L_9 : okL tab M (cL.getD 9 default) 9 = true := by decide +kernel

theorem ck_L_10 : okL tab M (cL.getD 10 default) 10 = true := by decide +kernel

theorem ck_L_11 : okL tab M (cL.getD 11 default) 11 = true := by decide +kernel

theorem ck_L_12 : okL tab M (cL.getD 12 default) 12 = true := by decide +kernel

theorem ck_L_13 : okL tab M (cL.getD 13 default) 13 = true := by decide +kernel

theorem ck_L_14 : okL tab M (cL.getD 14 default) 14 = true := by decide +kernel

theorem ck_L_15 : okL tab M (cL.getD 15 default) 15 = true := by decide +kernel

theorem ck_L_16 : okL tab M (cL.getD 16 default) 16 = true := by decide +kernel

theorem ck_L_17 : okL tab M (cL.getD 17 default) 17 = true := by decide +kernel

theorem ck_L_18 : okL tab M (cL.getD 18 default) 18 = true := by decide +kernel

theorem ck_L_19 : okL tab M (cL.getD 19 default) 19 = true := by decide +kernel

theorem ck_L_20 : okL tab M (cL.getD 20 default) 20 = true := by decide +kernel

theorem ck_L_21 : okL tab M (cL.getD 21 default) 21 = true := by decide +kernel

theorem ck_L_22 : okL tab M (cL.getD 22 default) 22 = true := by decide +kernel

theorem ck_L_23 : okL tab M (cL.getD 23 default) 23 = true := by decide +kernel

theorem ck_L_24 : okL tab M (cL.getD 24 default) 24 = true := by decide +kernel

theorem ck_L_25 : okL tab M (cL.getD 25 default) 25 = true := by decide +kernel

theorem ck_L_26 : okL tab M (cL.getD 26 default) 26 = true := by decide +kernel

theorem ck_L_27 : okL tab M (cL.getD 27 default) 27 = true := by decide +kernel

theorem ck_L_28 : okL tab M (cL.getD 28 default) 28 = true := by decide +kernel

theorem ck_L : ∀ s, s < 29 → okL tab M (cL.getD s default) s = true := by
  intro s hs
  interval_cases s
  exacts [ck_L_0, ck_L_1, ck_L_2, ck_L_3, ck_L_4, ck_L_5, ck_L_6, ck_L_7, ck_L_8, ck_L_9, ck_L_10, ck_L_11, ck_L_12, ck_L_13, ck_L_14, ck_L_15, ck_L_16, ck_L_17, ck_L_18, ck_L_19, ck_L_20, ck_L_21, ck_L_22, ck_L_23, ck_L_24, ck_L_25, ck_L_26, ck_L_27, ck_L_28]

end FurioLombardo.Discharge.SelmerBasis.W7
