import FurioLombardo.Discharge.SelmerBasis.W7Data
import FurioLombardo.Discharge.SelmerBasis.W7DataL
import FurioLombardo.Discharge.SelmerBasis.W7DataN
import FurioLombardo.Discharge.SelmerBasis.AssemblyData

/-!
# Kernel checks of the F₂ data at w7 (generated by code/selmer-local-conditions/kernel_checks_w7.sh)

The rows `Akap`, `Amu`, `Cg` are the bits of the certificates; the forms `QI` (with the left inverse `TI`) and `QC`
annihilate them as required, and `dotRow 10 Cg QC = C7Rows`.
Every certificate is closed by `decide +kernel` in its own declaration. Data: W7Data*.lean (code/selmer-local-conditions/lean_data_w7.gp).
-/

namespace FurioLombardo.Discharge.SelmerBasis.W7

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis
open FurioLombardo.M2.Special (al7)

theorem kap_bits : ∀ i, i < 2 → Akap.getD i 0 = kapLow i + 256 * (cK.getD i default).bits := by
  decide +kernel

theorem mu_bits : ∀ i, i < 3 → Amu.getD i 0 = (pairs.getD i default).bits := by
  decide +kernel

theorem cgL_bits : ∀ s, s < 29 → Cg.getD s 0 = bitsL (cL.getD s default) := by
  decide +kernel

theorem cgN_bits : ∀ s, s < 53 → Cg.getD (29 + s) 0 = bitsN (cN.getD s default) := by
  decide +kernel

theorem annI : annOK 10 (fun l => Akap.getD l 0) 2 (fun q => QI.getD q 0) nQI = true := by
  decide +kernel

theorem leftInv : leftInvOK (fun q => dotRow 10 (fun i => Amu.getD i 0) (QI.getD q 0) 3) nQI 3
    (fun q => TI.getD q 0) = true := by
  decide +kernel

theorem annCk : annOK 10 (fun l => Akap.getD l 0) 2 (fun q => QC.getD q 0) 5 = true := by
  decide +kernel

theorem annCm : annOK 10 (fun i => Amu.getD i 0) 3 (fun q => QC.getD q 0) 5 = true := by
  decide +kernel

theorem c7_rows : ∀ q, q < 5 → dotRow 10 (fun s => Cg.getD s 0) (QC.getD q 0) 82 =
    Assembly.C7Rows.getD q 0 := by
  decide +kernel

end FurioLombardo.Discharge.SelmerBasis.W7
