import FurioLombardo.Discharge.SelmerBasis.W7Data
import FurioLombardo.Discharge.SelmerBasis.W7DataN

/-!
# Kernel checks of the gensN certificates at w7, part 1 (generated by code/selmer-local-conditions/kernel_checks_w7.sh)

`ck_N_s` (27 ≤ s < 53): the `KCert`s of `gensN s` at the components 2, 3 and its `FCert` at `F'`.
Every certificate is closed by `decide +kernel` in its own declaration. Data: W7Data*.lean (code/selmer-local-conditions/lean_data_w7.gp).
-/

namespace FurioLombardo.Discharge.SelmerBasis.W7

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis
open FurioLombardo.M2.Special (al7)

theorem ck_N_27 : okN tab M (cN.getD 27 default) 27 = true := by decide +kernel

theorem ck_N_28 : okN tab M (cN.getD 28 default) 28 = true := by decide +kernel

theorem ck_N_29 : okN tab M (cN.getD 29 default) 29 = true := by decide +kernel

theorem ck_N_30 : okN tab M (cN.getD 30 default) 30 = true := by decide +kernel

theorem ck_N_31 : okN tab M (cN.getD 31 default) 31 = true := by decide +kernel

theorem ck_N_32 : okN tab M (cN.getD 32 default) 32 = true := by decide +kernel

theorem ck_N_33 : okN tab M (cN.getD 33 default) 33 = true := by decide +kernel

theorem ck_N_34 : okN tab M (cN.getD 34 default) 34 = true := by decide +kernel

theorem ck_N_35 : okN tab M (cN.getD 35 default) 35 = true := by decide +kernel

theorem ck_N_36 : okN tab M (cN.getD 36 default) 36 = true := by decide +kernel

theorem ck_N_37 : okN tab M (cN.getD 37 default) 37 = true := by decide +kernel

theorem ck_N_38 : okN tab M (cN.getD 38 default) 38 = true := by decide +kernel

theorem ck_N_39 : okN tab M (cN.getD 39 default) 39 = true := by decide +kernel

theorem ck_N_40 : okN tab M (cN.getD 40 default) 40 = true := by decide +kernel

theorem ck_N_41 : okN tab M (cN.getD 41 default) 41 = true := by decide +kernel

theorem ck_N_42 : okN tab M (cN.getD 42 default) 42 = true := by decide +kernel

theorem ck_N_43 : okN tab M (cN.getD 43 default) 43 = true := by decide +kernel

theorem ck_N_44 : okN tab M (cN.getD 44 default) 44 = true := by decide +kernel

theorem ck_N_45 : okN tab M (cN.getD 45 default) 45 = true := by decide +kernel

theorem ck_N_46 : okN tab M (cN.getD 46 default) 46 = true := by decide +kernel

theorem ck_N_47 : okN tab M (cN.getD 47 default) 47 = true := by decide +kernel

theorem ck_N_48 : okN tab M (cN.getD 48 default) 48 = true := by decide +kernel

theorem ck_N_49 : okN tab M (cN.getD 49 default) 49 = true := by decide +kernel

theorem ck_N_50 : okN tab M (cN.getD 50 default) 50 = true := by decide +kernel

theorem ck_N_51 : okN tab M (cN.getD 51 default) 51 = true := by decide +kernel

theorem ck_N_52 : okN tab M (cN.getD 52 default) 52 = true := by decide +kernel

theorem ck_N1 : ∀ s, 27 ≤ s → s < 53 → okN tab M (cN.getD s default) s = true := by
  intro s ha hs
  interval_cases s
  exacts [ck_N_27, ck_N_28, ck_N_29, ck_N_30, ck_N_31, ck_N_32, ck_N_33, ck_N_34, ck_N_35, ck_N_36, ck_N_37, ck_N_38, ck_N_39, ck_N_40, ck_N_41, ck_N_42, ck_N_43, ck_N_44, ck_N_45, ck_N_46, ck_N_47, ck_N_48, ck_N_49, ck_N_50, ck_N_51, ck_N_52]

end FurioLombardo.Discharge.SelmerBasis.W7
