import FurioLombardo.Discharge.SelmerBasis.W7Data

/-!
# Kernel checks of the w7 model, points, pairs and kappa (generated by code/selmer-local-conditions/kernel_checks_w7.sh)

The power table, the model `M`, the four points, the three pairs (`okU`, `toPt.okT`, `okC`) and the
certificates of `al7`, `-1` at `F'`.
Every certificate is closed by `decide +kernel` in its own declaration. Data: W7Data*.lean (code/selmer-local-conditions/lean_data_w7.gp).
-/

namespace FurioLombardo.Discharge.SelmerBasis.W7

open FurioLombardo.M1 FurioLombardo.Discharge.SelmerBasis
open FurioLombardo.M2.Special (al7)

theorem tab_len : tab.length = 9 := by decide +kernel

theorem tab_zero : tab.getD 0 [] = al7 := by decide +kernel

theorem ck_tab_0 : powOK tab (tabK.getD 0 0) 0 = true := by decide +kernel

theorem ck_tab_1 : powOK tab (tabK.getD 1 0) 1 = true := by decide +kernel

theorem ck_tab_2 : powOK tab (tabK.getD 2 0) 2 = true := by decide +kernel

theorem ck_tab_3 : powOK tab (tabK.getD 3 0) 3 = true := by decide +kernel

theorem ck_tab_4 : powOK tab (tabK.getD 4 0) 4 = true := by decide +kernel

theorem ck_tab_5 : powOK tab (tabK.getD 5 0) 5 = true := by decide +kernel

theorem ck_tab_6 : powOK tab (tabK.getD 6 0) 6 = true := by decide +kernel

theorem ck_tab_7 : powOK tab (tabK.getD 7 0) 7 = true := by decide +kernel

theorem ck_tab : ∀ i, i < 8 → powOK tab (tabK.getD i 0) i = true := by
  intro i hi
  interval_cases i
  exacts [ck_tab_0, ck_tab_1, ck_tab_2, ck_tab_3, ck_tab_4, ck_tab_5, ck_tab_6, ck_tab_7]

theorem ck_M : M.ok tab = true := by decide +kernel

theorem ck_pt_0 : (pts.getD 0 default).ok tab = true := by decide +kernel

theorem ck_pt_1 : (pts.getD 1 default).ok tab = true := by decide +kernel

theorem ck_pt_2 : (pts.getD 2 default).ok tab = true := by decide +kernel

theorem ck_pt_3 : (pts.getD 3 default).ok tab = true := by decide +kernel

theorem ck_pt : ∀ i, i < 4 → (pts.getD i default).ok tab = true := by
  intro i hi
  interval_cases i
  exacts [ck_pt_0, ck_pt_1, ck_pt_2, ck_pt_3]

theorem ck_pair_0 : (pairs.getD 0 default).okU tab pts = true ∧
    (pairs.getD 0 default).toPt.okT = true ∧ (pairs.getD 0 default).okC tab M = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_pair_1 : (pairs.getD 1 default).okU tab pts = true ∧
    (pairs.getD 1 default).toPt.okT = true ∧ (pairs.getD 1 default).okC tab M = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_pair_2 : (pairs.getD 2 default).okU tab pts = true ∧
    (pairs.getD 2 default).toPt.okT = true ∧ (pairs.getD 2 default).okC tab M = true := by
  refine ⟨?_, ?_, ?_⟩ <;> decide +kernel

theorem ck_pair : ∀ i, i < 3 → (pairs.getD i default).okU tab pts = true ∧
    (pairs.getD i default).toPt.okT = true ∧ (pairs.getD i default).okC tab M = true := by
  intro i hi
  interval_cases i
  exacts [ck_pair_0, ck_pair_1, ck_pair_2]

theorem ck_K_0 : (cK.getD 0 default).ok tab M.N M.E4U (kapXE 0) (.int 0) = true := by decide +kernel

theorem ck_K_1 : (cK.getD 1 default).ok tab M.N M.E4U (kapXE 1) (.int 0) = true := by decide +kernel

theorem ck_K : ∀ i, i < 2 → (cK.getD i default).ok tab M.N M.E4U (kapXE i) (.int 0) = true := by
  intro i hi
  interval_cases i
  exacts [ck_K_0, ck_K_1]

end FurioLombardo.Discharge.SelmerBasis.W7
