\\ descent_avoid_data.gp: writes lean/FurioLombardo/M1/DataAvoid.lean: for p = 3 and p = 439, the monic factors of f mod p
\\ (lower coefficients in [0, p)), the index of the degree one factor carrying pi3 (resp. pi439), and for every
\\ other factor phi the inverse of rho_phi(pi) in F_p[x]/(phi) (list, constant first). Also DB^-1, Dz^-1 mod p.
\\ Rechecked by the Lean kernel (SSet.lean).
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_search_lib.gp");
zkpol(a) = sum(i = 1, 21, a[i] * Polrev(zkNum[i], b));
DBv = polresultant(K21, K21');
lowl(ph, p) = { my(v = Vecrev(lift(ph))); vector(#v - 1, i, lift(Mod(v[i], p))) };
data = vector(2);
{
foreach([[3, G[17]], [439, G[18]]], pg, my(p = pg[1], g = pg[2], fa = factor(K21 * Mod(1, p))[, 1], k = #fa, i0 = 0, ws = vector(k));
  for (j = 1, k, my(ph = fa[j], w = Mod(Mod(zkpol(g), p), ph) / Mod(Dz, p));
    if (w == 0, if (poldegree(ph) != 1 || i0, error("zero at ", j)); i0 = j; ws[j] = [0],
      ws[j] = Vecrev(lift(lift(1 / w)), poldegree(ph)); ws[j] = vector(#ws[j], i, lift(Mod(ws[j][i], p)))));
  if (!i0, error("no zero"));
  data[if (p == 3, 1, 2)] = [p, vector(k, j, lowl(fa[j], p)), i0 - 1, ws, lift(Mod(DBv, p)^-1), lift(Mod(Dz, p)^-1)];
  print("p = ", p, ": ", k, " factors, degrees ", vector(k, j, poldegree(fa[j])), ", zero at factor ", i0 - 1, " (0-based)"));
}
if (DBv != DB0 && 0, error(""));
print("DB = ", DBv);
out = Str(LEANDIR, "FurioLombardo/M1/DataAvoid.lean");
system(Str("rm -f ", out));
write(out, "/-! Data of lane M1 (generated by code/descent/descent_avoid_data.gp, PARI/GP): factors of f modulo 3 and 439, the\ndegree one factor where pi3 (resp. pi439) vanishes, and inverses of the images of pi3 (resp. pi439) at the other\nfactors. Rechecked by the kernel in SSet.lean. -/\n\nnamespace FurioLombardo.M1\n\nset_option maxRecDepth 100000\n");
{
foreach([["3", data[1]], ["439", data[2]]], nd, my(n = nd[1], d = nd[2]);
  write(out, "/-- Monic factors of f modulo ", n, " (lower coefficients). -/\ndef avFac", n, " : List (List Int) :=\n  ", lstl(d[2]), "\n");
  write(out, "/-- Index of the factor where the generator vanishes. -/\ndef avIdx", n, " : Nat := ", d[3], "\n");
  write(out, "/-- Inverses of the images of the generator at the factors (`[0]` at `avIdx", n, "`). -/\ndef avInv", n, " : List (List Int) :=\n  ", lstl(d[4]), "\n");
  write(out, "/-- `DB⁻¹` modulo ", n, ". -/\ndef avUB", n, " : Int := ", d[5], "\n");
  write(out, "/-- `Dz⁻¹` modulo ", n, ". -/\ndef avUD", n, " : Int := ", d[6], "\n"));
}
write(out, "end FurioLombardo.M1");
print("written ", out);
