\\ descent_bezout_data.gp: writes lean/FurioLombardo/M1/DataBezout.lean: s f + t f' = DB (resultant of f, f'), used for
\\ the residue homomorphisms (DB O is contained in Z[theta]).
default(parisizemax, 2*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_data_lib.gp");
f = subst(K21, b, 'X); fp = deriv(f);
r = polresultantext(f, fp); us = r[1]; ut = r[2]; DB = r[3];
if (us*f + ut*fp != DB || denominator(content(us)) != 1 || denominator(content(ut)) != 1, error("bezout"));
print("DB = ", factor(DB));
out = Str(LEANDIR, "FurioLombardo/M1/DataBezout.lean");
write1(out, ""); system(Str("rm -f ", out));
write(out, "/-! Data of lane M1 (generated by code/descent/descent_bezout_data.gp, PARI/GP): the Bezout identity\n`s f + t f' = DB` in `ℤ[X]` for the defining polynomial `f` of K21 (`DB` is the resultant of `f` and `f'`). -/\n\nnamespace FurioLombardo.M1\n\nset_option maxRecDepth 100000\n");
write(out, "/-- The Bezout constant (resultant of f and f'). -/\ndef DB : Int := ", DB, "\n");
write(out, "/-- Bezout cofactor of f (constant term first). -/\ndef sL : List Int :=\n  ", lst(Vecrev(us)), "\n");
write(out, "/-- Bezout cofactor of f' (constant term first). -/\ndef tL : List Int :=\n  ", lst(Vecrev(ut)), "\n");
write(out, "/-- Coefficients of f' (constant term first). -/\ndef fdL : List Int :=\n  ", lst(Vecrev(fp)), "\n");
write(out, "end FurioLombardo.M1");
print("written ", out);
