\\ descent_bruin_data.gp: data of the Bruin step of M1 (lean/FurioLombardo/M1/DataBruin.lean). Not trusted: Lean
\\ rechecks every identity. Conic coefficients Q1, Q2, Q3 and cB, d0, d1 on the zk basis; the coefficients of
\\ dJ/dx, dJ/dy, dJ/dz (J the Jacobian cubic of the net); N = cS M^-1 with M the six matrix (rows Q1, Q2, Q3,
\\ dJ/dx, dJ/dy, dJ/dz on x^2, xy, xz, y^2, yz, z^2) and cS = 2^13 7^13 pi3^12 pi439^12, with pi3, pi439 the
\\ generators gensL[16], gensL[17] read from lean/FurioLombardo/M1/DataGens.lean (extracted to /tmp by sed).
\\ Run: (echo "gensLean = ["; awk '/def gensL /,/\]\]/' ../../FurioLombardo/M1/DataGens.lean | sed '1d; s/^  \[\[/[/; s/^  //; s/\]\]$/]/'; echo "];") | tr -d '\n' | sed 's/\]\[/],[/g' > /tmp/m1_gensLean.gp
\\ then gp -q descent_bruin_data.gp < /dev/null
\\ (gp continues after an error at top level, so everything runs in main(), which returns before writing on failure)
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_data_lib.gp");
read("/tmp/m1_gensLean.gp");
isint(v) = { for (i = 1, #v, if (denominator(v[i]) != 1, return(0))); 1 };
maxdig(V) = vecmax(apply(v -> vecmax(apply(n -> #digits(abs(n) + 1), Vec(v))), V));
lst3(V) = { my(s = "["); for (i = 1, #V, s = Str(s, lstl(V[i]), if (i < #V, ",\n  ", ""))); Str(s, "]") };
main() = {
  my(Gb, Nzk, cSb, cBZ, d0Z, d1Z, Jm, J, Dc, DZ, Mm, Nm, o);
  Gb = gensLean;
  for (i = 1, 3, for (m = 1, 6, if (!isint(QcZ[i][m]), print("FAIL Q not integral"); return(0))));
  cBZ = zkc(cB); d0Z = zkc(d0); d1Z = zkc(d1);
  if (!isint(cBZ) || !isint(d0Z) || !isint(d1Z), print("FAIL cB, d0, d1 not integral"); return(0));
  if (Mod(Q1*Q3 - Q2^2 - cB*F, K21) != 0, print("FAIL Bruin identity"); return(0));
  Jm = matrix(3, 3, i, j, deriv(Qs[i], [x, y, z][j])); J = matdet(Jm);
  Dc = vector(3, l, coefs2(deriv(J, [x, y, z][l])));
  DZ = vector(3, l, vector(6, m, zkc(Dc[l][m])));
  for (l = 1, 3, for (m = 1, 6, if (!isint(DZ[l][m]), print("FAIL D not integral"); return(0))));
  Mm = matrix(6, 6, r, m, if (r <= 3, Qc[r][m], Dc[r-3][m]));
  cSb = Mod(2^13 * 7^13, K21) * Mod(zkr(Gb[17]), K21)^12 * Mod(zkr(Gb[18]), K21)^12;
  Nm = cSb * Mm^-1;
  Nzk = matrix(6, 6, i, j, zkc(Nm[i, j]));
  for (i = 1, 6, for (j = 1, 6, if (!isint(Nzk[i, j]), print("FAIL N not integral"); return(0))));
  if (Nm * Mm != cSb * matid(6), print("FAIL N M != cS I"); return(0));
  if (idealnorm(nf, zkr(Gb[17])) != 3 || abs(idealnorm(nf, zkr(Gb[18]))) != 439, print("FAIL generator norms"); return(0));
  print("checks passed; max zk digits: Q ", maxdig(concat(QcZ)), ", D ", maxdig(concat(DZ)),
    ", N ", maxdig(concat(vector(6, i, vector(6, j, Nzk[i, j])))), ", cB ", maxdig([cBZ]), ", d ", maxdig([d0Z, d1Z]));
  o = Str(LEANDIR, "FurioLombardo/M1/DataBruin.lean");
  write1(o, "/-! Data of lane M1 (generated by code/descent/descent_bruin_data.gp, PARI/GP): zk coordinates of the coefficients of the\nconics Q1, Q2, Q3 (on x^2, xy, xz, y^2, yz, z^2), of cB, d0, d1 (Q1 Q3 - Q2^2 = cB F), of the coefficients of the\npartial derivatives of the Jacobian cubic of the net, and of N = cS M^-1 (M the six matrix). Rechecked by the kernel\nin BruinCheck.lean. -/\n\nnamespace FurioLombardo.M1\n\nset_option maxRecDepth 100000\n\n");
  write1(o, "/-- Conic coefficients: `qcL[i][m]` is the coefficient of monomial `m` in `Q_(i+1)`. -/\ndef qcL : List (List (List Int)) :=\n  ");
  write1(o, lst3(vector(3, i, vector(6, m, Vec(QcZ[i][m]))))); write1(o, "\n\n");
  write1(o, "/-- `cB`. -/\ndef cBL : List Int := "); write1(o, lst(Vec(cBZ))); write1(o, "\n\n");
  write1(o, "/-- `delta0`. -/\ndef d0L : List Int := "); write1(o, lst(Vec(d0Z))); write1(o, "\n\n");
  write1(o, "/-- `delta1`. -/\ndef d1L : List Int := "); write1(o, lst(Vec(d1Z))); write1(o, "\n\n");
  write1(o, "/-- Coefficients of `dJ/dx_l`. -/\ndef dJL : List (List (List Int)) :=\n  ");
  write1(o, lst3(vector(3, l, vector(6, m, Vec(DZ[l][m]))))); write1(o, "\n\n");
  write1(o, "/-- `N = cS M^-1`. -/\ndef nL : List (List (List Int)) :=\n  ");
  write1(o, lst3(vector(6, i, vector(6, j, Vec(Nzk[i, j]))))); write1(o, "\n\n");
  write1(o, "/-- `cS = 2^13 7^13 pi3^12 pi439^12`. -/\ndef cSL : List Int := "); write1(o, lst(Vec(zkc(cSb)))); write1(o, "\n\n");
  write1(o, "end FurioLombardo.M1\n");
  print("written ", o);
  1;
}
main();
