\\ field_data.gp: writes lean/FurioLombardo/M1/DataField.lean (zk numerators, Dz, multiplication table).
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_data_lib.gp");
print("Dz = ", Dz, "; zk[1] = ", zk[1], "; theta = ", zkc(b)~);
\\ check the table against the power basis
nchk = 0; { for (i = 1, 21, for (j = 1, 21, my(l = Mod(zk[i] * zk[j], K21), r = Mod(zkr(tab[i][j]), K21)); if (l != r, error("table")); nchk++)); }
if (nchk != 441, error("table check incomplete"));
print("table checked");
out = Str(LEANDIR, "FurioLombardo/M1/DataField.lean");
write1(out, ""); system(Str("rm -f ", out));
write(out, "/-! Data of lane M1 (generated by code/descent/field_data.gp, PARI/GP): the integral basis `zk` of PARI\nfor K21 as power basis numerators over `Dz`, and its multiplication table (every entry rechecked in Lean). -/\n\nnamespace FurioLombardo.M1\n\nset_option maxRecDepth 100000\n");
write(out, "/-- Common denominator of the integral basis. -/\ndef Dz : Nat := ", Dz, "\n");
write(out, "/-- Numerators of the 21 basis elements in the power basis `1, θ, ..., θ^20` (constant first). -/\ndef zkNum : List (List Int) :=\n  ", lstl(zkNum), "\n");
write(out, "/-- Multiplication table: `zkTab[i][j]` = zk coordinates of `w i * w j`. -/\ndef zkTab : List (List (List Int)) :=\n  [", concat(vector(21, i, Str(lstl(vector(21, j, tab[i][j]~)), if (i < 21, ",\n  ", "")))), "]\n");
write(out, "end FurioLombardo.M1");
print("written ", out);
