\\ known_classes_sqrt_data.gp: square roots for the two classes that survive the sieve of M1
\\ (lean/FurioLombardo/M1/DataKnown.lean): t_k with delta_k * G_e = t_k^2, e = survE 4 (k = 0) and survE 6 (k = 1),
\\ the inverses of the units delta_0, delta_1,
\\ G_e the product of the generators selected by e (gensLean, DataGens.lean), delta_k = d0, d1 of bruin_form.gp.
\\ Inputs: /tmp/m1_gensLean.gp and /tmp/m1w/surv.gp (see local_steps_design.gp). Not trusted: the kernel rechecks the identities.
\\ Run: gp -q known_classes_sqrt_data.gp < /dev/null
default(parisizemax, 2*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_data_lib.gp");
read("/tmp/m1_gensLean.gp");
read("/tmp/m1w/surv.gp");
Gz = vector(18, i, gensLean[i]~);
Gel(e) = prod(i = 1, 18, if (e[i], Mod(zkr(Gz[i]), K21), 1));
main() = {
  my(ts = vector(2), o, ds = [d0, d1], ks = [5, 7]);
  for (k = 1, 2,
    my(a = Mod(ds[k], K21) * Gel(surv[ks[k]]), r = nfroots(K21, X^2 - lift(a)));
    if (#r == 0, print("FAIL no square root for k = ", k - 1); return(0));
    ts[k] = zkc(r[1]);
    if (denominator(content(ts[k])) != 1, print("FAIL not integral"); return(0));
    if (Mod(zkr(ts[k]), K21)^2 != a, print("FAIL check"); return(0));
    print("k = ", k - 1, ": selected generators ", [i - 1 | i <- [1..18], surv[ks[k]][i]], ", max digits ", vecmax(apply(n -> #digits(abs(n) + 1), Vec(ts[k])))));
  \\ the other six survivors are not squares times delta0 or delta1 (consistency with the local kills)
  for (s = 1, 8, if (s != 5 && s != 7, for (k = 1, 2, if (#nfroots(K21, X^2 - lift(Mod(ds[k], K21) * Gel(surv[s]))) > 0, print("FAIL survivor ", s - 1, " is delta", k - 1, " class"); return(0)))));
  o = Str(LEANDIR, "FurioLombardo/M1/DataKnown.lean");
  system(Str("rm -f ", o));
  write1(o, "/-! Data of lane M1 (generated by code/descent/known_classes_sqrt_data.gp, PARI/GP): square roots `t_k` with\n`delta_k * G_e = t_k ^ 2` for the survivors `survE 4` (`k = 0`) and `survE 6` (`k = 1`), and the inverses of\n`delta_0`, `delta_1`. Rechecked by the kernel in\nSelmerSet.lean. -/\n\nnamespace FurioLombardo.M1\n\n");
  write1(o, Str("/-- `t_0`. -/\ndef t0L : List Int := ", lst(Vec(ts[1])), "\n\n"));
  write1(o, Str("/-- `t_1`. -/\ndef t1L : List Int := ", lst(Vec(ts[2])), "\n\n"));
  write1(o, Str("/-- `delta_0^-1`. -/\ndef d0iL : List Int := ", lst(Vec(zkc(1/Mod(d0, K21)))), "\n\n"));
  write1(o, Str("/-- `delta_1^-1`. -/\ndef d1iL : List Int := ", lst(Vec(zkc(1/Mod(d1, K21)))), "\n\n"));
  write1(o, "end FurioLombardo.M1\n");
  print("written ", o);
  1;
}
main();
