\\ sieve_3adic_data.gp: data of the 3-adic step of the Lean sieve of M1 (lean/FurioLombardo/M1/Data3.lean), the
\\ residue map O_K21 -> Z/27, theta -> 17 (the degree one prime pi3 above 3, theta = -1 mod 3). Not trusted: every
\\ datum is recomputed by the kernel in lean/FurioLombardo/M1/Local3.lean.
\\ Data: uB = DB^-1 mod 27, uD = Dz^-1 mod 27, the residues of the coefficients of Q1 and Q3 (on x^2, xy, xz, y^2,
\\ yz, z^2), and the residues of G_k = prod of the generators selected by the survivor k of the good prime sieve,
\\ k = 0..3 (0-based). It also runs the exact integer test that the kernel runs (three planes x = 1, y = 1, z = 1,
\\ coordinates in [0, 27)).
\\ Inputs (extracted from the Lean data files, see descent_bruin_data.gp and local_steps_design.gp):
\\   /tmp/m1_gensLean.gp (gensLean = the 18 generators, zk coordinates) and /tmp/m1w/surv.gp (surv = the survivors).
\\ Run: gp -q sieve_3adic_data.gp < /dev/null
default(parisizemax, 2*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_data_lib.gp");
read("/tmp/m1_gensLean.gp");
read("/tmp/m1w/surv.gp");
N27 = 27;
\\ residue of the element with zk coordinates v: uD * (sum_j v_j zkNum_j)(r) mod N
res27(v, r, uD) = lift(Mod(uD, N27) * sum(j = 1, 21, v[j] * subst(Pol(Vecrev(zkNum[j]), 'x), 'x, r)));
issq27(t) = { for (u = 0, N27 - 1, if ((u * u - t) % N27 == 0, return(1))); 0 };
qz(c, P) = c[1]*P[1]^2 + c[2]*P[1]*P[2] + c[3]*P[1]*P[3] + c[4]*P[2]^2 + c[5]*P[2]*P[3] + c[6]*P[3]^2;
Fz(P) = substvec(F, [x, y, z], P);
main() = {
  my(N = N27, r = 17, f, fp, rs, DB, uB, uD, gv, q1, q3, gk, npts, ok, o);
  f = subst(K21, b, 'X); fp = deriv(f);
  rs = polresultantext(f, fp); DB = rs[3];
  if (subst(f, 'X, r) % N != 0, print("FAIL root"); return(0));
  uB = lift(Mod(DB, N)^-1); uD = lift(Mod(Dz, N)^-1);
  gv = vector(18, i, res27(gensLean[i], r, uD));
  q1 = vector(6, m, res27(QcZ[1][m], r, uD));
  q3 = vector(6, m, res27(QcZ[3][m], r, uD));
  gk = vector(4, k, lift(prod(i = 1, 18, if (surv[k][i], Mod(gv[i], N), Mod(1, N)))));
  \\ cross-check of res against the field arithmetic: rho(a) = (Dz a)(r) / Dz mod N
  for (i = 1, 18, if (Mod(subst(lift(Mod(zkr(gensLean[i]), K21) * Dz), b, r), N) / Mod(Dz, N) != Mod(gv[i], N),
    print("FAIL res gen ", i); return(0)));
  print("uB = ", uB, ", uD = ", uD);
  print("gv = ", gv);
  print("q1 = ", q1, ", q3 = ", q3);
  print("gk = ", gk);
  \\ the kernel test: on each plane, F = 0 mod 27 implies that for every k < 4 one of q1(P) G_k, q3(P) G_k is a nonsquare
  npts = 0; ok = 1;
  for (u = 0, N - 1, for (v = 0, N - 1,
    foreach([[u, v, 1], [1, u, v], [u, 1, v]], P,
      if (Fz(P) % N == 0,
        npts++;
        for (k = 1, 4, if (issq27(qz(q1, P) * gk[k]) && issq27(qz(q3, P) * gk[k]), print("SURVIVES ", P, " k = ", k - 1); ok = 0))))));
  print("plane points with F = 0 mod 27 (with repetitions): ", npts, "; all killed: ", ok);
  if (!ok, return(0));
  o = Str(LEANDIR, "FurioLombardo/M1/Data3.lean");
  write1(o, ""); system(Str("rm -f ", o));
  write1(o, "/-! Data of lane M1 (generated by code/descent/sieve_3adic_data.gp, PARI/GP): the residue map `𝓞 K21 → ℤ/27`,\n`θ ↦ 17`. Inverses of `DB` and `Dz` modulo 27, residues of the coefficients of `Q1` and `Q3` (on x², xy, xz, y²,\nyz, z²) and of `G_k` for the survivors `k < 4` of the good prime sieve. Rechecked by the kernel in Local3.lean. -/\n\nnamespace FurioLombardo.M1\n\n");
  write1(o, Str("/-- `DB⁻¹` modulo 27. -/\ndef uB27 : Int := ", uB, "\n\n"));
  write1(o, Str("/-- `Dz⁻¹` modulo 27. -/\ndef uD27 : Int := ", uD, "\n\n"));
  write1(o, Str("/-- Residues of the coefficients of `Q1` and `Q3`. -/\ndef q27 : List (List Int) := [", lst(q1), ", ", lst(q3), "]\n\n"));
  write1(o, Str("/-- Residues of `G_k` (`k < 4`). -/\ndef g27 : List Int := ", lst(gk), "\n\n"));
  write1(o, "end FurioLombardo.M1\n");
  print("written ", o);
}
main();
