\\ sieve_data.gp: data of the sieve of M1 (lean/FurioLombardo/M1/DataSieve.lean). Not trusted: every datum is
\\ rechecked by the Lean kernel (SieveCheck.lean). Same method as sieve_design_run.gp, without bnfinit: the generators
\\ are read from lean/FurioLombardo/M1/DataGens.lean (extracted to /tmp/m1_gensLean.gp, see descent_bruin_data.gp).
\\ Rings R = F_p[x]/(phi), p = 5, 11, 13, 17, 19, 23, phi the monic irreducible factors of f mod p;
\\ rho(zkE a) = Dz^-1 sum a_i zkNum_i(x); chi(w) = w^((q-1)/2), q = p^deg phi. Normalized points of C(F_p):
\\ [x, 1, z], [1, 0, z], [0, 0, 1]. For each point and ring: conic index i (0 for Q1, 2 for Q3, the first whose
\\ value is a unit) and the bit of its character. Then the 3-adic kill in Z/27 (theta -> 17).
\\ Run: gp -q sieve_data.gp < /dev/null
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_data_lib.gp");
read("/tmp/m1_gensLean.gp");
Fi(P) = substvec(F, [x, y, z], P);
evq(cr, P) = sum(j = 1, 6, cr[j] * P[1]^mons2[j][1] * P[2]^mons2[j][2] * P[3]^mons2[j][3]);
zkpol(a) = sum(i = 1, 21, a[i] * Polrev(zkNum[i], b));
rho(a, p, phi) = Mod(Mod(zkpol(a), p), phi) / Mod(Dz, p);
chi(w, p, phi) = { my(q = p^poldegree(phi), c = w^((q-1)/2)); if (c == 1, 0, if (c == -1, 1, -1)) };
normpts(p) = {
  my(L = List());
  for (x0 = 0, p-1, for (z0 = 0, p-1, if (Fi([x0, 1, z0]) % p == 0, listput(L, [x0, 1, z0]))));
  for (z0 = 0, p-1, if (Fi([1, 0, z0]) % p == 0, listput(L, [1, 0, z0])));
  if (Fi([0, 0, 1]) % p == 0, listput(L, [0, 0, 1]));
  Vec(L);
}
\\ residue list of an element (length deg phi, entries in [0, p))
rl(w, p, phi) = { my(d = poldegree(phi), v = Vecrev(lift(lift(w)), d)); vector(d, k, lift(Mod(v[k], p))) };
glof(phi) = { my(d = poldegree(phi)); vector(d, k, lift(Mod(polcoef(phi, k-1), p0))) };
bstr(v) = { my(s = "["); for (i = 1, #v, s = Str(s, if (v[i], "true", "false"), if (i < #v, ", ", ""))); Str(s, "]") };
Gz = vector(18, i, gensLean[i]~);
main() = {
  my(rings = List(), bits = List(), gens = List(), qds = List(), blocks = List(), pts = List(), choices = List(), Vs = List(), off = 0, o, M, Lm, combos, surv, e);
  forprime(p = 5, 23, if (p == 7, next);
    my(fa = factor(K21 * Mod(1, p))[, 1], k = #fa, phis = vector(k, j, lift(fa[j])), P = normpts(p), ch = List(), im = List());
    p0 = p;
    for (j = 1, k, my(phi = phis[j], d = poldegree(phi));
      if (pollead(phi) != 1, print("FAIL not monic"); return(0));
      listput(rings, [p, glof(phi), lift(Mod(1/(Mod(polresultant(K21, deriv(K21)), p)), p)), lift(1/Mod(Dz, p))]);
      listput(bits, vector(18, i, my(c = chi(rho(Gz[i], p, phi), p, phi)); if (c < 0, print("FAIL gen unit"); return(0)); c));
      listput(gens, vector(18, i, rl(rho(Gz[i], p, phi), p, phi)));
      listput(qds, vector(3, i, if (i == 2, [], vector(6, m, rl(rho(QcZ[i][m], p, phi), p, phi))))));
    foreach(P, Q, my(v = vector(k), cc = vector(k));
      for (j = 1, k, my(phi = phis[j], q1 = evq(vector(6, t, rho(QcZ[1][t], p, phi)), Q), q3 = evq(vector(6, t, rho(QcZ[3][t], p, phi)), Q), c = chi(q1, p, phi), ci = 0);
        if (c < 0, c = chi(q3, p, phi); ci = 2);
        if (c < 0, print("FAIL both non units at ", p, " ", Q, " ring ", j); return(0));
        v[j] = c; cc[j] = [ci, c]);
      listput(ch, cc); listput(im, v));
    listput(blocks, [off, k]); off += k;
    listput(pts, P); listput(choices, Vec(ch)); listput(Vs, Set(im)));
  M = matrix(#rings, 18, r, i, bits[r][i]);
  if (matrank(M * Mod(1, 2)) != 18, print("FAIL rank"); return(0));
  Lm = lift(matsolve(M~ * M * Mod(1,2), M~ * Mod(1,2)));
  if (lift(Lm * M * Mod(1,2)) != matid(18), print("FAIL left inverse"); return(0));
  combos = [[]];
  foreach(Vec(Vs), V, my(nc = List()); foreach(combos, c, foreach(V, v, listput(nc, concat(c, v)))); combos = Vec(nc));
  surv = List();
  foreach(combos, c, e = lift(Lm * c~ * Mod(1,2)); if (lift(M * e * Mod(1,2)) == c~, listput(surv, e~)));
  surv = Vec(Set(Vec(surv)));
  print("rings ", #rings, ", combinations ", #combos, ", survivors ", #surv);
  print("survivors ", surv);
  o = Str(LEANDIR, "FurioLombardo/M1/DataSieve.lean");
  write1(o, "/-! Data of the sieve of lane M1 (generated by code/descent/sieve_data.gp, PARI/GP). Rechecked by the kernel in\nSieveCheck.lean. -/\n\nnamespace FurioLombardo.M1\n\nset_option maxRecDepth 100000\n\n");
  write1(o, "/-- Rings: `(p, lower coefficients of phi, DB^-1 mod p, Dz^-1 mod p)`. -/\ndef sieveRings : List (Nat × List Int × Int × Int) :=\n  [");
  for (r = 1, #rings, my(R = rings[r]); write1(o, Str("(", R[1], ", ", lst(R[2]), ", ", R[3], ", ", R[4], ")", if (r < #rings, ",\n  ", "]\n\n"))));
  write1(o, "/-- Character bits of the eighteen generators, per ring. -/\ndef sieveBits : List (List Bool) :=\n  [");
  for (r = 1, #rings, write1(o, Str(bstr(bits[r]), if (r < #rings, ",\n  ", "]\n\n"))));
  write1(o, "/-- Residues of the eighteen generators, per ring. -/\ndef sieveGen : List (List (List Int)) :=\n  [");
  for (r = 1, #rings, write1(o, Str(lstl(gens[r]), if (r < #rings, ",\n  ", "]\n\n"))));
  write1(o, "/-- Residues of the coefficients of Q1 and Q3 (Q2 left empty), per ring. -/\ndef sieveQ : List (List (List (List Int))) :=\n  [");
  for (r = 1, #rings, my(Qd = qds[r]); write1(o, Str("[", lstl(Qd[1]), ", [], ", lstl(Qd[3]), "]", if (r < #rings, ",\n  ", "]\n\n"))));
  write1(o, "/-- Blocks of rings per prime: `(offset, number of rings)`. -/\ndef sieveBlk : List (Nat × Nat) := [");
  for (i = 1, #blocks, write1(o, Str("(", blocks[i][1], ", ", blocks[i][2], ")", if (i < #blocks, ", ", "]\n\n"))));
  write1(o, "/-- Normalized points of C(F_p), per prime. -/\ndef sievePts : List (List (List Int)) :=\n  [");
  for (i = 1, #pts, write1(o, Str(lstl(pts[i]), if (i < #pts, ",\n  ", "]\n\n"))));
  write1(o, "/-- Per prime, per point, per ring of the block: the conic index (0 or 2) and the character bit. -/\ndef sieveChoice : List (List (List (Nat × Bool))) :=\n  [");
  for (i = 1, #choices, my(C = choices[i]); write1(o, "[");
    for (t = 1, #C, write1(o, "["); for (j = 1, #C[t], write1(o, Str("(", C[t][j][1], ", ", if (C[t][j][2], "true", "false"), ")", if (j < #C[t], ", ", "")))); write1(o, if (t < #C, "],\n   ", "]")));
    write1(o, if (i < #choices, "],\n  ", "]]\n\n")));
  write1(o, "/-- Per prime, the set of bit vectors of the points. -/\ndef sieveV : List (List (List Bool)) :=\n  [");
  for (i = 1, #Vs, my(V = Vs[i]); write1(o, "["); for (t = 1, #V, write1(o, Str(bstr(V[t]), if (t < #V, ", ", "")))); write1(o, if (i < #Vs, "],\n  ", "]]\n\n")));
  write1(o, "/-- A left inverse of the character matrix over F_2 (18 rows of 32). -/\ndef sieveL : List (List Bool) :=\n  [");
  for (i = 1, 18, write1(o, Str(bstr(Lm[i, ]), if (i < 18, ",\n  ", "]\n\n"))));
  write1(o, "/-- The survivors of the sieve. -/\ndef sieveSurv : List (List Bool) :=\n  [");
  for (i = 1, #surv, write1(o, Str(bstr(surv[i]), if (i < #surv, ",\n  ", "]\n\n"))));
  write1(o, "end FurioLombardo.M1\n");
  print("written ", o);
  1;
}
main();
