\\ sieve_sqrt_data.gp: square root certificates for the sieve of M1 (lean/FurioLombardo/M1/DataSqrt.lean).
\\ Same rings and point order as sieve_data.gp (DataSieve.lean). In each ring F_q = F_p[x]/(phi): a non-residue n,
\\ and for every generator residue and every chosen conic value at a listed point w = t y^2 with t = 1 (character
\\ bit false) or t = n (bit true), with y z = 1. The Lean kernel checks n^((q-1)/2) = -1 once per ring and
\\ w = t y^2, y z = 1 for every w, which replaces one exponentiation per character (SieveRing.lean, sqOK).
\\ Not trusted: every datum is rechecked by the kernel (SieveCheck*.lean).
\\ Run: gp -q sieve_sqrt_data.gp < /dev/null
default(parisizemax, 3*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_data_lib.gp");
read("/tmp/m1_gensLean.gp");
Fi(P) = substvec(F, [x, y, z], P);
evq(cr, P) = sum(j = 1, 6, cr[j] * P[1]^mons2[j][1] * P[2]^mons2[j][2] * P[3]^mons2[j][3]);
zkpol(a) = sum(i = 1, 21, a[i] * Polrev(zkNum[i], b));
rho(a, p, phi) = Mod(Mod(zkpol(a), p), phi) / Mod(Dz, p);
chi(w, p, phi) = { my(q = p^poldegree(phi), c = w^((q-1)/2)); if (c == 1, 0, if (c == -1, 1, -1)) };
normpts(p) = {
  my(L = List());
  for (x0 = 0, p-1, for (z0 = 0, p-1, if (Fi([x0, 1, z0]) % p == 0, listput(L, [x0, 1, z0]))));
  for (z0 = 0, p-1, if (Fi([1, 0, z0]) % p == 0, listput(L, [1, 0, z0])));
  if (Fi([0, 0, 1]) % p == 0, listput(L, [0, 0, 1]));
  Vec(L);
}
\\ coefficient list (length deg phi, entries in [0, p)) of a polynomial in the variable of the field
cl(pol, p, d) = { my(v = Vecrev(pol, d)); vector(d, k, lift(Mod(v[k], p))) };
Gz = vector(18, i, gensLean[i]~);
\\ [y, z] with w = t y^2, t = 1 or n, y z = 1, as coefficient lists; w an element of Mod(Mod(., p), phi)
cert(w, beta, nn, g, p, d) = {
  my(W = subst(lift(lift(w)), b, g), T = if (beta, subst(nn, b, g), 1), Y);
  if (!issquare(W / T), error("no square root"));
  Y = sqrt(W / T);
  if (T * Y^2 != W, error("sqrt check"));
  [cl(Y.pol, p, d), cl((1/Y).pol, p, d)];
}
main() = {
  my(nons = List(), gy = List(), gz = List(), py = List(), pz = List(), o);
  forprime(p = 5, 23, if (p == 7, next);
    my(fa = factor(K21 * Mod(1, p))[, 1], k = #fa, phis = vector(k, j, lift(fa[j])), P = normpts(p), bnon = vector(k), bg = vector(k));
    for (j = 1, k, my(phi = phis[j], d = poldegree(phi), q = p^d, g = ffgen(Mod(1, p) * phi, 'g), nn = 0, ys = vector(18), zs = vector(18));
      \\ smallest non-residue among c, b + c, b^2 + c, ...
      for (m = 0, d - 1, if (nn != 0, break); for (c = 0, p - 1, my(cand = b^m * (m > 0) + c);
        if (cand != 0 && subst(cand, b, g)^((q-1)/2) == -1, nn = cand; break)));
      if (nn == 0, error("no non-residue"));
      bnon[j] = nn; bg[j] = g;
      listput(nons, cl(nn, p, d));
      for (i = 1, 18, my(w = rho(Gz[i], p, phi), c = chi(w, p, phi), r);
        if (c < 0, error("generator not a unit"));
        r = cert(w, c, nn, g, p, d); ys[i] = r[1]; zs[i] = r[2]);
      listput(gy, ys); listput(gz, zs));
    my(bpy = vector(#P), bpz = vector(#P));
    for (t = 1, #P, my(Q = P[t], vy = vector(k), vz = vector(k));
      for (j = 1, k, my(phi = phis[j], d = poldegree(phi), q1 = evq(vector(6, s, rho(QcZ[1][s], p, phi)), Q), q3 = evq(vector(6, s, rho(QcZ[3][s], p, phi)), Q), w = q1, c = chi(q1, p, phi), r);
        if (c < 0, w = q3; c = chi(q3, p, phi));
        if (c < 0, error("both non units"));
        r = cert(w, c, bnon[j], bg[j], p, d); vy[j] = r[1]; vz[j] = r[2]);
      bpy[t] = vy; bpz[t] = vz);
    listput(py, bpy); listput(pz, bpz));
  o = Str(LEANDIR, "FurioLombardo/M1/DataSqrt.lean");
  system(Str("rm -f ", o));
  write1(o, "/-! Square root certificates of the sieve of lane M1 (generated by code/descent/sieve_sqrt_data.gp, PARI/GP), in the\nrings and point order of DataSieve.lean. Rechecked by the kernel in SieveCheck*.lean. -/\n\nnamespace FurioLombardo.M1\n\nset_option maxRecDepth 100000\n\n");
  write1(o, "/-- A non-residue of each ring. -/\ndef sieveNon : List (List Int) :=\n  "); write1(o, lstl(Vec(nons))); write1(o, "\n\n");
  write1(o, "/-- Square roots `y` for the generators, per ring. -/\ndef sieveGY : List (List (List Int)) :=\n  [");
  for (r = 1, #gy, write1(o, Str(lstl(gy[r]), if (r < #gy, ",\n  ", "]\n\n"))));
  write1(o, "/-- Inverses `z` of the square roots for the generators, per ring. -/\ndef sieveGZ : List (List (List Int)) :=\n  [");
  for (r = 1, #gz, write1(o, Str(lstl(gz[r]), if (r < #gz, ",\n  ", "]\n\n"))));
  write1(o, "/-- Square roots `y` at the points: per prime, per point, per ring of the block. -/\ndef sievePY : List (List (List (List Int))) :=\n  [");
  for (t = 1, #py, my(B = py[t]); write1(o, "["); for (s = 1, #B, write1(o, Str(lstl(B[s]), if (s < #B, ",\n   ", "")))); write1(o, if (t < #py, "],\n  ", "]]\n\n")));
  write1(o, "/-- Inverses `z` at the points: per prime, per point, per ring of the block. -/\ndef sievePZ : List (List (List (List Int))) :=\n  [");
  for (t = 1, #pz, my(B = pz[t]); write1(o, "["); for (s = 1, #B, write1(o, Str(lstl(B[s]), if (s < #B, ",\n   ", "")))); write1(o, if (t < #pz, "],\n  ", "]]\n\n")));
  write1(o, "end FurioLombardo.M1\n");
  print("written ", o, ": ", #nons, " rings");
  1;
}
main();
