\\ sunit_generators_k.gp: writes lean/FurioLombardo/M1/DataGens.lean: the 18 generators of K21(S,2) in zk coordinates, inverses
\\ of the units, the relations 2 = e2 la^3 lb^12 lc^6, theta = et lb^2, theta - 1 = e1 la^4 lc^3, 7 = e7 pi7^7 (unit
\\ cofactors with their inverses), the cofactors 2/la, 2/lb, 2/lc, 7/pi7, 3/pi3, 439/pi439, and the residue degree
\\ certificate (theta^49 - theta) u7 = 1 + 7 v7 at 7. Every datum is rechecked here and by the Lean kernel.
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_search_lib.gp");
la = G[13]; lb = G[14]; lc = G[15]; p7 = G[16]; p3 = G[17]; p439 = G[18]; th = zkc(b);

dv(u, v) = { my(r = zv(nfeltdiv(nf, u, v))); if (denominator(content(r)) != 1, error("not integral")); r };
e2 = dv(zkc(2), mulz(powz(la, 3), mulz(powz(lb, 12), powz(lc, 6))));
et = dv(th, powz(lb, 2));
e1 = dv(zkc(b - 1), mulz(powz(la, 4), powz(lc, 3)));
e7 = dv(zkc(7), powz(p7, 7));
us = [e2, et, e1, e7]; usi = vector(4, i, dv(zkc(1), us[i]));
Gi = vector(12, i, dv(zkc(1), G[i]));
cof = [dv(zkc(2), la), dv(zkc(2), lb), dv(zkc(2), lc), dv(zkc(7), p7), dv(zkc(3), p3), dv(zkc(439), p439)];
\\ residue degree certificate at 7
y7 = powz(th, 49) - th;
{ my(ab = idealaddtoone(nf, idealhnf(nf, y7), idealhnf(nf, 7))); u7 = dv(zv(ab[1]), y7); }
r7 = mulz(y7, u7) - zkc(1);
if (denominator(content(r7 / 7)) != 1, error("u7"));
v7 = r7 / 7;
\\ reduce u7 modulo 7 to keep it small (v7 changes accordingly)
u7r = vector(21, i, centerlift(Mod(u7[i], 7)))~; r7 = mulz(y7, u7r) - zkc(1);
if (denominator(content(r7 / 7)) != 1, error("u7r")); u7 = u7r; v7 = r7 / 7;
dig(v) = vecmax(apply(n -> #digits(abs(n) + 1), Vec(v)));
print("digits: e ", vector(4, i, dig(us[i])), " ei ", vector(4, i, dig(usi[i])), " Gi ", vecmax(vector(12, i, dig(Gi[i]))), " cof ", vector(6, i, dig(cof[i])), " u7 v7 ", [dig(u7), dig(v7)]);
out = Str(LEANDIR, "FurioLombardo/M1/DataGens.lean");
write1(out, ""); system(Str("rm -f ", out));
write(out, "/-! Data of lane M1 (generated by code/descent/sunit_generators_k.gp, PARI/GP; found with bnfinit, rechecked by the\nkernel in Gens.lean). Elements of K21 in coordinates on PARI's integral basis (`zkE`). -/\n\nnamespace FurioLombardo.M1\n\nset_option maxRecDepth 100000\n");
write(out, "/-- The 18 generators: `-1`, the 11 fundamental units, `la, lb, lc` (above 2), `pi7`, `pi3`, `pi439`. -/\ndef gensL : List (List Int) :=\n  ", lstl(vector(18, i, G[i]~)), "\n");
write(out, "/-- Inverses of the first 12 generators (units). -/\ndef gensInvL : List (List Int) :=\n  ", lstl(vector(12, i, Gi[i]~)), "\n");
write(out, "/-- Unit cofactors `e2, et, e1, e7` of `2 = e2 la^3 lb^12 lc^6`, `θ = et lb^2`, `θ - 1 = e1 la^4 lc^3`, `7 = e7 pi7^7`. -/\ndef unitsL : List (List Int) :=\n  ", lstl(vector(4, i, us[i]~)), "\n");
write(out, "/-- Inverses of `e2, et, e1, e7`. -/\ndef unitsInvL : List (List Int) :=\n  ", lstl(vector(4, i, usi[i]~)), "\n");
write(out, "/-- Cofactors `2/la, 2/lb, 2/lc, 7/pi7, 3/pi3, 439/pi439`. -/\ndef cofL : List (List Int) :=\n  ", lstl(vector(6, i, cof[i]~)), "\n");
write(out, "/-- `(θ^49 - θ) u7 = 1 + 7 v7`. -/\ndef u7L : List Int := ", lst(u7~), "\n");
write(out, "/-- See `u7L`. -/\ndef v7L : List Int := ", lst(v7~), "\n");
write(out, "end FurioLombardo.M1");
print("written ", out);
