#!/bin/bash
# Writes lean/FurioLombardo/Discharge/SelmerBasis/KappaCheck.lean: the kernel checks of the kappa data
# (KappaData.lean, code/selmer-assembly/kappa_data.gp), one declaration per check, then the statements for all t < 15.
# Usage: code/selmer-assembly/kernel_checks_kappa.sh (from the repository root); LEANOUT=<dir> writes into <dir> instead.
set -eu
cd "$(dirname "$0")/../.."
f=${LEANOUT:-lean/FurioLombardo/Discharge/SelmerBasis}; f=${f%/}/KappaCheck.lean
list() { local p=$1 s="" i; for ((i = 0; i < 15; i++)); do s="$s${s:+, }$p$i"; done; echo "$s"; }
PL='checkLC (pPL.getD @T@ 0) (ofL (prodL.getD @T@ [])) (selProdL (aK.getD @T@ []) SUnitData.gL) = true'
PN='checkNC (pPN.getD @T@ 0) (ofN (prodN.getD @T@ [])) (selProdN ((aK.getD @T@ []).drop 29) SUnitData.gN) = true'
SL='checkLC (pSL.getD @T@ 0) (smulLC (.mul (.int (((y1D.getD @T@ 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (@T@ + 1) []))) (ofL (prodL.getD @T@ []))) (mulLC (ofL (y1T.getD @T@ [])) (ofL (y1T.getD @T@ []))) = true'
SN='checkNC (pSN.getD @T@ 0) (smulNC (.mul (.int (((y2D.getD @T@ 0) ^ 2 : ℕ) : ℤ)) (.lin (FurioLombardo.M1.gensL.getD (@T@ + 1) []))) (ofN (prodN.getD @T@ []))) (mulNC (ofN (y2T.getD @T@ [])) (ofN (y2T.getD @T@ []))) = true'
sub() { echo "${1//@T@/$2}"; }
{
  cat <<'HEAD'
import FurioLombardo.Discharge.SelmerBasis.KappaData
import FurioLombardo.Discharge.SelmerBasis.MuTCert
import FurioLombardo.M1.DataGens

/-!
# Kernel checks of the kappa data (generated by code/selmer-assembly/kernel_checks_kappa.sh)

For `t < 15`: `ck_PL_t`, `ck_PN_t` (the products of the selected generators), `ck_SL_t`, `ck_SN_t` (the square
identities `y1D² c_t prodL = y1T²` in `L42`, `y2D² c_t prodN = y2T²` in `N84`, `c_t = M1.gensL (t + 1)`), each by
`decide +kernel`; `ck_bits`: `aK t` is `Kappa.κK t` read as a list.
-/

namespace FurioLombardo.Discharge.SelmerBasis.KappaData

set_option maxRecDepth 100000

open FurioLombardo.M1.Kron FurioLombardo.Discharge.SelmerBasis FurioLombardo.Discharge.SelmerBasis.Tower
  FurioLombardo.Discharge.SelmerBasis.MuTCert

HEAD
  for ((t = 0; t < 15; t++)); do
    for c in PL PN SL SN; do
      echo "theorem ck_${c}_$t : $(sub "${!c}" "$t") := by"
      echo "  decide +kernel"; echo
    done
  done
  for c in PL PN SL SN; do
    echo "theorem ck_$c : ∀ t, t < 15 → $(sub "${!c}" t) := by"
    echo "  intro t ht"; echo "  interval_cases t"; echo "  exacts [$(list ck_${c}_)]"; echo
  done
  cat <<'TAIL'
theorem ck_shape : ∀ t, t < 15 → (∀ b ∈ aK.getD t [], b ≤ 1) ∧ 82 ≤ (aK.getD t []).length ∧
    y1D.getD t 0 ≠ 0 ∧ y2D.getD t 0 ≠ 0 := by
  decide +kernel

end FurioLombardo.Discharge.SelmerBasis.KappaData
TAIL
} > $f
echo "wrote $f"
