\\ dyadic_map_data.gp: zk coordinates of PP = la (1 + la + la^2 + la^4) and w = 1 + la + la^2 + la^4 for the
\\ dyadic map of the M3b discharge (Discharge/M3b/DyadicMap.lean). Found here, rechecked by the Lean kernel.
\\ Run from code/descent: gp -q ../selmer-global-bound/dyadic_map_data.gp < /dev/null
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_search_lib.gp");
chk(cc, msg) = if (!cc, error("FAILED: ", msg), print("ok: ", msg));
la = G[13];
w = zkc(1) + la + powz(la, 2) + powz(la, 4); PP = mulz(la, w);
print("PP = ", PP~);
chk(idealval(nf, PP, S[1]) == 1, "PP is a uniformizer at (la)");
chk(idealval(nf, w, S[1]) == 0, "w is a unit at (la)");
out = Str(LEANDIR, "FurioLombardo/Discharge/M3b/DataDyadic.lean");
system(Str("rm -f ", out));
write(out, "import Mathlib\n\n/-! Data of the dyadic map of the M3b discharge (generated by code/selmer-global-bound/dyadic_map_data.gp, PARI/GP;\nrechecked by the kernel). Coordinates on PARI's integral basis (`FurioLombardo.M1.zkE`). -/\n\nnamespace FurioLombardo.Discharge.M3b\n");
write(out, "/-- `Π = la (1 + la + la² + la⁴)`. -/\ndef PiL : List ℤ := ", lst(PP~), "\n");
write(out, "end FurioLombardo.Discharge.M3b");
print("written ", out);
