\\ sunit_count_certs.gp: certificates of the prime counts #S_L <= 5, #S_N <= 8;
\\ Lean: lean/FurioLombardo/Discharge/SelmerBasis/SUnitCount.lean. Every element of K21 is a list of zk
\\ coordinates (M1's zkE). la, lb, lc, pi7 = gO 12, gO 13, gO 14, gO 15 of M1.
\\   lb inert in L = K21(sqrt eps): gamma_L = (x + omega) / lb^12 (M3b's RamL) is a root of X^2 + b X + c with
\\     b = -c0 x, c = y (c0 = e0 la^3 lc^6 = 2 / lb^12); certificates q1 = (1 - b) / lb, q2 = (1 - c) / lb.
\\   the prime above la is inert in N = L(sqrt e'): gamma_N = (x_L + omega_N) / 2 is a root of X^2 - x_L X + n_L;
\\     1 + x_L and 1 - n_L lie in every prime above la because their traces and norms over K21 do:
\\     q3 = (2 + al) / la, q4 = (1 + al + nx) / la, q5 = (2 - aln) / la, q6 = (1 - aln + nn) / la.
\\   la and lc ramified in L (Eisenstein): x in O_K21 with v(x^2 - eps) = 2k + 1 at the prime l, so that
\\     gamma = (x + omega) / l^k is a root of X^2 + b X + c, b = -2 x / l^k in (l), c = (x^2 - eps) / l^(2k) = l u,
\\     u not in (l) (certificates qu = (1 - u) / l, qb = b / l).
\\ Output: the Lean data file lean/FurioLombardo/Discharge/SelmerBasis/SUnitCountData.lean.
\\ Run from code/selmer-global-bound:
\\   ./sunit_lean2gp.sh && gp -q -D parisizemax=1000000000 sunit_count_certs.gp > sunit_count_certs.out (LEANOUT=<dir>/ writes
\\   SUnitCountData.lean to <dir> instead)
read("../descent/descent_data_lib.gp");
read("sunit_leandata.gp");
NCHK = 0; NFAIL = 0;
chk(c, msg) = { NCHK++; if (!c, NFAIL++; print("FAIL: ", msg)); };
o = Mod(1, K21);
el(v) = o * lift(zkr(v));
zl(e) = { my(v = zkc(lift(o * e))); if (denominator(content(v)) != 1, error("non integral")); v~ };
la = el(gensL[13]); lb = el(gensL[14]); lc = el(gensL[15]); pi7 = el(gensL[16]);
eps = el(epsL); e0 = el(unitsL[1]);
chk(abs(norm(la)) == 2 && abs(norm(lb)) == 2 && abs(norm(lc)) == 2 && abs(norm(pi7)) == 343, "norms of la, lb, lc, pi7");
chk(2 == e0 * la^3 * lb^12 * lc^6, "2 = e0 la^3 lb^12 lc^6");
x = el(xCL); y = el(yCL);
chk(x^2 - eps == lb^24 * y, "RamL: x^2 - eps = lb^24 y");
c0 = e0 * la^3 * lc^6;
q1 = (1 + c0 * x) / lb; q2 = (1 - y) / lb;
al = el(alL); be = el(beL); nx = el(nxL); aln = el(alnL); ben = el(benL); nn = el(nnL);
chk(al^2 - eps * be^2 == 4 * nx && aln^2 - eps * ben^2 == 4 * nn, "norm identities of x_L, n_L");
q3 = (2 + al) / la; q4 = (1 + al + nx) / la; q5 = (2 - aln) / la; q6 = (1 - aln + nn) / la;
\\ valuation at the prime generated by l (principal, prime of norm 2)
prOf(l) = { my(r = 0); foreach(idealprimedec(nf, 2), pr, if (idealval(nf, lift(l), pr) == 1 && pr.f == 1, r = pr)); r };
eis(l) = {
  my(pr = prOf(l), xx = o, m, t);
  for (it = 1, 40,
    m = idealval(nf, lift(xx^2 - eps), pr);
    if (m % 2 == 1, break);
    \\ residue field F_2: correct by l^(m/2) when (eps - xx^2) / l^m is odd
    t = (eps - xx^2) / l^m;
    if (idealval(nf, lift(t), pr) == 0, xx += l^(m / 2), error("no progress")));
  m = idealval(nf, lift(xx^2 - eps), pr);
  my(k = (m - 1) / 2, b = -2 * xx / l^k, c = (xx^2 - eps) / l^(2 * k), u = c / l);
  chk(idealval(nf, lift(b), pr) >= 1 && idealval(nf, lift(u), pr) == 0, "Eisenstein at l");
  [xx, k, b, c, u, (1 - u) / l, b / l]
};
Ea = eis(la); Ec = eis(lc);
printf("la: k = %d, lc: k = %d\n", Ea[2], Ec[2]);
lst(v) = { my(s = "["); for (i = 1, #v, s = Str(s, v[i], if (i < #v, ", ", ""))); Str(s, "]") };
dl(name, e) = Str("def ", name, " : List Int := ", lst(zl(e)), "\n");
{
  my(f = Str(if (#getenv("LEANOUT"), getenv("LEANOUT"), "../../FurioLombardo/Discharge/SelmerBasis/"), "SUnitCountData.lean"));
  my(s = Str("/-! Data of the prime counts of piece (b) (generated by code/selmer-global-bound/sunit_count_certs.gp, PARI/GP;\n",
    "rechecked by the kernel in SUnitCount.lean). Elements of K21 in coordinates on PARI's integral basis (`zkE`). -/\n\n",
    "namespace FurioLombardo.Discharge.SelmerBasis.SUnitCountData\n\n"));
  s = Str(s, dl("q1", q1), dl("q2", q2), dl("q3", q3), dl("q4", q4), dl("q5", q5), dl("q6", q6));
  s = Str(s, "/-- Eisenstein data at `la`: `x`, `b`, `c`, `u`, `qu`, `qb = b / la`, with exponent `kA`. -/\n");
  s = Str(s, dl("xA", Ea[1]), "def kA : Nat := ", Ea[2], "\n", dl("bA", Ea[3]), dl("cA", Ea[4]), dl("uA", Ea[5]), dl("quA", Ea[6]), dl("qbA", Ea[7]));
  s = Str(s, "/-- Eisenstein data at `lc`. -/\n");
  s = Str(s, dl("xC", Ec[1]), "def kC : Nat := ", Ec[2], "\n", dl("bC", Ec[3]), dl("cC", Ec[4]), dl("uC", Ec[5]), dl("quC", Ec[6]), dl("qbC", Ec[7]));
  s = Str(s, "\nend FurioLombardo.Discharge.SelmerBasis.SUnitCountData\n");
  my(fh = fileopen(f, "w")); filewrite1(fh, s); fileclose(fh);
}
printf("checks: %d, failures: %d\n", NCHK, NFAIL);
quit;
