\\ tower_field_data.gp: K21 data of the M3b discharge (found here, every datum rechecked by the Lean kernel).
\\ (C) the prime (lb) (e = 12) is unramified in L = K21(sqrt eps): x with x^2 = eps mod lb^24, y = (x^2 - eps) / lb^24.
\\ (D) the dyadic reduction at (la) (e = 3): PP = la w with PP^3 + 2 in la^6 O, images of u and eps in
\\     R = (Z/4)[pi]/(pi^3 + 2), a unit u with image U = (3, 3, 3), t with rho(eps t^2) = D = (1, 0, 2).
\\ Run from code/descent: gp -q ../selmer-global-bound/tower_field_data.gp < /dev/null
default(parisizemax, 4*10^9); default(nbthreads, 1);
LEANDIR = if (type(getenv("LEANOUT")) == "t_STR", getenv("LEANOUT"), "../../");  \\ LEANOUT=<dir>/ writes the Lean file under <dir> instead of lean/
read("descent_search_lib.gp");
chk(cc, msg) = if (!cc, error("FAILED: ", msg), print("ok: ", msg));
dig(v) = vecmax(apply(n -> #digits(abs(n) + 1), Vec(v)));
la = G[13]; lb = G[14]; lc = G[15]; p7 = G[16];
eps = G[1]; foreach([2, 5, 7, 10, 11], i, eps = mulz(eps, G[i]));
chk(unitq(eps) && nfeltsign(nf, eps) == [1, 1, 1], "eps is a totally positive unit");
print("eps = ", eps~);
Pa = S[1]; Pb = S[2]; Pc = S[3];
chk(idealval(nf, la, Pa) == 1 && idealval(nf, lb, Pb) == 1 && idealval(nf, lc, Pc) == 1, "la, lb, lc generate the three primes above 2");
\\ ---- (C)
Pb24 = idealpow(nf, Pb, 24);
bid = idealstar(nf, Pb24, 2);
lg = ideallog(nf, eps, bid);
print("cyc of (O/lb^24)^x: ", bid.cyc, "; log of eps: ", lg~);
hf = vector(#lg, i, my(c = bid.cyc[i]); if (c % 2 == 1, lift(Mod(lg[i], c) / 2), if (lg[i] % 2, error("eps is not a square mod lb^24"), lg[i] / 2)));
xC = zv(nffactorback(nf, bid.gen, hf~));
xC = zv(nfeltreduce(nf, xC, Pb24));
\\ shrink x by centred reduction modulo lb^24 O = the lattice Pb24 (nfeltreduce is already an LLL reduction)
rC = zv(nfeltdiv(nf, mulz(xC, xC) - eps, powz(lb, 24)));
chk(denominator(content(rC)) == 1, "y = (x^2 - eps) / lb^24 is integral");
print("xC digits ", dig(xC), ", yC digits ", dig(rC));
print("xC = ", xC~); print("yC = ", rC~);
\\ ---- (D)
dv(u, v) = { my(r = zv(nfeltdiv(nf, u, v))); if (denominator(content(r)) != 1, error("not integral")); r };
mp = nfmodprinit(nf, Pa);
res2(x) = if (nfmodpr(nf, x, mp) == 0, 0, 1);
digs(x, PP, n) = { my(c = vector(n), y = x); for (i = 1, n, c[i] = res2(y) % 2; y = nfeltdiv(nf, y - c[i], PP)); c };
toR(c) = vector(3, i, lift(Mod(c[i] - 2 * c[i + 3], 4)));
tm(a, q) = [lift(Mod(a[1]*q[1] - 2*(a[2]*q[3] + a[3]*q[2]), 4)), lift(Mod(a[1]*q[2] + a[2]*q[1] - 2*a[3]*q[3], 4)), lift(Mod(a[1]*q[3] + a[2]*q[2] + a[3]*q[1], 4))];
Rall = List(); forvec(c = [[0,3],[0,3],[0,3]], listput(Rall, c)); Rall = Vec(Rall);
uz = vectorv(21, k, k == 19) - zkc(1);
chk(unitq(uz), "u = zk[19] - 1 is a unit");
cands = List();
{forvec(w = [[0,1],[0,1],[0,1],[0,1]], my(ww = zkc(1), PP);
  for (i = 1, 4, ww = ww + w[i] * powz(la, i));
  PP = mulz(la, ww);
  if (idealval(nf, powz(PP, 3) + zkc(2), Pa) >= 6, listput(cands, [w, PP])));}
print("valid PP (PP^3 + 2 in P^6) among the 16 lifts: ", #cands);
{for (k = 1, #cands, my(PP = cands[k][2], Uu = toR(digs(uz, PP, 6)), De = toR(digs(eps, PP, 6)));
  print("  w digits ", cands[k][1], ": image of u ", Uu, ", image of eps ", De));}
\\ ---- the chosen PP (w digits [1, 1, 0, 1]: w = 1 + la + la^2 + la^4), t = 1 + PP^2
w = zkc(1) + la + powz(la, 2) + powz(la, 4); PP = mulz(la, w);
chk(toR(digs(uz, PP, 6)) == [3, 3, 3], "image of u is U = (3, 3, 3)");
tt = zkc(1) + powz(PP, 2); dd = mulz(eps, mulz(tt, tt));
chk(toR(digs(dd, PP, 6)) == [1, 0, 2], "image of eps t^2 is D = (1, 0, 2)");
chk(toR(digs(eps, PP, 6)) == [1, 2, 0], "image of eps is 1 + 2 pi (not a square in R)");
la6 = powz(la, 6);
z1 = dv(powz(PP, 3) + zkc(2), la6);
z2 = dv(uz - (zkc(3) + 3 * PP + 3 * powz(PP, 2)), la6);
z3 = dv(dd - (zkc(1) + 2 * powz(PP, 2)), la6);
ui = inv(uz);
print("digits: z1 ", dig(z1), " z2 ", dig(z2), " z3 ", dig(z3), " u^-1 ", dig(ui));
print("nfhilbert(u, eps) at la: ", nfhilbert(nf, uz, eps, Pa), " (expected -1)");
out = Str(LEANDIR, "FurioLombardo/Discharge/M3b/DataK21.lean");
system(Str("rm -f ", out));
write(out, "import Mathlib\n\n/-! Data of the M3b discharge on K21 (generated by code/selmer-global-bound/tower_field_data.gp, PARI/GP; every datum is\nrechecked by the kernel). Elements of K21 in coordinates on PARI's integral basis (`FurioLombardo.M1.zkE`). -/\n\nnamespace FurioLombardo.Discharge.M3b\n");
write(out, "/-- `x` with `x² - ε = lb^24 y` (the prime `(lb)`, `e = 12`, is unramified in `L`). -/\ndef xCL : List ℤ := ", lst(xC~), "\n");
write(out, "/-- `y = (x² - ε) / lb^24`. -/\ndef yCL : List ℤ := ", lst(rC~), "\n");
write(out, "/-- `u = zk[19] - 1` (PARI numbering; index 18 here), a unit. -/\ndef uL : List ℤ := ", lst(uz~), "\n");
write(out, "/-- `u⁻¹`. -/\ndef uInvL : List ℤ := ", lst(ui~), "\n");
write(out, "/-- `z1 = (Π³ + 2) / la^6`, `Π = la (1 + la + la² + la⁴)`. -/\ndef z1L : List ℤ := ", lst(z1~), "\n");
write(out, "/-- `z2 = (u - (3 + 3Π + 3Π²)) / la^6`. -/\ndef z2L : List ℤ := ", lst(z2~), "\n");
write(out, "/-- `z3 = (ε (1 + Π²)² - (1 + 2Π²)) / la^6`. -/\ndef z3L : List ℤ := ", lst(z3~), "\n");
write(out, "end FurioLombardo.Discharge.M3b");
print("written ", out);
