import Mathlib

/-!
# Lane M3b: abstract ambiguous class count (Chevalley's formula, group theory part)

Setting `InvData X I`: commutative groups `X`, `I` with involutions `sX`, `sI` and an equivariant
homomorphism `φ : X →* I`. For a quadratic extension `L/K` think of `X = Lˣ`, `I` = invertible
fractional ideals of `L`, `φ` = principal ideals, `sX`, `sI` = Galois conjugation. Main result
`InvData.chevalley_abstract`: under Hilbert 90 for `X` and for `I`,

  `|amb| * [E⁻ : (E⁻)²] * [E⁺ : E ∩ N X] = [fix I : φ(fix X)] * [E⁺ : (E⁺)²]`,

where `E = ker φ`, `E⁺` its fixed part, `E⁻` its norm one part, `amb` the fixed classes of `I / φ X`.
All indices are `Subgroup.relIndex` (value `0` for an infinite index), and the identity holds as stated.

Proof: `|amb| = [fix I : P ∩ fix I] [E ∩ N X : N E]` (`card_amb`), `[P ∩ fix I : PK] = [E⁻ : E^(s-1)]`
(`relIndex_PK_Pfix`), and the Herbrand quotient identities of an involution (`herbrand_plus`,
`herbrand_minus`).
-/

namespace FurioLombardo.M3b

/-- Data for the abstract ambiguous class count: commutative groups `X`, `I`, involutions
`sX`, `sI` and an equivariant homomorphism `φ : X →* I`. -/
structure InvData (X I : Type*) [CommGroup X] [CommGroup I] where
  sX : X →* X
  sI : I →* I
  φ : X →* I
  sX_sX : ∀ x, sX (sX x) = x
  sI_sI : ∀ a, sI (sI a) = a
  φ_sX : ∀ x, φ (sX x) = sI (φ x)

namespace InvData

variable {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I)

/-- The norm `x ↦ x * sX x`. -/
def normX : X →* X := MonoidHom.id X * D.sX

theorem normX_apply (x : X) : D.normX x = x * D.sX x := rfl

/-- The map `x ↦ sX x / x`. -/
def difX : X →* X := D.sX / MonoidHom.id X

theorem difX_apply (x : X) : D.difX x = D.sX x / x := rfl

/-- Elements of `X` fixed by `sX`. -/
def fixX : Subgroup X := MonoidHom.eqLocus D.sX (MonoidHom.id X)

theorem mem_fixX (x : X) : x ∈ D.fixX ↔ D.sX x = x := Iff.rfl

/-- Elements of `I` fixed by `sI` (ambiguous ideals). -/
def fixI : Subgroup I := MonoidHom.eqLocus D.sI (MonoidHom.id I)

theorem mem_fixI (a : I) : a ∈ D.fixI ↔ D.sI a = a := Iff.rfl

/-- The units: the kernel of `φ`. -/
def E : Subgroup X := D.φ.ker

theorem mem_E (x : X) : x ∈ D.E ↔ D.φ x = 1 := Iff.rfl

/-- The principal ideals: the range of `φ`. -/
def P : Subgroup I := D.φ.range

/-- Units fixed by `sX` (the units of the base field). -/
def Eplus : Subgroup X := D.E ⊓ D.fixX

/-- Units of norm one. -/
def Eminus : Subgroup X := D.E ⊓ D.normX.ker

/-- Norms of units. -/
def NE : Subgroup X := D.E.map D.normX

/-- Units that are norms of elements of `X`. -/
def NXE : Subgroup X := D.E ⊓ D.normX.range

/-- The subgroup `{sX e / e : e ∈ E}`. -/
def DE : Subgroup X := D.E.map D.difX

/-- Ambiguous principal ideals. -/
def Pfix : Subgroup I := D.P ⊓ D.fixI

/-- Principal ideals generated by fixed elements (ideals of the base field). -/
def PK : Subgroup I := D.fixX.map D.φ

theorem P_le_comap : D.P ≤ D.P.comap D.sI := by
  rintro _ ⟨x, rfl⟩
  exact ⟨D.sX x, D.φ_sX x⟩

/-- The involution induced on the class group `I ⧸ P`. -/
def sCl : I ⧸ D.P →* I ⧸ D.P := QuotientGroup.map D.P D.P D.sI D.P_le_comap

theorem sCl_mk (a : I) : D.sCl (QuotientGroup.mk a) = QuotientGroup.mk (D.sI a) := rfl

/-- The ambiguous classes: classes fixed by the induced involution. -/
def amb : Subgroup (I ⧸ D.P) := MonoidHom.eqLocus D.sCl (MonoidHom.id _)

theorem mem_amb (c : I ⧸ D.P) : c ∈ D.amb ↔ D.sCl c = c := Iff.rfl

/-- Hilbert 90 for `X`: an element of norm one is `y / sX y`. -/
def H90X : Prop := ∀ x, D.normX x = 1 → ∃ y, x = y / D.sX y

/-- Hilbert 90 for `I`: an element with `a * sI a = 1` is `b / sI b`. -/
def H90I : Prop := ∀ a, a * D.sI a = 1 → ∃ b, a = b / D.sI b

/-- Pairs `(a, x)` with `sI a = φ x * a`: ideals with ambiguous class, with a witness `x`. -/
def G : Subgroup (I × X) where
  carrier := {p | D.sI p.1 = D.φ p.2 * p.1}
  mul_mem' := by
    rintro ⟨a, x⟩ ⟨b, y⟩ ha hb
    simp only [Set.mem_ofPred_eq, Prod.fst_mul, Prod.snd_mul, map_mul] at ha hb ⊢
    rw [ha, hb]
    ac_rfl
  one_mem' := by simp
  inv_mem' := by
    rintro ⟨a, x⟩ ha
    simp only [Set.mem_ofPred_eq, Prod.fst_inv, Prod.snd_inv, map_inv] at ha ⊢
    rw [ha, mul_inv]

theorem mem_G (p : I × X) : p ∈ D.G ↔ D.sI p.1 = D.φ p.2 * p.1 := Iff.rfl

/-- The class of the ideal component. -/
def pi1 : D.G →* I ⧸ D.P := (QuotientGroup.mk' D.P).comp ((MonoidHom.fst I X).comp D.G.subtype)

theorem pi1_apply (p : D.G) : D.pi1 p = QuotientGroup.mk (p : I × X).1 := rfl

/-- The norm of the witness component. -/
def psi : D.G →* X := D.normX.comp ((MonoidHom.snd I X).comp D.G.subtype)

theorem psi_apply (p : D.G) : D.psi p = (p : I × X).2 * D.sX (p : I × X).2 := rfl

end InvData
end FurioLombardo.M3b

open FurioLombardo.M3b

theorem FurioLombardo.M3b.card_map_mk {G : Type*} [CommGroup G] (N K : Subgroup G) :
    Nat.card (K.map (QuotientGroup.mk' N)) = N.relIndex K := by
  calc
    Nat.card (K.map (QuotientGroup.mk' N)) = Nat.card ((QuotientGroup.mk' N).domRestrict K).range := by
      simp [MonoidHom.domRestrict_range]
    _ = ((QuotientGroup.mk' N).domRestrict K).ker.index := by
      rw [← Subgroup.index_ker]
    _ = (N.subgroupOf K).index := by
      simp [MonoidHom.ker_domRestrict, QuotientGroup.ker_mk']
    _ = N.relIndex K := rfl

theorem FurioLombardo.M3b.card_range_eq_card_map_mul_relIndex {G A B : Type*} [Group G] [Group A]
    [Group B] (f : G →* A) (g : G →* B) (H : Subgroup B) (h : f.ker ≤ H.comap g) :
    Nat.card f.range = Nat.card ((H.comap g).map f) * H.relIndex g.range := by
  set C := H.comap g with hC
  have h1 : Nat.card f.range = f.ker.index := by
    rw [Subgroup.index_ker]
  have h2 : f.ker.index = f.ker.relIndex C * C.index := by
    rw [Subgroup.relIndex_mul_index h]
  have h3 : C.index = H.relIndex g.range := by
    rw [Subgroup.index_comap]
  have h4 : f.ker.relIndex C = Nat.card (C.map f) := by
    rw [Subgroup.relIndex]
    -- Goal: (f.ker.subgroupOf C).index = Nat.card (C.map f)
    rw [← MonoidHom.ker_domRestrict f (K := C)]
    -- Goal: ((f.domRestrict C).ker).index = Nat.card (C.map f)
    rw [Subgroup.index_ker]
    -- Goal: Nat.card ((f.domRestrict C).range) = Nat.card (C.map f)
    rw [MonoidHom.domRestrict_range]
  calc
    Nat.card f.range = f.ker.index := h1
    _ = f.ker.relIndex C * C.index := h2
    _ = f.ker.relIndex C * H.relIndex g.range := by rw [h3]
    _ = Nat.card (C.map f) * H.relIndex g.range := by rw [h4]
    _ = Nat.card ((H.comap g).map f) * H.relIndex g.range := rfl

theorem FurioLombardo.M3b.InvData.E_inf_sup_minus {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.E ⊓ (D.Eminus ⊔ D.fixX) = D.Eplus ⊔ D.Eminus := by
  have hEminus_le_E : D.Eminus ≤ D.E := by
    unfold InvData.Eminus
    exact inf_le_left
  calc
    D.E ⊓ (D.Eminus ⊔ D.fixX) = (D.Eminus ⊔ D.fixX) ⊓ D.E := inf_comm _ _
    _ = D.Eminus ⊔ (D.fixX ⊓ D.E) := sup_inf_assoc_of_le D.fixX hEminus_le_E
    _ = D.Eminus ⊔ (D.E ⊓ D.fixX) := by rw [inf_comm]
    _ = D.Eminus ⊔ D.Eplus := by rw [InvData.Eplus]
    _ = D.Eplus ⊔ D.Eminus := sup_comm _ _

theorem FurioLombardo.M3b.InvData.E_inf_sup_plus {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.E ⊓ (D.Eplus ⊔ D.normX.ker) = D.Eplus ⊔ D.Eminus := by
  have hEplus_le_E : D.Eplus ≤ D.E := inf_le_left
  calc
    D.E ⊓ (D.Eplus ⊔ D.normX.ker) = (D.Eplus ⊔ D.normX.ker) ⊓ D.E := inf_comm _ _
    _ = D.Eplus ⊔ (D.normX.ker ⊓ D.E) := sup_inf_assoc_of_le _ hEplus_le_E
    _ = D.Eplus ⊔ (D.E ⊓ D.normX.ker) := by rw [inf_comm]
    _ = D.Eplus ⊔ D.Eminus := rfl

theorem FurioLombardo.M3b.InvData.ker_difX {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.difX.ker = D.fixX := by
  ext x
  simp [D.difX_apply, D.mem_fixX, MonoidHom.mem_ker, div_eq_one]

theorem FurioLombardo.M3b.InvData.ker_pi1_le {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.pi1.ker ≤ D.NE.comap D.psi := by
  intro p hp
  have hp1 : D.pi1 p = 1 := hp
  rw [D.pi1_apply] at hp1
  have hmemP : (p : I × X).1 ∈ D.P := (QuotientGroup.eq_one_iff _).mp hp1
  have hrange : (p : I × X).1 ∈ D.φ.range := hmemP
  obtain ⟨y, hy⟩ := (MonoidHom.mem_range (f := D.φ) (y := (p : I × X).1)).mp hrange
  have hG : (p : I × X) ∈ D.G := p.property
  rw [D.mem_G] at hG
  rw [← hy] at hG
  rw [← D.φ_sX y] at hG
  rw [← map_mul D.φ] at hG
  have hE : D.φ ((p : I × X).2 * y * (D.sX y)⁻¹) = 1 := by
    calc
      D.φ ((p : I × X).2 * y * (D.sX y)⁻¹) = D.φ ((p : I × X).2 * y) * D.φ ((D.sX y)⁻¹) := by
        rw [map_mul]
      _ = D.φ ((p : I × X).2 * y) * (D.φ (D.sX y))⁻¹ := by rw [map_inv]
      _ = D.φ (D.sX y) * (D.φ (D.sX y))⁻¹ := by rw [← hG]
      _ = 1 := by rw [mul_inv_cancel]
  have he : (p : I × X).2 * y * (D.sX y)⁻¹ ∈ D.E := by
    rw [D.mem_E]
    exact hE
  set e := (p : I × X).2 * y * (D.sX y)⁻¹ with he_def
  have hx_eq : (p : I × X).2 = e * D.sX y * y⁻¹ := by
    dsimp [e]
    group
  have h_norm_eq : D.normX ((p : I × X).2) = D.normX e := by
    rw [D.normX_apply, D.normX_apply, hx_eq]
    simp only [map_mul, map_inv, D.sX_sX]
    have htemp : e * D.sX y * y⁻¹ * (D.sX e * y * (D.sX y)⁻¹) =
                e * D.sX e * (D.sX y * y⁻¹ * y * (D.sX y)⁻¹) := by
      ac_rfl
    rw [htemp]
    have hinner : D.sX y * y⁻¹ * y * (D.sX y)⁻¹ = 1 := by
      calc
        D.sX y * y⁻¹ * y * (D.sX y)⁻¹ = D.sX y * (y⁻¹ * y) * (D.sX y)⁻¹ := by ac_rfl
        _ = D.sX y * 1 * (D.sX y)⁻¹ := by rw [inv_mul_cancel y]
        _ = D.sX y * (D.sX y)⁻¹ := by rw [mul_one]
        _ = 1 := by rw [mul_inv_cancel (D.sX y)]
    rw [hinner, mul_one]
  apply Subgroup.mem_comap.mpr
  rw [D.psi_apply, ← D.normX_apply, h_norm_eq]
  exact Subgroup.mem_map.mpr ⟨e, he, rfl⟩

theorem FurioLombardo.M3b.InvData.map_difX_comap {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) (h : D.H90X) :
    (D.fixI.comap D.φ).map D.difX = D.Eminus := by
  ext x
  constructor
  · intro hx
    rcases Subgroup.mem_map.mp hx with ⟨y, hy, rfl⟩
    have hφy_fix : D.φ y ∈ D.fixI := Subgroup.mem_comap.mp hy
    have hφy_eq : D.sI (D.φ y) = D.φ y := hφy_fix
    have hφ_difX : D.φ (D.difX y) = 1 := by
      calc
        D.φ (D.difX y) = D.φ (D.sX y / y) := by rw [D.difX_apply]
        _ = D.φ (D.sX y) / D.φ y := by rw [map_div]
        _ = D.sI (D.φ y) / D.φ y := by rw [D.φ_sX]
        _ = D.φ y / D.φ y := by rw [hφy_eq]
        _ = 1 := by simp
    have hnorm_difX : D.normX (D.difX y) = 1 := by
      calc
        D.normX (D.difX y) = D.normX (D.sX y / y) := by rw [D.difX_apply]
        _ = (D.sX y / y) * D.sX (D.sX y / y) := by rw [D.normX_apply]
        _ = (D.sX y / y) * (D.sX (D.sX y) / D.sX y) := by rw [map_div]
        _ = (D.sX y / y) * (y / D.sX y) := by rw [D.sX_sX]
        _ = 1 := by
          simp [div_eq_mul_inv, mul_assoc]
    have hmem_E : D.difX y ∈ D.E := by
      rw [D.mem_E]
      exact hφ_difX
    have hmem_ker : D.difX y ∈ D.normX.ker := by
      rw [MonoidHom.mem_ker]
      exact hnorm_difX
    have : D.Eminus = D.E ⊓ D.normX.ker := rfl
    rw [this]
    exact Subgroup.mem_inf.mpr ⟨hmem_E, hmem_ker⟩
  · intro hx
    rcases Subgroup.mem_inf.mp hx with ⟨hx_E, hx_ker⟩
    have hφx_eq_one : D.φ x = 1 := by rwa [D.mem_E] at hx_E
    have hnormx_eq_one : D.normX x = 1 := by rwa [MonoidHom.mem_ker] at hx_ker
    rcases h x hnormx_eq_one with ⟨y, hy⟩
    use y⁻¹
    constructor
    · apply Subgroup.mem_comap.mpr
      have htemp : x * D.sX y = y := by
        calc
          x * D.sX y = (y / D.sX y) * D.sX y := by rw [hy]
          _ = y := by
            simp [div_eq_mul_inv, mul_assoc]
      have h_sXy : D.sX y = y / x := by
        calc
          D.sX y = x⁻¹ * (x * D.sX y) := by group
          _ = x⁻¹ * y := by rw [htemp]
          _ = y / x := by rw [div_eq_mul_inv, mul_comm]
      have h_φ_sXy : D.sI (D.φ y) = D.φ y := by
        calc
          D.sI (D.φ y) = D.φ (D.sX y) := by rw [D.φ_sX]
          _ = D.φ (y / x) := by rw [h_sXy]
          _ = D.φ y / D.φ x := by rw [map_div]
          _ = D.φ y / 1 := by rw [hφx_eq_one]
          _ = D.φ y := by simp
      calc
        D.sI (D.φ (y⁻¹)) = D.sI ((D.φ y)⁻¹) := by rw [map_inv]
        _ = (D.sI (D.φ y))⁻¹ := by rw [map_inv]
        _ = (D.φ y)⁻¹ := by rw [h_φ_sXy]
        _ = D.φ (y⁻¹) := by rw [map_inv]
    · calc
        D.difX (y⁻¹) = D.sX (y⁻¹) / y⁻¹ := by rw [D.difX_apply]
        _ = (D.sX y)⁻¹ / y⁻¹ := by rw [map_inv]
        _ = (D.sX y)⁻¹ * (y⁻¹)⁻¹ := by rw [div_eq_mul_inv]
        _ = (D.sX y)⁻¹ * y := by simp
        _ = y / D.sX y := by rw [div_eq_mul_inv, mul_comm]
        _ = x := by rw [hy]

theorem FurioLombardo.M3b.InvData.map_sq_Eminus {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.Eminus.map (powMonoidHom 2) = D.Eminus.map D.difX := by
  ext x
  constructor
  · intro h
    rcases Subgroup.mem_map.mp h with ⟨b, hb, rfl⟩
    rcases Subgroup.mem_inf.mp hb with ⟨hbE, hbker⟩
    rw [MonoidHom.mem_ker] at hbker
    rw [D.normX_apply] at hbker
    have hsXb : D.sX b = b⁻¹ := eq_inv_of_mul_eq_one_right hbker
    have hb_inv_mem : b⁻¹ ∈ D.E ⊓ D.normX.ker := by
      refine Subgroup.mem_inf.mpr ⟨?_, ?_⟩
      · rw [InvData.E, MonoidHom.mem_ker] at hbE ⊢
        rw [map_inv, hbE, inv_one]
      · rw [MonoidHom.mem_ker]
        rw [D.normX_apply, map_inv, hsXb]
        simp
    have h_difX : D.difX (b⁻¹) = (powMonoidHom 2) b := by
      calc
        D.difX (b⁻¹) = D.sX (b⁻¹) / b⁻¹ := rfl
        _ = (D.sX b)⁻¹ / b⁻¹ := by rw [map_inv]
        _ = (b⁻¹)⁻¹ / b⁻¹ := by rw [hsXb]
        _ = b / b⁻¹ := by rw [inv_inv]
        _ = b * (b⁻¹)⁻¹ := by rw [div_eq_mul_inv]
        _ = b * b := by rw [inv_inv]
        _ = b ^ 2 := by rw [pow_two]
        _ = (powMonoidHom 2) b := rfl
    apply Subgroup.mem_map.mpr
    exact ⟨b⁻¹, hb_inv_mem, h_difX⟩
  · intro h
    rcases Subgroup.mem_map.mp h with ⟨b, hb, rfl⟩
    rcases Subgroup.mem_inf.mp hb with ⟨hbE, hbker⟩
    rw [MonoidHom.mem_ker] at hbker
    rw [D.normX_apply] at hbker
    have hsXb : D.sX b = b⁻¹ := eq_inv_of_mul_eq_one_right hbker
    have hb_inv_mem : b⁻¹ ∈ D.E ⊓ D.normX.ker := by
      refine Subgroup.mem_inf.mpr ⟨?_, ?_⟩
      · rw [InvData.E, MonoidHom.mem_ker] at hbE ⊢
        rw [map_inv, hbE, inv_one]
      · rw [MonoidHom.mem_ker]
        rw [D.normX_apply, map_inv, hsXb]
        simp
    have h_sq : (powMonoidHom 2) (b⁻¹) = D.difX b := by
      calc
        (powMonoidHom 2) (b⁻¹) = (b⁻¹) ^ 2 := rfl
        _ = (b⁻¹) * (b⁻¹) := by rw [pow_two]
        _ = b⁻¹ * b⁻¹ := rfl
        _ = b⁻¹ / b := by rw [div_eq_mul_inv]
        _ = D.sX b / b := by rw [hsXb]
        _ = D.difX b := rfl
    apply Subgroup.mem_map.mpr
    exact ⟨b⁻¹, hb_inv_mem, h_sq⟩

theorem FurioLombardo.M3b.InvData.map_sq_Eplus {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.Eplus.map (powMonoidHom 2) = D.Eplus.map D.normX := by
  apply Subgroup.ext
  intro y
  constructor
  · rintro ⟨a, ha, rfl⟩
    have ha_sX : D.sX a = a := (D.mem_fixX a).mp ((Subgroup.mem_inf.mp ha).2)
    refine ⟨a, ha, ?_⟩
    calc
      D.normX a = a * D.sX a := D.normX_apply a
      _ = a * a := by rw [ha_sX]
      _ = a ^ 2 := by simp [pow_two]
      _ = powMonoidHom 2 a := by simp
  · rintro ⟨a, ha, rfl⟩
    have ha_sX : D.sX a = a := (D.mem_fixX a).mp ((Subgroup.mem_inf.mp ha).2)
    refine ⟨a, ha, ?_⟩
    calc
      powMonoidHom 2 a = a ^ 2 := by simp
      _ = a * a := by simp [pow_two]
      _ = a * D.sX a := by rw [ha_sX]
      _ = D.normX a := by rw [D.normX_apply]

theorem FurioLombardo.M3b.InvData.NE_le_NXE {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.NE ≤ D.NXE := by
  intro z hz
  rcases Subgroup.mem_map.mp hz with ⟨e, he, rfl⟩
  have hφe : D.φ e = 1 := ((InvData.mem_E D e).mp he)
  refine Subgroup.mem_inf.mpr ⟨?_, (MonoidHom.mem_range (f := D.normX)).mpr ⟨e, rfl⟩⟩
  rw [InvData.mem_E, InvData.normX_apply, map_mul, D.φ_sX, hφe]
  simp

theorem FurioLombardo.M3b.InvData.NXE_le_Eplus {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.NXE ≤ D.Eplus := by
  intro x hx
  rcases Subgroup.mem_inf.mp hx with ⟨hxE, hxNXE⟩
  refine Subgroup.mem_inf.mpr ⟨hxE, ?_⟩
  rw [D.mem_fixX]
  rcases MonoidHom.mem_range.mp hxNXE with ⟨y, hy⟩
  rw [D.normX_apply] at hy
  calc
    D.sX x = D.sX (y * D.sX y) := by rw [hy]
    _ = D.sX y * D.sX (D.sX y) := by rw [map_mul]
    _ = D.sX y * y := by rw [D.sX_sX y]
    _ = y * D.sX y := by rw [mul_comm]
    _ = x := by rw [← hy]

theorem FurioLombardo.M3b.InvData.Pfix_eq {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.Pfix = (D.fixI.comap D.φ).map D.φ := by
  ext a
  constructor
  · intro h
    rcases Subgroup.mem_inf.mp h with ⟨hP, hfixI⟩
    rcases (MonoidHom.mem_range.mp hP) with ⟨x, hx⟩
    rw [Subgroup.mem_map]
    use x
    constructor
    · rw [Subgroup.mem_comap, hx]
      exact hfixI
    · exact hx
  · intro h
    rw [Subgroup.mem_map] at h
    rcases h with ⟨x, hx_comap, hx⟩
    show a ∈ D.P ⊓ D.fixI
    rw [Subgroup.mem_inf]
    constructor
    · rw [← hx]
      exact (MonoidHom.mem_range.mpr ⟨x, rfl⟩)
    · rw [← hx]
      rwa [Subgroup.mem_comap] at hx_comap

theorem FurioLombardo.M3b.InvData.PK_le_Pfix {X I : Type*} [CommGroup X] [CommGroup I] (D : InvData X I) :
    D.PK ≤ D.Pfix := by
  intro a ha
  rw [FurioLombardo.M3b.InvData.PK] at ha
  rw [Subgroup.mem_map] at ha
  rcases ha with ⟨x, hx, rfl⟩
  rw [FurioLombardo.M3b.InvData.Pfix, Subgroup.mem_inf]
  constructor
  · rw [FurioLombardo.M3b.InvData.P]
    exact ⟨x, rfl⟩
  · rw [FurioLombardo.M3b.InvData.mem_fixI]
    rw [← D.φ_sX x]
    rw [FurioLombardo.M3b.InvData.mem_fixX] at hx
    rw [hx]

theorem FurioLombardo.M3b.relIndex_map_map {G A : Type*} [Group G] [Group A] (f : G →* A)
    (H K : Subgroup G) : (H.map f).relIndex (K.map f) = (H ⊔ f.ker).relIndex K := by
  rw [← Subgroup.relIndex_comap, Subgroup.comap_map_eq]

theorem FurioLombardo.M3b.InvData.DE_le_Eminus {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) : D.DE ≤ D.Eminus := by
  rintro _ ⟨e, he, rfl⟩
  have he' : D.φ e = 1 := he
  refine ⟨?_, ?_⟩
  · show D.φ (D.difX e) = 1
    rw [D.difX_apply, map_div, D.φ_sX, he', map_one, div_one]
  · show D.normX (D.difX e) = 1
    rw [D.normX_apply, D.difX_apply, map_div, D.sX_sX, div_mul_div_comm, mul_comm e, div_self']

theorem FurioLombardo.M3b.InvData.range_pi1 {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) : D.pi1.range = D.amb := by
  ext c
  constructor
  · rintro ⟨p, rfl⟩
    rw [D.mem_amb, D.pi1_apply, D.sCl_mk, (D.mem_G _).1 p.2]
    refine (QuotientGroup.eq_iff_div_mem).2 ?_
    rw [mul_div_cancel_right]
    exact ⟨_, rfl⟩
  · intro hc
    obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective c
    rw [D.mem_amb, D.sCl_mk, QuotientGroup.eq_iff_div_mem] at hc
    obtain ⟨x, hx⟩ := hc
    refine ⟨⟨(a, x), ?_⟩, rfl⟩
    rw [D.mem_G]
    simp only
    rw [hx, div_mul_cancel]

theorem FurioLombardo.M3b.InvData.range_psi {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) (h : D.H90I) : D.psi.range = D.NXE := by
  ext e
  constructor
  · rintro ⟨p, rfl⟩
    have hp := (D.mem_G _).1 p.2
    refine ⟨?_, ⟨(p : I × X).2, rfl⟩⟩
    show D.φ (D.psi p) = 1
    rw [D.psi_apply, map_mul, D.φ_sX]
    have h2 := congrArg D.sI hp
    rw [D.sI_sI, map_mul, hp] at h2
    have h3 : D.sI (D.φ (p : I × X).2) * D.φ (p : I × X).2 = 1 := by
      have := h2.symm
      rw [← mul_assoc] at this
      exact mul_eq_right.1 this
    rw [mul_comm]; exact h3
  · rintro ⟨he, ⟨x, rfl⟩⟩
    have he' : D.φ (D.normX x) = 1 := he
    rw [D.normX_apply, map_mul, D.φ_sX] at he'
    obtain ⟨b, hb⟩ := h _ he'
    refine ⟨⟨(D.sI b, x), ?_⟩, rfl⟩
    rw [D.mem_G]
    simp only
    rw [D.sI_sI, hb, div_mul_cancel]

theorem FurioLombardo.M3b.InvData.map_comap_psi {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) (h : D.H90X) :
    (D.NE.comap D.psi).map D.pi1 = D.fixI.map (QuotientGroup.mk' D.P) := by
  ext c
  constructor
  · rintro ⟨p, hp, rfl⟩
    obtain ⟨e, he, heq⟩ := hp
    have he' : D.φ e = 1 := he
    have hG := (D.mem_G _).1 p.2
    set a := (p : I × X).1
    set x := (p : I × X).2
    have hn : D.normX (x / e) = 1 := by
      rw [map_div, D.normX_apply x, ← D.psi_apply, ← heq, div_self']
    obtain ⟨y, hy⟩ := h _ hn
    have hx : x = e * (y / D.sX y) := by rw [← hy, mul_div_cancel]
    refine ⟨a * D.φ y, ?_, ?_⟩
    · show D.sI (a * D.φ y) = a * D.φ y
      rw [map_mul, hG, ← D.φ_sX, hx, map_mul, he', one_mul, map_div]
      simp only [div_eq_mul_inv, mul_comm, mul_left_comm, mul_inv_cancel, one_mul]
    · rw [D.pi1_apply, QuotientGroup.mk'_apply, QuotientGroup.eq_iff_div_mem]
      show a * D.φ y / a ∈ D.P
      rw [mul_div_cancel_left]
      exact ⟨y, rfl⟩
  · rintro ⟨a, ha, rfl⟩
    have hG : (a, (1 : X)) ∈ D.G := by
      rw [D.mem_G]; simp only [map_one, one_mul]; exact ha
    refine ⟨⟨(a, 1), hG⟩, ?_, rfl⟩
    show D.psi ⟨(a, 1), hG⟩ ∈ D.NE
    rw [D.psi_apply]
    simp only [map_one, mul_one]
    exact one_mem _

theorem FurioLombardo.M3b.InvData.card_amb {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) (h90X : D.H90X) (h90I : D.H90I) :
    Nat.card D.amb = D.Pfix.relIndex D.fixI * D.NE.relIndex D.NXE := by
  have h := card_range_eq_card_map_mul_relIndex D.pi1 D.psi D.NE D.ker_pi1_le
  rw [D.range_pi1, D.map_comap_psi h90X, card_map_mk, D.range_psi h90I] at h
  rw [h, InvData.Pfix, Subgroup.inf_relIndex_right]

theorem FurioLombardo.M3b.InvData.relIndex_PK_Pfix {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) (h90X : D.H90X) :
    D.PK.relIndex D.Pfix = D.DE.relIndex D.Eminus := by
  rw [D.Pfix_eq, InvData.PK, relIndex_map_map, ← D.map_difX_comap h90X, InvData.DE,
    relIndex_map_map, D.ker_difX, sup_comm]
  rfl

theorem FurioLombardo.M3b.InvData.herbrand_plus {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) :
    D.NE.relIndex D.Eplus * (D.Eplus ⊔ D.Eminus).relIndex D.E =
      (D.Eplus.map (powMonoidHom 2)).relIndex D.Eplus := by
  have hPE : D.Eplus ≤ D.E := inf_le_left
  have h1 : D.Eplus.map (powMonoidHom 2) ≤ D.NE := by
    rw [D.map_sq_Eplus]; exact Subgroup.map_mono hPE
  have h2 : D.NE ≤ D.Eplus := D.NE_le_NXE.trans D.NXE_le_Eplus
  have h3 : (D.Eplus.map (powMonoidHom 2)).relIndex D.NE = (D.Eplus ⊔ D.Eminus).relIndex D.E := by
    rw [D.map_sq_Eplus, InvData.NE, relIndex_map_map, ← D.E_inf_sup_plus, inf_comm,
      Subgroup.inf_relIndex_right]
  rw [← Subgroup.relIndex_mul_relIndex _ _ _ h1 h2, h3, mul_comm]

theorem FurioLombardo.M3b.InvData.herbrand_minus {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) :
    D.DE.relIndex D.Eminus * (D.Eplus ⊔ D.Eminus).relIndex D.E =
      (D.Eminus.map (powMonoidHom 2)).relIndex D.Eminus := by
  have hME : D.Eminus ≤ D.E := inf_le_left
  have h1 : D.Eminus.map (powMonoidHom 2) ≤ D.DE := by
    rw [D.map_sq_Eminus]; exact Subgroup.map_mono hME
  have h3 : (D.Eminus.map (powMonoidHom 2)).relIndex D.DE = (D.Eplus ⊔ D.Eminus).relIndex D.E := by
    rw [D.map_sq_Eminus, InvData.DE, relIndex_map_map, D.ker_difX, ← D.E_inf_sup_minus, inf_comm,
      Subgroup.inf_relIndex_right]
  rw [← Subgroup.relIndex_mul_relIndex _ _ _ h1 D.DE_le_Eminus, h3, mul_comm]

/-- The abstract ambiguous class count: `|amb| [E⁻ : (E⁻)²] [E⁺ : E ∩ N X] = [fix I : PK] [E⁺ : (E⁺)²]`. -/
theorem FurioLombardo.M3b.InvData.chevalley_abstract {X I : Type*} [CommGroup X] [CommGroup I]
    (D : InvData X I) (h90X : D.H90X) (h90I : D.H90I) :
    Nat.card D.amb * (D.Eminus.map (powMonoidHom 2)).relIndex D.Eminus * D.NXE.relIndex D.Eplus =
      D.PK.relIndex D.fixI * (D.Eplus.map (powMonoidHom 2)).relIndex D.Eplus := by
  have hk : D.PK.relIndex D.Pfix * D.Pfix.relIndex D.fixI = D.PK.relIndex D.fixI :=
    Subgroup.relIndex_mul_relIndex _ _ _ D.PK_le_Pfix inf_le_right
  have hn : D.NE.relIndex D.NXE * D.NXE.relIndex D.Eplus = D.NE.relIndex D.Eplus :=
    Subgroup.relIndex_mul_relIndex _ _ _ D.NE_le_NXE D.NXE_le_Eplus
  rw [D.card_amb h90X h90I, ← D.herbrand_minus, ← D.herbrand_plus, ← hk, ← hn,
    D.relIndex_PK_Pfix h90X]
  ring
