/-
Lane M3b (furio-lombardo-quartic): fixed points of an involution on a finite commutative group.

If an involutive automorphism `σ` of a finite commutative group `A` has a fixed subgroup of odd
order, then `A` has no element of order 2. This is the group theory step that turns an odd
ambiguous class number `|Cl(L)^G|` into `Cl(L)[2] = 0` for a quadratic extension `L/K`.
-/
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.GroupTheory.SpecificGroups.Cyclic

namespace FurioLombardo.M3b

variable {A : Type*} [CommGroup A]

/-- The subgroup of elements fixed by a group endomorphism. -/
def fixedSubgroup (σ : A →* A) : Subgroup A := MonoidHom.eqLocus σ (MonoidHom.id A)

theorem mem_fixedSubgroup (σ : A →* A) (a : A) : a ∈ fixedSubgroup σ ↔ σ a = a := Iff.rfl

/-- The 2-torsion subgroup `A[2]`. -/
def twoTorsion (A : Type*) [CommGroup A] : Subgroup A := (powMonoidHom 2 : A →* A).ker

theorem mem_twoTorsion (a : A) : a ∈ twoTorsion A ↔ a ^ 2 = 1 := Iff.rfl

/-- An involution of a finite set has a number of fixed points congruent to the cardinality
modulo 2. -/
theorem card_modEq_card_fixed_of_involutive {α : Type*} [Finite α] (f : α → α)
    (hf : ∀ x, f (f x) = x) :
    Nat.card α ≡ Nat.card {x // f x = x} [MOD 2] := by
  classical
  have := Fintype.ofFinite α
  let g : Function.End α := f
  have hg : g ^ 2 ^ 1 = 1 := by
    funext x
    simp only [pow_one, sq]
    exact hf x
  have hmod := Equiv.Perm.card_fixedPoints_modEq (α := α) (f := g) (p := 2) (n := 1) hg
  calc Nat.card α = Fintype.card α := Nat.card_eq_fintype_card
    _ ≡ Fintype.card (Function.fixedPoints g) [MOD 2] := hmod
    _ = Nat.card (Function.fixedPoints g) := Nat.card_eq_fintype_card.symm
    _ = Nat.card {x // f x = x} :=
        Nat.card_congr (Equiv.subtypeEquivRight (fun x => Iff.rfl))

/-- If `σ` is an involutive endomorphism of a finite commutative group whose fixed subgroup has
odd order, then the 2-torsion of the group is trivial. -/
theorem eq_one_of_sq_eq_one_of_odd_card_fixed [Finite A] (σ : A →* A)
    (hσ : ∀ a, σ (σ a) = a) (hodd : Odd (Nat.card (fixedSubgroup σ))) :
    ∀ a : A, a ^ 2 = 1 → a = 1 := by
  classical
  intro a ha
  by_contra hne
  -- `A[2]` has even order: it contains the subgroup of order 2 generated by `a`.
  have hT : 2 ∣ Nat.card (twoTorsion A) := by
    have hord : orderOf a = 2 := orderOf_eq_prime ha hne
    have hle : Subgroup.zpowers a ≤ twoTorsion A := by
      rw [Subgroup.zpowers_le]
      exact ha
    have := Subgroup.card_dvd_of_le hle
    rwa [Nat.card_zpowers, hord] at this
  -- `σ` restricts to an involution of `A[2]`.
  let f : twoTorsion A → twoTorsion A := fun t =>
    ⟨σ t, by
      rw [mem_twoTorsion, ← map_pow, (mem_twoTorsion (t : A)).1 t.2, map_one]⟩
  have hf : ∀ t, f (f t) = t := fun t => Subtype.ext (hσ t)
  have hmod := card_modEq_card_fixed_of_involutive f hf
  -- the fixed points of `f` form the subgroup `A[2] ⊓ A^σ`
  let e : {t // f t = t} ≃ (twoTorsion A ⊓ fixedSubgroup σ : Subgroup A) :=
    { toFun := fun t => ⟨t.1, t.1.2, congrArg Subtype.val t.2⟩
      invFun := fun s => ⟨⟨s.1, s.2.1⟩, Subtype.ext s.2.2⟩
      left_inv := fun t => rfl
      right_inv := fun s => rfl }
  have hfix : 2 ∣ Nat.card (twoTorsion A ⊓ fixedSubgroup σ : Subgroup A) := by
    rw [← Nat.card_congr e]
    exact (Nat.modEq_zero_iff_dvd.1 (hmod.symm.trans (Nat.modEq_zero_iff_dvd.2 hT)))
  have hdvd : Nat.card (twoTorsion A ⊓ fixedSubgroup σ : Subgroup A) ∣
      Nat.card (fixedSubgroup σ) := Subgroup.card_dvd_of_le inf_le_right
  exact (Nat.not_even_iff_odd.2 hodd) (even_iff_two_dvd.2 (hfix.trans hdvd))

/-- A finite commutative group without elements of order 2 has odd order (Cauchy). -/
theorem odd_card_of_sq_eq_one [Finite A] (h : ∀ a : A, a ^ 2 = 1 → a = 1) :
    Odd (Nat.card A) := by
  rw [← Nat.not_even_iff_odd, even_iff_two_dvd]
  intro h2
  have : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨a, ha⟩ := exists_prime_orderOf_dvd_card' 2 h2
  have ha1 : a ^ 2 = 1 := by rw [← ha]; exact pow_orderOf_eq_one a
  have := h a ha1
  rw [this, orderOf_one] at ha
  exact absurd ha (by norm_num)

/-- Conversely, a finite commutative group of odd order has no element of order 2. -/
theorem sq_eq_one_of_odd_card [Finite A] (h : Odd (Nat.card A)) :
    ∀ a : A, a ^ 2 = 1 → a = 1 := by
  intro a ha
  by_contra hne
  have hord : orderOf a = 2 := orderOf_eq_prime ha hne
  have := orderOf_dvd_natCard a
  rw [hord] at this
  exact (Nat.not_even_iff_odd.2 h) (even_iff_two_dvd.2 this)

end FurioLombardo.M3b
