import FurioLombardo.M3b.Glue
import FurioLombardo.M3b.Factorization

/-!
# Lane M3b: ambiguous ideals of a quadratic extension

For `L/K` quadratic with nontrivial automorphism `σ`, in the invertible fractional ideals `I_L` of `L`:
`[fix I_L : PK] = 2 ^ t_f * h_K`, where `PK` is the group of principal ideals generated by elements
of `K`, `t_f` the number of finite primes of `K` ramified in `L` (`relIndex_PK_fixI`).

Proof: `PK = ext(P_K) ≤ ext(I_K) ≤ fix I_L`, extension is injective so `[ext I_K : ext P_K] = h_K`,
and `[fix I_L : ext I_K] = 2 ^ t_f` after transport through the factorization
`I_L ≃ ⊕_Q ℤ` (`factorization`): `fix I_L` becomes the `σ`-invariant functions and `ext I_K` the
invariant functions divisible by the ramification index at every prime (`mem_fixI_iff`,
`mem_range_extU_iff`), and the index of the second in the first is `2 ^ #{Q : e_Q = 2}` by a
count mod 2 at the ramified primes (`relIndex_ext_fix`). The primes of `L` with `e_Q = 2` are in
bijection with the ramified primes of `K` (`ncard_eQ_two`, from the fundamental identity
`e * g * f = 2` and the transitivity of the Galois action on the primes above a prime).
-/

set_option linter.unusedSectionVars false

namespace FurioLombardo.M3b

open NumberField IsDedekindDomain FractionalIdeal
open scoped nonZeroDivisors

/-! ### Primes and ideals under a ring automorphism -/

section Generic

variable {R : Type*} [CommRing R] [IsDedekindDomain R] {F : Type*} [Field F] [Algebra R F]
  [IsFractionRing R F]

/-- The image of a height one prime under a ring automorphism. -/
def mapHOS (τ : R ≃+* R) (P : HeightOneSpectrum R) : HeightOneSpectrum R where
  asIdeal := P.asIdeal.map τ
  isPrime := Ideal.map_isPrime_of_equiv τ
  ne_bot := by
    rw [Ne, Ideal.map_eq_bot_iff_of_injective τ.injective]
    exact P.ne_bot

theorem mapHOS_asIdeal (τ : R ≃+* R) (P : HeightOneSpectrum R) :
    (mapHOS τ P).asIdeal = P.asIdeal.map τ := rfl

theorem mapHOS_symm_mapHOS (τ : R ≃+* R) (P : HeightOneSpectrum R) :
    mapHOS τ.symm (mapHOS τ P) = P := by
  ext1
  rw [mapHOS_asIdeal, mapHOS_asIdeal]
  exact Ideal.map_of_equiv τ

theorem mapHOS_injective (τ : R ≃+* R) : Function.Injective (mapHOS τ) :=
  Function.LeftInverse.injective (mapHOS_symm_mapHOS τ)

/-- A ring automorphism maps the fractional ideal of an ideal to the fractional ideal of its image. -/
theorem coeIdeal_ringEquivOfRingEquiv (τ : R ≃+* R) (I : Ideal R) :
    ringEquivOfRingEquiv F F τ (I : FractionalIdeal R⁰ F) =
      ((I.map τ : Ideal R) : FractionalIdeal R⁰ F) := by
  ext x
  rw [← FractionalIdeal.mem_coe, ← FractionalIdeal.val_eq_coe, ringEquivOfRingEquiv_apply_val,
    Submodule.mem_map, FractionalIdeal.mem_coeIdeal]
  simp only [FractionalIdeal.val_eq_coe, FractionalIdeal.mem_coe, FractionalIdeal.mem_coeIdeal,
    Ideal.mem_map_of_equiv]
  constructor
  · rintro ⟨y, ⟨i, hi, rfl⟩, rfl⟩
    exact ⟨τ i, ⟨i, hi, rfl⟩, (IsFractionRing.ringEquivOfRingEquiv_algebraMap τ i).symm⟩
  · rintro ⟨j, ⟨i, hi, rfl⟩, rfl⟩
    exact ⟨algebraMap R F i, ⟨i, hi, rfl⟩, IsFractionRing.ringEquivOfRingEquiv_algebraMap τ i⟩

variable (F) in
/-- A ring automorphism acting on the invertible fractional ideals. -/
noncomputable def mapU (τ : R ≃+* R) : (FractionalIdeal R⁰ F)ˣ →* (FractionalIdeal R⁰ F)ˣ :=
  Units.map (ringEquivOfRingEquiv F F τ).toMonoidHom

theorem coe_mapU (τ : R ≃+* R) (a : (FractionalIdeal R⁰ F)ˣ) :
    ((mapU F τ a : (FractionalIdeal R⁰ F)ˣ) : FractionalIdeal R⁰ F) =
      ringEquivOfRingEquiv F F τ (a : FractionalIdeal R⁰ F) := rfl

theorem mapU_unitOfPrime (τ : R ≃+* R) (P : HeightOneSpectrum R) :
    mapU F τ (unitOfPrime F P) = unitOfPrime F (mapHOS τ P) :=
  Units.ext (coeIdeal_ringEquivOfRingEquiv τ P.asIdeal)

theorem mapU_ofFinsupp (τ : R ≃+* R) (g : HeightOneSpectrum R →₀ ℤ) :
    mapU F τ (ofFinsupp F g) = ofFinsupp F (g.mapDomain (mapHOS τ)) := by
  rw [ofFinsupp, ofFinsupp, map_finsuppProd,
    Finsupp.prod_mapDomain_index_inj (mapHOS_injective τ)]
  simp only [map_zpow, mapU_unitOfPrime]

/-- **Counts are transported by a ring automorphism.** -/
theorem count_mapU (τ : R ≃+* R) (P : HeightOneSpectrum R) (a : (FractionalIdeal R⁰ F)ˣ) :
    count F (mapHOS τ P) (mapU F τ a : FractionalIdeal R⁰ F) = count F P a := by
  conv_lhs => rw [← ofFinsupp_toFinsupp a]
  rw [mapU_ofFinsupp, count_ofFinsupp]
  exact Finsupp.mapDomain_apply_of_injective (mapHOS_injective τ) _ _

end Generic

/-! ### Invariant functions on a set with an involution -/

section Combinatorial

variable {V : Type*}

/-- Finitely supported functions invariant under `τ`. -/
def fixSubgroup (τ : V → V) : AddSubgroup (V →₀ ℤ) where
  carrier := {f | ∀ Q, f (τ Q) = f Q}
  add_mem' := by
    intro f g hf hg Q
    simp only [Finsupp.coe_add, Pi.add_apply, hf Q, hg Q]
  zero_mem' := by simp
  neg_mem' := by
    intro f hf Q
    simp only [Finsupp.coe_neg, Pi.neg_apply, hf Q]

theorem mem_fixSubgroup (τ : V → V) (f : V →₀ ℤ) : f ∈ fixSubgroup τ ↔ ∀ Q, f (τ Q) = f Q :=
  Iff.rfl

/-- Invariant functions whose value at `Q` is divisible by `e Q` (the extended ideals). -/
def extSubgroup (τ : V → V) (e : V → ℕ) : AddSubgroup (V →₀ ℤ) where
  carrier := {f | (∀ Q, f (τ Q) = f Q) ∧ ∀ Q, (e Q : ℤ) ∣ f Q}
  add_mem' := by
    rintro f g ⟨hf, hf'⟩ ⟨hg, hg'⟩
    exact ⟨fun Q ↦ by simp only [Finsupp.coe_add, Pi.add_apply, hf Q, hg Q],
      fun Q ↦ by simpa using dvd_add (hf' Q) (hg' Q)⟩
  zero_mem' := ⟨by simp, by simp⟩
  neg_mem' := by
    rintro f ⟨hf, hf'⟩
    exact ⟨fun Q ↦ by simp only [Finsupp.coe_neg, Pi.neg_apply, hf Q],
      fun Q ↦ by simpa using (hf' Q).neg_right⟩

theorem mem_extSubgroup (τ : V → V) (e : V → ℕ) (f : V →₀ ℤ) :
    f ∈ extSubgroup τ e ↔ (∀ Q, f (τ Q) = f Q) ∧ ∀ Q, (e Q : ℤ) ∣ f Q := Iff.rfl

/-- **Combinatorial core**: the invariant functions divisible by `e` have index `2 ^ #{e = 2}` in
the invariant functions, when `e` takes the values 1 and 2 and `τ` fixes the points with `e = 2`. -/
theorem relIndex_ext_fix (τ : V → V) (e : V → ℕ)
    (hinv : ∀ Q, τ (τ Q) = Q) (he : ∀ Q, e Q = 1 ∨ e Q = 2) (hτ : ∀ Q, e Q = 2 → τ Q = Q)
    (hR : {Q | e Q = 2}.Finite) :
    (extSubgroup τ e).relIndex (fixSubgroup τ) = 2 ^ {Q | e Q = 2}.ncard := by
  classical
  set R := {Q | e Q = 2} with hRdef
  have : Fintype R := hR.fintype
  let ρ : fixSubgroup τ →+ (R → ZMod 2) :=
    { toFun := fun f q => (((f : V →₀ ℤ) q.1 : ℤ) : ZMod 2)
      map_zero' := by ext; simp
      map_add' := by intro f g; ext; simp }
  have hρ : ∀ f q, ρ f q = (((f : V →₀ ℤ) q.1 : ℤ) : ZMod 2) := fun _ _ => rfl
  have hker : ρ.ker = (extSubgroup τ e).addSubgroupOf (fixSubgroup τ) := by
    ext f
    rw [AddMonoidHom.mem_ker, AddSubgroup.mem_addSubgroupOf, mem_extSubgroup]
    constructor
    · intro h
      refine ⟨f.2, fun Q => ?_⟩
      rcases he Q with h1 | h1
      · rw [h1]; exact_mod_cast one_dvd _
      · have := congrFun h ⟨Q, h1⟩
        rw [hρ, Pi.zero_apply, ZMod.intCast_zmod_eq_zero_iff_dvd] at this
        rw [h1]; exact_mod_cast this
    · rintro ⟨-, hd⟩
      funext q
      have := hd q.1
      rw [show e q.1 = 2 from q.2] at this
      rw [hρ, Pi.zero_apply, ZMod.intCast_zmod_eq_zero_iff_dvd]
      exact_mod_cast this
  have hsingle : ∀ q : R, Finsupp.single q.1 (1 : ℤ) ∈ fixSubgroup τ := by
    intro q P
    have hiff : q.1 = τ P ↔ q.1 = P := by
      constructor
      · intro h; rw [← hinv P, ← h, hτ q.1 q.2]
      · intro h; rw [← h, hτ q.1 q.2]
    simp only [Finsupp.single_apply, hiff]
  have hsurj : Function.Surjective ρ := by
    intro g
    refine ⟨⟨∑ q : R, ((g q).val : ℤ) • Finsupp.single q.1 (1 : ℤ),
      AddSubgroup.sum_mem _ fun q _ => AddSubgroup.zsmul_mem _ (hsingle q) _⟩, ?_⟩
    funext q
    rw [hρ]
    simp only [Finsupp.coe_finsetSum, Finset.sum_apply, Finsupp.coe_smul, Pi.smul_apply,
      Finsupp.single_apply, smul_eq_mul, mul_ite, mul_one, mul_zero]
    rw [Finset.sum_eq_single q]
    · rw [ite_eq_left rfl]; simp
    · intro b _ hb
      rw [ite_eq_right]
      intro h; exact hb (Subtype.ext h)
    · intro h; exact absurd (Finset.mem_univ q) h
  rw [AddSubgroup.relIndex, ← hker, AddSubgroup.index_ker, AddMonoidHom.range_eq_top.2 hsurj,
    AddSubgroup.card_top, Nat.card_fun, Nat.card_zmod, Nat.card_coe_set_eq]

end Combinatorial

/-! ### Primes of a quadratic extension -/

section Primes

variable {K L : Type} [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L]

/-- The prime of `𝓞 K` below a prime of `𝓞 L`. -/
def belowP (Q : HeightOneSpectrum (𝓞 L)) : HeightOneSpectrum (𝓞 K) where
  asIdeal := Q.asIdeal.under (𝓞 K)
  isPrime := Ideal.IsPrime.under (𝓞 K) Q.asIdeal
  ne_bot := Ideal.under_ne_bot (𝓞 K) Q.ne_bot

theorem belowP_asIdeal (Q : HeightOneSpectrum (𝓞 L)) :
    (belowP (K := K) Q).asIdeal = Q.asIdeal.under (𝓞 K) := rfl

variable (K) in
/-- The ramification index of a prime of `𝓞 L` over `𝓞 K`. -/
noncomputable def eQ (Q : HeightOneSpectrum (𝓞 L)) : ℕ := Q.asIdeal.ramificationIdx (𝓞 K)

/-- `σ` on the primes of `𝓞 L`. -/
noncomputable def sigmaP (σ : L ≃ₐ[K] L) (Q : HeightOneSpectrum (𝓞 L)) :
    HeightOneSpectrum (𝓞 L) :=
  mapHOS (sigmaO σ) Q

theorem sigmaP_asIdeal (σ : L ≃ₐ[K] L) (Q : HeightOneSpectrum (𝓞 L)) :
    (sigmaP σ Q).asIdeal = Q.asIdeal.map (sigmaO σ) := rfl

theorem sigmaO_algebraMap (σ : L ≃ₐ[K] L) (x : 𝓞 K) :
    sigmaO σ (algebraMap (𝓞 K) (𝓞 L) x) = algebraMap (𝓞 K) (𝓞 L) x := by
  apply RingOfIntegers.ext
  rw [sigmaO_apply]
  have h : ((algebraMap (𝓞 K) (𝓞 L) x : 𝓞 L) : L) = algebraMap K L ((x : 𝓞 K) : K) :=
    IsScalarTower.algebraMap_apply (𝓞 K) K L x
  rw [h]
  exact AlgEquiv.commutes σ ((x : 𝓞 K) : K)

/-- The Galois group acts on `𝓞 L` commuting with the scalars of `𝓞 K`. -/
instance smulCommClass_gal : SMulCommClass (L ≃ₐ[K] L) (𝓞 K) (𝓞 L) where
  smul_comm τ x y := by
    apply RingOfIntegers.ext
    change τ ((x • y : 𝓞 L) : L) = ((x • (τ • y) : 𝓞 L) : L)
    rw [Algebra.smul_def, Algebra.smul_def]
    change τ (((algebraMap (𝓞 K) (𝓞 L) x) : L) * (y : L)) =
      ((algebraMap (𝓞 K) (𝓞 L) x : 𝓞 L) : L) * τ (y : L)
    rw [map_mul]
    congr 1
    exact congrArg (fun z : 𝓞 L => (z : L)) (sigmaO_algebraMap τ x)

theorem sigmaO_eq_toRingHom (σ : L ≃ₐ[K] L) :
    ((sigmaO σ : 𝓞 L ≃+* 𝓞 L) : 𝓞 L →+* 𝓞 L) = MulSemiringAction.toRingHom _ (𝓞 L) σ := by
  ext x
  rfl

open scoped Pointwise in
/-- `sigmaP` is the pointwise action of the Galois group on ideals. -/
theorem sigmaP_asIdeal_eq_smul (σ : L ≃ₐ[K] L) (Q : HeightOneSpectrum (𝓞 L)) :
    (sigmaP σ Q).asIdeal = σ • Q.asIdeal := by
  rw [sigmaP_asIdeal, Ideal.pointwise_smul_def, ← sigmaO_eq_toRingHom]
  rfl

theorem belowP_sigmaP (σ : L ≃ₐ[K] L) (Q : HeightOneSpectrum (𝓞 L)) :
    belowP (K := K) (sigmaP σ Q) = belowP Q := by
  ext1
  rw [belowP_asIdeal, belowP_asIdeal, sigmaP_asIdeal_eq_smul]
  exact Ideal.under_smul (𝓞 K) Q.asIdeal σ

theorem sigmaP_sigmaP (h2 : Module.finrank K L = 2) (σ : L ≃ₐ[K] L)
    (Q : HeightOneSpectrum (𝓞 L)) : sigmaP σ (sigmaP σ Q) = Q := by
  ext1
  rw [sigmaP_asIdeal, sigmaP_asIdeal]
  have : ((sigmaO σ : 𝓞 L ≃+* 𝓞 L) : 𝓞 L →+* 𝓞 L).comp (sigmaO σ : 𝓞 L →+* 𝓞 L) =
      RingHom.id _ := RingHom.ext fun x => sigmaO_sigmaO σ (sigma_sigma h2 σ) x
  change Ideal.map ((sigmaO σ : 𝓞 L ≃+* 𝓞 L) : 𝓞 L →+* 𝓞 L)
    (Ideal.map ((sigmaO σ : 𝓞 L ≃+* 𝓞 L) : 𝓞 L →+* 𝓞 L) Q.asIdeal) = Q.asIdeal
  rw [Ideal.map_map, this, Ideal.map_id]

theorem eQ_sigmaP (σ : L ≃ₐ[K] L) (Q : HeightOneSpectrum (𝓞 L)) :
    eQ K (sigmaP σ Q) = eQ K Q := by
  rw [eQ, eQ, sigmaP_asIdeal_eq_smul, Ideal.ramificationIdx_smul]

theorem belowP_surjective : Function.Surjective (belowP (K := K) (L := L)) := by
  intro P
  obtain ⟨Q, -, hQp, hQP⟩ := Ideal.exists_ideal_over_prime_of_isIntegral (S := 𝓞 L) P.asIdeal ⊥
    (by simp [← RingHom.ker_eq_comap_bot])
  have hQ0 : Q ≠ ⊥ := by
    rintro rfl
    apply P.ne_bot
    rw [← hQP]
    exact Ideal.under_bot _ _
  exact ⟨⟨Q, hQp, hQ0⟩, by ext1; exact hQP⟩

theorem liesOver_belowP (Q : HeightOneSpectrum (𝓞 L)) :
    Q.asIdeal.LiesOver (belowP (K := K) Q).asIdeal := ⟨rfl⟩

/-- The fundamental identity at the prime below `Q`: `e_Q * (#primes above * f) = 2`. -/
theorem eQ_mul_eq_two (h2 : Module.finrank K L = 2) (Q : HeightOneSpectrum (𝓞 L)) :
    eQ K Q * ((Ideal.primesOver (belowP (K := K) Q).asIdeal (𝓞 L)).ncard *
      Ideal.inertiaDegIn (belowP (K := K) Q).asIdeal (𝓞 L)) = 2 := by
  have : FiniteDimensional K L := Module.finite_of_finrank_eq_succ h2
  have : Algebra.IsQuadraticExtension K L := ⟨h2⟩
  have := liesOver_belowP (K := K) Q
  have h := Ideal.ncard_primesOver_mul_ramificationIdxIn_mul_inertiaDegIn
    (belowP (K := K) Q).asIdeal (𝓞 L) (L ≃ₐ[K] L)
  rw [Ideal.ramificationIdxIn_eq_ramificationIdx (belowP (K := K) Q).asIdeal Q.asIdeal
    (L ≃ₐ[K] L), IsGalois.card_aut_eq_finrank, h2] at h
  rw [eQ, ← h]
  ring

theorem fiber_sigmaP (h2 : Module.finrank K L = 2) (σ : L ≃ₐ[K] L) (hσ1 : σ ≠ 1)
    (Q Q' : HeightOneSpectrum (𝓞 L)) (h : belowP (K := K) Q = belowP Q') :
    Q' = Q ∨ Q' = sigmaP σ Q := by
  have : FiniteDimensional K L := Module.finite_of_finrank_eq_succ h2
  have : Algebra.IsQuadraticExtension K L := ⟨h2⟩
  have := liesOver_belowP (K := K) Q
  have hQ' : Q'.asIdeal.LiesOver (belowP (K := K) Q).asIdeal := by
    rw [h]; exact liesOver_belowP Q'
  obtain ⟨τ, hτ⟩ := Ideal.exists_smul_eq_of_isGaloisGroup (belowP (K := K) Q).asIdeal Q.asIdeal
    Q'.asIdeal (L ≃ₐ[K] L)
  rcases aut_eq_one_or h2 σ hσ1 τ with rfl | rfl
  · left; ext1; rw [← hτ, one_smul]
  · right; ext1; rw [← hτ, sigmaP_asIdeal_eq_smul]

theorem eQ_cases (h2 : Module.finrank K L = 2) (Q : HeightOneSpectrum (𝓞 L)) :
    eQ K Q = 1 ∨ eQ K Q = 2 :=
  (Nat.dvd_prime Nat.prime_two).1 (Dvd.intro _ (eQ_mul_eq_two h2 Q))

theorem sigmaP_of_eQ_two (h2 : Module.finrank K L = 2) (σ : L ≃ₐ[K] L)
    (Q : HeightOneSpectrum (𝓞 L)) (he : eQ K Q = 2) : sigmaP σ Q = Q := by
  have h := eQ_mul_eq_two h2 Q
  rw [he] at h
  have h1 : (Ideal.primesOver (belowP (K := K) Q).asIdeal (𝓞 L)).ncard = 1 := by
    have : (Ideal.primesOver (belowP (K := K) Q).asIdeal (𝓞 L)).ncard *
      Ideal.inertiaDegIn (belowP (K := K) Q).asIdeal (𝓞 L) = 1 := by omega
    exact Nat.eq_one_of_mul_eq_one_right this
  obtain ⟨a, ha⟩ := Set.ncard_eq_one.1 h1
  have hQ : Q.asIdeal ∈ Ideal.primesOver (belowP (K := K) Q).asIdeal (𝓞 L) :=
    ⟨Q.isPrime, liesOver_belowP Q⟩
  have hσQ : (sigmaP σ Q).asIdeal ∈ Ideal.primesOver (belowP (K := K) Q).asIdeal (𝓞 L) := by
    refine ⟨(sigmaP σ Q).isPrime, ?_⟩
    have := liesOver_belowP (K := K) (sigmaP σ Q)
    rwa [belowP_sigmaP] at this
  rw [ha] at hQ hσQ
  ext1
  rw [Set.mem_singleton_iff.1 hQ, Set.mem_singleton_iff.1 hσQ]

attribute [local instance] FractionRing.liftAlgebra in
/-- Finitely many primes of `L` ramify over `K`: they divide the different ideal. -/
theorem finite_eQ_two :
    {Q : HeightOneSpectrum (𝓞 L) | eQ K Q = 2}.Finite := by
  have hD : differentIdeal (𝓞 K) (𝓞 L) ≠ ⊥ := differentIdeal_ne_bot
  refine (Ideal.finite_factors hD).subset ?_
  intro Q hQ
  change Q.asIdeal ∣ differentIdeal (𝓞 K) (𝓞 L)
  rw [dvd_differentIdeal_iff]
  intro hU
  have h1 := Ideal.ramificationIdx_eq_one Q.asIdeal (𝓞 K)
  have hQ' : eQ K Q = 2 := hQ
  rw [eQ, h1] at hQ'
  omega

/-- The primes of `L` with `e = 2` correspond to the finite primes of `K` ramified in `L`. -/
theorem ncard_eQ_two (h2 : Module.finrank K L = 2) :
    {Q : HeightOneSpectrum (𝓞 L) | eQ K Q = 2}.ncard = (ramifiedPrimes K L).ncard := by
  obtain ⟨σ, hσ1, -⟩ := exists_involution (K := K) (L := L) h2
  have hinj : Set.InjOn (belowP (K := K) (L := L)) {Q | eQ K Q = 2} := by
    intro Q hQ Q' _ hb
    rcases fiber_sigmaP h2 σ hσ1 Q Q' hb with h | h
    · exact h.symm
    · rw [h, sigmaP_of_eQ_two h2 σ Q hQ]
  have himage : belowP (K := K) '' {Q : HeightOneSpectrum (𝓞 L) | eQ K Q = 2} =
      ramifiedPrimes K L := by
    ext P
    constructor
    · rintro ⟨Q, hQ, rfl⟩
      refine ⟨Q.asIdeal, Q.isPrime, rfl, ?_⟩
      have : eQ K Q = 2 := hQ
      rw [eQ] at this
      omega
    · rintro ⟨Q, hQp, hQP, hQe⟩
      have hQ0 : Q ≠ ⊥ := by
        rintro rfl
        apply P.ne_bot
        rw [← hQP, Ideal.under_bot]
      let Q' : HeightOneSpectrum (𝓞 L) := ⟨Q, hQp, hQ0⟩
      have hb : belowP (K := K) Q' = P := by ext1; exact hQP
      refine ⟨Q', ?_, hb⟩
      rcases eQ_cases h2 Q' with h | h
      · exact absurd h (show ¬ Q.ramificationIdx (𝓞 K) = 1 by omega)
      · exact h
  rw [← himage, hinj.ncard_image]

open scoped Classical in
/-- The count at `Q` of the extension of a prime `P` of `K`: `e_Q` if `Q` lies over `P`, else 0. -/
theorem count_coeIdeal_map (Q : HeightOneSpectrum (𝓞 L)) (P : HeightOneSpectrum (𝓞 K)) :
    count L Q ((P.asIdeal.map (algebraMap (𝓞 K) (𝓞 L)) : Ideal (𝓞 L)) :
      FractionalIdeal (𝓞 L)⁰ L) = if belowP Q = P then (eQ K Q : ℤ) else 0 := by
  have hP0 : P.asIdeal.map (algebraMap (𝓞 K) (𝓞 L)) ≠ ⊥ := Ideal.map_ne_bot_of_ne_bot P.ne_bot
  rw [count_coe L Q hP0, Ideal.count_associates_factors_eq hP0 Q.isPrime Q.ne_bot]
  split_ifs with h
  · subst h
    have := liesOver_belowP (K := K) Q
    rw [eQ, Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count _ Q.asIdeal hP0]
  · rw [Nat.cast_eq_zero, Multiset.count_eq_zero]
    intro hmem
    apply h
    have hle : P.asIdeal ≤ Q.asIdeal.under (𝓞 K) :=
      Ideal.map_le_iff_le_comap.1
        (Ideal.le_of_dvd (UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hmem))
    ext1
    exact ((P.isMaximal).eq_of_le (Ideal.IsPrime.under (𝓞 K) Q.asIdeal).ne_top hle).symm

end Primes

/-! ### Transport through the factorization -/

section Transport

variable {K L : Type} [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L]

theorem extU_unitOfPrime (P : HeightOneSpectrum (𝓞 K)) :
    ((extU K L (unitOfPrime K P) : (FractionalIdeal (𝓞 L)⁰ L)ˣ) : FractionalIdeal (𝓞 L)⁰ L) =
      ((P.asIdeal.map (algebraMap (𝓞 K) (𝓞 L)) : Ideal (𝓞 L)) : FractionalIdeal (𝓞 L)⁰ L) := by
  rw [coe_extU, coe_unitOfPrime]
  exact FractionalIdeal.extendedHom_coeIdeal_eq_map L (𝓞 L) P.asIdeal

/-- **Counts of extended ideals**: `count_Q (ext b) = e_Q * count_{Q ∩ K} b`. -/
theorem count_extU (Q : HeightOneSpectrum (𝓞 L)) (b : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    count L Q (extU K L b : FractionalIdeal (𝓞 L)⁰ L) =
      (eQ K Q : ℤ) * count K (belowP Q) (b : FractionalIdeal (𝓞 K)⁰ K) := by
  classical
  have key : ∀ g : HeightOneSpectrum (𝓞 K) →₀ ℤ,
      count L Q (extU K L (ofFinsupp K g) : FractionalIdeal (𝓞 L)⁰ L) =
        (eQ K Q : ℤ) * g (belowP Q) := by
    intro g
    change Multiplicative.toAdd (countHom L Q (extU K L (ofFinsupp K g))) = _
    rw [ofFinsupp, map_finsuppProd, map_finsuppProd, Finsupp.prod, toAdd_prod]
    simp only [map_zpow, toAdd_zpow, countHom_apply, extU_unitOfPrime, count_coeIdeal_map,
      smul_eq_mul, mul_ite, mul_zero]
    rw [Finset.sum_ite_eq]
    split_ifs with h
    · ring
    · rw [Finsupp.notMem_support_iff.1 h]; ring
  conv_lhs => rw [← ofFinsupp_toFinsupp b]
  rw [key, toFinsupp_apply]

theorem sigmaI_eq_mapU (σ : L ≃ₐ[K] L) (a : (FractionalIdeal (𝓞 L)⁰ L)ˣ) :
    sigmaI σ a = mapU L (sigmaO σ) a := rfl

theorem count_sigmaI (σ : L ≃ₐ[K] L) (Q : HeightOneSpectrum (𝓞 L))
    (a : (FractionalIdeal (𝓞 L)⁰ L)ˣ) :
    count L (sigmaP σ Q) (sigmaI σ a : FractionalIdeal (𝓞 L)⁰ L) =
      count L Q (a : FractionalIdeal (𝓞 L)⁰ L) :=
  count_mapU (sigmaO σ) Q a

/-- Ambiguous ideals are the ideals with `σ`-invariant counts. -/
theorem mem_fixI_iff (h2 : Module.finrank K L = 2) (σ : L ≃ₐ[K] L)
    (a : (FractionalIdeal (𝓞 L)⁰ L)ˣ) :
    a ∈ (galData h2 σ).fixI ↔ toFinsupp a ∈ fixSubgroup (sigmaP σ) := by
  constructor
  · intro ha Q
    have ha' : sigmaI σ a = a := ha
    rw [toFinsupp_apply, toFinsupp_apply]
    conv_lhs => rw [← ha']
    exact count_sigmaI σ Q a
  · intro h
    change sigmaI σ a = a
    apply count_injective
    intro Q'
    have := count_sigmaI σ (sigmaP σ Q') a
    rw [sigmaP_sigmaP h2 σ Q'] at this
    rw [this]
    exact h Q'

/-- Extended ideals are the ideals with `σ`-invariant counts divisible by the ramification index. -/
theorem mem_range_extU_iff (h2 : Module.finrank K L = 2) (σ : L ≃ₐ[K] L) (hσ1 : σ ≠ 1)
    (a : (FractionalIdeal (𝓞 L)⁰ L)ˣ) :
    a ∈ (extU K L).range ↔ toFinsupp a ∈ extSubgroup (sigmaP σ) (eQ K) := by
  classical
  constructor
  · rintro ⟨b, rfl⟩
    refine ⟨fun Q => ?_, fun Q => ?_⟩
    · simp only [toFinsupp_apply, count_extU, eQ_sigmaP, belowP_sigmaP]
    · simp only [toFinsupp_apply, count_extU]
      exact dvd_mul_right _ _
  · rintro ⟨hfix, hdvd⟩
    choose above habove using (belowP_surjective (K := K) (L := L))
    set f := toFinsupp a with hf
    let g : HeightOneSpectrum (𝓞 K) →₀ ℤ :=
      Finsupp.onFinset (f.support.image belowP) (fun P => f (above P) / eQ K (above P)) (by
        intro P hP
        have hne : f (above P) ≠ 0 := by
          intro h0; apply hP; rw [h0, Int.zero_ediv]
        rw [Finset.mem_image]
        exact ⟨above P, Finsupp.mem_support_iff.2 hne, habove P⟩)
    refine ⟨ofFinsupp K g, count_injective fun Q => ?_⟩
    rw [count_extU, count_ofFinsupp, Finsupp.onFinset_apply]
    have hQ : count L Q (a : FractionalIdeal (𝓞 L)⁰ L) = f Q := rfl
    rw [hQ]
    rcases fiber_sigmaP h2 σ hσ1 Q (above (belowP Q)) (habove _).symm with h | h
    · rw [h]; exact Int.mul_ediv_cancel' (hdvd Q)
    · rw [h, eQ_sigmaP, hfix Q]; exact Int.mul_ediv_cancel' (hdvd Q)

/-- `[fix I_L : ext I_K] = 2 ^ t_f`. -/
theorem relIndex_extU_fixI (h2 : Module.finrank K L = 2) (σ : L ≃ₐ[K] L) (hσ1 : σ ≠ 1) :
    (extU K L).range.relIndex (galData h2 σ).fixI = 2 ^ (ramifiedPrimes K L).ncard := by
  set Φ := factorization (𝓞 L) L
  have h1 : (extU K L).range =
      (AddSubgroup.toSubgroup (extSubgroup (sigmaP σ) (eQ K))).comap Φ.toMonoidHom := by
    ext a
    rw [mem_range_extU_iff h2 σ hσ1 a]
    rfl
  have h1' : (galData h2 σ).fixI =
      (AddSubgroup.toSubgroup (fixSubgroup (sigmaP σ))).comap Φ.toMonoidHom := by
    ext a
    rw [mem_fixI_iff h2 σ a]
    rfl
  rw [h1, h1', Subgroup.relIndex_comap,
    Subgroup.map_comap_eq_self_of_surjective (f := Φ.toMonoidHom) Φ.surjective,
    AddSubgroup.relIndex_toSubgroup,
    relIndex_ext_fix (sigmaP σ) (eQ K) (sigmaP_sigmaP h2 σ) (eQ_cases h2) (sigmaP_of_eQ_two h2 σ)
      finite_eQ_two, ncard_eQ_two h2]

theorem index_principal :
    (toPrincipalIdeal (𝓞 K) K).range.index = classNumber K := by
  rw [Subgroup.index, ← Nat.card_congr (ClassGroup.equiv K).toEquiv, classNumber,
    Nat.card_eq_fintype_card]

theorem sigmaI_extU_unitOfPrime (σ : L ≃ₐ[K] L) (P : HeightOneSpectrum (𝓞 K)) :
    sigmaI σ (extU K L (unitOfPrime K P)) = extU K L (unitOfPrime K P) := by
  apply Units.ext
  rw [coe_sigmaI, extU_unitOfPrime, coeIdeal_ringEquivOfRingEquiv]
  congr 1
  change Ideal.map ((sigmaO σ : 𝓞 L ≃+* 𝓞 L) : 𝓞 L →+* 𝓞 L)
    (Ideal.map (algebraMap (𝓞 K) (𝓞 L)) P.asIdeal) = _
  rw [Ideal.map_map]
  congr 1
  exact RingHom.ext fun x => sigmaO_algebraMap σ x

/-- Ideals extended from `K` are `σ`-invariant. -/
theorem sigmaI_extU (σ : L ≃ₐ[K] L) (b : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    sigmaI σ (extU K L b) = extU K L b := by
  rw [← ofFinsupp_toFinsupp b, ofFinsupp, map_finsuppProd, map_finsuppProd]
  simp only [map_zpow, sigmaI_extU_unitOfPrime]

theorem extU_injective : Function.Injective (extU K L) := by
  apply Units.map_injective
  exact FractionalIdeal.extendedHom_injective (𝓞 K) K L (𝓞 L)

/-- **Ambiguous ideals modulo ideals of `K`**: `[fix I_L : PK] = 2 ^ t_f * h_K`. -/
theorem relIndex_PK_fixI (h2 : Module.finrank K L = 2) (σ : L ≃ₐ[K] L) (hσ1 : σ ≠ 1) :
    (galData h2 σ).PK.relIndex (galData h2 σ).fixI =
      2 ^ (ramifiedPrimes K L).ncard * classNumber K := by
  have hle1 : (galData h2 σ).PK ≤ (extU K L).range := by
    rw [galData_PK h2 σ hσ1]
    exact Subgroup.map_le_range _ _
  have hle2 : (extU K L).range ≤ (galData h2 σ).fixI := by
    rintro _ ⟨b, rfl⟩
    exact sigmaI_extU σ b
  have h1 : (galData h2 σ).PK.relIndex (extU K L).range = classNumber K := by
    rw [galData_PK h2 σ hσ1, MonoidHom.range_eq_map (extU K L),
      Subgroup.relIndex_map_map_of_injective _ _ extU_injective, Subgroup.relIndex_top_right,
      index_principal]
  rw [← Subgroup.relIndex_mul_relIndex _ _ _ hle1 hle2, h1, relIndex_extU_fixI h2 σ hσ1,
    mul_comm]

end Transport

end FurioLombardo.M3b
