import FurioLombardo.Discharge.M4Log.LamInt
import FurioLombardo.Discharge.M4Box.DFinal
import FurioLombardo.Discharge.M4Box.DCertData.K0I0
import FurioLombardo.Discharge.M4Box.DCertData.K0I1
import FurioLombardo.Discharge.M4Box.DCertData.K0I2
import FurioLombardo.Discharge.M4Box.DCertData.K0I3
import FurioLombardo.Discharge.M4Box.DCertData.K0I4
import FurioLombardo.Discharge.M4Box.DCertData.K0I5
import FurioLombardo.Discharge.M4Box.DCertData.K0I6
import FurioLombardo.Discharge.M4Box.DCertData.K1I0
import FurioLombardo.Discharge.M4Box.DCertData.K1I1
import FurioLombardo.Discharge.M4Box.DCertData.K1I2
import FurioLombardo.Discharge.M4Box.DCertData.K1I3
import FurioLombardo.Discharge.M4Box.DCertData.K1I4
import FurioLombardo.Discharge.M4Box.DCertData.K1I5
import FurioLombardo.Discharge.M4Box.DCertData.K1I6

/-!
# The value bounds of the fourteen points D_i (lane lean-m4box)

From the value certificates of the data files `K<k>I<i>.lean` (generated by code/local-group/di_value_certs_gen.lean,
checked by the kernel): the bounds `K<k>I<i>.cert` (`lamK_Dpt_of_cert`), `‖lamK k (D_i) j‖ ≤ 1` for all
`i, j`, hence `ChartLog k (lam k)` (`chartLog_of_values`), and the balls of lane M4, `HBallD` for `T0.data`,
`T1.data` (`hBallD_of_values`).
-/

namespace FurioLombardo.Discharge.M4Box.DCertData

open FurioLombardo.Discharge.KvArith FurioLombardo.Discharge.M4Box FurioLombardo.Discharge.M4Log
open FurioLombardo.Discharge.M4Cert FurioLombardo.Discharge.R7.ConcreteKv

theorem K0I0.cert (j : Fin 2) :
    ‖lamK 0 (SelmerSpan.Dpt 0 0) j‖ ≤ 1 ∧
      ‖lamK 0 (SelmerSpan.Dpt 0 0) j - evZ (lTriple (FurioLombardo.M4.T0.lD 0) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qD 0) :=
  lamK_Dpt_of_cert 0 0 dCtx_ok Tw0.hF Tw0.hg Tw0.hb Tw0.hE Tw0.hA hD hR hfin j

theorem K0I1.cert (j : Fin 2) :
    ‖lamK 0 (SelmerSpan.Dpt 0 1) j‖ ≤ 1 ∧
      ‖lamK 0 (SelmerSpan.Dpt 0 1) j - evZ (lTriple (FurioLombardo.M4.T0.lD 1) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qD 1) :=
  lamK_Dpt_of_cert 0 1 dCtx_ok Tw0.hF Tw0.hg Tw0.hb Tw0.hE Tw0.hA hD hR hfin j

theorem K0I2.cert (j : Fin 2) :
    ‖lamK 0 (SelmerSpan.Dpt 0 2) j‖ ≤ 1 ∧
      ‖lamK 0 (SelmerSpan.Dpt 0 2) j - evZ (lTriple (FurioLombardo.M4.T0.lD 2) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qD 2) :=
  lamK_Dpt_of_cert 0 2 dCtx_ok Tw0.hF Tw0.hg Tw0.hb Tw0.hE Tw0.hA hD hR hfin j

theorem K0I3.cert (j : Fin 2) :
    ‖lamK 0 (SelmerSpan.Dpt 0 3) j‖ ≤ 1 ∧
      ‖lamK 0 (SelmerSpan.Dpt 0 3) j - evZ (lTriple (FurioLombardo.M4.T0.lD 3) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qD 3) :=
  lamK_Dpt_of_cert 0 3 dCtx_ok Tw0.hF Tw0.hg Tw0.hb Tw0.hE Tw0.hA hD hR hfin j

theorem K0I4.cert (j : Fin 2) :
    ‖lamK 0 (SelmerSpan.Dpt 0 4) j‖ ≤ 1 ∧
      ‖lamK 0 (SelmerSpan.Dpt 0 4) j - evZ (lTriple (FurioLombardo.M4.T0.lD 4) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qD 4) :=
  lamK_Dpt_of_cert 0 4 dCtx_ok Tw0.hF Tw0.hg Tw0.hb Tw0.hE Tw0.hA hD hR hfin j

theorem K0I5.cert (j : Fin 2) :
    ‖lamK 0 (SelmerSpan.Dpt 0 5) j‖ ≤ 1 ∧
      ‖lamK 0 (SelmerSpan.Dpt 0 5) j - evZ (lTriple (FurioLombardo.M4.T0.lD 5) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qD 5) :=
  lamK_Dpt_of_cert 0 5 dCtx_ok Tw0.hF Tw0.hg Tw0.hb Tw0.hE Tw0.hA hD hR hfin j

theorem K0I6.cert (j : Fin 2) :
    ‖lamK 0 (SelmerSpan.Dpt 0 6) j‖ ≤ 1 ∧
      ‖lamK 0 (SelmerSpan.Dpt 0 6) j - evZ (lTriple (FurioLombardo.M4.T0.lD 6) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.qD 6) :=
  lamK_Dpt_of_cert 0 6 dCtx_ok Tw0.hF Tw0.hg Tw0.hb Tw0.hE Tw0.hA hD hR hfin j

theorem K1I0.cert (j : Fin 2) :
    ‖lamK 1 (SelmerSpan.Dpt 1 0) j‖ ≤ 1 ∧
      ‖lamK 1 (SelmerSpan.Dpt 1 0) j - evZ (lTriple (FurioLombardo.M4.T1.lD 0) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qD 0) :=
  lamK_Dpt_of_cert 1 0 dCtx_ok Tw1.hF Tw1.hg Tw1.hb Tw1.hE Tw1.hA hD hR hfin j

theorem K1I1.cert (j : Fin 2) :
    ‖lamK 1 (SelmerSpan.Dpt 1 1) j‖ ≤ 1 ∧
      ‖lamK 1 (SelmerSpan.Dpt 1 1) j - evZ (lTriple (FurioLombardo.M4.T1.lD 1) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qD 1) :=
  lamK_Dpt_of_cert 1 1 dCtx_ok Tw1.hF Tw1.hg Tw1.hb Tw1.hE Tw1.hA hD hR hfin j

theorem K1I2.cert (j : Fin 2) :
    ‖lamK 1 (SelmerSpan.Dpt 1 2) j‖ ≤ 1 ∧
      ‖lamK 1 (SelmerSpan.Dpt 1 2) j - evZ (lTriple (FurioLombardo.M4.T1.lD 2) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qD 2) :=
  lamK_Dpt_of_cert 1 2 dCtx_ok Tw1.hF Tw1.hg Tw1.hb Tw1.hE Tw1.hA hD hR hfin j

theorem K1I3.cert (j : Fin 2) :
    ‖lamK 1 (SelmerSpan.Dpt 1 3) j‖ ≤ 1 ∧
      ‖lamK 1 (SelmerSpan.Dpt 1 3) j - evZ (lTriple (FurioLombardo.M4.T1.lD 3) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qD 3) :=
  lamK_Dpt_of_cert 1 3 dCtx_ok Tw1.hF Tw1.hg Tw1.hb Tw1.hE Tw1.hA hD hR hfin j

theorem K1I4.cert (j : Fin 2) :
    ‖lamK 1 (SelmerSpan.Dpt 1 4) j‖ ≤ 1 ∧
      ‖lamK 1 (SelmerSpan.Dpt 1 4) j - evZ (lTriple (FurioLombardo.M4.T1.lD 4) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qD 4) :=
  lamK_Dpt_of_cert 1 4 dCtx_ok Tw1.hF Tw1.hg Tw1.hb Tw1.hE Tw1.hA hD hR hfin j

theorem K1I5.cert (j : Fin 2) :
    ‖lamK 1 (SelmerSpan.Dpt 1 5) j‖ ≤ 1 ∧
      ‖lamK 1 (SelmerSpan.Dpt 1 5) j - evZ (lTriple (FurioLombardo.M4.T1.lD 5) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qD 5) :=
  lamK_Dpt_of_cert 1 5 dCtx_ok Tw1.hF Tw1.hg Tw1.hb Tw1.hE Tw1.hA hD hR hfin j

theorem K1I6.cert (j : Fin 2) :
    ‖lamK 1 (SelmerSpan.Dpt 1 6) j‖ ≤ 1 ∧
      ‖lamK 1 (SelmerSpan.Dpt 1 6) j - evZ (lTriple (FurioLombardo.M4.T1.lD 6) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.qD 6) :=
  lamK_Dpt_of_cert 1 6 dCtx_ok Tw1.hF Tw1.hg Tw1.hb Tw1.hE Tw1.hA hD hR hfin j

theorem fin7_cases (i : Fin 7) : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 := by
  revert i; decide

theorem lamK_Dpt_le_one_0 (i : Fin 7) (j : Fin 2) : ‖lamK 0 (SelmerSpan.Dpt 0 i) j‖ ≤ 1 := by
  obtain rfl | rfl | rfl | rfl | rfl | rfl | rfl := fin7_cases i
  exacts [(K0I0.cert j).1, (K0I1.cert j).1, (K0I2.cert j).1, (K0I3.cert j).1, (K0I4.cert j).1, (K0I5.cert j).1, (K0I6.cert j).1]

theorem lamK_Dpt_sub_0 (i : Fin 7) (j : Fin 2) :
    ‖lamK 0 (SelmerSpan.Dpt 0 i) j - evZ (lTriple (FurioLombardo.M4.T0.data.lD i) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T0.data.qD i) := by
  obtain rfl | rfl | rfl | rfl | rfl | rfl | rfl := fin7_cases i
  exacts [(K0I0.cert j).2, (K0I1.cert j).2, (K0I2.cert j).2, (K0I3.cert j).2, (K0I4.cert j).2, (K0I5.cert j).2, (K0I6.cert j).2]

theorem lamK_Dpt_le_one_1 (i : Fin 7) (j : Fin 2) : ‖lamK 1 (SelmerSpan.Dpt 1 i) j‖ ≤ 1 := by
  obtain rfl | rfl | rfl | rfl | rfl | rfl | rfl := fin7_cases i
  exacts [(K1I0.cert j).1, (K1I1.cert j).1, (K1I2.cert j).1, (K1I3.cert j).1, (K1I4.cert j).1, (K1I5.cert j).1, (K1I6.cert j).1]

theorem lamK_Dpt_sub_1 (i : Fin 7) (j : Fin 2) :
    ‖lamK 1 (SelmerSpan.Dpt 1 i) j - evZ (lTriple (FurioLombardo.M4.T1.data.lD i) j)‖ ≤ ‖pv‖ ^ (3 * FurioLombardo.M4.T1.data.qD i) := by
  obtain rfl | rfl | rfl | rfl | rfl | rfl | rfl := fin7_cases i
  exacts [(K1I0.cert j).2, (K1I1.cert j).2, (K1I2.cert j).2, (K1I3.cert j).2, (K1I4.cert j).2, (K1I5.cert j).2, (K1I6.cert j).2]

theorem lamK_Dpt_le_one (k : Fin 2) (i : Fin 7) (j : Fin 2) : ‖lamK k (SelmerSpan.Dpt k i) j‖ ≤ 1 := by
  obtain rfl | rfl : k = 0 ∨ k = 1 := by revert k; decide
  · exact lamK_Dpt_le_one_0 i j
  · exact lamK_Dpt_le_one_1 i j

/-- **`ChartLog` for lane M4's logarithm**, both twists. -/
theorem chartLog (k : Fin 2) : FurioLombardo.Discharge.R7.ChartLog k (lam k) :=
  chartLog_of_values k (lamK_Dpt_le_one k)

/-- **The balls of the D_i logarithms** (`hBD` of `M4RestKvW`), twist 0. -/
theorem hBD_0 : FurioLombardo.M4.HBallD FurioLombardo.M4.T0.data (fun i => lam 0 (SelmerSpan.Dpt 0 i)) :=
  hBallD_of_values 0 FurioLombardo.M4.T0.data (lamInt_of 0 (lamK_Dpt_le_one 0)) lamK_Dpt_sub_0

/-- **The balls of the D_i logarithms** (`hBD` of `M4RestKvW`), twist 1. -/
theorem hBD_1 : FurioLombardo.M4.HBallD FurioLombardo.M4.T1.data (fun i => lam 1 (SelmerSpan.Dpt 1 i)) :=
  hBallD_of_values 1 FurioLombardo.M4.T1.data (lamInt_of 1 (lamK_Dpt_le_one 1)) lamK_Dpt_sub_1

end FurioLombardo.Discharge.M4Box.DCertData
