import Mathlib

/-! Data of the dyadic map of the M3b discharge (generated by code/selmer-global-bound/dyadic_map_data.gp, PARI/GP;
rechecked by the kernel). Coordinates on PARI's integral basis (`FurioLombardo.M1.zkE`). -/

namespace FurioLombardo.Discharge.M3b

/-- `Π = la (1 + la + la² + la⁴)`. -/
def PiL : List ℤ := [-260, 190, 124, 103, -98, -131, 90, 34, 80, 73, -91, 129, 31, -129, 65, 47, -19, -168, 26, 86, -29]

end FurioLombardo.Discharge.M3b
